### PR TITLE
openssl: 1.0.2e→1.0.2f & reformat recipe

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
Sorry, I did not know there was a reason for using a `.patchset` suffix. The reason why I used `.patch` instead of `.patchset` was that I noticed that when we browse them on GitHub's website ,`.patch` files are shown with patch-syntax highlight, whereas `.patchset` files are shown as plain text without any colors. So I looked around to see their distribution. The current results are 319 `.patch` files and 551 `.patchset` files. So I though it would the choice was free and that it would have been OK to use a `.patch` suffix. If you don't like the `.patch` suffix I can stop using it and switch to the `.patchset` suffix.

**Comment by mmuman** [comment]
Could we open an issue on github to have them add the extension to the known list?

**Comment by fbrosson** [comment]
That's a good idea. I think we can have `.patchset` files appear the same way as `.patch` files by editing the https://github.com/haikuports/haikuports/blob/master/.gitattributes config file in order to add something like: `*.patchset linguist-language=Diff` or `*.patchset linguist-language=Patch` to that file.
I found this in https://github.com/github/linguist#troubleshooting but I havent found yet what is the name (`Diff` or `Patch`) of the language that is associated to `.patch` files by default. I'm sure the answer to that question is somewhere in https://github.com/github/linguist.

**Comment by fbrosson** [comment]
Well, according to https://github.com/github/linguist/tree/master/samples/Diff it looks like the name of the language associated by default to `.patch` files is `Diff`.
This means we just need to append this line:
`*.patchset linguist-language=Diff`
to https://github.com/haikuports/haikuports/blob/master/.gitattributes. Should I edit that file myself? (I would need to create a PR for that.)

**Comment by fbrosson** [comment]
Hi @mmuman! I've just commented https://github.com/haikuports/haikuports/pull/450.

**Comment by mmuman** [comment]
I just asked them on twitter: https://twitter.com/mmu_man/status/694512649590214656 we'll see.

**Pull request merged**
