### PR TITLE
curl, revbump for missing develop packages references

### PR DESCRIPTION
**Pull request by Begasus**
~> pkg-config libcurl --cflags
  Package libssh2 was not found in the pkg-config search path.

### CODE REVIEW

**Comment by Begasus** [comment]
@korli could you have a look here? I never trust myself with curl, but these changes are needed so curl is detected and working fine with pkg-config search.

**Comment by korli** [comment]
pkgconfig is weird, this looks wrong when checking the curl headers: only dependents on posix headers.
we could try to remove the Requires.private in the pc file, and see what happens.

**Comment by Begasus** [comment]
> we could try to remove the Requires.private in the pc file, and see what happens.

Could give it a look at tomorrow, downside for this would be that external packages requiring curl will have to add those requirements to their list then.

**Comment by korli** [comment]
> Could give it a look at tomorrow, downside for this would be that external packages requiring curl will have to add those requirements to their list then.

These requirements in the case of curl are only for static linking.

**Comment by korli** [comment]
I removed the curl devel dependencies. Tested a bit OK.

**Comment by Begasus** [comment]
Superseded by: https://github.com/haikuports/haikuports/commit/de1a699f7b33176b9240ad7390248aa36fbb46d8

**Comment by Begasus** [comment]
> I removed the curl devel dependencies. Tested a bit OK.

I'll test in the morning for kiwix. Thanks!

**Pull request closed without merging**
