### PR TITLE
Bsap: new recipe

### PR DESCRIPTION
**Pull request by bach5000**
Does anyone actually how I could get rid of those older commits?
I'm struggling with Github 🙁

### CODE REVIEW

**Comment by fbrosson** [comment]
You need to rebase against 1f5b4eff70cdf03e4f256bebea24efc649b0b959 (because that was the commit you had in master when you started working on Drawpile.)
BTW, that's the reason why most users prefer to use [feature-branches](https://github.com/haikuports/haikuports/wiki/DevelopmentModel#what-are-feature-branches).

```
EDITOR=vi git rebase -i 1f5b4eff70cdf03e4f256bebea24efc649b0b959
```
Then edit these lines:
```
pick 3b3dff754 Create Drawpile.rdef
pick e7e0bc54b Add .iom
pick 085d8c4f0 Bump revision
pick 44c8e8383 Add app signature
pick d5635f785 Fix rdef format
pick 5974666be Make icon useable
pick 53762e3b7 Remove comment
pick 1ea34f502 Create bsap-1.0.recipe
pick c43006b39 Add patch
pick 487d1d874 Fix weird whitespace issues
pick 9287af1e2 Remove trailing tab
```
to replace the 7 first "pick" by "drop" (or "d") in order to get:
```
d 3b3dff754 Create Drawpile.rdef
d e7e0bc54b Add .iom
d 085d8c4f0 Bump revision
d 44c8e8383 Add app signature
d d5635f785 Fix rdef format
d 5974666be Make icon useable
d 53762e3b7 Remove comment
pick 1ea34f502 Create bsap-1.0.recipe
pick c43006b39 Add patch
pick 487d1d874 Fix weird whitespace issues
pick 9287af1e2 Remove trailing tab
```
If you're not used to vim you can achieve this by typing "3xrdj" 7 times (without the quotes) and then pressing ZZ

Then you'll need to update your remote branch:
```
git push --force
```

In case you want to make a backup of your local branch before the rebase:
```
git checkout -b bsap-recipe-backup bsap-recipe
git checkout bsap-recipe
```

**Comment by bach5000** [comment]
@fbrosson Woah! It worked! 😄 Thanks for the detailed step by step instructions!!
First time something worked on Github. Usually I end up deleting my fork and reforking haikuports :/

**Comment by bach5000** [comment]
@fbrosson Thanks!
This is part of the GCI task... can you check?

**Comment by bach5000** [comment]
Oops @fbrosson did not see your commits! You could have told me to make the fixes instead of doing all the work 😄

**Comment by fbrosson** [comment]
Yeah, I saw that the recipe was almost okay and only needed a few cosmetic and easy changes, so I pushed them myself because it was easier for me and because I knew you would be okay with it :)
(GCI task approved :)

Regarding the patchset format, the prefered method is to use haikuporter.
Suppose you have your patch working, but created with git. You just need to:
```bash
hp -c bsap
np -B bsap
cd /boot/home/haikuports/haiku-apps/bsap/work-0.8/sources/beos-bsap-*
git log -p # if you wish to check everything is ok
cd /boot/home/haikuports/haiku-apps/bsap/patches
cp bsap-0.8.patchset bsap-0.8.patchset.backup # if you want to keep a copy of your initial patchset
np -e bsap # note: you can but you don't need to be in the paches directory
diff bsap-0.8.patchset.backup bsap-0.8.patchset # if you want to compare the old vs the new patchsets
```

**Comment by bach5000** [comment]
@fbrosson ah ok. I used `git format-patch`, which gave different patchset file format...
I'll keep in mind to use HaikuPorter next time. I remember I did something similar last year, but I couldn't go back and check :(

**Pull request merged**
