### PR TITLE
simutrans: fix references to libSDL*

### PR DESCRIPTION
**Pull request by AlwaysLivid**

### CODE REVIEW

**Comment by Begasus** [comment]
@taosxx as you are keeping track on this, this is an older recipe, maybe we can just drop it?

**Comment by alwayslivid** [comment]
@korli I tried to compile it, but there seems to be a definition conflict with the integers that was also mentioned in the Haiku IRC a few days ago.

Should I patch the definitions out?

**Comment by korli** [comment]
> @korli I tried to compile it, but there seems to be a definition conflict with the integers that was also mentioned in the Haiku IRC a few days ago.
> 
> Should I patch the definitions out?

Try to build on x86_64 first. We can disable the build on 32-bit if required.

**Comment by alwayslivid** [comment]
> > @korli I tried to compile it, but there seems to be a definition conflict with the integers that was also mentioned in the Haiku IRC a few days ago.
> > Should I patch the definitions out?
> 
> Try to build on x86_64 first. We can disable the build on 32-bit if required.

Done, the recipe builds, but it is going to need further updates due to unmet dependencies. (namely, svn.)

https://paste.ubuntu.com/p/cQCJHtxbDX

**Comment by Begasus** [comment]
There is already an updated recipe for this, should we still look into this?

**Comment by Begasus** [comment]
Closing as the newer versions already have the fix

**Pull request closed without merging**
