### PR TITLE
icu70: Add initial icu70 patchset for testing

### PR DESCRIPTION
**Pull request by kallisti5**
still needs a little refactoring.  opening a pr for testing

### CODE REVIEW

**Comment by kallisti5** [comment]
https://unicode-org.atlassian.net/browse/ICU-21920 was uncovered during testing.

**Comment by kallisti5** [comment]
https://dev.haiku-os.org/ticket/17612 was raised to discuss raising our maximum arg length

**Comment by kenmays** [comment]
icu70: builds on x86_64. Tweak devel packaging.

**Comment by kenmays** [comment]
icu70: builds on x86_64 (nightly, current). 
- Devel packaging failed.
- Unit testing failed.
   - PASSED: testdata iotest
   - FAILED: intltest cinttst

**Comment by kallisti5** [comment]
I'm merging this one.  It's disabled on all architectures so we can test.

**Comment by kenmays** [comment]
icu70: built on Haiku R1B3 x86 (+64).

    Unit testing passed.
        PASSED: testdata iotest
        FAILED: intltest cintltst

NOTE: Unit tests passed successfully.

**Pull request merged**
