### PR TITLE
CMake: add gui subpackage

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by extrowerk** [comment]
Probably we don't want to merge this. Maybe some of the Qt's dependency requires cmake to build with.

**Comment by korli** [comment]
you're right, but we can also try and see how problematic it is, the cmake package won't have runtime dependency on Qt anyway.

**Comment by extrowerk** [comment]
Thats true, but actually the gui is not that useful as i expected. IT lets generate a makefile, but that's all. I tought it will also build things, but thats probably not the scope of the gui. So i don't really see the point to have a gui, but other platforms providing it, so if it doesn't makes a headache us then we could do the same.

**Comment by Begasus** [comment]
Can this be merged @extrowerk ?

**Comment by extrowerk** [comment]
I'vw tested it only on 64 bit, but i am not against it.

Schrijvers Luc <notifications@github.com>:

**Comment by Begasus** [comment]
Let's merge then ;)

**Pull request merged**
