### PR TITLE
Fixed boost dependencies for mpd

### PR DESCRIPTION
**Pull request by trungnt2910**
Fixed dependencies for boost in recipe for mpd-0.21.19 (#4619)
This should fix gcc2h broken package.

### CODE REVIEW

**Comment by Begasus** [comment]
Thanks, will check in a bit :+1:

**Comment by Begasus** [comment]
Please, also bump REVISION

**Comment by trungnt2910** [comment]
Ok. I've done that.

**Comment by Begasus** [comment]
Build is almost finished here, so the requirements seems to be OK :)

**Comment by trungnt2910** [comment]
Thanks.

**Comment by korli** [comment]
Why not >= 1.66.0?

**Comment by Begasus** [comment]
> Why not >= 1.66.0?

The lowest version required seemed to be >= 1.58
Checked a local build with this, worked ok, and the buildbot seems to be ok with it too

**Comment by Begasus** [comment]
For the record, I have 1.69.0 here

**Comment by korli** [comment]
> For the record, I have 1.69.0 here

One day, we want to drop everything older than 1.69. So we should tell the builders to use a current version. Otherwise users will have to install multiple versions.

**Pull request merged**
