### PR TITLE
FS-UAE and launcher version bump

### PR DESCRIPTION
**Pull request by moochris**
I have updated `fs-uae` and `fs-uae-launcher` - the existing patches applied fine for the first, and I re-enabled `PyQt5.QtOpenGL` in the PyQt5 recipe for the latter to work.

### CODE REVIEW

**Comment by moochris** [comment]
Not sure why travis failed to build `fs-uae` - I just checked building from clean again and works here...

**Comment by Begasus** [comment]
> Not sure why travis failed to build `fs-uae` - I just checked building from clean again and works here...

Trailing whitespace in 'dev-python/pyqt/pyqt5-5.15.2.recipe'

**Comment by moochris** [comment]
> Trailing whitespace in 'dev-python/pyqt/pyqt5-5.15.2.recipe'

Thanks - I thought the travis log wasn't working, but it was just webpositive...

**Comment by korli** [comment]
Did you build and test on beta2?

**Comment by moochris** [comment]
> Did you build and test on beta2?
Ah, no, just the latest nightly. I'll test on beta2 as well and report.

**Comment by moochris** [comment]
Yes, builds and runs fine on beta2

**Pull request merged**
