### PR TITLE
bump version of DocumentViewer

### PR DESCRIPTION
**Pull request by ivanholmes**
This should be the last piece of the puzzle in my project to update mupdf.
If everyone else is happy, #6823, #6824 and #6838 are now ready to merge.

### CODE REVIEW

**Comment by Begasus** [comment]
I'll checkout the build and report later :)

**Comment by Begasus** [comment]
Thanks! Great job on fixing this and pdftranslator! :+1:

**Comment by ivanholmes** [comment]
> Thanks! Great job on fixing this and pdftranslator! +1

No problem, happy to see it all merged, thanks for your guidance!

I've been working on porting some other apps (Jellyfin Media Player, melonDS), both compile but don't run, what's the right place to discuss this with other devs?

**Comment by ivanholmes** [comment]
> Maybe on IRC (OFTC #haiku) ?

Ok will try it, thanks

**Pull request merged**
