### PR TITLE
libice, bump revision after changes to util-macros and xorgproto

### PR DESCRIPTION
**Pull request by Begasus**
Should we use "lib:libICE" or "lib:libice" here?

### CODE REVIEW

**Comment by Begasus** [comment]
Point taken, but it isn't the first time this has come up, if so, why not use "lib:libX*" instead of "lib:libx*" for all the other recipes then?

**Comment by alaviss** [comment]
We name `lib:` after the library soname, which in this case is `libICE`, so yes, `libICE` :)

**Comment by Begasus** [comment]
My point in another discussion soname for libxau is libXau, so why not change those too?

**Comment by fbrosson** [comment]
_Short answer:_
It's up to you :)
I'd say that as long as it works, you can choose the variant of your choice.

_Long answer:_
I think `libICE`, `libX11` and  `libXau` look nicer than `libice`, `libx11` and  `libxau`, but I'm OK with whatever variant you might choose.
Also, you don't need to change the case of all occurrences of these `lib:lib*`, unless you really want to. You can, for example, "convert" only the lines that you already need to edit.

**Comment by Begasus** [comment]
It doesn't matter what would be nicer :) It would be about setting an example on how to correctly use the sonames as @alaviss mentioned (it has been brought up earlier - eg libSDL/libsdl libGL/libgl etc ... 
It would be good to make some guidance line in what to use (I'm in favor here for libX*)

**Pull request merged**
