### PR TITLE
Qt5: look for SSL library with version 3 suffix

### LINKED ISSUE #10836: Broken Otter browser
screenshot313

hrev57937+36 64 bit

### LINKED ISSUE #10837: yt_dlp wanting to install ffmpeg-4.2.9 etc.
I was just about to install yt-dlp on the beta5-test-image and wondered why it wants to install ffmpeg-4.2.9, ffmpeg_avdevice-4.2.9 and ffmpeg_tools-4.2.9.  Why doesn't it go for the ffmpeg6-6.1.1_* versions? ffmpeg6-6.1.1-3-x86_64.hpkg is already installed with the beta5-test-image...

### PR DESCRIPTION
**Pull request by lonemadmax**
Fixes #10836 and #10818

Only built and tested on a recent x86_64 nightly with openssl3.

Just below the changed lines, the typical unix lib paths are added, maybe those should also be changed to finddir calls for Haiku.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Makes sense to me. Anything this is waiting for in particular?

**Comment by lonemadmax** [comment]
A 32-bit check. I can't currently build it even without changes, it looks like some issue on my side: sometimes make crashes, sometimes it doesn't find something.

Until proven wrong, I'm guessing it wouldn't work, as LIBRARY_PATH contains lib, not lib/x86.

**Comment by waddlesplash** [comment]
I think we search the path automatically on `dlopen` if a non-absolute path is specified. So, can't we just patch Qt to do that?

**Comment by lonemadmax** [comment]
> I think we search the path automatically on `dlopen` if a non-absolute path is specified. So, can't we just patch Qt to do that?

It seems that's what the function is trying to do here. Without the details for different OSes, it builds a list of paths from LD_LIBRARY_PATH and then adds /lib, /usr/lib and company.

The new version just takes B_{USER,SYSTEM}{NONPACKAGED,}_LIB_DIRECTORY for Haiku.


> I guess this fixes #10836 instead of #10837?

Right, thank you.

**Comment by waddlesplash** [comment]
> Without the details for different OSes, it builds a list of paths from LD_LIBRARY_PATH and then adds /lib, /usr/lib and company.

No, I mean that on Haiku, `dlopen("libcrypto.so.3")` (for example) should automatically search through the given library paths. Plus this should automatically respect "Disable user addons" and secondary architecture subdirectories, which manually searching the paths won't. So if you can make the code do that (and it works) that would be ideal.

**Comment by lonemadmax** [comment]
> `dlopen("libcrypto.so.3")` should automatically [work]. So if you can make the code do that (and it works) that would be ideal.

In the end it was already doing that. Almost.

Manually looking in the lib dirs for libcrypto.so.* until finding one that loads is the *third* thing it tries, the first one being what it is supposed to do: `dlopen("libcrypto.so.<version>")`, with version taken from SHLIB_VERSION_NUMBER, which is removed in OpenSSL 3. Using OPENSSL_SHLIB_VERSION solves the issue.

**Review by waddlesplash — APPROVED** [review]

**Pull request merged**
