### PR TITLE
kottan: bumped version

### PR DESCRIPTION
**Pull request by andimachovec**
new beta version 0.13.2

### CODE REVIEW

**Review by humdingerb — CHANGES_REQUESTED** [review]
The description could do with a bit more meat... :)

Maybe at least:
> Kottan lets you view and edit the contents of files that contain \
flattened BMessages, a common technique for applications to archive their \
settings and other data.

**Comment by andimachovec** [comment]
That sounds like a good improvement of my original description ;-)
Thanks!

**Comment by andimachovec** [comment]
Done :-)

**Review by humdingerb — APPROVED** [review]

**Comment by humdingerb** [comment]
Thanks!

**Pull request merged**
