### PR TITLE
Updated recipe for elixir

### PR DESCRIPTION
**Pull request by trungnt2910**
I've updated the recipe for elixir from v1.4.2 to v1.9.4 (latest).
Terminal window running elixir v1.9.4
Elixir v1 9 4

### CODE REVIEW

**Comment by extrowerk** [comment]
Please do not link packages here, we are sure you dont want to steal our password, data, etc with a malicious crafted package, but the devil never sleeps.
So please remove that link. Thank you.

**Comment by extrowerk** [comment]
I forgot that i can also remove it.

**Comment by trungnt2910** [comment]
> Could you please remove the old recipe? Thank you!
I've removed it, like you said.
However, I've seen that there are many apps in haikuports that keep recipes of their older versions.

**Comment by extrowerk** [comment]
But now we can see what did you changed: https://github.com/haikuports/haikuports/pull/4612/files

**Comment by Begasus** [comment]
LGTM, ready to merge @extrowerk ?

**Comment by trungnt2910** [comment]
In the last commit, I've updated the build requirements for Elixir. The documentation says that Elixir 1.9.4 requires Erlang 20.0 or later, so I fixed the recipe to check for this.

**Comment by Begasus** [comment]
Not on x86_64 atm so can't check, could you provide a buildlog?

**Comment by trungnt2910** [comment]
You mean when running haikuporter?

**Comment by Begasus** [comment]
> You mean when running haikuporter?

Yes (output in Terminal)

**Comment by trungnt2910** [comment]
Here is the terminal output:

[elixir_build.log](https://github.com/haikuports/haikuports/files/4080515/elixir_build.log)

**Comment by Begasus** [comment]
Ah :) just saw that there isn't actually anything build :)
Would be nice to see if this would work on the gcc2h, but that's another thing (erlang needs to be checked if it builds there)

**Comment by trungnt2910** [comment]
Thanks.

**Pull request merged**
