### PR TITLE
New recipe: JXL Translator

### PR DESCRIPTION
**Pull request by wattoc**
@Begasus please check this one :)

### CODE REVIEW

**Comment by Begasus** [comment]
Will try it out when I get a chance to it, in the meantime all that could check could do the same :) Thanks so far! :+1:

**Comment by Begasus** [comment]
Build is OK as is the install part, one question, on 32bit this is installed in the x86 subdirectory, whey I try to select a "save as" in ShowImage the translator doesn't show up? (ps, not checked on 64bit yet)

**Comment by korli** [comment]
> Build is OK as is the install part, one question, on 32bit this is installed in the x86 subdirectory, whey I try to select a "save as" in ShowImage the translator doesn't show up? (ps, not checked on 64bit yet)

Then the translator will only show up on 32-bit for x86 applications.

**Comment by wattoc** [comment]
The gcc2 exclusion is inherited from the libjxl recipe - I suspect the translator itself would compile OK on gcc2 but the dependency wouldn't be available.  I'm not aware of any way to make it work but someone else might know.

**Comment by Begasus** [comment]
Some other translators are suffering from the same, no gcc2 possible, don't think it should really matter at this point.
As for me this could be merged.

**Pull request merged**
