### PR TITLE
recipe for qtx11extras

### PR DESCRIPTION
**Pull request by TURX**
This is for #4593.

### CODE REVIEW

**Comment by TURX** [comment]
I do not know if the build produces any file. The log is at https://paste.ubuntu.com/p/pb4YrbD5cY/.

**Comment by extrowerk** [comment]
“ mv: cannot stat '/packages/qtx11extras-5.9.9-1/.self/lib/qml': No such file or directory”
This is obviously wrong.

**Comment by Begasus** [comment]
Maybe it would be good to test a recipe locally before pushing to a PR?

**Comment by Begasus** [comment]
For now, not needed

**Pull request closed without merging**
