### PR TITLE
libtool, disable static library, remove libtool file

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Actually, I think this one is a case where we want to delete the shared library, not the static library.

**Comment by Begasus** [comment]
Thanks will give it another spin.

**Comment by korli** [comment]
> Actually, I think this one is a case where we want to delete the shared library, not the static library.

Why actually?

**Comment by waddlesplash** [comment]
The shared library is a set of helper routines for dlopen only, I think? I'm not sure it really warrants being dynamically linked.

**Comment by Begasus** [comment]
Just did a check on PR https://github.com/haikuports/haikuports/pull/8141

With the changes from here I only get a static library build in the source, with the current one from the depot (with the shared library from libtool) I'm getting the shared library for libtermkey ...

**Comment by Begasus** [comment]
Reverted changes and now it disables the static library, will do some further testing, but so far looking good.

**Pull request merged**
