### PR TITLE
mesa: update to 19.3.3, HGL fixes

### PR DESCRIPTION
**Pull request by X547**
BGLView::CopyPixelsIn/Out is not yet implemented.

Front and back buffer BBitmap are now allocated in winsys, memory copy count is
reduced.

Fixes:
	#4471
	#4466
	Fix buffer leak.

New features:
	Double buffering.
	Shared contexts (needed for Blender).

### CODE REVIEW

**Comment by waddlesplash** [comment]
Can you submit these patches upstream to Mesa, please?

**Comment by X547** [comment]
Fixed 32 bit build.

**Comment by kenmays** [comment]
@X547 - On Haiku3D testing, just for reference: https://dev.haiku-os.org/attachment/ticket/15246/Haiku3d-hrev53368_x64_cocobean.jpeg

**Comment by X547** [comment]
Note that some debugging output is not removed and most of changes are in big "HGL rework" commit.

**Comment by kenmays** [comment]
Verified Mesa 19.3.3-1 recipe built on R1B1 x86_64. Applied Mesa 19.3.3 patchset to Mesa 19.3.4. No issues. Verified Mesa 19.3.4 built successfully on Haiku R1B1 x86_64.

**Comment by diversys** [comment]
Would be nice to bump this to mesa 20.0.0
https://www.mesa3d.org/relnotes/20.0.0.html

**Comment by kenmays** [comment]
mesa 20.0.0 build on Haiku R1B1: PASSED
Tweaked your haiku-softpipe/GalliumContext.cpp patch code to current.

**Comment by X547** [comment]
I don't touched Haiku EGL implementation. I'm not sure that it actually working. Does anyone know how to test EGL (code samples etc.)?

**Comment by X547** [comment]
Obsolete, new version is available: https://github.com/haikuports/haikuports/pull/4740.

**Comment by waddlesplash** [comment]
You don't need to make new PRs (actually we prefer to keep the history all in one place); just force-push over your existing branch to update the PR.

**Comment by X547** [comment]
mesa 20.0.0 have bugs in upstream, reopening.

**Comment by X547** [comment]
Can't reopen, I create new pull request.

**Pull request closed without merging**
