### PR TITLE
nodejs20, bump to latest LST release

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Test case output comparible with previous version(s). Might need libuv merged first? https://github.com/haikuports/haikuports/pull/10733

**Comment by Begasus** [comment]
Build fails on 32bit (not supprising but still), adding some output here just in case ...
```
g++ -o /sources/node-v20.15.1/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/wasm/canonical-types.o ../deps/v8/src/wasm/canonical-types.cc '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DICU_NO_USER_DATA_OVERRIDE' '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DV8_TARGET_ARCH_IA32' '-DV8_EMBEDDER_STRING="-node.23"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DOBJECT_PRINT' '-DV8_INTL_SUPPORT' '-DV8_ATOMIC_OBJECT_FIELD_WRITES' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DV8_SHARED_RO_HEAP' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_USE_ZLIB' '-DV8_ENABLE_TURBOFAN' '-DV8_ENABLE_WEBASSEMBLY' '-DV8_ENABLE_JAVASCRIPT_PROMISE_HOOKS' '-DV8_ALLOCATION_FOLDING' '-DV8_ALLOCATION_SITE_TRACKING' '-DV8_ADVANCED_BIGINT_ALGORITHMS' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' -I/packages/zlib_x86-1.3-3/.self/develop/headers/x86 -I/packages/libuv_x86-1.48.0-1/.self/develop/headers/x86 -I/packages/c_ares_x86-1.19.1-2/.self/develop/headers/x86 -I/packages/nghttp2_x86-1.59.0-1/.self/develop/headers/x86 -I/packages/openssl_x86-1.1.1w-1/.self/develop/headers/x86 -I/packages/icu74_x86-74.1-3/.self/develop/headers/x86 -I../deps/v8 -I../deps/v8/include -I/sources/node-v20.15.1/out/Release/obj/gen/inspector-generated-output-root -I../deps/v8/third_party/inspector_protocol -I/sources/node-v20.15.1/out/Release/obj/gen -I/sources/node-v20.15.1/out/Release/obj/gen/generate-bytecode-output-root -I../deps/v8/third_party/zlib -I../deps/v8/third_party/zlib/google  -Wno-unused-parameter -Wno-return-type -flax-vector-conversions -fPIC -m32 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++17 -MMD -MF /sources/node-v20.15.1/out/Release/.deps//sources/node-v20.15.1/out/Release/obj.target/v8_base_without_compiler/deps/v8/src/wasm/canonical-types.o.d.raw   -c
In file included from ../deps/v8/src/wasm/baseline/liftoff-assembler.h:1885,
                 from ../deps/v8/src/wasm/baseline/liftoff-assembler.cc:5:
../deps/v8/src/wasm/baseline/ia32/liftoff-assembler-ia32.h:421:6: error: no declaration matches 'void v8::internal::wasm::LiftoffAssembler::Load(v8::internal::wasm::LiftoffRegister, v8::internal::Register, v8::internal::Register, uint32_t, v8::internal::wasm::LoadType, uint32_t*, bool, bool, bool)'
  421 | void LiftoffAssembler::Load(LiftoffRegister dst, Register src_addr,
      |      ^~~~~~~~~~~~~~~~
../deps/v8/src/wasm/baseline/liftoff-assembler.h:823:15: note: candidate is: 'void v8::internal::wasm::LiftoffAssembler::Load(v8::internal::wasm::LiftoffRegister, v8::internal::Register, v8::internal::Register, uintptr_t, v8::internal::wasm::LoadType, uint32_t*, bool, bool, bool)'
  823 |   inline void Load(LiftoffRegister dst, Register src_addr, Register offset_reg,
      |               ^~~~
```

**Comment by Begasus** [comment]
Any takes on this? As it is atm this is dead for 32bit, from what I could check it's working fine here.

**Comment by korli** [comment]
It seems linux x86 reappeared as unofficial-builds, so you might enable it if it works. You might need to disable it again in a future upgrade :)

**Comment by Begasus** [comment]
@korli from what I can see in the source x86(i386/ia32) is "supported", just can't get the darn thing to build on 32bit, beleive me, I tried. :D 
So if nothing else pops up I'll merge this later today, atm looking into poppler/labplot issue.

**Comment by korli** [comment]
> @korli from what I can see in the source x86(i386/ia32) is "supported", just can't get the darn thing to build on 32bit, beleive me, I tried. :D So if nothing else pops up I'll merge this later today, atm looking into poppler/labplot issue.

https://unofficial-builds.nodejs.org/download/release/    unofficial means unspported to me :)

**Comment by Begasus** [comment]
> https://unofficial-builds.nodejs.org/download/release/ unofficial means unspported to me :)

My bad, was actually looking inside the source (not releases) :)
On that note, for this version I don't see any 32bit released there too? https://unofficial-builds.nodejs.org/download/release/v20.9.0/

**Comment by korli** [comment]
> My bad, was actually looking inside the source (not releases) :) On that note, for this version I don't see any 32bit released there too? https://unofficial-builds.nodejs.org/download/release/v20.9.0/

It's again available from https://unofficial-builds.nodejs.org/download/release/v20.12.1/

**Comment by Begasus** [comment]
@korli forgive me for not going through the full directory there ;)

**Pull request merged**
