### PR TITLE
photograbber, fix recipe, bump version

### PR DESCRIPTION
**Pull request by Begasus**
Builds ok for x86_gcc2 x86 and x86_64 (just didn't put in x86 in the recipe) :)

### CODE REVIEW

**Comment by Begasus** [comment]
photograbber

**Comment by scottmc** [comment]
Feel free to update the readme on HaikuArchives page for this, such as adding mention that it handle PTP/USB cameras and phones.  Confirmed it works with my Pixel2 last night.

**Comment by Begasus** [comment]
@scottmc that would be something for @humdingerb or someone with access to it :)

**Comment by humdingerb** [comment]
Done.

**Pull request merged**
