### PR TITLE
Vim: bump to 8.0.1230

### PR DESCRIPTION
**Pull request by kenmays**
Built and tested on hrev52399 x86_gcc2.

### CODE REVIEW

**Comment by extrowerk** [comment]
**Please, this time don't close this ticket.**

**Comment by kenmays** [comment]
extrowek - I posted this info at the very beginning of the PR: "Built and tested on hrev52399 x86_gcc2."
"

**Comment by extrowerk** [comment]
Then test it on x86_64 too as it seems to be broken here.

**Comment by kenmays** [comment]
Something changed recently on x86_64 that breaks the vim gui_haiku.cc patch (same exact build issue on vim 8.0.1176 now). Vim 8.0.1176/1200 still build fully on x86_gcc2 without any changes. Both platforms are on hrev52347.

**Comment by extrowerk** [comment]
It seems libstdc++ is missing somewhere.

**Comment by kenmays** [comment]
Built and tested on hrev52347 x86_64.
Everything passed.

**Comment by extrowerk** [comment]
https://github.com/haikuports/haikuports/issues/3088 related.

**Comment by extrowerk** [comment]
I literally told you to not close this PR, mate.

**Comment by fbrosson** [comment]
Yeah,, @kenmays, you should not be opening and closing PRs everytime there is a new release of some software.
It is OK to close a PR which has not been merged, but we only do this if we know we are not going to open another PR for a newer release of that same software. Here, you are closing PRs and opening new ones. You should really consider reading some help articles from GitHub and more tutorials to learn how to:
* Merge into a feature branch the commits that have been pushed by others to the master branch. This is often called "rebase against master". Hint: `git checkout master` + `git pull upstream master` + `git checkout vim-update` + `git merge master` + `git rebase --interactive master` (or `git rebase master`).
* Push your rebased branch to your remote branch, using the `--force` switch. This is required whenever you have rebased a local branch which you had already pushed to your remote branch before the rebase. Hint: `git push --force` (or `git push -f`).
* Update your remote master. Deleting your fork and then forking the projects' master again works fine, but there is a much better and faster method to do that. It's quite easy. Once you know how to do this, you will never forget. Hint: `git checkout master` + `git pull upstream master` + `git push origin master` (or `git push` because `origin` is the name of the default remote repo.)
* Delete your local branches, your remote branches and your local refs to your remote branch once the PR which was based on your remote branch has been merged or closed. You can skip this, but that's not recommended because this means you would have name your branches with different names everytime you wish to update a recipe. Hint: `git branch -D vim-update` + `git branch -r -d vim-update` + "Delete branch" button on GitHub's web interface.

The learing curve for Git + GitHub can last a few months, so please consider digging these topics.
But please don't stop contributing! And please do not hesitate to ask for guidance if you wish to do something and haven't found a nice tutorial about it. Thanks!

**Comment by kenmays** [comment]
@fbrosson - I'll focus on consolidating things so it doesn't affect your end as much by not updating my Github web branch so often. Anyhow, point(s) taken.

**Pull request closed without merging**
