### PR TITLE
speedcrunch: add rdef with bitmap icon

### PR DESCRIPTION
**Pull request by augiedoggie**
I haven't yet found any software that would export their SVG icon in a format compatible with Icon-O-Matic.

### CODE REVIEW

**Comment by pulkomandy** [comment]
Icon-O-Matic should be able to import SVG files. If you have SVG that are not being imported correctly, I'd like to have a look at them so I can improve Icon-O-Matic import

**Comment by augiedoggie** [comment]
> Icon-O-Matic should be able to import SVG files. If you have SVG that are not being imported correctly, I'd like to have a look at them so I can improve Icon-O-Matic import

https://bitbucket.org/heldercorreia/speedcrunch/src/master/gfx/speedcrunch.svg

The basic shape seems ok since Icon-O-Matic changed to nanosvg but there are still problems with the text and some of the highlight shapes(like the little lens flare circle that shows up as solid gray)

**Comment by Begasus** [comment]
@pulkomandy anything needed here, or can we merge for now?

**Comment by pulkomandy** [comment]
No problem from me. We should do a native-style icon anyway, but until then, the bitmap icon will work.

**Pull request merged**
