### PR TITLE
qtwebengine_bin, revbump release

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Could use some checking, so far things have been running smooth, used variable "hpkgHOME" in case somone does the next update, also switched revision to match the main building recipe.

**Comment by korli** [comment]
> Could use some checking, so far things have been running smooth, used variable "hpkgHOME" in case somone does the next update, also switched revision to match the main building recipe.
> 
> EDIT: build against Qt-5.15.11 (so in case you don't have that updated it will come part of this one)

Theorically version requirements should be hardcoded with current versions, because the current ones in the haikuports repo at the time of the _bin build are irrelevant. But: nobody should trigger a rebuild of _bin recipes anyway.

**Comment by korli** [comment]
Seems the builder didn't take some versions:
`haiku >= r1~beta4_hrev56578_87-1
       lib:libavcodec
       lib:libavformat
       lib:libavutil
       lib:libdbus_1
       lib:libexecinfo
       lib:libexpat >= 1.8.10
       lib:libevent_2.1 >= 6.0.2
       lib:libfontconfig >= 1.12.0
       lib:libfreetype >= 6.18.3
       lib:libgl
       lib:libharfbuzz >= 0.60821.0
       lib:libjpeg
       lib:liblcms2
       lib:libminizip
       lib:libnspr4
       lib:libnss3
       lib:libnssutil3
       lib:libopus
       lib:libplc4
       lib:libplds4
       lib:libpng16 >= 16.40.0
       lib:libqt5core
       lib:libqt5gui
       lib:libqt5network
       lib:libqt5positioning
       lib:libqt5printsupport
       lib:libqt5qml
       lib:libqt5qmlmodels
       lib:libqt5quick
       lib:libqt5quickwidgets
       lib:libqt5webchannel
       lib:libqt5widgets
       lib:libsmime3
       lib:libsnappy
       lib:libstdc++ >= 6.0.32
       lib:libvpx
       lib:libwebp
       lib:libwebpdemux
       lib:libwebpmux
       lib:libxslt
       lib:libxml2 >= 2.10.4
       lib:libz >= 1.2.13`

**Comment by Begasus** [comment]
Thanks for taking care of it, was out of the house. :+1:

**Pull request merged**
