### PR TITLE
Opencv 3.2.0

### PR DESCRIPTION
**Pull request by miqlas**
Work in progress: do not merge yet.

### CODE REVIEW

**Comment by miqlas** [comment]
Compiles and packages just fine on x86_64. One can merge this stuff.

**Comment by miqlas** [comment]
Could not resolve symbol '__stack_chk_fail'
No idea, why.

**Comment by korli** [comment]
Try to disable the gcc stack protector.

**Comment by miqlas** [comment]
Already did, See the patchset.

**Comment by miqlas** [comment]
Still complaining about missing '__stack_chk_fail' symbol.

**Comment by miqlas** [comment]
Now it works, but the pkgconfig and. cmake files needs a bit sed magic.

**Comment by miqlas** [comment]
Builds, packages fine, it is possible to build the sample programs and some works really well. Some hovewer not, but i can't debug it. I would say LGTM, and it will evolve slowly.

**Comment by miqlas** [comment]
@korli: Order fixed.

**Pull request merged**
