### PR TITLE
dooble: bump version

### PR DESCRIPTION
**Pull request by kenmays**
Tested with Haiku R1B4 (hrev56578+93) w/qtwebengine_bin 5.15.2-8 (Qt 5.15.11).
* No issues with Youtube A/V playback.

### CODE REVIEW

**Comment by kenmays** [comment]
Just rebuilt on my updated machine - no issues here.... hmmm....

**Comment by Begasus** [comment]
Could you check if you got libQt5WebEngine.so in /system/lib? It's missing in the current package.

**Comment by kenmays** [comment]
Not there for Qr5 or Qt6 ( i.e. libQt5WebEngine.so nor libQt6WebEngine.so)  - but built fine on my end.

**Comment by Begasus** [comment]
Strange as buildmaster and here are failing on not finding them, I checked the Qt5 package where the linked *.so are also included in the base package, the latest qtwebengine contains the links also. Anyway, created a PR that solves the issue.

**Comment by kenmays** [comment]
Seems we need to rekick the build on the buildmaster...

**Pull request merged**
