### PR TITLE
Dust Racing 2D: Add recipe

### PR DESCRIPTION
**Pull request by win8linux**
[Dust Racing 2D](https://juzzlin.github.io/DustRacing2D/) is an open-source, tile-based, top-down racing game built on Qt. This recipe adds both the main game and its map editor.

Confirmed working on `x86_64`:
image
image
image
image

### CODE REVIEW

**Review by augiedoggie — CHANGES_REQUESTED** [review]
The game should be in the `games-sports` category according to http://gpo.zugaina.org/games-sports/dustrac

**Comment by augiedoggie** [comment]
I pushed some changes to your PR but I haven't had a chance to test them on 32 bit.  Also, it would be nice to find some icons for the game and editor but I didn't see any good svg files from a quick glance.

**Review by augiedoggie — APPROVED** [review]

**Comment by augiedoggie** [comment]
In the future we may want to adjust the default settings for the game.  It ran very slowly by default in my VM at least.

**Comment by win8linux** [comment]
> Also, it would be nice to find some icons for the game and editor but I didn't see any good svg files from a quick glance.

I tried to make an icon from scratch, but unfortunately my skill with I-O-M still isn't up to par for that yet.

> In the future we may want to adjust the default settings for the game. It ran very slowly by default in my VM at least.

There aren't really many graphics settings present. It's just windowed/fullscreen and resolution. Suppose it could be set to windowed by default, but we'd need to pick a resolution that would work for most people.

**Comment by augiedoggie** [comment]
> There aren't really many graphics settings present. It's just windowed/fullscreen and resolution.

Changing the FPS and vsync options helps too.

**Pull request merged**
