### PR TITLE
Blender: bump version, updated patchset

### PR DESCRIPTION
**Pull request by miqlas**
Work in progress!

### CODE REVIEW

**Comment by miqlas** [comment]
@korli: you worked on Blender, and i see you haven't updated the Haiku GHOST code from the earlier patches. Does they upstreamed? (If so, then they already deleted from the official git repo, because i cannot find them there.)

If you don't used the haiku ghost backend, then what kind of backend are you used in your port?
I took your patches and updated to the current version, but without SDL it crashes for me too.

Currently i see Cocoa, NULL, SDL, Win32, X11 backends in the blender repo. Maybe there is some kind of OpenGL backend, i'm not sure, will check later.

**Comment by korli** [comment]
You know you can use "git am" to apply a previous version patch? It's not very nice to change authorship like this...

**Comment by miqlas** [comment]
@korli: i told you already, i have almost no idea about git and yet less about patch management.

The old patchset doesn't apply cleanly anymore, so i had to apply it manually.

**Comment by korli** [comment]
Well, haikuporter uses "git am" for a reason, you just have to fix conflicts, remove unneeded parts, "git add", "git am --continue".

**Comment by miqlas** [comment]
It compiles and packages fine. If it is okay, you can merge it.

**Comment by scottmc** [comment]
Compiles and packages fine, but does it actually run?  Can you post a screenshot?

**Comment by miqlas** [comment]
http://chunk.io/f/fb9b4a0097a445f4ae2719496af962ed13
http://chunk.io/f/604155b4788c4f7d8412cecb045d8f0111

GHOST (the Blender GUI) requires SDL2, i built without it, but it crashes at Start (@korli?) so i had to enable the SDL2 output.
It starts in full-screen, tried to resize, but it doesn't works. So i cannot give you any nice Haiku with Blender screenshot.

The SDL2 output not realible, as it forgets to update the window content. Maybe it requires extra patching. Somebody can look into it.

**Comment by miqlas** [comment]
360b9434b1a54091b489c1e1fda0c6e4
It is on Haiku.

**Comment by scottmc** [comment]
Any luck on getting the patch reviewed by upstream?

**Comment by miqlas** [comment]
Haven't tried.

**Comment by waddlesplash** [comment]
Merge this now?

**Comment by miqlas** [comment]
Theretically it is a minimal Blender, what still works. One can extend it.
I think you can merge it, hovewer it would be good to hear any experience on gcc2h

**Pull request merged**
