### PR TITLE
X11 fixesproto: new recipe

### PR DESCRIPTION
**Pull request by miqlas**

### CODE REVIEW

**Comment by waddlesplash** [comment]
This is quite a lot of recipes for protos (I mean the other PRs too). How do Linux distros do this? Can we combine them all into one recipe?

**Comment by miqlas** [comment]
They have a separate recipe for every proto package.

**Comment by waddlesplash** [comment]
:/

Must we do the same? Or is there some technical reason why this is the only way to go?

**Comment by miqlas** [comment]
Have no idea, i’m just copying this: https://packages.gentoo.org/categories/x11-proto <https://packages.gentoo.org/categories/x11-proto>

**Comment by waddlesplash** [comment]
Alright, well, seeing as they're all similar, perhaps it makes sense to at least put them all in one PR?

**Pull request merged**
