### PR TITLE
Changing set of recipes to download from secure sources

### PR DESCRIPTION
**Pull request by Abogical**
This is to complete the GCI task: https://codein.withgoogle.com/dashboard/task-instances/6318061434961920

Several recipes have been adjusted to download from secure https sources, followed by checksum verifications. also styling issues were also fixed as well.

### CODE REVIEW

**Comment by waddlesplash** [comment]
> Trailing whitespace in 'haiku-apps/slayer/slayer-0.9.recipe'.

**Comment by Abogical** [comment]
I doubel-checked, but I can't find a trailing whitespace in the slayer recipe.

**Comment by Abogical** [comment]
@KapiX found it, thanks.

**Comment by Abogical** [comment]
Travis test passed, I think it's good to go.

**Pull request merged**
