### PR TITLE
dooble: bump version

### PR DESCRIPTION
**Pull request by kenmays**
Dooble 2022.12.25
Tested on hrev56673 x64.

### CODE REVIEW

**Comment by Begasus** [comment]
@kenmays could you squash your commits before a merge (when done), no need to add a separate commit for every change in the PR. Thanks :)

**Comment by Begasus** [comment]
On a second commit you can always use `git commit --amend`, this is enough to keep it to one commit (that's how I use it). :)

**Comment by Begasus** [comment]
@kenmays Buid failure on 32bit: https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=&viewMode=expanded

**Comment by kenmays** [comment]
QtWebEngine not available on x86.

**Comment by kenmays** [comment]
For now, yes. - we can disable the x86 building.

**Pull request merged**
