### PR TITLE
colobot: bump version

### PR DESCRIPTION
**Pull request by TheZeldakatze**
Colobot did have some problems under x86_gcc2, however after rebuilding it, it does work fine. The version currently in the repository did not work on my VM, crashing during start

I also changed it to use the latest boost, it seems to work fine with it

### CODE REVIEW

**Comment by korli** [comment]
any chance to upstream Haiku parts of the patch?

**Comment by TheZeldakatze** [comment]
I don't know how you do proper attribution and stuff, as the patch is mostly just the old patch with some fixes. Do you just put the patch files into the repository and create a PR on the upstream project leaving in the commit log stuff? Then I could try to do that, is it ok to upstream patches like that?

**Comment by korli** [comment]
Please check upstream contribution guidelines. But yes, keeping the commits like in the patch set should be OK.

**Comment by Begasus** [comment]
Fresh build on 64bit crashes on launch too:
```
~> /boot/system/apps/Colobot/Colobot
[INFO]: Colobot: Gold Edition 0.2.1-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: /packages/colobot-0.2.1-1/.self/data/Colobot
[INFO]: Save path: /boot/home/config/settings/colobot
[INFO]: Mod search dirs:
[INFO]:   * /packages/colobot-0.2.1-1/.self/data/Colobot/mods
[INFO]:   * /boot/home/config/settings/colobot/mods
[INFO]: Found mods:
[INFO]:   * /packages/colobot-0.2.1-1/.self/data/Colobot/mods/AltTextures
[INFO]: Additional mod paths:
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: Error on parsing config file: No such node (Setup.Resolution)
[INFO]: Error on parsing config file: No such node (Setup.Fullscreen)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
OpenGL load add-on: /boot/system/add-ons/opengl/Software Pipe
OpenGL add-on registered: /boot/system/add-ons/opengl/Software Pipe
GalliumContext: CreateDisplay: Using llvmpipe (LLVM 12.0.1, 256 bits) driver.
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 4.5 (Compatibility Profile) Mesa 22.0.5 (git-b50852e138)
[INFO]: llvmpipe (LLVM 12.0.1, 256 bits)
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 4
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[INFO]: Maximum texture size: 16384
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 16384
[INFO]: CDevice created successfully
[ERROR]: Error creating CText: Error on parsing fonts config file: failed to open file
OK
[INFO]: Didn't run main loop. Exiting with code 6
[INFO]: Unloading files and closing device...
```

**Comment by TheZeldakatze** [comment]
> Fresh build on 64bit crashes on launch too:

I just did a build on a fresh&updated install of Haiku r1beta4 and it works without a problem. I could check if the problem occurs with nightlies.

But whilst checking that I noticed that python2 isn't in the repository anymore and changed a dependency of colobot_data

**Comment by Begasus** [comment]
Same here, probably done something wrong last attempt, working fine, thanks!

**Pull request merged**
