### PR TITLE
MPlayer: improved icon, it looks almost like the official one.

### PR DESCRIPTION
**Pull request by miqlas**
The earlier one looks a bit ehh in Deskbar

### CODE REVIEW

**Comment by Giova84** [comment]
Hi, is nice, but why not to use the McClintock icon which is more in Haiku's style? :-)
Mplayer icon

**Comment by miqlas** [comment]
‘cause unlike his other icons it looks terrible.

**Comment by Giova84** [comment]
Obviously is a matter of personal taste :-)
So I will avoid to propose also the Haiku's style icon for QupZilla ;)
QupZilla Haiku's icon
To me, this icon, looks better than the newer one (I talk about Qupzilla)

**Comment by humdingerb** [comment]
Though OT... :) I, too, like the old QupZilla icon better. But the QupZilla guys went with a new one, so I guess it's polite to follow. But we could work on a haikuified version, i.e. projected on sphere.

**Comment by humdingerb** [comment]
@miqlas : Could you add the IOM file to the "additional-files"? Then it's easier to modify the icon. (Applies to your other added icons as well.)

**Comment by miqlas** [comment]
One can convert the hrdef resource to iom, right?

**Comment by humdingerb** [comment]
I think one can with IIRC "rc" and stuff, but why make it so difficult?
Sure, one can get the package and get the icon from the filetype, but that still loses the names of the shapes, styles, paths. Adding the IOM is really the easiest and most convenient.

**Comment by miqlas** [comment]
They are svg Icons converted to hvif, shapes got default names. No Data loss i suppose,

**Pull request merged**
