### PR TITLE
starfighter: new recipe

### PR DESCRIPTION
**Pull request by Crestwave**
Should the `x86` architecture always be marked as untested?

EDIT: Also, I wasn't sure whether to put this in games-action or games-arcade

### CODE REVIEW

**Comment by korli** [comment]
it would be nice to convert the patch to a git patch. It could eventually upstreamed with your author name.

**Comment by Crestwave** [comment]
I'll submit a PR upstream when this gets merged.

**Comment by korli** [comment]
games-arcade is correct.

**Comment by Crestwave** [comment]
Upstreamed: https://github.com/pr-starfighter/starfighter/pull/4

**Pull request merged**
