### PR TITLE
Use libpng16 in BUILD_REQUIRES

### PR DESCRIPTION
**Pull request by humdingerb**
in cpctools and lbreakout2 as it's already in master.

### CODE REVIEW

**Comment by fbrosson** [comment]
I thought the recommended method (to update the release branch) was to cherry-pick the commits made to master.
@pulkomandy, ain't this the recommended method?

**Comment by scottmc** [comment]
Perhaps add links to this PR as well?

**Comment by pulkomandy** [comment]
Either cherry-pick or importing the files is fine. As long as the recipe revisions stay in sync...

**Comment by korli** [comment]
IMO it's a pity to drop author information from commits made to master.

**Pull request merged**
