### PR TITLE
neofetch: fix uptime

### PR DESCRIPTION
**Pull request by Crestwave**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Can you submit this patch upstream, please?

**Comment by Crestwave** [comment]
It's already been upstreamed (I told the author of the original patch as well)

**Comment by waddlesplash** [comment]
The indentation in the patch looks wrong; can you try to repair that at least so that we have 1:1 parity with the upstream patch? (Or did upstream re-indent the file?)

**Comment by Crestwave** [comment]
It looks fine to me. I told the author of the issue and fix while chatting with him in IRC, so he did it separately, but I ran `diff` on them now and my patch seems to match.

**Comment by waddlesplash** [comment]
I just realized this didn't bump the revision?

**Comment by Crestwave** [comment]
Whoops, my bad. You'll have to do it at this point, right?

**Comment by waddlesplash** [comment]
Sure.

**Pull request merged**
