### PR TITLE
librsvg, new recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
2 from the tests fail, haven't investigated further (today) :)

**Comment by kenmays** [comment]
Got one fail on hrev54131 x86_64:
```
# Storing test result image at /tmp/masking-path-04-b-out.png
# **59372 pixels differ (with maximum difference of 255) from reference image**

# Storing test result image at /tmp/masking-path-04-b-diff.png
not ok 23 /rsvg/reftest/svg1.1/masking-path-04-b.svg
FAIL: rsvg-test 23 /rsvg/reftest/svg1.1/masking-path-04-b.svg
```

**Comment by Begasus** [comment]
Thanks for checking out @kenmays

**Comment by Begasus** [comment]
Failing tests on x86_gcc2 (secondary architecture):
```
# Storing test result image at /tmp/masking-mask-01-b-diff.png
not ok 17 /rsvg/reftest/svg1.1/masking-mask-01-b.svg
FAIL: rsvg-test 17 /rsvg/reftest/svg1.1/masking-mask-01-b.svg
# Storing test result image at /tmp/masking-mask-02-f-out.png
# 32 pixels differ (with maximum difference of 1) from reference image

# Storing test result image at /tmp/masking-path-04-b-diff.png
not ok 23 /rsvg/reftest/svg1.1/masking-path-04-b.svg
FAIL: rsvg-test 23 /rsvg/reftest/svg1.1/masking-path-04-b.svg
# Storing test result image at /tmp/struct-cond-03-t-out.png
# 36 pixels differ (with maximum difference of 1) from reference image
```

**Comment by Begasus** [comment]
Wasn't sure where I saved it, but this is an image from when I started to work on this :)
librsvg-example-output

**Pull request merged**
