### PR TITLE
Drag[en]gine 1.6: Fixed issue with implicit casting of nullptr to function pointers

### PR DESCRIPTION
**Pull request by LordOfDragons**
Follow up of https://github.com/haikuports/haikuports/pull/6274#issuecomment-944051888

### CODE REVIEW

**Comment by Begasus** [comment]
Crossing fingers :)

**Comment by Begasus** [comment]
Argh, no revision bump ...

**Comment by LordOfDragons** [comment]
I used sha256sum to calculate the checksum. Not good if this does not produce the right results :(

**Comment by LordOfDragons** [comment]
Okay. It looks like I need to explicit cast all nullptr usage in the vulkan code. Not a big deal... just annoying.

**Pull request merged**
