### PR TITLE
Strip debug info from release packages

### PR DESCRIPTION
**Pull request by owenca**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Why not make a debuginfo package?

**Comment by mmuman** [comment]
About the commit log:
- you'll want to prefix the first line with the name of the port to make it clearer, like "friss: strip debug..." ; it's a widespread convention with git, although some projects do it differently.
- Please mention the ticked reference in the log so we know what it's supposed to fix, like "fixes https://github.com/pulkomandy/fRiSS/issues/33 " (it's not the same repo so we can't use just the number).

I agree it'd be better to have the debug package.

**Comment by owenca** [comment]
When I switched to `defineDebugInfoPackage friss $binDir/friss`, it failed to build:

~/haikuports/haiku-apps/friss> hp friss
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Checking if package dependencies need to be updated ...
        updating dependency infos of friss-0.8.1
----------------------------------------------------------------------
haiku-apps::friss-0.8.1
        /boot/home/haikuports/haiku-apps/friss/friss-0.8.1.recipe
----------------------------------------------------------------------
Skipping download of source for 0.8.1.tar.gz
Skipping checksum validation of 0.8.1.tar.gz
Skipping unpack of 0.8.1.tar.gz
Cleaning up temporary directories ...
chroot has these packages active:
        /boot/system/packages/bash-4.3.42-4-x86_gcc2.hpkg
        /boot/system/packages/binutils-2.17_2016_07_24-2-x86_gcc2.hpkg
        /boot/system/packages/bzip2-1.0.6-5-x86_gcc2.hpkg
        /boot/system/packages/ca_root_certificates-2017_01_18-1-any.hpkg
        /boot/system/packages/coreutils-8.24-1-x86_gcc2.hpkg
        /boot/system/packages/curl-7.45.0-2-x86_gcc2.hpkg
        /boot/system/packages/expat-2.2.0-1-x86_gcc2.hpkg
        /boot/system/packages/fontconfig-2.12.6-1-x86_gcc2.hpkg
        /boot/system/packages/freetype-2.8.1-1-x86_gcc2.hpkg
        /boot/system/packages/gcc-2.95.3_2017_07_20-1-x86_gcc2.hpkg
        /boot/system/packages/gettext_libintl-0.19.8.1-4-x86_gcc2.hpkg
        /boot/system/packages/giflib6-5.0.5-2-x86_gcc2.hpkg
        /boot/system/packages/grep-2.24-1-x86_gcc2.hpkg
        /boot/system/packages/gutenprint-5.2.12-2-x86_gcc2.hpkg
        /boot/system/packages/gzip-1.6-2-x86_gcc2.hpkg
        /boot/system/packages/haiku-r1~alpha4_pm_hrev51602-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_devel-r1~alpha4_pm_hrev51602-1-x86_gcc2.hpkg
        /boot/system/packages/icu-57.1-1-x86_gcc2.hpkg
        /boot/system/packages/jam-2.5_2012_10_12-4-x86_gcc2.hpkg
        /boot/system/packages/jasper-1.900.1-4-x86_gcc2.hpkg
        /boot/system/packages/jpeg-9b-2-x86_gcc2.hpkg
        /boot/system/packages/libicns-0.8.1-3-x86_gcc2.hpkg
        /boot/system/packages/libiconv-1.13.1-9-x86_gcc2.hpkg
        /boot/system/packages/libpng16-1.6.34-1-x86_gcc2.hpkg
        /boot/system/packages/libsolv-0.3.0_haiku_2014_12_22-1-x86_gcc2.hpkg
        /boot/system/packages/libwebp-0.6.0-1-x86_gcc2.hpkg
        /boot/system/packages/libxml2-2.9.3-2-x86_gcc2.hpkg
        /boot/system/packages/mesa-7.9.2-10-x86_gcc2.hpkg
        /boot/system/packages/ncurses6-6.0-2-x86_gcc2.hpkg
        /boot/system/packages/noto-20170202-6-any.hpkg
        /boot/system/packages/noto_sans_cjk_jp-1.004-2-any.hpkg
        /boot/system/packages/openssl-1.0.2g-1-x86_gcc2.hpkg
        /boot/system/packages/qrencode-3.4.4-1-x86_gcc2.hpkg
        /boot/system/packages/readline-6.3.8-3-x86_gcc2.hpkg
        /boot/system/packages/sed-4.2.1-6-x86_gcc2.hpkg
        /boot/system/packages/tar-1.28-1-x86_gcc2.hpkg
        /boot/system/packages/tiff4-4.0.6-3-x86_gcc2.hpkg
        /boot/system/packages/unzip-6.0-3-x86_gcc2.hpkg
        /boot/system/packages/zlib-1.2.11-2-x86_gcc2.hpkg
----- Package Info ----------------
header size:                     80
heap size:                      954
TOC size:                        41
package attributes size:       1185
total size:                    1034
-----------------------------------
----- Package Info ----------------
header size:                     80
heap size:                     1032
TOC size:                        41
package attributes size:       1304
total size:                    1112
-----------------------------------
waiting for build package friss-0.8.1-2 to be activated
waiting for build package friss_debuginfo-0.8.1-2 to be activated
Skipping build ...
Collecting files to be packaged ...
objcopy: '/packages/friss-0.8.1-2/.self/bin/friss': No such file
objcopy: error: the input file '/packages/friss-0.8.1-2/.self/bin/friss' is empty
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1
Error: Build has failed - stopping.
~/haikuports/haiku-apps/friss>

**Comment by owenca** [comment]
Fixed.

**Pull request merged**
