### PR TITLE
gphoto2: bump to 2.5.15

### PR DESCRIPTION
**Pull request by Vidrep**

### CODE REVIEW

**Comment by Vidrep** [comment]
Both recipes in one push request. Not sure why.

**Comment by fbrosson** [comment]
Your recipes need a few minor changes. I can push them for you, on your branch, before the merge.

Oops, your PR is attached to your master branch...
That's not recommended because it makes it harder for you to update your master branch with new commits (unrelated to this PR) should you wish to resync your remote repo before the merge,
But don't worry, we can continue with this PR, and we will also be able to merge it too.

Regarding gphoto2, it would be better to move it to a separate PR. That's not strictly required, but if we kept gphoto2 here then, when we would merge this PR we would have to choose between 2 scenari:
a) Squash and merge, which would merge your two commits into one, and that's not a good idea because the recipes are not related to one another.
b) Rebase and merge, which would be OK if your commits were all correct. But since they need a couple of changes, we would have to push 2 squashed commits, so your first commits would be replaced by these new commits.

So, here's what suggest:
1) I drop your commit for gphoto2 in your master branch.
2) I fix your recipe for tipster, and push a commit for it to your master branch.
3) I merge this PR with the "Squash and merge" button.
4) You resync your master with upstream. (I can guide you with this if you wish.)
5) You create a branch for gphoto2 and push your recipe there then open a PR for it. (I can also guide you with this if you wish.)
6) We proceed with gphoto2 in that new PR.

Shall do that?

**Comment by fbrosson** [comment]
After all, if you wish, I can update your PR for both recipes and then use the "Rebase and merge" button.

**Comment by fbrosson** [comment]
If/when you create the separate PR for gphoto2, please use a [feature-branch](https://github.com/haikuports/haikuports/wiki/DevelopmentModel#what-are-feature-branches). Thanks ;)

**Comment by Vidrep** [comment]
Do whatever you think is best. Now you know why I’m a reluctant Git user.

**Comment by fbrosson** [comment]
@Vidrep, now that I have merged this PR, the gphoto2 recipe has been updated, you can update your [master branch](https://github.com/Vidrep/haikuports).

> This branch is 3 commits ahead, 10 commits behind haikuports:master. 

I can copy/paste the commands here if you need help.
Of course, you can also choose the simple "method": delete your remote repo, and recreate it again.

**Pull request merged**
