### PR TITLE
Gutenprint 5.2.14 recipe and patchset

### PR DESCRIPTION
**Pull request by Vidrep**
Tested working on x86 and x86_64. Fails on x86_gcc2.
Error log attached.

### CODE REVIEW

**Comment by Vidrep** [comment]
[Gutenprint_x86_gcc2_error.txt](https://github.com/haikuports/haikuports/files/2019676/Gutenprint_x86_gcc2_error.txt)

**Comment by Begasus** [comment]
diff --git a/src/main/channel.c b/src/main/channel.c
index 93d8439..b3d9464 100644
--- a/src/main/channel.c
+++ b/src/main/channel.c
@@ -1192,6 +1192,7 @@ stp_channel_get_output_8bit(const stp_vars_t *v)
   if (! cg->output_data_8bit)
     cg->output_data_8bit = stp_malloc(sizeof(unsigned char) * 
 				      cg->total_channels * cg->width);
+  {
   int i;
   (void) memset(cg->output_data_8bit, 0, sizeof(unsigned char) * 
 		cg->total_channels * cg->width);
@@ -1199,4 +1200,5 @@ stp_channel_get_output_8bit(const stp_vars_t *v)
     cg->output_data_8bit[i] = cg->output_data[i] / (unsigned short) 257;
   cg->valid_8bit = 1;
   return cg->output_data_8bit;
+  }
 }
-- 
2.16.2

**Comment by Vidrep** [comment]
Is the diff shown above added as a patch to the gutenprint patset file? Please elaborate.

**Comment by Vidrep** [comment]
Never mind, I figured it out. I simple did a copy/paste of the diff into the patchset and gutenprint now builds OK on x86_gcc2h.

**Comment by Begasus** [comment]
You probably need to re-apply the changes to the patchset to set in:
*hp -b foo (this extracts the current source with the current patchset)
make changes to the file (patch)
in the source tree
*git status (to see you only have the file with the changes)
*git commit -a (with a commit, something like "gcc2 fix")
then in a Terminal do
*hp -e foo 
(hope it's clear enough) :)

**Comment by Vidrep** [comment]
OK changes pushed to master

**Comment by Begasus** [comment]
Looks good to me, still need to check :)

**Comment by fbrosson** [comment]
The recipe builds fine on x86_gcc2 and x86_64.
But there are a few minor errors (e.g. the versions of the libraries), and the patchset was not generated with `hp -e`.
@Vidrep, I can update this PR and take care of these small things if you agree.
(While at it, I'll drop `gutenprint-5.2.13.recipe` and `gutenprint-5.2.13.patchset`. This way we will have a smaller `git log -p`.)

**Comment by Vidrep** [comment]
Be my guest :)

**Pull request merged**
