### PR TITLE
SVT-AV1: bump

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by korli** [comment]
is libVersion correct? SONAME changed?

**Comment by extrowerk** [comment]
The lib have still 0.8.7 as soname.

**Comment by Begasus** [comment]
Any reason why secondary architecture is not enabled @korli ?

**Comment by korli** [comment]
> Any reason why secondary architecture is not enabled @korli ?

https://github.com/AOMediaCodec/SVT-AV1/issues/1231

**Comment by Begasus** [comment]
Thanks :)

**Pull request merged**
