### PR TITLE
psi_plus: bump version to 1.4.1000

### PR DESCRIPTION
**Pull request by tehnick**

### CODE REVIEW

**Comment by tehnick** [comment]
I have just updated a system and see strange configuration error:
```
CMake Error at /boot/system/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
 Found package configuration file:

  /boot/system/lib/cmake/Qt5WebKit/Qt5WebKitConfig.cmake

 but it set Qt5WebKit_FOUND to FALSE so package "Qt5WebKit" is considered to
 be NOT FOUND. Reason given by package:

 Qt5WebKit could not be found because dependency is required to have exact
 version 5.13.x.
```

Before update all were built fine. Any idea what is changed?

**Comment by tehnick** [comment]
> I have just updated a system

Previous update was somewhere in summer, so a lot of packages were updated...

**Comment by tehnick** [comment]
`qtwebkit` and `qtwebkit_devel` packages are installed of course.

**Comment by Begasus** [comment]
I've got a problem with qca packages here, first part builds OK, installs but when it starts on the next part I get "missing: Qca_LIBRARY"

**Comment by Begasus** [comment]
>  Qt5WebKit could not be found because dependency is required to have exact
>  version 5.13.x.
> ```
> 
> Before update all were built fine. Any idea what is changed?

Qt has been bumped to 5.14.0, maybe that is a problem for psi_plus?

**Comment by tehnick** [comment]
> Qt has been bumped to 5.14.0, maybe that is a problem for psi_plus?

I am maintainer of Psi+ for MS Windows, macOS and deb based GNU/Linux distos and in all these systems Psi+ builds fine with Qt 5.14.0...

**Comment by Begasus** [comment]
Was checking the buildlogs:
qwebkit was build on December 15th
Qt5 only passed the build at December 30th
That's probably why qwebkit is still linked to the previous Qt5 version? Maybe a revbump could help here @threedeyes ?

**Comment by Begasus** [comment]
> > Qt has been bumped to 5.14.0, maybe that is a problem for psi_plus?
> 
> I am maintainer of Psi+ for MS Windows, macOS and deb based GNU/Linux distos and in all these systems Psi+ builds fine with Qt 5.14.0...

Yes, saw that on you github page, checking a revbump for qwebkit here

**Comment by tehnick** [comment]
> checking a revbump for qwebkit here

Thanks!

**Comment by Begasus** [comment]
Have to give qwebkit a go later when I don't need anything else (takes too long to build) :)

**Comment by tehnick** [comment]
I'll update Psi+ to 1.4.1000 in this PR.

**Comment by korli** [comment]
should be better with qtwebkit-5.212.0~pre20191212-2

**Comment by Begasus** [comment]
Could you also rename the recipe while you are at it? :)

**Comment by tehnick** [comment]
@Begasus I have renamed it locally, but have forgot to run `git add .`. Thanks!

**Comment by tehnick** [comment]
Done.

**Pull request merged**
