### PR TITLE
gemrb: clean up libSDL dependencies

### PR DESCRIPTION
**Pull request by Ra-V2**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Btw, we also had a new release, among other things removing the need for the manual patching.

**Comment by Begasus** [comment]
Thanks for pointing this out @lynxlynxlynx !
@Ra-V2 could you bump version while you are at it? :)

**Comment by Begasus** [comment]
Thanks! Could you provide a build log for this?

**Comment by Ra-V2** [comment]
Build log:
[gemrb.txt](https://github.com/haikuports/haikuports/files/4080307/gemrb.txt)

**Comment by Begasus** [comment]
Maybe add DISABLE_SOURCE_PACKAGE="yes"

**Comment by Begasus** [comment]
@korli I've got "--no-source-packages" in my profile, so they are disabled by default, when do we use DISABLE_SOURCE_PACKAGE="yes" and when not? (saw in some build logs that they are build there)

**Comment by Begasus** [comment]
nvm, https://github.com/haikuports/haikuports/wiki/HaikuPorter-BuildRecipes#disable_source_package
Strike the remark @Ra-V2 :)

**Pull request merged**
