### PR TITLE
asylum, new recipe for an old arcade game

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Not tested on x86_64, but it builds ok with gcc7, patch to set the path to the user settings may not be the best (the best I could do :) ) but it's working ok like that :)

**Comment by fbrosson** [comment]
I've tested on x86_64 (and x86_gcc2) and the game works fine.

BTW, I added the "wip-no-merge" label because I would like to suggest a couple of neutral changes to make the patchset smaller.
Shall I push an extra commit? Or would you prefer to have comments with diffs?
Hmm, let me push the commit. I can "eat" it afterwards if you don't like it :smile:
Of course, you can also overwrite it with anything you prefer.

**Comment by fbrosson** [comment]
@Begasus, shall I remove the "wip-no-merge" label? Or would you prefer that I drop the commit I added?

**Comment by Begasus** [comment]
Won't be checking out today, I got a feeling you know what you're doing :) Otherwise I'll check tomorrow

**Comment by Begasus** [comment]
I'll look into it later today :)

**Comment by Begasus** [comment]
Looks ok to me @fbrosson, can we merge? :)

**Comment by Begasus** [comment]
Now I need a way to rebase with your changes @fbrosson before I can push my new changes:
binary -> appsDir + DeskbarSymlink

**Comment by fbrosson** [comment]
```
git checkout asylum # if you're not already on that branch
git pull origin asylum
EDITOR=vi git rebase -i HEAD~2 # then type `j3xrfZZ` (this will replace the "pick" in line 2 by a "f")
```

**Comment by fbrosson** [comment]
@Begasus: Of course, what the above commands do is squash the 2 commits in this PR, so you'll need to  `git push --force` (or `git push --force --set-upstream origin asylum` if you had used `git branch -M asylum asylum-old && git checkout -b asylum asylum-old` before rebasing.)

**Comment by Begasus** [comment]
Doesn't seem to work and i don't wont to mess up, the patch to make it launch from Tracker is here: https://pastebin.com/VAJGfKZJ
Then I altered the path for the binary in the recipe to use appsDir/Asylum instead of binDir/asylum (also in provides app:Asylum instead of cmd:asylum and last added the DeskbarSymlink), ow and created appsDir instead of binDir with mkdir

**Comment by Begasus** [comment]
eeps, got one to many now :/

**Comment by fbrosson** [comment]
Sorry, I think I have overwritten your `git push` with mine because I had to use `--force`.
Would you like to practice some git rebasing ?
```diff
git pull
EDITOR=vi git rebase -i HEAD~3 # then type "j3xrfj3xrfZZ" without the quotes in order to replace the "pick" in lines 2 and 3 by a "f"
git push -f
```

**Comment by Begasus** [comment]
Wouldn't git pull just pull the changes on my fork, not the changes here?

**Comment by fbrosson** [comment]
No. If you have correctly set your remote branch then `git pull` should fetch the commits on this PR to your local branch.
But if you made local changes then you would need to e.g.
```
git branch -M asylum asylum-wip
git fetch origin asylum
git checkout -b asylum origin/asylum
```
But don't worry. We can merge this PR as is, using the "Squash and merge" method.
Of course, if you wish to practice that's ok. We can merge later, whenever you wish.

**Comment by Begasus** [comment]
My setup: working branch ~/haikuports, my fork for pushing ~/haikuport_games
My remote -v
~/haikuport_games> git remote -v
origin  https://github.com/Begasus/haikuports.git (fetch)
origin  https://github.com/Begasus/haikuports.git (push)
upstream        https://github.com/haikuports/haikuports.git (fetch)
upstream        https://github.com/haikuports/haikuports.git (push)

**Comment by Begasus** [comment]
@fbrosson best merge it before I screw things over ;) (should need an extra sandbox for it and it would lead to too much noise here) :)

**Pull request merged**
