### PR TITLE
Free:ac - bump revision, icon added

### PR DESCRIPTION
**Pull request by lelldorin**

### CODE REVIEW

**Comment by humdingerb** [comment]
Since Robert was very active with his Haiku port (even visiting BeGeistert), I feel it's a bit rude to change the icon without his permission.

As I said at the forums, this should be a pull-request for resources/resources.rdef at https://github.com/enzo1982/freac

**Comment by lelldorin** [comment]
First there are no icon available for it. Second i send him the icon with a mail and get no aswer. And third no one need to activate my upload and pull request, we can wait Robert give it free by himself.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.01.21, 08:13 schrieb humdinger <notifications@github.com>:

   
  Since Robert was very active with his Haiku port (even visiting BeGeistert), I feel it's a bit rude to change the icon without his permission. 
  As I said at the forums, this should be a pull-request for resources/resources.rdef at https://github.com/enzo1982/freac

**Comment by humdingerb** [comment]
Not sure I understand you 100%. Do you want to do a PR for the .rdef at Robert's github and close this one?

**Comment by lelldorin** [comment]
I remove all changes of the recipe to add the icon. So only the icon is included. -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.01.21, 19:33 schrieb humdinger <notifications@github.com>:

   
  Not sure I understand you 100%. Do you want to do a PR for the .rdef at Robert's github and close this one?

**Comment by humdingerb** [comment]
I made a PR at the freac github: https://github.com/enzo1982/freac/pull/185

**Comment by Begasus** [comment]
Closing this as a newer version is already merged and an upstream PR has been filed

**Pull request closed without merging**
