### PR TITLE
libsdl2: bump

### PR DESCRIPTION
**Pull request by BeagleJoe**

### CODE REVIEW

**Comment by BeagleJoe** [comment]
It looks to me that all the patches from version 2.0.14 have been upstreamed to SDL.
If future patches are to be upstreamed, it makes sense to base them off the latest version.

**Comment by waddlesplash** [comment]
There's also #4535 which we should probably incorporate.

**Comment by waddlesplash** [comment]
BTW, how much did you test this?

**Comment by BeagleJoe** [comment]
> BTW, how much did you test this?

Almost none so far.  SDL2-2.0.18 was just released a few days ago.
On Haiku, it should be essentially the same as 2.0.14 with all the patches applied.

**Comment by BeagleJoe** [comment]
> There's also #4535 which we should probably incorporate.
Yes, definitely needed.
I forgot that @threedeyes already has plans to do this:
https://github.com/haikuports/haikuports/commit/543946ffd9df80f0a78b5cf5185c3ca5e1d135c7#commitcomment-60149375
It still might be better to start from 2.0.18

**Comment by kenmays** [comment]
@BeagleJoe - libsdl2 2.0.18-1 is now in repo.

**Comment by BeagleJoe** [comment]
> @BeagleJoe - libsdl2 2.0.18-1 is now in repo.

@kenmays - Where? I don't see it at 
https://github.com/haikuports/haikuports/tree/master/media-libs/libsdl2

**Comment by kenmays** [comment]
Sorry. The files are in the LOTE repo.
LOTE: http://haikuware.ru/package_list.php?repo=lote
- http://haikuware.ru/repo/lote/packages/libsdl2-2.0.18-1-x86_64.hpkg
- http://haikuware.ru/repo/lote/packages/libsdl2_devel-2.0.18-1-x86_64.hpkg

**Comment by BeagleJoe** [comment]
Is there some reason why SDL2 cannot be updated at HaikuPorts ?

**Comment by kenmays** [comment]
@BeagleJoe - Request with @threedeyes - does it fix all of your remaining issues?

**Comment by threedeyes** [comment]
I'm still doing some testing. Found at least one application that does not work with this version - 0AD game.

**Comment by BeagleJoe** [comment]
> I'm still doing some testing. Found at least one application that does not work with this version - 0AD game.

@threedeyes - Ok, thanks. I installed libsdl2-2.0.18 from LOTE:

In my initial testing, this fixes #6257 

Also works with a test app I have for live switching openGL contexts.

What did not work with 0AD ? 

I can try it with SDL2-2.0.16, if you would like.

**Comment by threedeyes** [comment]
>> What did not work with 0AD ?

Crash on start

**Comment by BeagleJoe** [comment]
> > > What did not work with 0AD ?
> 
> Crash on start

Just installed and it ran OK for me. Maybe it packages it own SDL2 ?

**Comment by threedeyes** [comment]
> Just installed and it ran OK for me

with sdl2 from LOTE repo?

**Comment by BeagleJoe** [comment]
> with sdl2 from LOTE repo?

Yes. 
screenshot0ad

**Comment by BeagleJoe** [comment]
I installed hrev55742 x86_64 to a newly created partition.
Installed libsdl2-2.0.18-1-x86_64.hpkg (from LOTE).
Installed 0ad (via pkgman install)
Played 15 minutes with 0ad. No problems.
Installed speed_dreams. #6257 seems fixed.
Installed mame. #6486 did not occur.

I tried installing libsdl2-2.0.18-1-x86_64.hpkg on Haiku R1B3 but the package requires  hrev55742.
If you can post recipe and patchset somewhere, I will try to build with HaikuPorter on R1B3.

**Pull request closed without merging**
