### PR TITLE
ProjectConceptor [fix build on x86_64]

### PR DESCRIPTION
**Pull request by bach5000**
Fixed build on x86_64.

### CODE REVIEW

**Comment by alaviss** [comment]
I'd be appreciated if you could upstream this patchset instead :)

**Comment by bach5000** [comment]
@alaviss To the owner of ProjectConceptor? Sure :)

**Comment by Begasus** [comment]
Compare your changes to the latest changes at the resource (maybe start from the most recent srcGitRev checkout?)

**Comment by bach5000** [comment]
@Begasus Seems like the author only changed the directories and updated the Makefile since this revision.
I'll make a new patchset.

**Comment by Begasus** [comment]
Even then @bach5000 starting out from the most recent commit should be used (when it doesn't brake the build) :)

**Comment by Begasus** [comment]
Still builds ok on x86_gcc2 (primary architecture) :+1:

**Comment by bach5000** [comment]
@Begasus Could you check my GCI task? :)

**Comment by Begasus** [comment]
Just checked for primary arch in x86_gcc2, stilll need to check on x86_64 :)

**Comment by bach5000** [comment]
Thanks, @Begasus! :D

**Comment by Begasus** [comment]
Build is ok on x86_64, but upon closing the app it crashes (will try to upload a report later)

**Comment by bach5000** [comment]
@Begasus This crash seems to be caused by a bug in ProjectConceptor... I might have to make a new issue on the upstream repo.
I'll also make a PR on the upstream repo :)

**Comment by korli** [comment]
This patch leaves me puzzled and should be declined. Casting pointers to int32 will eventually lead to problems.
For instance the map<int32,BMessage*> is used with pointers as keys.  Why not just switch to map<void*,BMessage*>?

**Comment by bach5000** [comment]
@korli I found out that I could use "-fpermissive" to get the build to run... I don't know if this would be a valid patch though...

**Comment by korli** [comment]
@bach5000 no,  "-fpermissive" just hides the mess, while the problems pointed by the compiler are true problems for x86_64.

**Comment by alaviss** [comment]
Can you update the version to `0.1.0_<date of commit in yyyymmdd>`. Also, it would be nice to upstream the patchset.

**Comment by Begasus** [comment]
New version release, might be good to investigate if the patch still applies :)

**Comment by Paradoxianer** [comment]
Thank you for alle the work done here, i will look into the issue with the x86_64 it as soon as i have a 64 Haiku running. There are definitly some serios problemes with my code here... not shure if i can fix it fast... since i didnt looked at the code for nearly a year and did no serios devolpment for serveral years... thank you @korli for the tipp with the map

**Comment by Begasus** [comment]
Closing this one as wip is on the way in the new version https://github.com/haikuports/haikuports/pull/4405

**Pull request closed without merging**
