### PR TITLE
pipepanic, no need for $secondaryArchSuffix

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by korli** [comment]
This is kind of a useless change, isn't it?

**Comment by Begasus** [comment]
Maybe, but iirc there has been a conversation to not use X86 architectures if not needed ...

**Comment by korli** [comment]
Hmm yeah as secondary arch, it's fine as primary arch.
-1 from me.

**Comment by Begasus** [comment]
Even if it builds with gcc2_x86?

**Comment by waddlesplash** [comment]
The recipe does not (and will never) need to be built on anything but primary arch; so there's no need to have the machinery for that in the recipe file.

**Comment by korli** [comment]
Augustin, IMO you should really think twice before merging any patch that comes up. Just have a look at the commit message... This commit also changes supported primary architectures for no good reason.
This kind of cleanup can be done through a script. Why should we accept such a change for one recipe only, this is more pollution. Just my thought.

**Comment by waddlesplash** [comment]
> This kind of cleanup can be done through a script. Why should we accept such a change for one recipe only, this is more pollution. Just my thought.

Ah, true, that's a good point. Makes sense; I'll reject changes like this in the future.

**Pull request merged**
