### PR TITLE
nss, restore 3.46.1

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
@diversys could you check, last version bump deleted this one (needed for libreoffice amongst others), don't have the time today to check a build ...

**Comment by Begasus** [comment]
Both this one and version 3.52.1 fail to build on 32bit, @kenmays could you have a look here?

**Comment by Begasus** [comment]
For 3.52.1:
```
make[2]: Entering directory '/sources/nss-3.52.1/lib/certdb'
gcc -o BeOS1_PTH_OPT.OBJ/alg1485.o -c -std=c99 -O2 -fPIC -Di386 -Wall -Wno-switch -pipe -Wall -Wshadow -Werror -DXP_BEOS -DXP_HAIKU -UDEBUG -DNDEBUG -DBEOS -D_REENTRANT -DNSS_DISABLE_AVX2 -DNSS_NO_INIT_SUPPORT -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES -I../../../dist/BeOS1_PTH_OPT.OBJ/include -I../../../dist/public/nss -I../../../dist/private/nss  alg1485.c
gcc -o BeOS1_PTH_OPT.OBJ/certdb.o -c -std=c99 -O2 -fPIC -Di386 -Wall -Wno-switch -pipe -Wall -Wshadow -Werror -DXP_BEOS -DXP_HAIKU -UDEBUG -DNDEBUG -DBEOS -D_REENTRANT -DNSS_DISABLE_AVX2 -DNSS_NO_INIT_SUPPORT -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES -I../../../dist/BeOS1_PTH_OPT.OBJ/include -I../../../dist/public/nss -I../../../dist/private/nss  certdb.c
In file included from ../../../dist/public/nss/seccomon.h:27,
                 from cert.h:18,
                 from certdb.c:12:
certdb.c: In function 'CERT_UnlockCertRefCount':
../../../dist/public/nss/secport.h:127:24: error: implicit declaration of function 'PR_ASSERT_ARG'; did you mean 'PR_ASSERT'? [-Werror=implicit-function-declaration]
 #define PORT_AssertArg PR_ASSERT_ARG
                        ^~~~~~~~~~~~~
certdb.c:2893:5: note: in expansion of macro 'PORT_AssertArg'
     PORT_AssertArg(prstat == PR_SUCCESS);
     ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
../../coreconf/rules.mk:392: recipe for target 'BeOS1_PTH_OPT.OBJ/certdb.o' failed
make[2]: *** [BeOS1_PTH_OPT.OBJ/certdb.o] Error 1
make[2]: Leaving directory '/sources/nss-3.52.1/lib/certdb'
```

**Comment by kenmays** [comment]
@Begasus  - Needs NSPR 4.25+ (fixes the issue, mentioned in PR). I think R1B2 is built on NSPR 4.19-1.

**Comment by Begasus** [comment]
> @Begasus - Needs NSPR 4.21+ (fixes the issue, mentioned in PR). I think R1B2 is built on NSPR 4.19-1.

But that doesn't explain why the previous version 3.46.1 doesn't build anymore (or it was an old build that hasn't been updated since it was merged?)

**Comment by Begasus** [comment]
@kenmays same error when using nspr 4.23 ...

**Comment by kenmays** [comment]
I mentioned NSPR 4.25+ earlier, but the PR_ASSERT change happened in NSPR 4.21. Seems NSPR 4.26 is preferred overall.
The older NSS builds see to break due to some recent kernel changes. Reviewing.

**Comment by Begasus** [comment]
Thanks, we need to get this fixed :)

**Pull request closed without merging**
