### PR TITLE
Gerbera: bump

### PR DESCRIPTION
**Pull request by extrowerk**
Still cant't find its sql file:
```
error: File '/packages/gerbera-1.7.0~git-1/.self/share/gerbera/sqlite3.sql' does not exist
```

Good luck grepping for "share" in the sources of a media sharing program :(

### CODE REVIEW

**Comment by Begasus** [comment]
This one?

https://github.com/gerbera/gerbera/blob/6e98805242c8b3f7cc08d2200b9e3a36163b6755/CMakeLists.txt#L560

**Comment by Begasus** [comment]
At least duktape needs to be fixed for x86_gcc2 (got one in the pipeline for that)

**Comment by Begasus** [comment]
Adding ```<init-sql-file>/system/data/gerbera/sqlite3.sql</init-sql-file>``` before line https://github.com/haikuports/haikuports/blob/1780b2c92f88c880d46551199d64c6a9f03e6151/net-misc/gerbera/additional-files/config.xml#L29 worked here, but gerbera crashed after launch ;)

**Comment by extrowerk** [comment]
We should decomission mediatomb now

**Comment by Begasus** [comment]
> worked here, but gerbera crashed after launch ;)

I would leave it for now, issue is still the same as before (I think it's about the same why mediatomb wouldn''t work on 64bit?)

**Pull request merged**
