### PR TITLE
Slang: bump version

### PR DESCRIPTION
**Pull request by miqlas**

### CODE REVIEW

**Comment by miqlas** [comment]
Please ,do not merge yet.

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1486
@miqlas could you see it this works for you?

**Comment by scottmc** [comment]
Check it with Jed.

**Comment by Begasus** [comment]
Will do later :) thanks for the pointer :)

**Comment by Begasus** [comment]
Jed compiled fine and is working ok here ...

**Pull request closed without merging**
