### PR TITLE
crawl: new recipe

### PR DESCRIPTION
**Pull request by Crestwave**
(Patch will be submitted upstream after this gets merged)

### CODE REVIEW

**Comment by Begasus** [comment]
64bit failed on buildmaster: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5905/builds/75642.log

**Comment by korli** [comment]
github.com|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... Read error (Operation timed out) in headers.
Giving up.

**Comment by Begasus** [comment]
Same SOURCE_URI worked for 32bit though?

**Comment by Crestwave** [comment]
Yeah and given that it timed out connecting to _GitHub itself_, it's probably an issue with the system's connection.
There's also this preceding part:
```
Resolving github.com... failed: Operation timed out.
wget: unable to resolve host address ‘github.com’
```

**Comment by korli** [comment]
build is now successful

**Pull request merged**
