### PR TITLE
git: bump to 2.16.4.

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
For some reason, unknown to me, git was passing most of the tests until recently on all architectures.

Commit | Date | Commit title | Comments
-- | -- | -- | --
a195721b7c38acb42ea3d1dd73bf6d1eba83c116 | 2016-08-21 | `git: bump to 2.9.3, pass PERL_PATH=/bin/perl to make.` | Thanks to this commit, `hp --test git` has started working fine.
7c5e78e9f876724495f55a503aa477bd6b6631a2 | 2018-01-25 | `git: bump to 2.16.1.` | This was the last time the tests were working on all architectures.
6f255120a9b432f8d5c9433cfb21814d7f2dc530 | 2018-02-09 | `bash: bump to 4.4.019.` | **Question:** Could this be origin of the test failures in git?
99b5ce0a6ffec38d8db4304ec4fc2f58108a9253 | 2018-02-10 | `perl 5.26: mark as tested on x86_gcc2` | **Question:** Or is it the transition from perl 5.18 to 5.26 which is making most git tests to fail?
7eafec092dd8d33daf689dd0f9826d2ee9f2670f | 2018-02-14 | `libedit: bump to 20170329-3.1` | **Question:** Or was it this change which broke the tests in git?
3935ef1eb61d666dfa3d3c4338ffd0d434170853 | 2018-02-19 | `git: bump to 2.16.2.` | The tests have started to fail on x86_gcc2 and x86_64 (but are still OK on x86.)
This PR | 2018-03-?? | `git: bump to 2.16.3.` | Shall we merge this?

When I tested git 2.16.1 on x86_64 I believe I was still using perl 5.18, so most of the tests were OK.

For every bump since 2.16.2, git fails most of the tests on x86_gcc2 and x86_64, while it still passes most tests on x86. This is what made me think that the problem was not in git itself.

I've been trying to figure out what was causing the tests to fail on x86_gcc2 and x86_64.
Is it the bump to bash 4.4.019, to perl 5.26, or to libedit 20170329-3.1? Or is it a Haiku itself? (I'm using hrev51205 on x86, as it was the last official update for that arch.)
This is puzzling. I've been trying to investigate this since the bump to 2.16.2...
Help would be very welcome. Thanks!

BTW, the tests for 2.16.3 on x86 are identical to those of 2.16.2 on that same arch:
```
*** t0000-basic.sh ***
...
# passed all 78 test(s)
1..78


*** t0001-init.sh ***
...
# passed all 44 test(s)
1..44


*** t0002-gitfile.sh ***
...
# passed all 14 test(s)
1..14


*** t0003-attributes.sh ***
...
# passed all 24 test(s)
1..24


*** t0004-unwritable.sh ***
...
# passed all 5 test(s)
1..5


*** t0005-signals.sh ***
ok 1 - sigchain works
ok 2 - signals are propagated using shell convention
ok 3 - create blob
not ok 4 - a constipated git dies with SIGPIPE
#	
#		OUT=$( ((large_git; echo $? 1>&3) | :) 3>&1 ) &&
#		test_match_signal 13 "$OUT"
#	
not ok 5 - a constipated git dies with SIGPIPE even if parent ignores it
#	
#		OUT=$( ((trap "" PIPE; large_git; echo $? 1>&3) | :) 3>&1 ) &&
#		test_match_signal 13 "$OUT"
#	
# failed 2 among 5 test(s)
1..5
make[2]: *** [Makefile:51: t0005-signals.sh] Error 1
make[2]: Leaving directory '/sources/git-2.16.3/t'
make[1]: *** [Makefile:38: test] Error 2
make[1]: Leaving directory '/sources/git-2.16.3/t'
make: *** [Makefile:2467: test] Error 2
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
Error: Test has failed - stopping.
```

The tests for 2.16.3 on x86_gcc2 and x86_64 are also the same as those of 2.16.2 on these same architectures. And 2.16.2 seems to be working fine on all architectures, so I think we can merge this PR. I'll wait a few days before the merge, in case someone would prefer to stick to 2.16.2, but I think the problem is not in git itself, but in the test suite.

**Comment by alaviss** [comment]
We should investigate it. `git` appears to die over `SIGPIPE`, so I assume the other side of the pipe died (unlikely, it's `/bin/true` after all), or bash got weird when constructing a pipe, or there is a problem in how the OS handle pipes.

Does the tests passes on x86 with the new bash, perl, libedit? If so then it would suggest a possible Haiku bug. But again, I can't run any VMs right now, so this is all just speculation.

**Comment by korli** [comment]
There were a few commits related to select()/poll() of pipes in hrev51811. Might be an idea to check before and after.

**Comment by fbrosson** [comment]
Cool, thanks @korli for the hint about the commits in hrev51811.

Well, this is a separate issue which already affected git before 2.16.3.
My biggest issue is that I'm quite sure that between ~`2018-01-25` and ~`2018-02-19` there was a change in Haiku which made most tests start to fail. (The small copy/paste is just for the small number of tests that were already failing.)
What I have indeed noticed is that until `hrev51205` any version of git passes all tests.
And that between January 25 and February 19 there was a change that makes any version of git fail the tests.

What I need to do is:
* install old Haiku systems (x86_gcc2 and x86_64) and check that git passes most the tests again.
* build a recent Haiku x86 and check that git fails most tests again.

BTW, I have already followed @alaviss's suggestion (about installing the new releases of bash, perl, and libedit on my old x86 system) and noticed that these new releases are not the cause of the test failures of git. (I've updated my comment accordingly, some time ago.)

**Comment by fbrosson** [comment]
Let's merge this! `2.16.4` is as good as `2.16.3`, which is as good as `2.16.2`.
On x86, all these versions pass most of the tests, while on x86_gcc2 and x86_64, all these versions fail on many more tests.
The reason why the tests are not OK is not related to git itself but to Haiku.
Postponing the merge is useless. If something was really broken we would already have noticed it with `2.16.2`.

FWIW, the tests on x86 are here:
<Details>

```
Testing ...
    SUBDIR perl
    SUBDIR templates
make -C t/ all
make[1]: Entering directory '/sources/git-2.16.4/t'
rm -f -r 'test-results'
make aggregate-results-and-cleanup
make[2]: Entering directory '/sources/git-2.16.4/t'
*** t0000-basic.sh ***
ok 1 - verify that the running shell supports "local"
ok 2 - .git/objects should be empty after git init in an empty repo
ok 3 - .git/objects should have 3 subdirectories
ok 4 - success is reported like this
ok 5 - pretend we have a fully passing test suite
ok 6 - pretend we have a partially passing test suite
ok 7 - pretend we have a known breakage
ok 8 - pretend we have fixed a known breakage
ok 9 - pretend we have fixed one of two known breakages (run in sub test-lib)
ok 10 - pretend we have a pass, fail, and known breakage
ok 11 - pretend we have a mix of all possible results
ok 12 - test --verbose
ok 13 - test --verbose-only
ok 14 - GIT_SKIP_TESTS
ok 15 - GIT_SKIP_TESTS several tests
ok 16 - GIT_SKIP_TESTS sh pattern
ok 17 - --run basic
ok 18 - --run with a range
ok 19 - --run with two ranges
ok 20 - --run with a left open range
ok 21 - --run with a right open range
ok 22 - --run with basic negation
ok 23 - --run with two negations
ok 24 - --run a range and negation
ok 25 - --run range negation
ok 26 - --run include, exclude and include
ok 27 - --run include, exclude and include, comma separated
ok 28 - --run exclude and include
ok 29 - --run empty selectors
ok 30 - --run invalid range start
ok 31 - --run invalid range end
ok 32 - --run invalid selector
ok 33 - test runs if prerequisite is satisfied
ok 34 # skip unmet prerequisite causes test to be skipped (missing DONTHAVEIT)
ok 35 - test runs if prerequisites are satisfied
ok 36 # skip unmet prerequisites causes test to be skipped (missing DONTHAVEIT of HAVEIT,DONTHAVEIT)
ok 37 # skip unmet prerequisites causes test to be skipped (missing DONTHAVEIT of DONTHAVEIT,HAVEIT)
ok 38 - test runs if lazy prereq is satisfied
ok 39 # skip missing lazy prereqs skip tests (missing !LAZY_TRUE)
ok 40 - negative lazy prereqs checked
ok 41 # skip missing negative lazy prereqs will skip (missing LAZY_FALSE)
ok 42 - tests clean up after themselves
ok 43 - tests clean up even on failures
ok 44 - git update-index without --add should fail adding
ok 45 - git update-index with --add should succeed
ok 46 - writing tree out with git write-tree
ok 47 - validate object ID of a known tree
ok 48 - git update-index without --remove should fail removing
ok 49 - git update-index with --remove should be able to remove
ok 50 - git write-tree should be able to write an empty tree
ok 51 - validate object ID of a known tree
ok 52 - adding various types of objects with git update-index --add
ok 53 - showing stage with git ls-files --stage
ok 54 - validate git ls-files output for a known tree
ok 55 - writing tree out with git write-tree
ok 56 - validate object ID for a known tree
ok 57 - showing tree with git ls-tree
ok 58 - git ls-tree output for a known tree
ok 59 - showing tree with git ls-tree -r
ok 60 - git ls-tree -r output for a known tree
ok 61 - showing tree with git ls-tree -r -t
ok 62 - git ls-tree -r output for a known tree
ok 63 - writing partial tree out with git write-tree --prefix
ok 64 - validate object ID for a known tree
ok 65 - writing partial tree out with git write-tree --prefix
ok 66 - validate object ID for a known tree
ok 67 - put invalid objects into the index
ok 68 - writing this tree without --missing-ok
ok 69 - writing this tree with --missing-ok
ok 70 - git read-tree followed by write-tree should be idempotent
ok 71 - validate git diff-files output for a know cache/work tree state
ok 72 - git update-index --refresh should succeed
ok 73 - no diff after checkout and git update-index --refresh
ok 74 - git commit-tree records the correct tree in a commit
ok 75 - git commit-tree records the correct parent in a commit
ok 76 - git commit-tree omits duplicated parent in a commit
ok 77 - update-index D/F conflict
ok 78 - very long name in the index handled sanely
# passed all 78 test(s)
1..78
*** t0001-init.sh ***
ok 1 - plain
ok 2 - plain nested in bare
ok 3 - plain through aliased command, outside any git repo
ok 4 - plain nested through aliased command
ok 5 - plain nested in bare through aliased command
ok 6 - No extra GIT_* on alias scripts
ok 7 - plain with GIT_WORK_TREE
ok 8 - plain bare
ok 9 - plain bare with GIT_WORK_TREE
ok 10 - GIT_DIR bare
ok 11 - init --bare
ok 12 - GIT_DIR non-bare
ok 13 - GIT_DIR & GIT_WORK_TREE (1)
ok 14 - GIT_DIR & GIT_WORK_TREE (2)
ok 15 - reinit
ok 16 - init with --template
ok 17 - init with --template (blank)
ok 18 - init with init.templatedir set
ok 19 - init --bare/--shared overrides system/global config
ok 20 - init honors global core.sharedRepository
ok 21 - init allows insanely long --template
ok 22 - init creates a new directory
ok 23 - init creates a new bare directory
ok 24 - init recreates a directory
ok 25 - init recreates a new bare directory
ok 26 - init creates a new deep directory
ok 27 - init creates a new deep directory (umask vs. shared)
ok 28 - init notices EEXIST (1)
ok 29 - init notices EEXIST (2)
ok 30 # skip init notices EPERM (missing SANITY of POSIXPERM,SANITY)
ok 31 - init creates a new bare directory with global --bare
ok 32 - init prefers command line to GIT_DIR
ok 33 - init with separate gitdir
ok 34 - init in long base path
ok 35 - init in long restricted base path
ok 36 - re-init on .git file
ok 37 - re-init to update git link
ok 38 - re-init to move gitdir
ok 39 - re-init to move gitdir symlink
ok 40 # skip .git hidden (missing MINGW)
ok 41 # skip bare git dir not hidden (missing MINGW)
ok 42 - remote init from does not use config from cwd
ok 43 - re-init from a linked worktree
ok 44 # skip redirect std handles (missing MINGW)
# passed all 44 test(s)
1..44
*** t0002-gitfile.sh ***
ok 1 - initial setup
ok 2 - bad setup: invalid .git file format
ok 3 - bad setup: invalid .git file path
ok 4 - final setup + check rev-parse --git-dir
ok 5 - check hash-object
ok 6 - check cat-file
ok 7 - check update-index
ok 8 - check write-tree
ok 9 - check commit-tree
ok 10 - check rev-list
ok 11 - setup_git_dir twice in subdir
ok 12 - enter_repo non-strict mode
ok 13 - enter_repo linked checkout
ok 14 - enter_repo strict mode
# passed all 14 test(s)
1..14
*** t0003-attributes.sh ***
ok 1 - open-quoted pathname
ok 2 - setup
ok 3 - command line checks
ok 4 - attribute test
ok 5 - attribute matching is case sensitive when core.ignorecase=0
ok 6 - attribute matching is case insensitive when core.ignorecase=1
ok 7 # skip additional case insensitivity tests (missing CASE_INSENSITIVE_FS)
ok 8 - unnormalized paths
ok 9 - relative paths
ok 10 - prefixes are not confused with leading directories
ok 11 - core.attributesfile
ok 12 - attribute test: read paths from stdin
ok 13 - attribute test: --all option
ok 14 - attribute test: --cached option
ok 15 - root subdir attribute test
ok 16 - negative patterns
ok 17 - patterns starting with exclamation
ok 18 - "**" test
ok 19 - "**" with no slashes test
ok 20 - using --git-dir and --work-tree
ok 21 - setup bare
ok 22 - bare repository: check that .gitattribute is ignored
ok 23 - bare repository: check that --cached honors index
ok 24 - bare repository: test info/attributes
# passed all 24 test(s)
1..24
*** t0004-unwritable.sh ***
ok 1 - setup
ok 2 # skip write-tree should notice unwritable repository (missing SANITY of POSIXPERM,SANITY)
ok 3 # skip commit should notice unwritable repository (missing SANITY of POSIXPERM,SANITY)
ok 4 # skip update-index should notice unwritable repository (missing SANITY of POSIXPERM,SANITY)
ok 5 # skip add should notice unwritable repository (missing SANITY of POSIXPERM,SANITY)
# passed all 5 test(s)
1..5
*** t0005-signals.sh ***
ok 1 - sigchain works
ok 2 - signals are propagated using shell convention
ok 3 - create blob
not ok 4 - a constipated git dies with SIGPIPE
#	
#		OUT=$( ((large_git; echo $? 1>&3) | :) 3>&1 ) &&
#		test_match_signal 13 "$OUT"
#	
not ok 5 - a constipated git dies with SIGPIPE even if parent ignores it
#	
#		OUT=$( ((trap "" PIPE; large_git; echo $? 1>&3) | :) 3>&1 ) &&
#		test_match_signal 13 "$OUT"
#	
# failed 2 among 5 test(s)
1..5
make[2]: *** [Makefile:51: t0005-signals.sh] Error 1
make[2]: Leaving directory '/sources/git-2.16.4/t'
make[1]: *** [Makefile:38: test] Error 2
make[1]: Leaving directory '/sources/git-2.16.4/t'
make: *** [Makefile:2467: test] Error 2
```
</Details>

**Comment by alaviss** [comment]
@fbrosson Can you file an issue on Trac for `git` test failures? Thanks.

**Comment by fbrosson** [comment]
Yeah, well... maybe :)

**Comment by fbrosson** [comment]
It looks like all we needed to add to fix most test failures in `2.16.4`, `2.17.0` and `2.18.0` was a simple `TEST_REQUIRES="cmd:diff"` :smile:
Done with `2.19.0` in 2b4a6858ec6263b596acd9d1f35a1a81795a82f5.

**Pull request merged**
