### PR TITLE
LibreOffice: Update Icon

### PR DESCRIPTION
**Pull request by roired**
Good day,

Tried again this time. Added the HVIF icon to the additional-files and also modified the RDEF.
Hope I don't mess anything now.

### CODE REVIEW

**Comment by roired** [comment]
This is the PNG, I can't paste it here... also plenty of issues with the web interface on WebPositive. Apologies
https://gitlab.com/rrhaiku/haikuicons/-/blob/master/Libreoffice/LibreOffice-new.png

**Comment by diversys** [comment]
Can you add before/after images to so we can see what changed?

**Comment by humdingerb** [comment]
You can download the current hvif from https://depot.haiku-os.org/__pkgicon/libreoffice.hvif?m=1591893024428
and see the icon at https://depot.haiku-os.org/#!/pkg/libreoffice/haikuports/6/4/3.1/-/8/x86_64

**Comment by humdingerb** [comment]
To be 100% correct, the ".hvif" is actually an Icon-O-Matic file. You could rename it to ".iom".

**Comment by roired** [comment]
Good day @humdinger,

Already changed the icon. Now it's the IOM file. Hope I did it right, and thanks for the tips on IOM and its filetypes.
Regards,
RR

**Comment by humdingerb** [comment]
Almost there. :)
The .hvif isn't needed, can you remove it, please? All we need is the .rdef, for the actual icon when the package is built, and the .iom in case someone wants to keep working on the icon. The title of the commit message should be prefixed with "LibreOffice:".
Thanks!

**Comment by roired** [comment]
Well, let's see if now... Crash course on Git, GitHub and GitLab.... XD

**Comment by humdingerb** [comment]
Hmm... I didn't mean you to add another .rdef, just the modified .rdef.in... :)

Let me be 100% specific: There are currently `libreoffice.iom`  and `libreoffice.rdef.in` in the 'additional-files' folder. Just replace those wth your modifiedd versions. No more, no less, and mind the all lower-case of the file names.

**Comment by roired** [comment]
All right... hope now everything is right. Thank god it's just a simple icon and not code, what a mess.. XD

Thanks @humdinger,
Regards,
RR

**Comment by humdingerb** [comment]
>.. what a mess.. XD

No worries. There've been much, much longer review threads at haikuports... :)
Unfortunately, there has just been a re-build of the LibreOffice package. I don't think we should have people update the big HPKG just for a minor change in the icon. I expect the package will be updated soon with actual bugfixes before too long anyway.

**Pull request merged**
