### PR TITLE
irrxml: new recipe

### PR DESCRIPTION
**Pull request by theclue**
libirrxml is a simple and fast open source xml parser for C++

it is used in some open source RPG games, so making a shared version of the library sounded useful to me

### CODE REVIEW

**Comment by Begasus** [comment]
Is there any benefit on using this one (guessing it's as a requirement for assimp?)?

**Comment by theclue** [comment]
> Is there any benefit on using this one (guessing it's as a requirement for assimp?)?

Ehm...if I remember correctly it was u who asked me to provide a shared library for this :D

**Comment by Begasus** [comment]
I know I did :) for what it's worth, did you try to build assimp with system irrxml? (eg this one)

**Comment by theclue** [comment]
> I know I did :) for what it's worth, did you try to build assimp with system irrxml? (eg this one)

no...well...not yet. I eventually will.

**Comment by Begasus** [comment]
assimp is merged, we could always look into this one later :)

**Comment by Begasus** [comment]
@theclue did you try upstreaming the new files? Otherwise for now we could skip this one :)

**Comment by Begasus** [comment]
@theclue made some changes, merged now, you can delete your branch :), thanks for the ground work!

**Pull request merged**
