### PR TITLE
nss, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Updating does not change the behavior for poppler as mentioned in issue: https://github.com/haikuports/haikuports/issues/6335
Updating that one only works for TeXstudio and extractpdfmark if nss is not involved (for poppler)

**Comment by Begasus** [comment]
Packages involved:
- [ ] libfprint
- [x] qca (no revbump needed)
- [ ] qtwebengine_bin
- [ ] xmlsec
- [ ] libpurple
- [ ] qtwebengine
- [ ] libreoffice (revbump)

**Comment by korli** [comment]
I think I have this update locally, but didn't push it yet, trying to solve some runtime_loader issue in the test suite. Is it ok to wait until next week?

**Comment by Begasus** [comment]
> I think I have this update locally, but didn't push it yet, trying to solve some runtime_loader issue in the test suite. Is it ok to wait until next week?

No problem, I'll focus on the packages relying on this one for the time being, I'll put a wip label on it. (breaking my head over it also and searching the net for answers, no luck here either, hence I pushed it to the PR)

**Comment by Begasus** [comment]
@korli any progress on your part?

**Comment by korli** [comment]
I'm trying here to switch to build.sh using gyp. it builds, tests are pending.

**Comment by Begasus** [comment]
Me pokes @korli ;)

**Comment by korli** [comment]
@Begasus  I get lost trying to move to gyp, the possibility of regressions is difficult to assess. Please go ahead for the bump, thanks.

**Comment by Begasus** [comment]
Will take a look at buildmaster if every thing is OK, if need be ... we can always look a head :)

**Pull request merged**
