### PR TITLE
gnutls: cosmetic fix: drop "?x86_64" from secondary arch

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Since @fbrosson apparently doesn't have Haiku installed; to whoever reviews this PR, please test that the recipe builds/works before merging.

**Comment by fbrosson** [comment]
This PR was initialy created to resurrect gnutls 3.4.6 because 3.4.9 was not building.
But this is now solved, thanks to https://github.com/haikuports/haikuports/pull/471 which fixes the recipe for nettle 3.2.
So there seems to be no need to resurrect 3.4.6 anymore.
I am therefore recycling this PR into a cosmetic fix. If you agree, you can merge 471 and then 465. Thanks

**Comment by waddlesplash** [comment]
Squash your changes, please.

**Comment by fbrosson** [comment]
Hi, sorry for the delay. The commit in this PR is already squashed. Were you suggesting that I merge that change into PR 471 (for nettle) and close this PR? What about letting the PR for nettle alone and add a few cleaning edits to this one?
I've noticed that 4 other recipes have x86_64 in their SECONDARY_ARCHITECTURES:
* games-arcade/edgar/edgar-1.16_1.recipe
* haiku-apps/paladin/paladin-git.recipe
* media-libs/sdl2_mixer/sdl2_mixer-2.0.1.recipe
* media-libs/mediainfo/mediainfo-0.7.61.recipe

Instead of merging the commit of this PR with the one for nettle, may I merge to this PR (in a single squashed commit) the removals of these x86_64 as secondary archs for these 4 recipes?

**Pull request merged**
