### PR TITLE
picard: Final 2.2.0 release

### PR DESCRIPTION
**Pull request by phw**
Picard 2.2 has just been released: https://github.com/metabrainz/picard/releases/tag/release-2.2.0

This adds the recipe for this version.

Also notable: Haiku is among the first to receive the new package! Official release announcement will be made tomorrow (we had some build delays today), also the website will be updated then and will feature Haiku on the download page.

### CODE REVIEW

**Comment by diversys** [comment]
You probably want to rename old recipe to new one. Does the new version need patches as well?

**Comment by phw** [comment]
@diversys I'm not familiar with the policies of how old recipes are treated. So I should just remove the old recipe then?



> Does the new version need patches as well?

Yes, they are supplied in https://github.com/haikuports/haikuports/pull/4175/files#diff-bf70196a3abbe742facd90481b76b5aa

**Comment by diversys** [comment]
> @diversys I'm not familiar with the policies of how old recipes are treated. So I should just remove the old recipe then?

Yep.

**Comment by phw** [comment]
Here we go.

**Comment by waddlesplash** [comment]
Looks good! 🎊

**Pull request merged**
