### PR TITLE
libsodium: bump version and remove secondary_arch

### PR DESCRIPTION
**Pull request by return**
libsodium is able to build on all architectures and patches are now up-streamed due to [this commit](https://github.com/jedisct1/libsodium/commit/9cae7b6b7c6f527df807157602ba48821281048b).

### CODE REVIEW

**Comment by korli** [comment]
Any reason to remove secondary architectures? This is actually required for most libraries.

**Comment by return** [comment]
@korli If a recipe 'architectures' field supports all architectures, then the $secondary_arch suffix is not need and can be removed. Or is that not the case with libsodium?

**Comment by korli** [comment]
This is a wrong assumption: libraries can be needed for a secondary​ architecture.

**Comment by pulkomandy** [comment]
"x86" in ARCHITECTURES: the library can be built with gcc5 for a gcc5 system.
"x86" in SECONDARY_ARCHITECTURES: the library can be built with gcc5, for a gcc2hybrid system

The build in both cases is mostly the same, but there are some changed paths and different package metadata, both needing special care. Hence the support for building as secondary arch package needs to be explicit.

**Comment by return** [comment]
OK, my mistake for following those assumptions on removing the architecture suffixes. Is there a need to revert these changes  or open another PR to re-add the suffixes?

**Comment by korli** [comment]
Please add a PR reintroducing the secondary suffixes.

**Comment by return** [comment]
@korli OK, I have opened a PR addressing this at #1217

**Pull request merged**
