### PR TITLE
(GCI) Removed ?x86_64 from recipies that build on x86_64

### PR DESCRIPTION
**Pull request by hermord**
Got a bunch of recipes to build on x86_64, modified where needed. Updated ARCHITECTURES to reflect the fact.

### CODE REVIEW

**Comment by korli** [comment]
Please leave gcc6 and gcc7 out. There are marked with ? to avoid building them yet.

**Comment by korli** [comment]
And you should bump the revision for gcc6 and gcc7 if you intend to fix the PROVIDES.

**Comment by korli** [comment]
Never mind, I tweaked the recipes myself :)

**Comment by hermord** [comment]
Sorry, it was night in my timezone. Thanks a lot, could you please have a look at the GCI task as well?

**Comment by korli** [comment]
You should link this PR in the GCI task for this to happen.

**Comment by hermord** [comment]
:thumbsup: Thanks, I'll do just that, then.

**Pull request merged**
