### PR TITLE
advancemame, bump, fix build for _x86

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Not checked if this works for x86_64, maybe the patch for _x86 should be in a separate patchset?
(and maybe the variables used are not the correct ones) :) waiting for reply's :)

**Comment by Begasus** [comment]
Related to https://github.com/haikuports/haikuports/issues/3594?

**Comment by extrowerk** [comment]
Pls remove old versions.

**Comment by extrowerk** [comment]
On 64 bit:
```
/boot/system/develop/headers/os/support/SupportDefs.h:25:26: error: conflicting types for 'uint32'
typedef __haiku_uint32   uint32;
```

**Comment by extrowerk** [comment]
Without the x86 patch it builds fine on 64 bit. Please move the patch into a separate patchfile and guard it with targetarch == x86 or something so it won't be applied on 64 bit.

**Comment by Begasus** [comment]
@extrowerk Could you check? Moved the fix to a seperate patchset

**Comment by Begasus** [comment]
Should be good to go now, if someone could check this on x86_64?

**Pull request merged**
