### PR TITLE
mupen64plus: Fix build and use Boost 1.70

### PR DESCRIPTION
**Pull request by robxnano**

### CODE REVIEW

**Comment by Begasus** [comment]
Build failure on 32bit: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3802/builds/79773.log

**Comment by robxnano** [comment]
Sorry, I don't know why it's not working. Since the problem seems to be with LTO, maybe it would be okay to just disable it for the x86 build?

**Comment by diversys** [comment]
Either that or you could try to disable ASLR with ```export DISABLE_ASLR=1```.

**Comment by robxnano** [comment]
> Either that or you could try to disable ASLR with `export DISABLE_ASLR=1`.

Thanks, that fixed it.

**Pull request merged**
