### PR TITLE
Opensound: introduce x86_64 support

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by extrowerk** [comment]
I'm stupid, i already did a PR for this.

**Comment by scottmc** [comment]
if this is still the active open pull request for this, please update it to remove the conflicts.

**Comment by scottmc** [comment]
already done?

**Comment by extrowerk** [comment]
Tested, not working on "vendor 8086: Intel Corporation / device 1e20: 7 Series/C216 Chipset Family High Definition Audio Controller
 (17aa/3977)", thanks cardboard65

**Comment by extrowerk** [comment]
According to the syslog from cardboard65:
```KERN: Could not load kernel add-on "/boot/system/add-ons/kernel/drivers/bin/oss_loader": Bad data```

**Comment by mikedebian** [comment]
Hello.

Is there an hpkg available? I'd like to test this.

[Link to dev ticket](https://dev.haiku-os.org/ticket/14799)

**Comment by extrowerk** [comment]
@mikedebian : Nope.

**Comment by diversys** [comment]
Superseded by 635ae302da93740826f7702ae5b2ae6501e091ef.

**Pull request closed without merging**
