### PR TITLE
FFTW: bump, soname unchanged

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by extrowerk** [comment]
Ouch:
```
bench: ../../libbench2/verify-lib.c:53: assertion failed: !isnan(e)
FAILED /sources/fftw-3.3.9/long-double/tests/bench:  --verify 'obr8x13x3v12' --verify 'ibr8x13x3v12' --verify 'ofr8x13x3v12' --verify 'ifr8x13x3v12' --verify '//obc8x13x3v12' --verify '//ibc8x13x3v12' --verify '//ofc8x13x3v12' --verify '//ifc8x13x3v12' --verify 'obc8x13x3v12' --verify 'ibc8x13x3v12' --verify 'ofc8x13x3v12' --verify 'ifc8x13x3v12' --verify 'ok13e01v6' --verify 'ik13e01v6' --verify 'obr7x5v19' --verify 'ibr7x5v19' --verify 'ofr7x5v19' --verify 'ifr7x5v19' --verify '//obc7x5v19' --verify '//ibc7x5v19' --verify '//ofc7x5v19' --verify '//ifc7x5v19' --verify 'obc7x5v19' --verify 'ibc7x5v19' --verify 'ofc7x5v19' --verify 'ifc7x5v19' --verify 'okd32e11*21' --verify 'ikd32e11*21' --verify '//obrd12960' --verify '//ibrd12960' --verify '//ofrd12960' --verify '//ifrd12960' --verify 'obrd12960' --verify 'ibrd12960' --verify 'ofrd12960' --verify 'ifrd12960' --verify '//obcd12960' --verify '//ibcd12960' --verify '//ofcd12960' --verify '//ifcd12960' --verify 'obcd12960' --verify 'ibcd12960' --verify 'ofcd12960' --verify 'ifcd12960'
```

**Comment by Begasus** [comment]
No errors on the test run here (32-bit)

**Comment by Begasus** [comment]
Superseded by https://github.com/haikuports/haikuports/commit/9526ceabfceb2a3bfec6bec8947d1b3db06145b4
@korli did the testrun work ok for you on x86_64?

**Comment by korli** [comment]
@Begasus sorry can't remember. I usually add the failing tests in the recipe, nothing was detailed here.

**Pull request closed without merging**
