### PR TITLE
scipy: enable x86_64, stats module fix

### PR DESCRIPTION
**Pull request by iam-git**
Python 3.8 and 3.9 versions are enabled.
Commented out ndimage import statement in stats module.
Did not test it on x86

### CODE REVIEW

**Comment by Begasus** [comment]
Numpy could use an update on this, there has been a patch in the last push, this has been mentioned upstream and a ticket for it was filed also to the bug-tracker, this should be solved but I didn't have time to check this out, feel free if needed (probably will be a few days until I can check)

**Comment by iam-git** [comment]
Are we talking about #5624? I was aware of broken openBLAS, but now numpy works fine on x86_64 too. I do just cosmetical changes in this recipe.

**Comment by Begasus** [comment]
Ticked was filed here: https://dev.haiku-os.org/ticket/16965 (as said this should be fixed and our numpy patch could be dropped), nice too see that numpy is working fine for you on x86_64, could you mention this at the issue you linked before?

**Comment by iam-git** [comment]
I should call my pull request "scipy: dirty hacks" :( But I am still unable to build full scipy package, ndimage module fails

**Comment by Begasus** [comment]
> I should call my pull request "scipy: dirty hacks" :( But I am still unable to build full scipy package, ndimage module fails

This was disabled in the previous patch? https://github.com/haikuports/haikuports/blob/6eecb6a37389f30e372f9b27bdd5830c6777574b/dev-python/scipy/patches/scipy-1.6.3.patchset#L4

**Comment by iam-git** [comment]
In newer versions of scipy appeared one function in stats module which also depends on ndimage. So, there is one more dirty hack in the recipe.

**Comment by Begasus** [comment]
Did not check it out, but maybe you can bump scipy to latest version 1.7.1? (there are some ndimage fixes there)

**Comment by Begasus** [comment]
Checked a build on 32bit, seems to be OK (ran python3(.8,.9) import scipy and help (scipy), no issues there

**Comment by Begasus** [comment]
@iam-git what's the status on your side?

**Comment by iam-git** [comment]
I recall, there were some problems with 1.7.1. I was unable to build it month ago. Haven't time to look at it again, though.

**Comment by Begasus** [comment]
OK, we can have a look at the newer version later, this one is OK for you on 64bit?

**Comment by iam-git** [comment]
Yes, my scipe-related code works fine.

**Comment by Begasus** [comment]
Merged, let's keep an eye on buildmaster for this now, thanks! :+1:

**Pull request merged**
