### PR TITLE
Vim 8.0.1850

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Does it work?

**Comment by extrowerk** [comment]
Does it builds fine on x86 and x86_64?

**Comment by kenmays** [comment]
Yes, I tested and built it on x86_gcc2.

> ~/vim-8.0.1850> uname -a
> Haiku shredder 1 hrev52282 Aug 25 2018 20:42:46 BePC x86 Haiku
> 
> ~/vim-8.0.1850> src/vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 26 2018 19:02:59)
> Included patches: 1-1850
> Compiled by user@shredder
> Huge version without GUI.  Features included (+) or not (-):

**Comment by extrowerk** [comment]
Looks great, will build afternoon and report back.

**Comment by extrowerk** [comment]
@kenmays : 
```~/vim-8.0.1850>```

You built VIM out of HaikuPorter. Possibly without any patching.
Please, test your recipes before you make a pull request. Retesting them just to see the patch is unchanged and doesn't apply is wasting time.

**Comment by kenmays** [comment]
No, I applied the same patches to my Haiku test build. No issues there and patch applies cleanly.
The patch seems to apply to my Haikuporter build cleanly without error - but I'll recheck and have
Haikuporter regenerate it.

**Comment by kenmays** [comment]
Ok, it s all good now.

**Comment by extrowerk** [comment]
Patch applies cleanly, but build fails: https://gist.github.com/extrowerk/b4fe1cfd4f19153d485eeea096206023

It seems you forgot the bzero patch.
I have no time to find out the culprit of the other failure (#endif without #if), you have to dive deep and fix it.

So again: please, always check your recipe before you creates a PR. It is not a big deal if it is broken, we are here to help you if you met with something strange bug, but do not tell it is ok-to-merge while it is broken.

**Comment by kenmays** [comment]
Migrating this PR to Vim 8.1 work. Closing ticket.

**Comment by extrowerk** [comment]
Why do you close this ticket? You can just rename your recipe, adjust the patchset and that's all.

I assume you are doing the recipes on the github website. Reading a simple guideline about git would boost your general productivity like 100%.

**Comment by kenmays** [comment]
No, I migrated the work to Vim 8.1 and wanted to start fresh on that one.

**Pull request closed without merging**
