### PR TITLE
imutils: retire recipe.

### PR DESCRIPTION
**Pull request by OscarL**
Not used by anything in-tree, attepts to update it to 0.5.4 ended
with installable, but non-working modules.

Upstream repo possibly unmaintained.

### CODE REVIEW

**Comment by korli** [comment]
imutils can also be dropped.

**Comment by korli** [comment]
> > imutils can also be dropped.
> 
> Done.

we might as well disable it instead (sorry). maybe @extrowerk wants to fix it.

**Comment by extrowerk** [comment]
LAtely i don't have time for HP, so please do what you see to fit in this case. Thanks for the understanding.

**Comment by korli** [comment]
OK. The recipe can be revived anytime from the history.

**Pull request merged**
