### PR TITLE
icebreaker, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Related to https://github.com/haikuports/haikuports/issues/3878 and fixes https://github.com/haikuports/haikuports/issues/663 @humdingerb could you check?

**Comment by humdingerb** [comment]
It appears highscores arent saved at all any more.

**Comment by Begasus** [comment]
Let me check again tomorrow

**Comment by Begasus** [comment]
I guess this could be merged, issue as reported remains so far

**Comment by Begasus** [comment]
Past issue still remains ... https://github.com/haikuports/haikuports/issues/663

**Pull request merged**
