### PR TITLE
Vim: version bump

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by extrowerk** [comment]
- [ ] Does the patch applies cleanly?
- [ ] Does it builds and packages fine on x86?
- [ ] Does it builds and packages fine on x86_64?

If untested, add a note to the PR description in the future please. If you are not finished with this PR, mark it as "wip and do not merge".

**Comment by extrowerk** [comment]
Oh, and btw, my name is ZoltaN, not ZoltaR.

**Comment by kenmays** [comment]
This patch applies cleanly and usually is built before I submit them. Past issue was lazy in not updating patches between minor version releases for some apps. 

The main issue I had was how haikuporter accepts/regenerates patches versus the standard 'diff' or 'git' patches accepted on most platforms (basically, what command do you use to generate patches that will work without issue with haikuporter). Recently, that was reviewing white spaces and other things usually accepted by other systems. Reading git commands or watching a video does not help in that case - this requires detailed knowledge of haikuporter and what git command structure to properly use to guarantee patch acceptance checking (didn't find this in wiki yet)..

Anyhow, I did fix your name in the patch file.

**Comment by pulkomandy** [comment]
On Wed, Sep 05, 2018 at 04:08:22PM +0000, kenmays wrote:
> This patch applies cleanly and usually is built before I submit them. Past issue was lazy in not updating patches between minor version releases for some apps. 
> 
> The main issue I had was how haikuporter accepts/regenerates patches versus the standard 'diff' or 'git' patches accepted on most platforms (basically, what command do you use to generate patches that will work without issue with haikuporter). Recently, that was reviewing white spaces and other things usually accepted by other systems. Reading git commands or watching a video does not help in that case - this requires detailed knowledge of haikuporter and what git command structure to properly use to guarantee patch acceptance checking (didn't find this in wiki yet)..

haikuporter --extract-patchset

The output is basically the same as git format-patch, except all patches
are concatenated into a singe file, rather than one patch per file.

**Comment by extrowerk** [comment]
Please, test your recipes.

```
In file included from vim.h:1834:0,
                 from arabic.c:16:
structs.h:3147:5: error: unknown type name 'BMenuItem'
     BMenuItem *id;      /* Id of menu item */
     ^~~~~~~~~
In file included from vim.h:1834:0,
                 from beval.c:11:
structs.h:3147:5: error: unknown type name 'BMenuItem'
     BMenuItem *id;      /* Id of menu item */
     ^~~~~~~~~
structs.h:3148:5: error: unknown type name 'BMenu'
     BMenu *submenu_id;     /* If this is submenu, add children here */
     ^~~~~
structs.h:3148:5: error: unknown type name 'BMenu'
     BMenu *submenu_id;     /* If this is submenu, add children here */
     ^~~~~
In file included from vim.h:1834:0,
                 from blowfish.c:22:
structs.h:3147:5: error: unknown type name 'BMenuItem'
     BMenuItem *id;      /* Id of menu item */
     ^~~~~~~~~
structs.h:3148:5: error: unknown type name 'BMenu'
     BMenu *submenu_id;     /* If this is submenu, add children here */
     ^~~~~
In file included from vim.h:1834:0,
                 from buffer.c:28:
structs.h:3147:5: error: unknown type name 'BMenuItem'
     BMenuItem *id;      /* Id of menu item */
     ^~~~~~~~~
structs.h:3148:5: error: unknown type name 'BMenu'
     BMenu *submenu_id;     /* If this is submenu, add children here */
     ^~~~~
In file included from vim.h:2125:0,
                 from beval.c:11:
proto.h:271:13: fatal error: gui_haiku.pro: No such file or directory
 #   include "gui_haiku.pro"
             ^~~~~~~~~~~~~~~
compilation terminated.
In file included from vim.h:2125:0,
                 from arabic.c:16:
proto.h:271:13: fatal error: gui_haiku.pro: No such file or directory
 #   include "gui_haiku.pro"
             ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:2996: recipe for target 'objects/beval.o' failed
make: *** [objects/beval.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from vim.h:2125:0,
                 from blowfish.c:22:
proto.h:271:13: fatal error: gui_haiku.pro: No such file or directory
 #   include "gui_haiku.pro"
             ^~~~~~~~~~~~~~~
compilation terminated.
In file included from vim.h:2125:0,
                 from buffer.c:28:
proto.h:271:13: fatal error: gui_haiku.pro: No such file or directory
 #   include "gui_haiku.pro"
             ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:2915: recipe for target 'objects/arabic.o' failed
make: *** [objects/arabic.o] Error 1
Makefile:2918: recipe for target 'objects/blowfish.o' failed
make: *** [objects/blowfish.o] Error 1
Makefile:2921: recipe for target 'objects/buffer.o' failed
make: *** [objects/buffer.o] Error 1
```

**Pull request closed without merging**
