### PR TITLE
tuxpaint, revbump, fix build

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Build completed on the buildbot(s), @mazbrili could you check (again) :)

**Comment by mazbrili** [comment]
dear @Begasus  .. i try tuxpaint from depot.but i cannot do anything. cannot change stamp, cannot new.. and even cannot close..

**Comment by Begasus** [comment]
@mazbrili Thanks for reporting, thought it was something from my side, we'll have to investigate then what's causing this, thanks for the report!

**Comment by mazbrili** [comment]
> @mazbrili Thanks for reporting, thought it was something from my side, we'll have to investigate then what's causing this, thanks for the report!

ok @Begasus .. thanks for your hardwork

**Pull request merged**
