### PR TITLE
ICU: bump

### PR DESCRIPTION
**Pull request by extrowerk**
```
echo "$BRKITR_INDEX_TXT_CONTENT" > ./out/tmp/brkitr/res_index.txt
LIBRARY_PATH=../lib:../stubdata:../tools/ctestfw:$LIBRARY_PATH  ../bin/gendict -i ./out/build/icudt69l -c --bytes --transform offset-0x1000 ./brkitr/dictionaries/burmesedict.txt ./out/build/icudt69l/brkitr/burmesedict.dict
/bin/sh: line 1: ../bin/genrb: Argument too big
../data/rules.mk:1966: recipe for target 'out/build/icudt69l/pool.res' failed
```

Argument is too big :(

### CODE REVIEW

**Comment by pulkomandy** [comment]
Don't we already have a patch for this in the previous versions?

**Comment by korli** [comment]
Version 70.1 is out

**Comment by extrowerk** [comment]
Still "argrument is too big."

**Comment by kallisti5** [comment]
An icu 70 recipe was merged, and the argument list too long issue should be fixed in the latest master and r1b3 builds.

Is this one still relevant?

**Comment by kallisti5** [comment]
https://github.com/haikuports/haikuports/pull/6646

**Comment by extrowerk** [comment]
Probably not.

**Pull request closed without merging**
