### PR TITLE
lynx: update patch for Haiku > r1b2

### PR DESCRIPTION
**Pull request by ihatemyisp**
A Haiku [commit](https://review.haiku-os.org/plugins/gitiles/haiku/+/e04970ad6fb948e03aeb803b00f535a2e712a526) hrev54720 and forward broke Lynx and this fixes things.

### CODE REVIEW

**Comment by Begasus** [comment]
Maybe revbump the recipe?

**Comment by ihatemyisp** [comment]
Are you referring to to the file name or the rev number in the recipe?

I didn't think to change anything other than the patch.

**Comment by Begasus** [comment]
"REVISION" should be bumped for this to be rebuild

**Comment by ihatemyisp** [comment]
Gotcha, will update shortly.

**Comment by ihatemyisp** [comment]
Revision bumped.

**Comment by korli** [comment]
this patch isn't interesting for us, because:
1. the buildbot is on r1b2
2. this is a workaround to fix the build, doesn't explain the issue, doesn't fix the issue
3. it should be fixed on the Haiku side to build without ifdef(HAIKU)

**Comment by ihatemyisp** [comment]
Ok...

**Comment by ihatemyisp** [comment]
I'm still looking into fixing this in Haiku itself but that may take me a while.

I doubt there are many users going after this port specifically, but the resolv.h issue might affect more than just this one (and php 7).

**Comment by Begasus** [comment]
@ihatemyisp if you created a bug report upstream could you paste a link to this and the PR for php?
As on R1B2 it seems to be OK, it would be nice to get this out of the way before R1B3 would hit ground :)

**Comment by ihatemyisp** [comment]
> @ihatemyisp if you created a bug report upstream could you paste a link to this and the PR for php?
> 
> As on R1B2 it seems to be OK, it would be nice to get this out of the way before R1B3 would hit ground :)

I'll get it submitted later tonight.

**Comment by ihatemyisp** [comment]
@korli @Begasus I misspoke on PHP7 being related to this workaround. I have opened an issue for this upstream.

https://dev.haiku-os.org/ticket/16851

**Comment by korli** [comment]
thanks, it will be handled at the Haiku bugtracker.

**Pull request closed without merging**
