### PR TITLE
gmp, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
There is still gmp-6.0.0 for gcc2, is this still in use? (or somehow required for Haiku itself)

**Comment by jmairboeck** [comment]
IIRC gmp is a dependency of gcc itself.

**Comment by Begasus** [comment]
> IIRC gmp is a dependency of gcc itself.

gcc is still happy with this update (checked on 64bit). :)

**Comment by Begasus** [comment]
Will keep the older version in tree for now.

**Pull request merged**
