### PR TITLE
glm, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
From a build in Terminal I got this (with cmake and gcc2), so I disabled gcc2_x86 for now, comments welcome:
```
/Opslag/haikuports/media-libs/glm/work-x86-0.9.9.8/sources/glm-0.9.9.8/glm/../glm/detail/../simd/platform.h:222: #error "GLM requires GCC 4.6 or higher"
```

**Comment by Begasus** [comment]
PS, this is needed to bump the version for Solarus ...

**Comment by korli** [comment]
lib:libGL$secondaryArchSuffix should be removed.

**Comment by korli** [comment]
did you try to build libetonyek on x86 secondary arch?

**Comment by Begasus** [comment]
Not yet, busy atm with imagemagick build and checkup on RC for new TuxPaint, will do in a bit
There are a few candidates IIRC that uses glm${secondaryArchSuffix}_devel atm, need to investigate those too (although I don't think it would break existing builds as they are only used at build time?)

**Comment by Begasus** [comment]
> did you try to build libetonyek on x86 secondary arch?

I build the latest solarus_x86 with this though :)

**Comment by Begasus** [comment]
Will revbump the others with the changes in a bit :)

**Pull request merged**
