### PR TITLE
libdl, new recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Huh? Why do we need this? Can't we just patch anything that wants it?

**Comment by Begasus** [comment]
It was one of the things I encountered when trying to build boswars ...

**Comment by jessicah** [comment]
I agree with waddlesplash, this is not the solution. `dlopen` and friends are part of libroot. You need to modify boswars or whatever to not link to libdl on Haiku.

**Comment by Begasus** [comment]
Ok, this can be closed then :)

**Pull request closed without merging**
