### PR TITLE
gnupg: add recipe for 1.4.20 (latest classic)

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
Recipe tested on Haiku x86_gcc2 hrev50075:
```
ls -go gnupg*-1.4.20-1-*.hpkg
-rw-r--r-- 1 5330114 Feb 19 10:10 gnupg_source-1.4.20-1-source.hpkg
-rw-r--r-- 1 4059729 Feb 19 10:10 gnupg-1.4.20-1-x86_gcc2.hpkg

package checksum gnupg_source-1.4.20-1-source.hpkg
648d8eac920c5c71896b1bcb1a65017b1e2d5357d80b7a7ac40a0359f731e415

package checksum gnupg-1.4.20-1-x86_gcc2.hpkg
33b507a60e7fbbebd7cfb0821fad481196a09906f56f623701c63ed4a1fd9023

package info gnupg-1.4.20-1-x86_gcc2.hpkg
name: gnupg  version: 1.4.20-1

gpg --version
gpg: Please note that you don't have secure memory on this system
gpg (GnuPG) 1.4.20
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB
```

FYI, from https://lists.gnupg.org/pipermail/gnupg-announce/2015q4/000382.html

What's New in GnuPG 1.4.20
==========================

 * Reject signatures made using the MD5 hash algorithm unless the
   new option --allow-weak-digest-algos or --pgp2 are given.

 * New option --weak-digest to specify hash algorithms which
   should be considered weak.
...
```
gpg --dump-options | grep weak
--weak-digest
--allow-weak-digest-algos
```

**Comment by fbrosson** [comment]
https://github.com/haikuports/haikuports/commit/f412fad60a4ff1a456bb237e5f2dc7b6f98be7b6 ([Travis #576](https://travis-ci.org/haikuports/haikuports/builds/110362103)), which did not call **`libtoolize`** in `INSTALL`, worked for x86_gcc2 and x86_64 but __failed__ for __x86__, so I fixed it in https://github.com/haikuports/haikuports/commit/036cc9d9717bb475ca3352d7ad6879c36bbf8bc7 ([Travis #577](https://travis-ci.org/haikuports/haikuports/builds/110405599)) by adding back the **`cmd:libtoolize`** (in `BUILD_PREREQUIRES`) as well as the call to **`libtoolize --force --copy --install`** in `BUILD` (which is commented in [gnupg-1.4.16.recipe](https://github.com/haikuports/haikuports/blob/master/app-crypt/gnupg/gnupg-1.4.16.recipe#L57)).
Therefore, since Travis job 577 was launched, this PR contains the exact copy of what I have successfully rebuilt and tested on each of the 3 main architectures: x86_gcc2, x86 and x86_64.
So I think this PR is ready for merge. Please review. Thanks!

**Comment by korli** [comment]
As a general rule you'll find easier to just launch "[autoreconf](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoreconf-Invocation.html) -fi" and let it handle the build system required regeneration.

**Comment by fbrosson** [comment]
OK, thanks for the link and your feedback.
Shall I replace the call to **`autoconf`** by a call to **`autoreconf -fi`** in `BUILD` ?
The link you gave explains that «autoreconf runs autoconf, autoheader, aclocal, automake, libtoolize, and autopoint (when appropriate) repeatedly …» so I guess I can remove the call to **`libtoolize --force --copy --install`** in `BUILD`. But I found several recipes that call both libtoolize and autoreconf. Should I really remove the call to libtoolize and, eventualy, the **`cmd:libtoolize`** in `BUILD_PREREQUIRES` ?
Should I add **`cmd:autoreconf`** and remove **`cmd:autoconf`** in `BUILD_PREREQUIRES` and let haikuporter pull all indirect dependencies ?
I can edit the recipe in whatever way you suggest and then rebuild and test it on each of the 3 architectures declared. To summarize, shall I ajust `BUILD_PREREQUIRES` and put the following block in `BUILD` ?
```Shell
	libtoolize --force --copy --install
	autoreconf -fi
	runConfigure ./configure
	make $jobArgs
```

Just let me know what is best and I'll update the commit. Thanks!

**Comment by korli** [comment]
Just remove libtoolize in BUILD().

**Comment by fbrosson** [comment]
> Just remove libtoolize in BUILD().

Did you mean «just remove **`libtoolize`**» or «remove **`libtoolize`** **_and_** replace **`autoconf`** by **`autoreconf -fi`**» ?
Because I have already tried _without_ libtoolize and found that it did not work on x86 (although it worked for x86_gcc2 and x86_64). But maybe it will work without libtoolize if I **_also_** replace «**`autoconf`**» by «**`autoreconf -fi`**».

**Comment by korli** [comment]
Again just launch "autoreconf -fi" before configure. Nothing more.

**Comment by fbrosson** [comment]
OK, done. I can't retest it now but will do so later this evening.

**Comment by fbrosson** [comment]
Switching to autoreconf has made it necessary to add **`cmd:find`** and **`cmd:aclocal`**. I then was able to rebuild and test on x86 and x86_64. On these architectures everything is OK.
On x86_gcc2, however, I have a new problem:
```
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.19.3 but this version
               is older. Please upgrade to gettext-0.19.3 or newer.
autopoint: *** Stop.
```

I'm still using hrev50075 which has gettext 0.18.1.1-6 pre-installed. I have started building gettext-0.19.6.recipe but it is quite big and will take some time to build.
I have therefore updated the commit (https://github.com/haikuports/haikuports/commit/8b8929fd99b3ce78dd75a88b587541a3573a5446) in case someone already having gettext 0.19.3 (or newer) would like to test building gnupg 1.4.20 on x86_gcc2.

**Comment by fbrosson** [comment]
The compilation of gettext 0.19.6 is finished and I have been able to rebuild and test gnupg 1.4.20.
So I think the recipe is OK for a merge. Thanks!
BTW, I noticed that the latest binary package of gettext is 0.18.1.1-6 for x86_gcc2 and 0.19.4-1 for x86. Only x86_64 is in sync with the latest recipe (0.19.6-1).

**Pull request merged**
