### PR TITLE
xrick, move binary patches to additional-files

### PR DESCRIPTION
**Pull request by Begasus**
Co-Authored by Humdinger humdingerb@gmail.com

### CODE REVIEW

**Comment by Begasus** [comment]
@humdingerb could you have a look? patched to build on 64bit too but segfaults on launch there.

**Comment by Begasus** [comment]
Closes: https://github.com/haikuports/haikuports/issues/1719

**Comment by humdingerb** [comment]
I'm afraid I have no idea what's wrong and how to fix it. Syslog says:

`kern: vm_soft_fault: va 0x21546000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x215467a8, ip 0xc29cf63e5c, write 0, user 1, exec 0, thread 0x25ec`

Sometimes also:

`kern: read access attempted on read-protected area 0x4 at 0xffffffff93a27000
KERN: vm_page_fault: vm_soft_fault returned error 'Permission denied' on fault at 0xffffffff93a27738, ip 0x12ff6b02e5c, write 0, user 1, exec 0, thread 0x265f`

Maybe @korli knows the fix?

**Comment by Begasus** [comment]
I'm fine with it not running on 64bit (or gcc11), it was only enabled for 32bit (gcc2), so nothing really changes there in regards to running it, only changes are the binary files moved out of the patch.

**Pull request merged**
