### PR TITLE
noto_cjk, bump fonts

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Related to: https://github.com/haikuports/haikuports/issues/9727

**Comment by Begasus** [comment]
@korli any thoughts on this one, otherwise this can be closed?

**Comment by korli** [comment]
you could use the source archive at `https://github.com/googlefonts/noto-cjk`  and select the files you need.
with https://dev.haiku-os.org/ticket/18381 implemented we could switch to ttc files, but this is for the next release.

**Comment by korli** [comment]
OK. I can't compare easily with the old recipes. What I meant is: in the future a ttc file would replace the five otf files, the subpackages will be gone.

**Comment by Begasus** [comment]
This push didn't realy help :) Hoped it would show the diff between the old and new :/

**Comment by korli** [comment]
It looks OK to merge :)

**Pull request merged**
