### PR TITLE
qmplay2: bump to 23.10.22

### PR DESCRIPTION
**Pull request by kenmays**
Tested on Haiku x86-64 (56578+93).

### CODE REVIEW

**Comment by Begasus** [comment]
Works a bit better on some links, but crashes when accassing the volume control.

**Comment by Begasus** [comment]
No crash report (app just shuts down), from Terminal (nothing from syslog):
```
/system/apps/QMPlay2> ./QMPlay2 
[ass] libass API version: 0x1701000
[ass] libass source: custom after: 0.17.1
[ass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 8.2.1 (COMPLEX)
[ass] Using font provider fontconfig
[opus @ 0x1217a4ec4850] Could not update timestamps for skipped samples.
[swscaler @ 0x1217a5088460] No accelerated colorspace conversion found from yuv420p to bgra.
[ass] fontselect: (Noto Sans Display, 400, 0) -> /boot/system/data/fonts/ttfonts/NotoSansDisplay-Regular.ttf, 0, NotoSansDisplay-Regular
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock
Abort
[09 nov. 2023 10:34:52.004] QMPlay2 has been aborted (SIGABRT)
Abort
```

**Comment by kenmays** [comment]
@nephele-gh: All previous patches were upstreamed and accepted last year.

@begasus: I duplicate the issue. and reported this upstream. No crash if a video is not playing. Same video control GUI testing works fine using QMPlay2 22.08.21.

Ref: https://github.com/zaps166/QMPlay2/issues/669

**Comment by kenmays** [comment]
I was able to isolate the main issue. with the current QMPlay2 release. I'll resubmit once the issue gets resolved. in a newer release.
Moving this over to issues.

**Pull request closed without merging**
