### PR TITLE
GCC: bump

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by Begasus** [comment]
Build failure on 32bit (R1B3 551881+66)
```
g++ -std=c++11 -no-pie   -g -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-error=format-diag -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H  -o cc1 c/c-lang.o c-family/stub-objc.o attribs.o c/c-errors.o c/c-decl.o c/c-typeck.o c/c-convert.o c/c-aux-info.o c/c-objc-common.o c/c-parser.o c/c-fold.o c/gimple-parser.o c-family/c-common.o c-family/c-cppbuiltin.o c-family/c-dump.o c-family/c-format.o c-family/c-gimplify.o c-family/c-indentation.o c-family/c-lex.o c-family/c-omp.o c-family/c-opts.o c-family/c-pch.o c-family/c-ppoutput.o c-family/c-pragma.o c-family/c-pretty-print.o c-family/c-semantics.o c-family/c-ada-spec.o c-family/c-ubsan.o c-family/known-headers.o c-family/c-attribs.o c-family/c-warn.o c-family/c-spellcheck.o i386-c.o default-c.o \
  cc1-checksum.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a   -lmpc -lmpfr -lgmp   -lz 
g++ -std=c++11 -no-pie   -g -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-error=format-diag -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H  -o cc1plus \
      cp/cp-lang.o c-family/stub-objc.o cp/call.o cp/class.o cp/constexpr.o cp/constraint.o cp/coroutines.o cp/cp-gimplify.o cp/cp-objcp-common.o cp/cp-ubsan.o cp/cvt.o cp/cxx-pretty-print.o cp/decl.o cp/decl2.o cp/dump.o cp/error.o cp/except.o cp/expr.o cp/friend.o cp/init.o cp/lambda.o cp/lex.o cp/logic.o cp/mangle.o cp/mapper-client.o cp/mapper-resolver.o cp/method.o cp/module.o cp/name-lookup.o cp/optimize.o cp/parser.o cp/pt.o cp/ptree.o cp/rtti.o cp/search.o cp/semantics.o cp/tree.o cp/typeck.o cp/typeck2.o cp/vtable-class-hierarchy.o attribs.o incpath.o c-family/c-common.o c-family/c-cppbuiltin.o c-family/c-dump.o c-family/c-format.o c-family/c-gimplify.o c-family/c-indentation.o c-family/c-lex.o c-family/c-omp.o c-family/c-opts.o c-family/c-pch.o c-family/c-ppoutput.o c-family/c-pragma.o c-family/c-pretty-print.o c-family/c-semantics.o c-family/c-ada-spec.o c-family/c-ubsan.o c-family/known-headers.o c-family/c-attribs.o c-family/c-warn.o c-family/c-spellcheck.o i386-c.o default-c.o cc1plus-checksum.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a ../libcody/libcody.a  \
        libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a   -lmpc -lmpfr -lgmp   -lz 
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/11.2.0/../../../../i586-pc-haiku/bin/ld: BFD (GNU Binutils) 2.36.1 internal error, aborting at /sources/buildtools-795d2053a07fdd2ce3c4ef6f649b0a27e2b085d1/bfd/merge.c:939 in _bfd_merged_section_offset

/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/11.2.0/../../../../i586-pc-haiku/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
/sources/gcc-11.3.0/gcc/cp/Make-lang.in:135: recipe for target 'cc1plus' failed
make[3]: *** [cc1plus] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gcc.pod
make[3]: Leaving directory '/sources/gcc_x86-11.3.0_2022_04_21-obj/gcc'
Makefile:4786: recipe for target 'all-stage1-gcc' failed
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory '/sources/gcc_x86-11.3.0_2022_04_21-obj'
Makefile:23940: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/sources/gcc_x86-11.3.0_2022_04_21-obj'
Makefile:1009: recipe for target 'all' failed
make: *** [all] Error 2
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2.
```

**Comment by kallisti5** [comment]
this is working in the wrong direction.  To maintain gcc, we import new versions to the core buildtools repository, then replicate the patches in buildtools out to haikuports and haikuports.cross.

Trying to work in reverse confuses things and is difficult.

**Comment by kallisti5** [comment]
Ok.. closing might have been a little over the top.   I re-opened.     The main issue historically i'm trying to fix is changes keep getting merged in haikuports for gcc, but never making their way to buildtools.

We gotta keep this stuff synced up until we can get it merged with upstream gcc.

**Comment by pulkomandy** [comment]
Honestly, both ways are pretty bad. Why can't we have the haikuports recipe download gcc and buildtools from our fork? That would be a lot simplerfor everyone involved.

**Comment by kallisti5** [comment]
> Honestly, both ways are pretty bad. Why can't we have the haikuports recipe download gcc and buildtools from our fork? That would be a lot simplerfor everyone involved.

No disagreements.  Originally it did work like this, not sure when or why we started using upstream gcc and "repatching".

Maybe intent was to keep a clear set of Haiku support patches for gcc that could be up-streamed... but all it has done is create two places we have to patch (buildtools, and here).

I think as long as we keep the patches to buildtools sanitized  (every time we bump gcc, we roll all the previous relevant haiku fixes / patches into a "haiku support" megapatch), then the recipe can just reference our buildtools repo.

**Comment by waddlesplash** [comment]
Indeed let's bump only via buildtools, please.

**Pull request closed without merging**
