### PR TITLE
Kottan: new maintenance release 0.14.3 

### PR DESCRIPTION
**Pull request by andimachovec**
- links against libcolumnlistview directly 
- added new and updated language translations

### CODE REVIEW

**Comment by pulkomandy** [comment]
you need to increment the REVISION, otherwise the package won't be rebuilt

**Comment by korli** [comment]
> you need to increment the REVISION, otherwise the package won't be rebuilt

not for a new version

**Comment by andimachovec** [comment]
Thanks korli for clarifying. Seems more logical to me than having to increment the revision for a new version.

**Comment by pulkomandy** [comment]
Ah yes sorry, I didn't notice the filename had changed.

**Comment by andimachovec** [comment]
No problem ;-) Thanks Pulkomandy!

**Pull request merged**
