### PR TITLE
curl: bump to 7.84.0

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by Begasus** [comment]
Searching `lib:libcurl$secondaryArchSuffix` here reveals 173 hits, do all these need a revbump?

**Comment by pulkomandy** [comment]
If libVersionCompat didn't change, no revbump is needed. I'm not sure if it changes or not with the way it's generated. Is it "7" or "7.84"?

**Comment by Begasus** [comment]
Haven't checked a build yet, but looking at $libVersion, $libVersionCompat changes from 4.7 to 4.8

**Comment by kenmays** [comment]
libversion last changed in Jan 7, 2021 (i.e. curl 7.74, 4.6->4.7). I didn't see a major rebuild requirement during that commit..

**Pull request merged**
