### PR TITLE
SDL2_mixer fix (libGL added, it require it, idk why...)

### PR DESCRIPTION
**Pull request by miqlas**

### CODE REVIEW

**Comment by diversys** [comment]
This probably needs a better commit message

**Comment by Begasus** [comment]
Iirc SDL2 requires libGL, hence all libs depending on SDL2 require libGL? Maybe it would be an idea to remove the dependency for libGL for SDL2, there have been people running SDL2 things without libGL (with own build recipes), haven't looked into that so far ...

**Comment by waddlesplash** [comment]
If SDL2 requires libGL, then that should be the fix made, not this.

**Comment by waddlesplash** [comment]
Oh, and it's in the recipe now: https://github.com/haikuports/haikuports/blob/master/media-libs/libsdl2/libsdl2-2.0.5.recipe#L25

**Pull request closed without merging**
