### PR TITLE
qemu-7.2.0: new recipe

### PR DESCRIPTION
**Pull request by davidkaroly**
Successful build for both 64-bit and 32-bit, no policy warnings :heavy_check_mark: 
Running Haiku inside Haiku :heavy_check_mark: 
Network access with devendored libslirp :heavy_check_mark: 

Wonky mouse pointer :x:
Ctrl/Alt/Shift doesn't work :x:

Edit:
These two issues were there also on 6.2.0
It seems to be much worse on qemu-3.1.1.1 (unless I'm doing something wrong?)

### CODE REVIEW

**Comment by khallebal** [comment]
> Wonky mouse pointer x
Ctrl/Alt/Shift doesn't work x

The first issue is likely dependent on the pointing device you choose, i did not experience it using `-usb -device usb-tablet`, the second issue is a wayland problem as i mentioned it in the other PR [.7607](https://github.com/haikuports/haikuports/pull/7607)

**Comment by davidkaroly** [comment]
yep it works much better with `-usb -device usb-tablet`

**Comment by Begasus** [comment]
Good to merge?

**Comment by davidkaroly** [comment]
> Good to merge?

I wanted to do one more update as the patch for `os-posix.c` is not needed anymore.

**Comment by davidkaroly** [comment]
> Good to merge?

it's marked as `"?all"` but I think it can be meged now as it isn't any worse than qemu-6.2.0

we can workaround the wonky mouse pointer with `-usb -device usb-tablet`

we can workaround the lack of Ctrl/Alt/Shift modifier keys with `-console sdl` (unfortunately they don't work on GTK UI)

**Comment by davidkaroly** [comment]
> The first issue is likely dependent on the pointing device you choose, i did not experience it using `-usb -device usb-tablet`, the second issue is a wayland problem as i mentioned it in the other PR [.7607](https://github.com/haikuports/haikuports/pull/7607)

yep you're right, it seems related to GTK-on-Wayland on Haiku
* qemu with SDL UI works fine
* qemu with GTK-on-Wayland does not recognize Crtl/Alt/Shift modifier keys as their scancodes are not dispatched to `gd_key_event()` handler
* qemu with GTK UI on Fedora works fine (probably it's GTK-on-X but it would be good to try it also with Wayland eventually)

**Comment by davidkaroly** [comment]
ok, the issue with ctrl/alt/shift seems to be related to the xkb keymap generation logic in Wayland inproc server.

The key codes for Ctrl/Alt/Shift are dispatched from Wayland server to GTK but they are not recognized by GTK as they are not mapped to a valid keysym in the xkb keymap. So GTK does not generate any key event for them.

I can get Ctrl/Alt/Shift working in qemu if I add the mapping for codes 0x4b, 0x56, 0x5c, 0x5d, 0x5f, 0x60 in `WriteSymbol()` (map them to Shift_L, Shift_R, Control_L, Alt_L, Alt_R, Control_R respectively)

**Comment by khallebal** [comment]
If you've tested it and it works, you can create a PR at [@X547](https://github.com/X547/wayland-server/pulls), he is probably busy doing other stuff.

**Comment by davidkaroly** [comment]
> If you've tested it and it works, you can create a PR at [@X547](https://github.com/X547/wayland-server/pulls), he is probably busy doing other stuff.

I tried it only with qemu. Some more testing will be needed with other applications.

**Comment by khallebal** [comment]
AWESOME, thanks for working on this.

**Comment by davidkaroly** [comment]
> AWESOME, thanks for working on this.

credit goes to @mmlr

**Comment by mmlr** [comment]
This is indeed very cool to see live on. I wouldn't have expected it to still be applicable after this long a time and am glad that it could still be useful. Thanks for your work!

**Comment by waddlesplash** [comment]
Can we build just the SDL2 and Haiku-native backends, then, and skip the GTK3 one for now if the key shortcuts are kind of broken? Plus that will cut out a lot of dependencies...

**Comment by davidkaroly** [comment]
Sure we can disable GTK UI for the time being

**Comment by khallebal** [comment]
Is the SDL2 backend here just an alternative or is it somehow tied to the haiku backend?

**Comment by davidkaroly** [comment]
Well i think it doesn't get much better than this... we can use either SDL display+audio or Haiku native display+audio depending on command line args. (however take care not to mix them, Haiku display with SDL audio results in a crash)
GTK display disabled for now, because of the Wayland keymap issue with the Ctrl/Alt/Shift modifier keys.

Still I think it works better than version 3.1.1.1 and we can get up to date qemu feature set.

**Comment by khallebal** [comment]
Did you notice any difference in performance when using the haiku backend compared to the other backends? CPU load?

**Comment by pulkomandy** [comment]
Nice, thanks for working on this :)

Is it useful to keep all the older recipes for qemu as well, or should we delete them?

Should we keep the SDL2 backend enabled, or should we leave only the Haiku one to reduce dependencies?

Any plans for upstreaming the patch?

**Comment by davidkaroly** [comment]
> Did you notice any difference in performance when using the haiku backend compared to the other backends? CPU load?

I haven't really noticed any difference in performance, it's rather slow either way :man_shrugging: emulation only, no HW acceleration...


> Is it useful to keep all the older recipes for qemu as well, or should we delete them?

I don't really see much use in the older recipes, and anyway github will remember them in the commit history - so I think they can be removed.

> Should we keep the SDL2 backend enabled, or should we leave only the Haiku one to reduce dependencies?
> 
> Any plans for upstreaming the patch?

At least a few people should try the native backend first.

**Comment by davidkaroly** [comment]
Any further review comments?

**Comment by khallebal** [comment]
I'd say just go ahead and commit  it so that it can be tested by more users, a lot of the users don't know about it, you might even make an announcement on the forum to get more feedback.

**Comment by Begasus** [comment]
Any more work needed here (didn't check a build myself)?

**Pull request merged**
