### PR TITLE
bsnow: fix objects directory

### PR DESCRIPTION
**Pull request by hanya**
Related to  #3594.

### CODE REVIEW

**Comment by Begasus** [comment]
Has this been checked on x86_64? If so please enable the architecture

**Comment by Begasus** [comment]
For x86_64 I'm getting  (amongst others) "undefined reference to `operator new(unsigned long)'" atm

**Comment by Begasus** [comment]
Sorry, didn't check this one to see if it was ok, I checked and created a new PR for this disabling all architectures, not stable enough to use (build is also broken for gcc7)

**Comment by Begasus** [comment]
You can still adjust the recipe with my changes and your fix for the OBJDIR to get this merged

**Comment by hanya** [comment]
I'll close this since its hard remove snow from the desktop once it start. 
I needed to remove ~/config/settings/Tracker/tracker_shelf to stop the snow.

**Comment by Begasus** [comment]
Had the same problem, hence why I disabled architectures :)

**Pull request closed without merging**
