### PR TITLE
Add recipe Barrier

### PR DESCRIPTION
**Pull request by unarix**
I took the work of Alex Von Gluck, make some changes in the keymap and the clipboard feature to make this usable. Tested in x32 and x64. Works good for me!

### CODE REVIEW

**Comment by Begasus** [comment]
Isn't it possible to use the gitlab source from @kallisti5 and upstream the changes there? (also if this is better to be used then synergy maybe remove it or disable synergy?)

**Comment by korli** [comment]
Could you use https://gitlab.com/kallisti5/barrier-haiku as a basis? There is a commit history which should stay IMO

**Comment by unarix** [comment]
i can remove the binaries, but i dont use gitlab, maybe Alex can take the changes and merge in his repo: or if he use github i can do the pullrequest with the patches... if that is posible, i can rewrite the recipe to point to the orginal sources no problem!

**Comment by korli** [comment]
> i can remove the binaries, but i dont use gitlab, maybe Alex can take the changes and merge in his repo: or if he use github i can do the pullrequest with the patches... if that is posible, i can rewrite the recipe to point to the orginal sources no problem!

You could at least clone his gitlab repository and use that as basis for your github repo.

**Comment by kallisti5** [comment]
y'all could just submit PR's :-|

**Comment by ModeenF** [comment]
I made a patch to synergy_haiku, Can push the to your rep unarix. Made some other changes also.

I do think we should "merge" both clients and perhaps rename classes to our own name when we supports both synergy and Barrier.

**Comment by unarix** [comment]
Sure @ModeenF. If you need direct push tell me. You can do pr too!

**Comment by ModeenF** [comment]
It's done ;). Did that over my phone after I wrote this :)

**Comment by unarix** [comment]
Closed, @ModeenF added support for barrier in a single synergy client.

**Pull request closed without merging**
