### PR TITLE
afl, bump version, dirty hack to get it to build

### PR DESCRIPTION
**Pull request by Begasus**
This has been in the dark for a while, not tested on x86_64 (yet)

### CODE REVIEW

**Comment by korli** [comment]
Really dirty!! ;)

**Comment by Begasus** [comment]
Well, it could be closed if to dirty ;)

**Comment by Begasus** [comment]
I'll close this, and leave the branch open, in case someone would like to look into it :)

**Comment by korli** [comment]
Well it's a better to have something that builds, is up to date, and with a patch in the tree. 
But does it really work without shared memory?

**Comment by Begasus** [comment]
It's been a while since I tested it, but as I said the branch is still around so if someone wants to have a go at it they can :)

**Pull request closed without merging**
