### PR TITLE
libcoverart, fix build

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
This needs to wait before merging until neon is merged: https://github.com/haikuports/haikuports/pull/4879

**Comment by Begasus** [comment]
Builds and installs OK on _x86, test run OK, didn't test x86_64 (yet)

**Comment by korli** [comment]
Looks good. Theorically doesn't need a revbump if it wasn't enabled til today.

**Comment by Begasus** [comment]
Will revert the revbump for this one later :)

**Comment by Begasus** [comment]
@phw any chance this could be used for Picard? If it's not very useful we can just delete the old bep file instead of trying to get this to work :)

**Comment by phw** [comment]
No, Picard does not need this, it has it's own implementation in Python. I think just going the easy way to fix this is fine :)

**Comment by Begasus** [comment]
As this isn't used earlier, it's ok to have it in for now so people could check if there is a need for it ...

**Pull request merged**
