### PR TITLE
MPFR: bump

### PR DESCRIPTION
**Pull request by extrowerk**
AFAIK the patch is not needed anymore.

### CODE REVIEW

**Comment by extrowerk** [comment]
All test passes

**Comment by extrowerk** [comment]
Was unable to update binutils, so you probably don't want to morge this.

**Comment by extrowerk** [comment]
@korli does it have any use for us or should i close them? (MPFR, GPC, GMP)?

**Comment by korli** [comment]
@extrowerk  please keep the old version as mpfr4-3.1.6.recipe for compatibility.

**Comment by extrowerk** [comment]
I hope i understood you correctly. Old renamed to mpfr3, conflicts added to devel.

**Comment by korli** [comment]
Ok, i usually use the soname as suffix.

**Pull request merged**
