### PR TITLE
Tor: bump to 0.3.4.8

### PR DESCRIPTION
**Pull request by kenmays**
Tor 0.3.4.8
Ref: [3114](https://github.com/haikuports/haikuports/pull/3114)
Built on Haiku x86_64.
NOTE: This build just replaces and updates the previous version. No build regressions at this time.

### CODE REVIEW

**Comment by extrowerk** [comment]
What is with https://github.com/haikuports/haikuports/pull/3114 does this superseeds that PR?

**Comment by extrowerk** [comment]
I see no point in this, it doesn't fix the known problems in https://github.com/haikuports/haikuports/pull/3114 so it is superfluous.

**Comment by fbrosson** [comment]
@extrowerk: You are right; the patchset in this PR won't fix anything. That said, I believe @kenmays is willing to add more patches in order to make the tests succeed.
Yeah, one might think he should have waited until he had a working patch before opening this PR.
But he can argue that he did so to signal that he was working on it, so that other contributors would not spend time on something he was already working on.

So, imo it is perfectly ok to re-open this PR if we add a "wip-no-merge" label. 

@kenmays, I'm adding that label so you can re-open this PR if you wish and when you wish :)

**Comment by kenmays** [comment]
@fbrosson - This is fine. I opened the PR per your request,. Both tor-0.3.3.10 and tor 0.3.4.8 fail the same tests, which is what I isolated yesterday.

**Pull request closed without merging**
