### PR TITLE
ponyexpress, bump version

### PR DESCRIPTION
**Pull request by wattoc**
Several bugfixes, tested on x86-gcc2 and x64

### CODE REVIEW

**Comment by Begasus** [comment]
Could you remove the previous recipe, that way it's easier to see the changes and reduces git noise :)

**Comment by wattoc** [comment]
Does 282ed2345f3fbeea2afcae664df925bd59b19b70 not do that?

**Comment by Begasus** [comment]
> Does [282ed23](https://github.com/haikuports/haikuports/commit/282ed2345f3fbeea2afcae664df925bd59b19b70) not do that?

Usually it should've done that, maybe squash the commits fixes it?

**Comment by Begasus** [comment]
Thanks! :)

**Comment by wattoc** [comment]
I'll just create a clean branch next time - think that's what messed it up.

**Comment by Begasus** [comment]
Yeah, saw it too, I always delete a branch after a merge :)

**Pull request merged**
