### PR TITLE
wayland: bump to git latest commit

### PR DESCRIPTION
**Pull request by kenz-gelsoft**
- par request from X512.
  - https://github.com/haikuports/haikuports/pull/11368#issuecomment-2501477612

### CODE REVIEW

**Comment by Begasus** [comment]
Keep in mind 32bit buildmaster is down at the moment, so could take some time to end up there.

**Comment by kenz-gelsoft** [comment]
Thank you for merging. Taking time is no problem. BTW, I think this package disables 32bit build...

**Comment by Begasus** [comment]
> Thank you for merging. Taking time is no problem. BTW, I think this package disables 32bit build...

It mentions: SECONDARY_ARCHITECTURES="x86" (so 32bit secondary architecture) :)

**Comment by kenz-gelsoft** [comment]
Oh, I see. 32bit gcc2 build is disabled, but 32bit newer gcc build is enabled.

**Pull request merged**
