### PR TITLE
new Scriptureguide release wich fixes ScriptureguideManager

### PR DESCRIPTION
**Pull request by Paradoxianer**

### CODE REVIEW

**Comment by Begasus** [comment]
Could you remove the previous version while bumping to this one?

**Comment by Paradoxianer** [comment]
> Could you remove the previous version while bumping to this one?

I can do this but may i ask why because with the former bump i didnt need to delete the old one. Just out of curiosity :)

**Comment by Begasus** [comment]
For some recipes it's useful to have an older version around, for this, it fixes things that are broken in the previous version (probably overseen with the previous version bump) :)
So there wouldn't be a need to keep the previous versions around at haikuports (keeps git log smaller as we only see what's changed in the recipe)

**Comment by Begasus** [comment]
You can see it in my PR for lapack here: https://github.com/haikuports/haikuports/pull/5910/files

**Comment by Begasus** [comment]
Good to go?

**Comment by Paradoxianer** [comment]
👍

**Pull request merged**
