### PR TITLE
capnproto: add new recipe, version 0.10.2

### PR DESCRIPTION
**Pull request by pengphei**
Signed-off-by: Han Pengfei <pengphei@qq.com>

### CODE REVIEW

**Comment by Begasus** [comment]
Some changes probably needed for 32bit, but build fails on 32bit atm:
```
/sources/capnproto-c++-0.10.2/src/capnp/message.c++: In member function 'bool capnp::MessageReader::isCanonical()':
/sources/capnproto-c++-0.10.2/src/capnp/message.c++:57:42: error: static assertion failed: arenaSpace is too small to hold a ReaderArena.  Please increase it.  This will break ABI compatibility.
   57 |     static_assert(sizeof(_::ReaderArena) <= sizeof(arenaSpace),
      |                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/sources/capnproto-c++-0.10.2/src/capnp/message.c++: In member function 'capnp::AnyPointer::Reader capnp::MessageReader::getRootInternal()':
/sources/capnproto-c++-0.10.2/src/capnp/message.c++:91:42: error: static assertion failed: arenaSpace is too small to hold a ReaderArena.  Please increase it.  This will break ABI compatibility.
   91 |     static_assert(sizeof(_::ReaderArena) <= sizeof(arenaSpace),
      |                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
src/capnp/CMakeFiles/capnp.dir/build.make:159: recipe for target 'src/capnp/CMakeFiles/capnp.dir/message.c++.o' failed
make[2]: *** [src/capnp/CMakeFiles/capnp.dir/message.c++.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by pengphei** [comment]
with nightly x86-gcc2 image, with **setarch x86**, it will cause building errors:

```
build-requires "haiku_devel" of package "xxxxx" could not be resolved
```

**Comment by augiedoggie** [comment]
> with nightly x86-gcc2 image, with **setarch x86**, it will cause building errors:

You shouldn't need to use the `setarch` command.  You should be able to build the recipe with `haikuporter capnproto_x86`

**Comment by pengphei** [comment]
With your commands, it shows:

```
build-requires "haiku_x86_devel" of package "xxxxx" could not be resolved
```

**Comment by augiedoggie** [comment]
I was able to start a build using that command but there is a compile error in the code.  Make sure you are using a newly opened terminal and that you have **not** used the `setarch` command. The x86_gcc2 arch/compiler should be active when you run the haikuporter command.

```

cpr@haiku32 ~/haikuports/dev-libs/capnproto ()$ haikuporter -S -j8 --get-dependencies --no-source-packages capnproto_x86
Checking if any dependency-infos need to be updated ...

----------------------------------------------------------------------
dev-libs::capnproto_x86-0.10.2
        /boot/home/haikuports/dev-libs/capnproto/capnproto-0.10.2.recipe
----------------------------------------------------------------------

Downloading: https://github.com/capnproto/capnproto/archive/refs/tags/v0.10.2.tar.gz ...
--2022-10-27 10:22:33--  https://github.com/capnproto/capnproto/archive/refs/tags/v0.10.2.tar.gz
Resolving github.com... 140.82.114.3
Connecting to github.com|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/capnproto/capnproto/tar.gz/refs/tags/v0.10.2 [following]
--2022-10-27 10:22:34--  https://codeload.github.com/capnproto/capnproto/tar.gz/refs/tags/v0.10.2
Resolving codeload.github.com... 140.82.114.9
Connecting to codeload.github.com|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/boot/home/haikuports/dev-libs/capnproto/download/v0.10.2.tar.gz’
     0K ........ ........ ........ ........ ..                 969K=2.3s
2022-10-27 10:22:36 (969 KB/s) - ‘/boot/home/haikuports/dev-libs/capnproto/download/v0.10.2.tar.gz’ saved [2279393]
Validating checksum of v0.10.2.tar.gz
Unpacking source of v0.10.2.tar.gz
Initialized empty Git repository in /boot/home/haikuports/dev-libs/capnproto/work-x86-0.10.2/sources/capnproto-0.10.2/.git/
Applying patchset "/boot/home/haikuports/dev-libs/capnproto/patches/capnproto-0.10.2.patchset" ...
Applying: Fix missing pwritev
Using index info to reconstruct a base tree...
A       src/kj/filesystem-disk-unix.c++
Falling back to patching base and 3-way merge...
chroot has these packages active:
        /boot/system/packages/bash-5.1.016-1-x86_gcc2.hpkg
        /boot/system/packages/binutils-2.17_2016_07_24-4-x86_gcc2.hpkg
        /boot/system/packages/binutils_x86-2.36.1_btrev43189-1-x86_gcc2.hpkg
        /boot/system/packages/bzip2-1.0.8-1-x86_gcc2.hpkg
        /boot/system/packages/bzip2_x86-1.0.8-1-x86_gcc2.hpkg
        /boot/system/packages/ca_root_certificates-2022_07_19-1-any.hpkg
        /boot/system/packages/cmake_x86-3.24.2-1-x86_gcc2.hpkg
        /boot/system/packages/coreutils_x86-9.1-1-x86_gcc2.hpkg
        /boot/system/packages/curl_x86-7.84.0-1-x86_gcc2.hpkg
        /boot/system/packages/enca_x86-1.19-2-x86_gcc2.hpkg
        /boot/system/packages/expat-2.4.9-1-x86_gcc2.hpkg
        /boot/system/packages/expat_x86-2.4.9-1-x86_gcc2.hpkg
        /boot/system/packages/fdk_aac_x86-2.0.2-2-x86_gcc2.hpkg
        /boot/system/packages/ffmpeg-4.2.7-1-x86_gcc2.hpkg
        /boot/system/packages/ffmpeg_x86-4.2.7-1-x86_gcc2.hpkg
        /boot/system/packages/fontconfig-2.13.92-1-x86_gcc2.hpkg
        /boot/system/packages/fontconfig_x86-2.13.96-1-x86_gcc2.hpkg
        /boot/system/packages/freetype-2.11.1-3-x86_gcc2.hpkg
        /boot/system/packages/freetype_x86-2.11.1-3-x86_gcc2.hpkg
        /boot/system/packages/fribidi_x86-1.0.11-1-x86_gcc2.hpkg
        /boot/system/packages/game_music_emu_x86-0.6.3-1-x86_gcc2.hpkg
        /boot/system/packages/gcc_x86-11.2.0_2021_07_28-8-x86_gcc2.hpkg
        /boot/system/packages/gcc_x86_syslibs-11.2.0_2021_07_28-8-x86_gcc2.hpkg
        /boot/system/packages/gettext_libintl-0.19.8.1-7-x86_gcc2.hpkg
        /boot/system/packages/gettext_x86_libintl-0.19.8.1-7-x86_gcc2.hpkg
        /boot/system/packages/giflib-5.1.4-2-x86_gcc2.hpkg
        /boot/system/packages/giflib_x86-5.2.1-1-x86_gcc2.hpkg
        /boot/system/packages/gmp_x86-6.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/graphite2_x86-1.3.14-1-x86_gcc2.hpkg
        /boot/system/packages/grep_x86-3.8-1-x86_gcc2.hpkg
        /boot/system/packages/gutenprint8-5.3.1-2-x86_gcc2.hpkg
        /boot/system/packages/gzip-1.12-1-x86_gcc2.hpkg
        /boot/system/packages/haiku-r1~beta3_hrev55181_67-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_devel-r1~beta3_hrev55181_67-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_x86-r1~beta3_hrev55181_67-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_x86_devel-r1~beta3_hrev55181_67-1-x86_gcc2.hpkg
        /boot/system/packages/harfbuzz_x86-4.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/icu-57.2-3-x86_gcc2.hpkg
        /boot/system/packages/icu66_x86-66.1-2-x86_gcc2.hpkg
        /boot/system/packages/jasper-2.0.16-4-x86_gcc2.hpkg
        /boot/system/packages/jasper_x86-2.0.16-4-x86_gcc2.hpkg
        /boot/system/packages/lame-3.100-3-x86_gcc2.hpkg
        /boot/system/packages/lame_x86-3.100-3-x86_gcc2.hpkg
        /boot/system/packages/lcms_x86-2.12-1-x86_gcc2.hpkg
        /boot/system/packages/libass_x86-0.15.2-1-x86_gcc2.hpkg
        /boot/system/packages/libedit-20210910_3.1-2-x86_gcc2.hpkg
        /boot/system/packages/libicns-0.8.1-8-x86_gcc2.hpkg
        /boot/system/packages/libicns_x86-0.8.1-8-x86_gcc2.hpkg
        /boot/system/packages/libiconv-1.16-1-x86_gcc2.hpkg
        /boot/system/packages/libiconv_x86-1.16-1-x86_gcc2.hpkg
        /boot/system/packages/libjpeg_turbo-2.1.3-1-x86_gcc2.hpkg
        /boot/system/packages/libjpeg_turbo_x86-2.1.3-1-x86_gcc2.hpkg
        /boot/system/packages/libogg-1.3.5-1-x86_gcc2.hpkg
        /boot/system/packages/libogg_x86-1.3.5-1-x86_gcc2.hpkg
        /boot/system/packages/libopenmpt_x86-0.6.2-1-x86_gcc2.hpkg
        /boot/system/packages/libpcre_x86-8.45-2-x86_gcc2.hpkg
        /boot/system/packages/libpng16-1.6.37-2-x86_gcc2.hpkg
        /boot/system/packages/libpng16_x86-1.6.37-2-x86_gcc2.hpkg
        /boot/system/packages/libsolv-0.3.0_haiku_2014_12_22-3-x86_gcc2.hpkg
        /boot/system/packages/libsolv_x86-0.3.0_haiku_2014_12_22-3-x86_gcc2.hpkg
        /boot/system/packages/libssh2_x86-1.9.0-2-x86_gcc2.hpkg
        /boot/system/packages/libtheora-1.1.1-7-x86_gcc2.hpkg
        /boot/system/packages/libtheora_x86-1.1.1-7-x86_gcc2.hpkg
        /boot/system/packages/libuv_x86-1.44.1-1-x86_gcc2.hpkg
        /boot/system/packages/libvorbis-1.3.7-1-x86_gcc2.hpkg
        /boot/system/packages/libvorbis_x86-1.3.7-1-x86_gcc2.hpkg
        /boot/system/packages/libvpx_x86-1.11.0-2-x86_gcc2.hpkg
        /boot/system/packages/libwebp-1.2.2-1-x86_gcc2.hpkg
        /boot/system/packages/libwebp_x86-1.2.2-1-x86_gcc2.hpkg
        /boot/system/packages/libxml2-2.9.13-1-x86_gcc2.hpkg
        /boot/system/packages/libxml2_x86-2.9.13-1-x86_gcc2.hpkg
        /boot/system/packages/make-4.1-5-x86_gcc2.hpkg
        /boot/system/packages/mpc_x86-1.2.1-1-x86_gcc2.hpkg
        /boot/system/packages/mpfr_x86-4.1.0-1-x86_gcc2.hpkg
        /boot/system/packages/ncurses6-6.3-1-x86_gcc2.hpkg
        /boot/system/packages/ncurses6_x86-6.3-1-x86_gcc2.hpkg
        /boot/system/packages/nghttp2_x86-1.43.0-1-x86_gcc2.hpkg
        /boot/system/packages/noto-20200106-1-any.hpkg
        /boot/system/packages/noto_sans_cjk_jp-1.004-2-any.hpkg
        /boot/system/packages/openexr-2.2.1-3-x86_gcc2.hpkg
        /boot/system/packages/openexr_x86-2.4.1-1-x86_gcc2.hpkg
        /boot/system/packages/openjpeg-2.1.2-3-x86_gcc2.hpkg
        /boot/system/packages/openjpeg_x86-2.4.0-1-x86_gcc2.hpkg
        /boot/system/packages/openssl-1.1.1q-1-x86_gcc2.hpkg
        /boot/system/packages/openssl_x86-1.1.1q-1-x86_gcc2.hpkg
        /boot/system/packages/openssl_x86_devel-1.1.1q-1-x86_gcc2.hpkg
        /boot/system/packages/opus-1.3.1-1-x86_gcc2.hpkg
        /boot/system/packages/opus_x86-1.3.1-1-x86_gcc2.hpkg
        /boot/system/packages/pkgconfig_x86-0.29.2-4-x86_gcc2.hpkg
        /boot/system/packages/readline-8.1.002-1-x86_gcc2.hpkg
        /boot/system/packages/rhash_x86-1.4.2-1-x86_gcc2.hpkg
        /boot/system/packages/sed-4.2.1-6-x86_gcc2.hpkg
        /boot/system/packages/snappy_x86-1.1.9-1-x86_gcc2.hpkg
        /boot/system/packages/soxr_x86-0.1.3-1-x86_gcc2.hpkg
        /boot/system/packages/speex-1.2.0-4-x86_gcc2.hpkg
        /boot/system/packages/speex_x86-1.2.0-4-x86_gcc2.hpkg
        /boot/system/packages/tar_x86-1.34-1-x86_gcc2.hpkg
        /boot/system/packages/tiff4-4.2.0-1-x86_gcc2.hpkg
        /boot/system/packages/tiff4_x86-4.4.0-1-x86_gcc2.hpkg
        /boot/system/packages/unzip-6.10c23-4-x86_gcc2.hpkg
        /boot/system/packages/wavpack_x86-5.4.0-1-x86_gcc2.hpkg
        /boot/system/packages/xz_utils_x86-5.2.5-1-x86_gcc2.hpkg
        /boot/system/packages/zlib-1.2.12-1-x86_gcc2.hpkg
        /boot/system/packages/zlib_x86-1.2.12-1-x86_gcc2.hpkg
        /boot/system/packages/zlib_x86_devel-1.2.12-1-x86_gcc2.hpkg
----- Package Info ----------------
header size:                     80
heap size:                      769
TOC size:                        41
package attributes size:       1027
total size:                     849
-----------------------------------
----- Package Info ----------------
header size:                     80
heap size:                      758
TOC size:                        41
package attributes size:       1010
total size:                     838
-----------------------------------
waiting for build package capnproto_x86-0.10.2-1 to be activated
waiting for build package capnproto_x86_devel-0.10.2-1 to be activated
Building ...
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /boot/system/bin/x86/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include initializer_list
-- Looking for C++ include initializer_list - found
-- Found OpenSSL: /packages/openssl_x86-1.1.1q-1/.self/develop/lib/x86/libcrypto.so (found version "1.1.1q") found components: Crypto SSL 
-- Looking for makecontext in c
-- Looking for makecontext in c - not found
-- Found PkgConfig: /boot/system/bin/x86/pkg-config (found version "0.29.2") 
-- Checking for module 'libucontext'
--   No package 'libucontext' found
-- Found ZLIB: /boot/system/develop/lib/x86/libz.so (found version "1.2.12") 
-- Configuring done
-- Generating done
-- Build files have been written to: /sources/capnproto-0.10.2
[  1%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/list.c++.o
[  2%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/array.c++.o
[  3%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/common.c++.o
[  4%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/debug.c++.o
[  5%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/io.c++.o
[  6%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/memory.c++.o
[  7%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/exception.c++.o
[  8%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/mutex.c++.o
[  9%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/string.c++.o
[ 10%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/source-location.c++.o
[ 11%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/hash.c++.o
[ 12%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/table.c++.o
/sources/capnproto-0.10.2/c++/src/kj/mutex.c++: In constructor 'kj::_::Mutex::Mutex()':
/sources/capnproto-0.10.2/c++/src/kj/mutex.c++:873:17: warning: missing initializer for member '_pthread_rwlock::<unnamed union>::<unnamed struct>::unused' [-Wmissing-field-initializers]
  873 | Mutex::Mutex(): mutex(PTHREAD_RWLOCK_INITIALIZER) {}
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/sources/capnproto-0.10.2/c++/src/kj/mutex.c++:873:17: warning: missing initializer for member '_pthread_rwlock::<unnamed union>::<unnamed struct>::reader_count' [-Wmissing-field-initializers]
/sources/capnproto-0.10.2/c++/src/kj/mutex.c++:873:17: warning: missing initializer for member '_pthread_rwlock::<unnamed union>::<unnamed struct>::writer_count' [-Wmissing-field-initializers]
/sources/capnproto-0.10.2/c++/src/kj/mutex.c++:873:17: warning: missing initializer for member '_pthread_rwlock::<unnamed union>::<unnamed struct>::waiters' [-Wmissing-field-initializers]
[ 13%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/thread.c++.o
[ 14%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/main.c++.o
[ 15%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/arena.c++.o
[ 16%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/test-helpers.c++.o
[ 17%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/units.c++.o
[ 18%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/encoding.c++.o
[ 20%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/refcount.c++.o
[ 21%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/string-tree.c++.o
[ 22%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/time.c++.o
[ 23%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/filesystem.c++.o
[ 24%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/filesystem-disk-unix.c++.o
[ 25%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/filesystem-disk-win32.c++.o
[ 26%] Building CXX object c++/src/kj/CMakeFiles/kj.dir/parse/char.c++.o
[ 27%] Linking CXX shared library libkj.so
[ 27%] Built target kj
[ 28%] Building CXX object c++/src/kj/CMakeFiles/kj-test.dir/test.c++.o
[ 29%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/c++.capnp.c++.o
[ 30%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/blob.c++.o
[ 31%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/arena.c++.o
[ 32%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/layout.c++.o
[ 33%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/list.c++.o
[ 34%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/async.c++.o
[ 35%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/async-unix.c++.o
[ 37%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/async-win32.c++.o
[ 37%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/async-io-win32.c++.o
[ 40%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/any.c++.o
[ 40%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/message.c++.o
[ 41%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/async-io.c++.o
[ 42%] Linking CXX shared library libkj-test.so
/sources/capnproto-0.10.2/c++/src/capnp/message.c++: In member function 'bool capnp::MessageReader::isCanonical()':
/sources/capnproto-0.10.2/c++/src/capnp/message.c++:57:42: error: static assertion failed: arenaSpace is too small to hold a ReaderArena.  Please increase it.  This will break ABI compatibility.
   57 |     static_assert(sizeof(_::ReaderArena) <= sizeof(arenaSpace),
      |                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/sources/capnproto-0.10.2/c++/src/capnp/message.c++: In member function 'capnp::AnyPointer::Reader capnp::MessageReader::getRootInternal()':
/sources/capnproto-0.10.2/c++/src/capnp/message.c++:91:42: error: static assertion failed: arenaSpace is too small to hold a ReaderArena.  Please increase it.  This will break ABI compatibility.
   91 |     static_assert(sizeof(_::ReaderArena) <= sizeof(arenaSpace),
      |                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
[ 42%] Built target kj-test
[ 43%] Building CXX object c++/src/capnp/CMakeFiles/capnp.dir/schema.capnp.c++.o
[ 44%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/async-io-unix.c++.o
c++/src/capnp/CMakeFiles/capnp.dir/build.make:159: recipe for target 'c++/src/capnp/CMakeFiles/capnp.dir/message.c++.o' failed
make[2]: *** [c++/src/capnp/CMakeFiles/capnp.dir/message.c++.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object c++/src/kj/CMakeFiles/kj-async.dir/timer.c++.o
CMakeFiles/Makefile2:328: recipe for target 'c++/src/capnp/CMakeFiles/capnp.dir/all' failed
make[1]: *** [c++/src/capnp/CMakeFiles/capnp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 46%] Linking CXX shared library libkj-async.so
[ 46%] Built target kj-async
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2.
Error: Build has failed - stopping.

```

**Comment by pengphei** [comment]
> I was able to start a build using that command but there is a compile error in the code. Make sure you are using a newly opened terminal and that you have **not** used the `setarch` command. The x86_gcc2 arch/compiler should be active when you run the haikuporter command.


Thanks @augiedoggie , I have make it works, it's caused by my haikuports.conf, I shouldn't change the *ARCHITECTURES* field to **x86**

**Comment by pengphei** [comment]
Thanks @augiedoggie @Begasus

**Pull request merged**
