### PR TITLE
PR for receipt Heimer 

### PR DESCRIPTION
**Pull request by mazbrili**
Pull request for Heimer recipe   A Qt Mind map application

### CODE REVIEW

**Comment by korli** [comment]
1/ Could you squash and rebase your commits?
2/ Please use the latest 1.10.0.

**Comment by mazbrili** [comment]
> 1/ Could you squash and rebase your commits?
> 2/ Please use the latest 1.10.0.

i've been rebase and squashed it.. CMIIW

**Comment by korli** [comment]
It doesn't look like it's revised or squashed...

**Comment by mazbrili** [comment]
> It doesn't look like it's revised or squashed...

..maybe i cancel this pr and try next after fix from my side?

**Pull request closed without merging**
