### PR TITLE
LibVPX4: bump

### PR DESCRIPTION
**Pull request by extrowerk**
Closes: https://github.com/haikuports/haikuports/issues/2568

### CODE REVIEW

**Comment by fbrosson** [comment]
Oops, sorry, I had not noticed your PR.

**Comment by extrowerk** [comment]
@fbrosson ?

**Comment by fbrosson** [comment]
I started working on this recipe and had almost finished it when I assigned myself to #2571. At that moment I had not noticed you had already opened this PR.)
(The only thing which I had not finished was the very last chunk of the patchset and the `CONFLICTS_devel` topic.)

Well, when I noticed some errors in your PR and also that your patchset was a bit different from the one I wrote, closely based on that of `1.6.1`, I decided to finish my recipe and open a PR.

I'll add a [`Co-authored-by:`](https://help.github.com/articles/creating-a-commit-with-multiple-authors/) with your `users.noreply.github.com` e-mail address so that, if you agree, we can switch to my PR.

**Comment by fbrosson** [comment]
The alternate PR is #2573. I'll only merge it if you are OK with it, of course.
BTW, if you prefer, instead of switching to #2573, I can update #2571 with my changes but keeping you as unique author or adding myself as co-author to the commit. Hmm, after all, this last scenari seems to be the best option. What do you think?

**Comment by extrowerk** [comment]
let's @fbrosson have all the fun :)

**Comment by kenmays** [comment]
@fbrosson - Update didn't include this header: svc_context.h

**Comment by fbrosson** [comment]
Hmm, we need to add `--enable-vp9` to have that file installed.
Let me check and I'll fix this asap.

**Comment by fbrosson** [comment]
Passing `--enable-vp9` was not enough. We also need to pass `CONFIG_SPATIAL_SVC=yes`.
I'll open a PR with this change so that other contributors can comment on this.

**Comment by fbrosson** [comment]
→ #2596

**Pull request closed without merging**
