### PR TITLE
geos: fix libVersion

### PR DESCRIPTION
**Pull request by sikmir**
Fixup #7107

### CODE REVIEW

**Comment by Begasus** [comment]
some packages already exist at /var/buildmaster/haikuports/packages, revision bump required

https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=3029&viewMode=expanded

Maybe needed to get the correct libVersion for other packages that will use it?

**Comment by sikmir** [comment]
> some packages already exist at /var/buildmaster/haikuports/packages, revision bump required

Sure

> Maybe needed to get the correct libVersion for other packages that will use it?

As far as I see only gdal and qgis use geos now. They don't have any requirements for geos version. Or what do you mean?

**Comment by Begasus** [comment]
The fix for the libVersion hasn't been rebuild, so if a package pulls in geos it will still see `libVersion="1.16.0"` atm.

**Comment by sikmir** [comment]
Well, am I right that all we need is to bump geos revision now?

**Pull request merged**
