### PR TITLE
Handbrake 1.1.1 update

### PR DESCRIPTION
**Pull request by kenmays**
Handbrake v1.1.1 released on Monday, June 18, 2018
See: https://handbrake.fr/news.php
Docs: https://handbrake.fr/docs/en/1.1.0/

### CODE REVIEW

**Comment by fbrosson** [comment]
@kenmays, could you please regenerate the patchset with haikuporter?
It looks like it was hand-edited. The prefered way to (re)generate a patchset is to ask haikuporter to do it for you. The following method is not the only one, but it is the easiest to explain: 
1) Backup your current patchset to a safe place.
2) Run:
```
haikuporter --clean handbrake
haikuporter --patch-files-only handbrake
haikuporter --extract-patchset handbrake
```
3) Compare the generated patchset against your backup copy. (In case something goes wrong you will notice it easily.)

N.B. The one-letter shortcuts for the above commands are:
* `--clean` = `-c`
* `--patch-files-only` = `-B`
* `--extract-patchset` = `-e`

(We have a [Patching-with-HaikuPorter](https://github.com/haikuports/haikuports/wiki/Patching-with-HaikuPorter) page in the wiki.)

**Comment by fbrosson** [comment]
Thanks @kenmays for the update and sorry for this late reply...
(I have noticed that you have correctly regenerated your patchset.)
I kicked a build but it failed on my system. (I did not investigate...)

**Comment by extrowerk** [comment]
It fails here at x265.h
@kenmays : you removed the ```--disable-x265``` configure flag, but haven't added the x265 libs and devel libs to the recipe.
Sadly adding the x265 libs to the recipe doesn't helps as it fails to link the executable because missing symbol (x265_api_query).
Readding ```--disable-x265``` without any other changes results a proper package. Please, readd it.

**Comment by scottmc** [comment]
added no merge tag until the pending issue is resolved.  Once resolved, please update the tag.

**Comment by kenmays** [comment]
Resolved in: https://github.com/haikuports/haikuports/pull/2994

**Pull request closed without merging**
