### PR TITLE
optipng: 0.7.4→0.7.5 (bump version & reformat recipe)

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Since @fbrosson apparently doesn't have Haiku installed; to whoever reviews this PR, please test that the recipe builds/works before merging.

**Comment by fbrosson** [comment]
Hi @waddlesplash! I've installed Haiku x86_gcc2 hrev50072 on a real hardware and was able to build optipng-0.7.5 with the recipe in this PR.
Now I'm trying to figure out why Travis CI is throwing this error:
> [Errno 2] No such file or directory: '/home/travis/build/haikuports/haikuports/repository/recipeCache'

If you know what I am missing then could you please give me a hint? Thanks!

**Comment by pulkomandy** [comment]
It is probably because of the changes I did yesterday in haikuporter, and not because of the recipe.

**Comment by fbrosson** [comment]
OK, thanks for the info.

**Comment by korli** [comment]
Please don't add secondary architectures for such tools.

Also as an advice, it would be easier to review when you don't mix changes related to a version update, a reformat, or fixes. You should refrain from doing too much changes for something not broken. Otherwise thanks for your contribution :)

**Comment by fbrosson** [comment]
ok, I've just reverted my recent changes (SECONDARY_ARCHITECTURES and $secondaryArchSuffix)  Should I also get rid of the 5 $secondaryArchSuffix that were already in the recipe before my edits?
I know it does not hurt to keep them, but if I'm not wrong they are useless without a SECONDARY_ARCHITECTURES.

**Comment by korli** [comment]
Thanks.

**Pull request merged**
