### PR TITLE
beshare, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by korli** [comment]
It should be a version bump (2.33)

https://github.com/HaikuArchives/BeShare/archive/v2.33.tar.gz

**Comment by Begasus** [comment]
Will fix later :)

**Comment by Begasus** [comment]
new tar.gz doesn't include the gcc7 fixes ...

**Comment by Begasus** [comment]
So I could update the version but still use the srcGitRev?

**Comment by korli** [comment]
The recipe doesn't seem to reference the patchset.

**Comment by Begasus** [comment]
> The recipe doesn't seem to reference the patchset.

It wasn't suppose to @korli , it was to point out the wrong version being declared, fixed in the new tag release :)

**Comment by korli** [comment]
thanks!

**Pull request merged**
