### PR TITLE
libgeotiff, remove libtool file

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
This needs to be done after bumping proj_x86 .... https://github.com/haikuports/haikuports/issues/3124

**Comment by Begasus** [comment]
wait a sec, need to push some changes :) @korli

**Comment by korli** [comment]
argh!

**Comment by Begasus** [comment]
eeps ... checking

**Comment by Begasus** [comment]
I'll do another revbump to include these changes (without this one)
https://github.com/Begasus/haikuports/commit/3166c1bfa20efa7c4ff7fdf7b2ac1b38ab2f5690

**Comment by Begasus** [comment]
well there are no functional changes in the latest commit, so maybe we could leave it as is?

**Pull request merged**
