### PR TITLE
neon, bump version, remove old recipes, packages depending on neon should be rebuild due compat change

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
From their website: API and ABI backwards-compatible with 0.27.x and later

The provides mention compat >= 29 (should be OK) but maybe it should be changed to 27?

**Comment by pulkomandy** [comment]
The libversioncompat is fine, I think that's the only thing that matters.

**Comment by Begasus** [comment]
> The libversioncompat is fine, I think that's the only thing that matters.

Hence why I didn't change the other :)

**Comment by Begasus** [comment]
Checked with installing LibreOffice, works OK

**Comment by korli** [comment]
Please tell in the commit message, that the compat version changed. Packages depending on neon should be rebuilt.

**Comment by Begasus** [comment]
Packages using neon (from what I can find with a search at haikuports):
- [ ] cadaver
- [ ] musicbrainz
- [ ] libcoverart
- [ ] audacious_plugins
- [ ] subversion
- [ ] libreoffice

**Comment by Begasus** [comment]
@korli Would you prefer a bulk revbump after the merge, or seperate revbumps? (Some patches need an update also (versioning = 31 now, issues with -Werror))

**Comment by korli** [comment]
Bulk revbump when possible. If patches are needed individual revbump plus patch.

**Pull request merged**
