### PR TITLE
coreutils, don't provide suffix-less PROVIDES, make depending package…

### PR DESCRIPTION
**Pull request by Begasus**
…s rely on cmd:* from the package

### CODE REVIEW

**Comment by Begasus** [comment]
Note, this will have a huger impact then the one for diffutils ...
Quite a lot of `BUILD_PREREQUIRES="coreutils"` them out there

**Comment by Begasus** [comment]
Looks like on 32bit Haiku depends on the non suffixed package.

**Comment by korli** [comment]
Isn't coreutils a hard dependency of haikuporter?

**Comment by Begasus** [comment]
When I wanted to install the suffix-less package it wanted to bring down the whole system, so my guess is that the base gcc2 hrev depends on it?

**Comment by Begasus** [comment]
Then this can't be applied as long as it isn't fixed there, I guess coreutils can be replaced like the ones currently mentioned in the PR's for autoconf and automake.

**Pull request closed without merging**
