### PR TITLE
libuninameslist, new recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by korli** [comment]
is it used by fontforge?

**Comment by Begasus** [comment]
> is it used by fontforge?

Yes, haven't bumped the PR for fontforge yet to include this and the one for libspiro, fontforge is pretty heavy to my build system so it tends to freeze my laptop (not related to Haiku)

**Comment by Begasus** [comment]
Not really sure about the license for both this and libspiro, so maybe someone could take a closer look at this?

**Comment by korli** [comment]
Maybe we could skip this one. ArchLinux doesn't seem to use this library for fontforge.

**Comment by Begasus** [comment]
No, problem, this could be closed then without merging

**Pull request closed without merging**
