### PR TITLE
Haiku mime support for Fish

### PR DESCRIPTION
**Pull request by miqlas**
Use /bin/open on Haiku to open files with the associated programs from cli.

Slowly enabling advanced features in fish.....

### CODE REVIEW

**Comment by mmuman** [comment]
I already have a port of XDG utils around but it's not upstreamed nor packaged yet, so meanwhile it's useful to have this fallback.

**Comment by miqlas** [comment]
mmuman, it is nice to see, that you follow the fish port developement. And thanks for your xdg port, but i don't really want an another layer to get the same results. But it is my own preference.

Btw, i sent a PR for fish-shell to get it upstreamed: https://github.com/fish-shell/fish-shell/pull/3487

**Comment by mmuman** [comment]
Well, when the xdg-utils package will be installed it will take precedence anyway, but that's fine.

**Comment by miqlas** [comment]
Not surely, check the upstream link for more info.

-- Z.

2016.10.24. dátummal, 18:39 időpontban François Revol <notifications@github.com> írta:

**Comment by mmuman** [comment]
Yes, it does a ```else if type -q -f xdg-open```, before the test you added, so it will use xdg-open first.
Btw, on linux open is an alias for openvt, which does something completely different. You might want to actually check for Haiku...

**Pull request merged**
