### PR TITLE
Ri-li, new recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
https://ibb.co/zJk61Wp

**Comment by pulkomandy** [comment]
I think it makes sense to get this working only with gcc7. Patches to make it build with gcc2 are not maintainable, and since this isn't a library, there is no point in making it available as a gcc2 program (why would one want to have both gcc2 and gcc7 packages of this available?)

**Comment by Begasus** [comment]
Development ended in 2006, so either I could drop gcc2 support entirely or keep one for those wanting to play it on 32bit (primary) arch, or drop gcc2 support and only go for the gcc7 support (with secondaryArchSuffix), opinions welcome :)

**Comment by pulkomandy** [comment]
Just go with gcc7 everywhere (and $secondaryArchSuffix, of course). We should try to minimize the use of gcc2 at this point.

**Comment by alaviss** [comment]
Here's a patch I hacked up with `find_directory()`, untested :P

```diff
diff --git a/Ri-li-2.0.1.orig/src/utils.cc b/Ri-li-2.0.1/src/utils.cc
index ef41f67..6b8992f 100644
--- a/Ri-li-2.0.1.orig/src/utils.cc
+++ b/Ri-li-2.0.1/src/utils.cc
@@ -32,6 +32,11 @@
 #include <commdlg.h>
 #endif
 
+#ifdef __HAIKU__
+#include <FindDirectory.h>
+#include <Path.h>
+#endif
+
 #include "utils.h"
 #include "preference.h"
 #include "sprite.h"
@@ -308,6 +313,11 @@ bool LoadPref(void)
   char PathPref[512];
   char *Env="PROGDIR:";
   sprintf(PathPref,"%s.ri-li.pref",Env);
+#elif defined(__HAIKU__)
+  BPath SettingPath;
+  if (find_directory(B_USER_SETTINGS_DIRECTORY, SettingPath) != B_OK)
+    return false;
+  const char *PathPref = SettingPath.Path();
 #endif
 
 #ifdef MAC_OSX
@@ -347,6 +357,12 @@ void SauvePref(void)
   char *Env="PROGDIR:";
   sprintf(Provi,"%s.ri-li.pref",Env);
   SauveFichier(Provi,(char*)&Pref,sizeof(sPreference));
+#elif defined(__HAIKU__)
+  BPath SettingPath;
+  if (find_directory(B_USER_SETTINGS_DIRECTORY, SettingPath) == B_OK)
+    SauveFichier(SettingPath.Path(),(char*)&Pref,sizeof(sPreference));
+  else
+    SauveFichier("", NULL, 0);
 #endif
 
 #ifdef MAC_OSX
```

**Comment by alaviss** [comment]
Here's a patch that uses `find_directory` (haven't tested :P)

```diff
diff --git a/src/utils.cc b/src/utils.cc
index ef41f67..57d43df 100644
--- a/src/utils.cc
+++ b/src/utils.cc
@@ -32,6 +32,11 @@
 #include <commdlg.h>
 #endif
 
+#ifdef __HAIKU__
+#include <FindDirectory.h>
+#include <Path.h>
+#endif
+
 #include "utils.h"
 #include "preference.h"
 #include "sprite.h"
@@ -308,6 +313,12 @@ bool LoadPref(void)
   char PathPref[512];
   char *Env="PROGDIR:";
   sprintf(PathPref,"%s.ri-li.pref",Env);
+#elif defined(__HAIKU__)
+  BPath SettingPath;
+  if (find_directory(B_USER_SETTINGS_DIRECTORY,SettingPath) != B_OK)
+    return false;
+  char PathPref[512];
+  sprintf(PathPref,"%s/ri-li.pref",SettingPath.Path());
 #endif
 
 #ifdef MAC_OSX
@@ -347,6 +358,14 @@ void SauvePref(void)
   char *Env="PROGDIR:";
   sprintf(Provi,"%s.ri-li.pref",Env);
   SauveFichier(Provi,(char*)&Pref,sizeof(sPreference));
+#elif defined(__HAIKU__)
+  BPath SettingPath;
+  char Provi[512];
+  if (find_directory(B_USER_SETTINGS_DIRECTORY, SettingPath) == B_OK)
+    sprintf(Provi,"%s/ri-li.pref",SettingPath.Path());
+    SauveFichier(Provi,(char*)&Pref,sizeof(sPreference));
+  else
+    SauveFichier("",NULL,0);
 #endif
 
 #ifdef MAC_OSX
```

**Comment by Begasus** [comment]
This should do it, builds and runs ok on x86 (secondaryArchSuffix) and x86_64

**Pull request merged**
