### PR TITLE
atanks, new recipe (WIP)

### PR DESCRIPTION
**Pull request by Begasus**
The game shows the first screen but halts from there with the message it can't create the config folder, that however is created but the config file isn't created, not sure if that is why it is stopping from going further ...

### CODE REVIEW

**Comment by scottmc** [comment]
See the section on making files writable on the common issues wiki page: https://github.com/haikuports/haikuports/wiki/Common-Issues-when-Porting-Games
It might also require patching to the code so that it points to the settings directory if they hard coded it.

**Comment by scottmc** [comment]
Have you tried the suggestion above yet?

**Comment by Begasus** [comment]
It's been a while since I last checked, iirc I did some checking with the global files and user settings files ... not sure though :) Will check

**Comment by Begasus** [comment]
Checked it this morning, maybe it's not related to creating the config files, I just can't seem to launch the app properly, it shows up but rendering is a problem I think, if so you can discard this PR

**Comment by Begasus** [comment]
Haven't made any progress so far, this one could be closed (no need to stick around if there is no progress) ...

**Comment by waddlesplash** [comment]
Makes sense.

**Pull request closed without merging**
