### PR TITLE
bash_completion: fix the recipe and add support for pkgman and finddir

### PR DESCRIPTION
**Pull request by Max-Might**
Hello.

I have fixed the recipe and added tab-completion support for pkgman and finddir. The pkgman completion script can even complete package names for the 'install' and 'uninstall' options.

To test it install the package, start a shell and execute `source /system/data/bash-completion/bash_completion`.

To have it automatically enabled you have to put the following code in ~/.bashrc as the README says:

```
# Use bash-completion, if available
[[ $PS1 && -f /system/data/bash-completion/bash_completion ]] && \
    . /system/data/bash-completion/bash_completion
```

I have not tested that last part though.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Is there some other way to activate it that we could do from the recipe? A post-install script that does that?

**Comment by Max-Might** [comment]
According the README the `/etc/bashrc` file should work too.
But I am not sure if we have it in Haiku or if our bash port sources it upon startup.

On my ubuntu system there is `/etc/bash.bashrc` file. Which does source the completion file but those lines are commented out so it is only included in `~/.bashrc`.
It should be only used in an interactive shell. (It checks for the PS1 variable) so instead of a post-install script it would be better to do it the ubuntu/debian way because that way it would be enabled for every new user in the system too and every user can disable it for themselves only.

Maybe bash has a template for `~/.bashrc` somewhere so we can patch it before installation.

**Comment by Max-Might** [comment]
After some research it turns out that the `~/.bashrc` template is located at `/etc/skel/.bashrc`.
When you execute `useradd` to create a new user it copies the template(s) to the user's home directory.

**Comment by jessicah** [comment]
Bash config files go in the user settings folder. Previous versions of the recipe have been patched to do this. There is also an existing post install script if you'd like to extend it...

**Comment by Max-Might** [comment]
@jessicah Thanks, I did not know that.

I updated the bash recipe to create a `bashrc` file which loads the completions if they are installed.
Can anyone else test it before it is merged?

**Comment by waddlesplash** [comment]
Thanks!

**Pull request merged**
