### PR TITLE
pyserial, bump version, working recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Probably needs some fine-tuning to be able to work:

```
~> miniterm.py 
don't know how to enumerate ttys on this system.
! I you know how the serial ports are named send this information to
! the author of this module:

sys.platform = 'haiku1'
os.name = 'posix'
pySerial version = 3.2.1

also add the naming scheme of the serial ports and with a bit luck you can get
this module running...
Traceback (most recent call last):
  File "/bin/miniterm.py", line 16, in <module>
    from serial.tools.list_ports import comports
  File "/packages/python3_x86-3.7.6-2/.self/lib/python3.7/vendor-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/packages/python3_x86-3.7.6-2/.self/lib/python3.7/vendor-packages/serial/tools/list_ports_posix.py", line 96, in <module>
    raise ImportError("Sorry: no implementation for your platform ('{}') available".format(os.name))
ImportError: Sorry: no implementation for your platform ('posix') available
```

**Comment by korli** [comment]
I would leave out python2 and python3.6.

**Comment by Begasus** [comment]
Will check in a bit :)

**Comment by Begasus** [comment]
Pushed changes, @korli could you check (not so familiar with python) :)

**Comment by korli** [comment]
Sounds OK.

**Pull request merged**
