### PR TITLE
libsdl2: Implement message box for Haiku

### PR DESCRIPTION
**Pull request by EXL**
Add implementation for functions:

SDL_ShowSimpleMessageBox()
SDL_ShowMessageBox()

Support for simple customization is implemented too.

### CODE REVIEW

**Comment by extrowerk** [comment]
Great job! Can you try to upstream it?

**Comment by EXL** [comment]
tests

Some tests:

```bash
> curl -LOJ http://esxi.z-lab.me:666/~exl_lab/others/SDL2_messagebox_test.c
> gcc `sdl2-config --cflags --libs` SDL2_messagebox_test.c -o msg
> ./msg
```

**Comment by EXL** [comment]
@extrowerk 
No, I did not try.

I think we should send all the relevant patches we have to the SDL2 upstream because the SDL2 library is broken in official repository. In addition, there has recently been a huge renaming stuff which may complicate the transfer of our patches: https://hg.libsdl.org/SDL/rev/09999a0e8f9a

Can anyone prepare our patches for SDL2 upstream before porting of 2.0.9?

@korli @kallisti5 @waddlesplash

**Comment by waddlesplash** [comment]
@EXL, I don't have much experience upstreaming patches; could you look into it?

Otherwise, I could contact one of the SDL developers I guess...

**Comment by EXL** [comment]
@waddlesplash @korli 

>Otherwise, I could contact one of the SDL developers I guess...

Yes please. I created this issue several months ago, but so far no answer.

https://bugzilla.libsdl.org/show_bug.cgi?id=4442

**Comment by korli** [comment]
Smaller patchs are often better to be upstreamed.
you can check the history:
https://bugzilla.libsdl.org/buglist.cgi?bug_status=NEW&bug_status=WAITING&bug_status=RESPONDED&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&op_sys=Haiku&order=bug_id&query_format=advanced

**Comment by EXL** [comment]
Most our patches are merged into the SDL2 upstream today but some questions remain:

https://bugzilla.libsdl.org/show_bug.cgi?id=4442

These are mainly questions on fixing autotools build files by @korli and @pulkomandy, also question about `B_NO_POINTER_HISTORY` patch by @threedeyes.

I think it’s worth clarifying the situation in the official SDL2 BugTracker...
Regards.

**Comment by pulkomandy** [comment]
They contacted me over twitter as well to ask me to look into it. Maybe we need a recipe for the git version sowe can more easily keep track of what is upstreamed already?

**Pull request merged**
