### PR TITLE
qtwebengine, add missing requirement

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Policy error without this when packaging.  @korli , could you do a _bin update on this, been running it on some problem sites and so far no crashes. :)

**Comment by korli** [comment]
thanks @Begasus sorry I let other people do the _bin update.

**Comment by Begasus** [comment]
@korli I saw the current _bin SOURCE_URI set to your account, if you want I could do a PR there to push the files I have here? (that way you can check also before releasing it to the public)

**Comment by korli** [comment]
@Begasus i see current _bin files are from @threedeyes, not from me. Please push an update. I know my local packages aren't up to date, so that's not a good build environmnent anyway.

**Comment by Begasus** [comment]
Maybe @threedeyes already got an updated package ready? If not I'll look into it later :)

**Comment by Begasus** [comment]
PR for an update at: https://github.com/haikuports/haikuports/pull/9802

**Pull request merged**
