### PR TITLE
x264: bump

### LINKED ISSUE #4658: x264: Bump to 20191217
Tested and packaged on Haiku R1B1: 

> x264 0.152.x
> (libswscale 5.5.100)
> (libavformat 58.29.100)
> built on Jan 26 2020, gcc: 8.3.0
> x264 configuration: --bit-depth=8 --chroma-format=all
> libx264 configuration: --bit-depth=8 --chroma-format=all
> x264 license: GPL version 2 or later
> libswscale/libavformat license: LGPL version 3 or later

https://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20191217-2245.tar.bz2

### PR DESCRIPTION
**Pull request by extrowerk**
libversioncompat, debuginfo, remove old
closes #4658

### CODE REVIEW

**Comment by korli** [comment]
SONAME is bumped.

**Comment by extrowerk** [comment]
> SONAME is bumped.

Yep, but only mplayer depends on it, and i am on my way to update/bump that too.

**Comment by extrowerk** [comment]
media-video/avidemux/avidemux-2.7.4.recipe
media-video/handbrake/handbrake-1.2.2.recipe
media-video/mplayer/mplayer-1.4.0.recipe
media-video/shotcut/shotcut-19.12.31.recipe
media-video/vlc/vlc-0.8.6i.recipe
media-video/vlc/vlc-2.2.8.recipe

**Comment by extrowerk** [comment]
VLC is not important, afaik.

**Comment by korli** [comment]
Please note this PR is not yet merged.

**Comment by korli** [comment]
merged manually. x86 build is delayed, will trigger x86 rebuild when needed.

**Pull request closed without merging**
