### PR TITLE
libaddressinput, Co-authored-by: Shiroko

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Passes all tests, not checked on x86_64 (yet)

**Comment by Begasus** [comment]
The download for grit changes the checksum with each download, needs to be looked into ...

**Comment by alaviss** [comment]
I'm thinking if we could just drop this PR. The reasons are:

- This library appears to be designed for bundling. There aren't any `SONAME`.
- This library is not packaged by any linux distribution, which means most (if not all) of its user will be bundling the library (for example: chromium).

**Comment by Begasus** [comment]
Ok, closing this one then :)

**Pull request closed without merging**
