### PR TITLE
curl: bump to 8.10.1

### PR DESCRIPTION
**Pull request by kenmays**
Built and unit tested on Haiku R1B5 hrev57937+122 and hrev58246 x86_gcc2 with GCC2.

### CODE REVIEW

**Comment by Begasus** [comment]
This should be tackled by one of the master developers. :) (had issues myself trying to update this in the past (ps not this PR)).

**Comment by kenmays** [comment]
Ok. Archiving.

**Comment by Begasus** [comment]
It's getting tiresome opening and closing PR's, why close this?

**Comment by kenmays** [comment]
You said 'This should be tackled by one of the master developers. '.... was this intended for someone else to handle?

**Pull request closed without merging**
