### PR TITLE
padblock: disable for <= r1~beta3_pm_hrev54357

### PR DESCRIPTION
**Pull request by humdingerb**
The Padblock input filter has moved into the Haiku tree.

### CODE REVIEW

**Comment by humdingerb** [comment]
I suppose once beta4 is out, we can remove the recipe (and also the code from HaikuArchives).

**Comment by Begasus** [comment]
@humdingerb what's the status on this one, doesn't seem to be included in R1B4?

**Comment by humdingerb** [comment]
It should be, see https://cgit.haiku-os.org/haiku/commit/?id=13b45a2ea30c69f86ec914d82fa88680ac380c06

I cannot really test, because my touchpad isn't recognized as such by Haiku. I just see it as mouse and therefore don't see any "Keyboard lock delay" or "Tapping sensitivity" sliders.

**Comment by Begasus** [comment]
I'm guessing this is the one then?

Input-Preferences

**Comment by pulkomandy** [comment]
Yes, the "Keyboard Lock Delay" at the bottom is what allows to configure the touchpad blocking. This recipe is now unneeded.

**Comment by humdingerb** [comment]
👍

**Comment by Begasus** [comment]
Removed in: https://github.com/haikuports/haikuports/pull/8693

**Pull request merged**
