### PR TITLE
Fish: hide socket warning at start.

### PR DESCRIPTION
**Pull request by miqlas**
Not an ideal solution, but works and doesn't breaks anything.

### CODE REVIEW

**Comment by waddlesplash** [comment]
The error is completely valid, no? So why should we hide it?

**Comment by mmuman** [comment]
That's odd, we should already support AF_UNIX... maybe only for SOCK_STREAM sockets though?
Ah, indeed, cf. src/add-ons/kernel/network/protocols/unix/unix.cpp

**Comment by miqlas** [comment]
This code is used to check for old fish version:
https://github.com/fish-shell/fish-shell/issues/3317#issuecomment-268859613

So we can freely disable it, as "old" means Fish 1.xx, our Fish 1.xx recipe long gone (i deleted it), and the package was instable, i don't expect any real world user in the wild.

**Comment by waddlesplash** [comment]
Oh, very well, it can be merged I guess.

**Pull request merged**
