### PR TITLE
mesa: fix some bugs

### LINKED ISSUE #4458: [mesa] Black border in right an bottom sides of GLView
Component is sys-libs/mesa.
Platform is x86_64.

In BeOS/Haiku rectangle right and bottom sides are inclusive, so actual rectangle size in pixels is (right - left + 1, bottom - top + 1). I attached sample application based on BeBook sample, that showing issue.

screenshot
[OpenGLTest.zip](https://github.com/haikuports/haikuports/files/3976709/OpenGLTest.zip)

### LINKED ISSUE #4470: [sdl2] Deadlock when resizing window with selected OpenGL context
Component: media-libs/libsdl2.
Version: 2.0.10-1.
Platform: x86_64.

SDL_GL_MakeCurrent is implemented as BGLView::LockGL. When window is resized, LockGL is called inside BGLView::FrameResized and lock window thread until OpenGL context will be unset. Input events will be not sent and application will permanently lock.

### PR DESCRIPTION
**Pull request by X547**
Fixes #4458.
Fixes CopyPixels.
Fixes https://dev.haiku-os.org/ticket/14658.
Fixes #4470.

### CODE REVIEW

**Comment by korli** [comment]
Thanks for the PR. What is your build of Haiku and which test apps did you use?

**Comment by X547** [comment]
Haiku is hrev53644 x86_64. Build platform is also Haiku.

I used [OpenGLTest](https://github.com/X547/HaikuUtils/tree/master/OpenGLTest), GLTeapot and Blender 2.79 for test. I use modified version of libsdl2 to fix some bugs in it.

**Comment by kenmays** [comment]
@X547 - Upstream verified patches to mesa dev. Verify Haiku3D demo functionality (i.e. open/close app).

**Comment by X547** [comment]
> Upstream verified patches to mesa dev.

Latest Mesa version 19.2.8 don't work on Haiku because of https://dev.haiku-os.org/ticket/13294.

> Verify Haiku3D demo functionality

Haiku3D work, but all objects are white. Except #4458, functionality was not changed. Haiku3D crash sometimes when resized, but this behavior is not changed by proposed patch.

**Comment by X547** [comment]
What is better, add new patches here or create new requests?

**Comment by kenmays** [comment]
Add them here for Mesa 17. I can upstream the new patches for Mesa 19 dev.

**Comment by waddlesplash** [comment]
> Add them here for Mesa 17. I can upstream the new patches for Mesa 18/19 dev.

Please don't. Let an actual developer who has knowledge of Mesa internals do that.

**Comment by waddlesplash** [comment]
CopyPixels is #4476, yes?

**Comment by X547** [comment]
> CopyPixels is #4476, yes?

No. It just fixes copy rectangle width (off-by-one error). Fixing of that bug require more fundamental changes.

**Comment by kallisti5** [comment]
These look 100% sane.  I remember having some issues around this code and I took a while of "playing" to fix the viewport.   Given the modifications here, I feel like this is a correct adjustment.

 I need to validate if the current mesa build however.. so not going to merge, but this gets a +1 instead of a +2 :-)

**Comment by X547** [comment]
It's maybe good to not merge for now. I will upload more patches later.

**Comment by waddlesplash** [comment]
@X547, is this ready for a merge, or not?

**Comment by X547** [comment]
I have working mesa-19.3.3 port. Everything except CopyPixelsIn/Out (buffer management was changed and BBitmap is now allocated in HGL winsys) is working. This patch is obsolete now.

**Pull request merged**
