### PR TITLE
fpc: fix script shebang

### LINKED ISSUE #10140: fpc: bad script shebang during creation
`fpcbuild-3.2.2/fpcsrc/compiler/cscript.pas` in `dev-lang/fpc/work-3.2.2/sources` in line 400 contains
```pascal
{$ifdef BEOS}
   AddStart('#!/boot/beos/bin/sh');
{$else}
  AddStart('#!/bin/sh');
{$endif}
```

My guess is that the if should be changed to `{$ifdef BEOS and not defined(HAIKU)}`

### PR DESCRIPTION
**Pull request by halamix2**
- fixes #10140
- tested on x86_64 master 

Edit: it's still broken

### CODE REVIEW

**Comment by Begasus** [comment]
Checked with hedgewars, detection was fine, in Terminal I was able to build that one, just not yet with haikuporter.

**Comment by hfsfox** [comment]
In haiku libGLU.so does not exist, that libGLU.so.1, programs with  uses GLU broken, so patch need to revert or create symlink in haiku

**Comment by Begasus** [comment]
libGLU.so exists in $developLibDir, can you provide me an example where it fails? I'm happy to put it back in, just haven't found any downside so far (neither working with Lazarus).

**Comment by Begasus** [comment]
> In haiku libGLU.so does not exist

Isn't this the same for libiconv? there is no libiconv.so in $libDir, that's also in $developLibDir.

**Comment by hfsfox** [comment]
> libGLU.so exists in $developLibDir, can you provide me an example where it fails? I'm happy to put it back in, just haven't found any downside so far (neither working with Lazarus).

in /system/lib only libGLU.so.1

If add GLU to modules and try to run program:
`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
Exception at 00000201F5B4C26B: Exception:
Could not load library: libGLU.so.`

Same situation with libiconv

**Comment by Begasus** [comment]
OK, I'll have another run tomorrow on this and if things work out fine I'll revert the changes for libiconv and libGLU, thanks for stepping in.

**Pull request merged**
