### PR TITLE
gerbera, new recipe

### PR DESCRIPTION
**Pull request by Begasus**
Needs someone to fix the path to search for the config.xml file (or a way to find to cp the config.xml file to ~/config/settings/gerbera)

### CODE REVIEW

**Comment by extrowerk** [comment]
Postinstallscript?

**Comment by Begasus** [comment]
> Postinstallscript?

Had been thinking about it, need to give it a closer look :+1:

**Comment by Begasus** [comment]
I think it has something to do with it here?
https://github.com/gerbera/gerbera/blob/0f1083e1dd4f390a548c3e4fdc5dc29dc159b4f6/src/main.cc#L223

**Comment by Begasus** [comment]
Almost there, need to parch CMakeList.txt to check for "network" instead of "socket" (same for "nsl")

**Comment by Begasus** [comment]
Think I got as far as I can here, reported on the issue for mediatomb: https://github.com/haikuports/haikuports/issues/4722

**Pull request merged**
