### PR TITLE
Recipe for BePhoneBook (Need the license).

### PR DESCRIPTION
**Pull request by arnavbhatt288**
This is the functional recipe for BePhoneBook.
Keep in mind that the app crashes in Haiku (read this issue - https://github.com/HaikuArchives/BePhoneBook/issues/2)
So I am marking this recipe as broken. Also I need the license for it.

### CODE REVIEW

**Comment by bach5000** [comment]
The BePhoneBook recipe has already been done...
https://github.com/haikuports/haikuports/pull/3354
@fbrosson @scottmc Were there 2 recipe tasks for BePhoneBook?

**Comment by fbrosson** [comment]
Oops, good catch! Thanks @bach5000.
There were indeed two tasks for the same recipe!
* https://codein.withgoogle.com/dashboard/tasks/6723428720574464/ (completed 22 days ago)
* https://codein.withgoogle.com/dashboard/tasks/6081553340825600/ (the task associated to this PR.)

**Comment by scottmc** [comment]
Closing this as a duplicate.

**Comment by arnavbhatt288** [comment]
Lol, I hope this mistake won't come again :P

**Pull request closed without merging**
