### PR TITLE
Create youtube_dl-2016.05.21.2.recipe

### PR DESCRIPTION
**Pull request by Vidrep**
New recipe for youtube-dl

### CODE REVIEW

**Comment by waddlesplash** [comment]
Please squash your commits.

**Comment by jessicah** [comment]
@waddlesplash perhaps we should enable squash merge for HaikuPorts, so this can be done automatically?

**Comment by waddlesplash** [comment]
There is squash merge on most PRs. I wonder why I don't see the option here?

**Comment by fbrosson** [comment]
Hmm, maybe it was disabled, or maybe it's only available for PRs which only contain commits from users who already have write permission.

**Pull request merged**
