### PR TITLE
OpenShot: revbump for new python

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by extrowerk** [comment]
Search and replace for president!

**Comment by threedeyes** [comment]
I test OpenShot with python 3.7 and it works very unstable for me. I don't know why, but i have many dedlocks.

**Comment by extrowerk** [comment]
I did not extensively tested it, just started, got the ui, closed it.
Do you happen to have experience with the python3.6 version to be able to compare?

-- Z.

2019.10.03. dátummal, 0:07 időpontban Gerasim Troeglazov <notifications@github.com> írta:

**Comment by extrowerk** [comment]
Just tested but didnot experienced any stability problems at all. It isslow, but stable for me.
Canyou tell me how did you got it crash?

**Comment by threedeyes** [comment]
>Do you happen to have experience with the python3.6 version to be able to compare?
Yep. This video created with OpenShot on Haiku without any problem (python3.6)- https://www.youtube.com/watch?v=3B9pQePQiwU

When i build openshot and pyqt for python 3.7 - i get many dedlocks (when encode video and on close application).  It was a long time ago. I can try again.

**Comment by threedeyes** [comment]
OpenShot switched to python 3.7 in #2306d4e35d080322cea4ec3053538e6193180e8b and #5754b1be6801608e05e98003ca417b9d34ef734e

**Pull request closed without merging**
