### PR TITLE
SimGear: Remove OSG 3.6.x patch

### PR DESCRIPTION
**Pull request by kenmays**
Fix SimGear patchset and recipe to fully build with OSG 3.4.1., not OSG 3.6.3.

### CODE REVIEW

**Comment by extrowerk** [comment]
Whats the status of this? Builds successfully?

**Comment by extrowerk** [comment]
You have to add the 3.4.1 constraint to OSG in the BUILD REQ section, HaikuPorter need to know, otherwise it will use the latest version!

**Comment by kenmays** [comment]
This builds properly. We can review contraint method for best compatibility with current Haukuporter w/ OSG 3.6.3.

**Comment by extrowerk** [comment]
You have to bump the REVISION, as there is already one in the Depot.

**Comment by extrowerk** [comment]
Use ```==``` instead of ```=```.

**Comment by extrowerk** [comment]
```runtime_loader: /boot/system/lib/libSimGearScened.so.2018.2.2: Could not resolve symbol 'glXGetProcAddress'```

**Comment by extrowerk** [comment]
Proposal: SimGear depends on OSG, but there is no graphics support in OSG for Haiku, so we should close this and mark SimGear as broken on every arch.

**Comment by extrowerk** [comment]
WIP-NO-MERGE: as there is no busted tag currently.

**Comment by kenmays** [comment]
Closed per request, as OSG graphic support is unsupported for Haiku. Remove from pkg Haikuports - if needed..

**Pull request closed without merging**
