### PR TITLE
youtube_dl, remove recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Legal issue it seems ...

**Comment by waddlesplash** [comment]
It can still be downloaded from https://ytdl-org.github.io/youtube-dl/download.html ?

**Comment by waddlesplash** [comment]
Or, rather, https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17

**Comment by Begasus** [comment]
OK, will switch later, thanks on the update.

**Comment by Begasus** [comment]
My bad, revived in: https://github.com/haikuports/haikuports/pull/9183

**Pull request merged**
