### PR TITLE
tox: new recipe for messaging platform (WIP, do not merge yet)

### PR DESCRIPTION
**Pull request by raefaldhia**
Adding new recipe for tox, an encrypted, P2P, messaging, audio/video calling platform.

### CODE REVIEW

**Comment by raefaldhia** [comment]
Are you sure not facing kernel panic with --test? i still get it atm.

**Comment by fbrosson** [comment]
OMG, I also get the kernel crash when I run the tests!
I thought you were getting the crash when lauching the runtime. I had not tried the test before you mentioned it.

**Comment by raefaldhia** [comment]
Yes the crash caused by encryptsave_test, tox_test, union_test, and dhf_test. still have no idea what caused it.

For encryptsave_test that's caused by something inside `new_network_ex`.

**Comment by raefaldhia** [comment]
After some hours spending time to track the code flow, `setsocketopt` above `return NULL;` causes crash for `encryptsave_test` still have no idea why this is happened.

screenshot from 2017-01-15 17-24-32

Ignore the `return NULL;` that's just my code to track the code flow.

**Comment by mmlr** [comment]
KDLs are never the fault of the port (or porter) but always a bug in Haiku itself that should be taken up in the Haiku bug tracker at https://dev.haiku-os.org/ . Your last comment makes for a nice bug report as you've already narrowed the cause down significantly.

**Pull request merged**
