### PR TITLE
mini-xml, bump version

### PR DESCRIPTION
**Pull request by Begasus**
Marked as "?" because the creation of the documentation still errors out the build, see: https://github.com/haikuports/haikuports/commit/54f1fa8771392f1f23d80b8998fecdd1847b8feb#commitcomment-26342020

### CODE REVIEW

**Comment by Begasus** [comment]
> The comment speaks of crashes when testing. Is it what you mean with "the creation of the documentation still errors out"?

Yes, the buildlog for v2.11 is the same as for v2.9 mentioned above

**Comment by korli** [comment]
> Yes, the buildlog for v2.11 is the same as for v2.9 mentioned above

I see your patchset removes "testmxml mxml.xml @MXML_EPUB@" because it breaks the build. so the build isn't broken with the patchset? Does "make check" actually do something?

**Comment by Begasus** [comment]
Build is ok, the make check doesn't do something (so obsolete)

**Comment by korli** [comment]
then TEST() should call "make testmxml"

**Comment by Begasus** [comment]
With textxml it fails (as expected I think) ...

**Pull request merged**
