### PR TITLE
SBCL: bump to 2.4.11

### PR DESCRIPTION
**Pull request by kenmays**
Built/unit tested on Haiku hrev58463 x64.

### CODE REVIEW

**Comment by Begasus** [comment]
@al-popa is still looking into this, and according to his last reply in the forum it still needs work, why not wait until he is ready for this?

Then again, @al-popa could you have a look at the changes here?

**Comment by al-popa** [comment]
Unfortunately, -1 from me this time. This commit has several problems:

1. Allows building x86 package (?), which is wrong.
2. The provided patches need improvement (hardcoded value in BSD Sockets).
3. Many of these patches are corrected and upstreamed. The December release 2.5.0 is more appropriate for recipe.

**Comment by Begasus** [comment]
Thanks for checking @al-popa , closing for now, let's wait for next release with upstreamed patches first.
Thanks @kenmays for the PR, but I guess it's not the time to push this out to the public.

**Comment by kenmays** [comment]
@al-popa - Awesome.

**Comment by al-popa** [comment]
@kenmays, thank you for trying this. I probably did not make my intentions with next SBCL recipe sufficiently clear, sorry. Today version 2.5.0 was released. Now I am preparing a recipe for Haiku x86-64.

**Pull request closed without merging**
