### PR TITLE
[WIP] python-setuptools: bump version.

### PR DESCRIPTION
**Pull request by netpositive36**

### CODE REVIEW

**Comment by scottmc** [comment]
Any idea why the checksum changed?  If there was no change to the revision of the source code then why does it have a different checksum than before?

**Comment by extrowerk** [comment]
@scottmc: version bump.
The Revision should be 1.

**Comment by korli** [comment]
setuptools newer versions might not be compatible. I would suggest to rebuild everything depending on it locally before pushing.

**Comment by netpositive36** [comment]
@korli you mean all hp packages depending on the setuptools, right?

**Comment by korli** [comment]
@netpositive36 yes

**Comment by scottmc** [comment]
Task here is to rebuild all haikuports packages that use this and verify nothing gets broken

**Comment by Begasus** [comment]
Last version (at this moment) is 40.6.3

**Comment by waddlesplash** [comment]
Obsolete.

**Pull request closed without merging**
