### PR TITLE
Move openarena and quake3 to a different folder?

### PR DESCRIPTION
**Pull request by kwyxz**
Maybe a silly question, but I see openarena and quake3 in games-action when we have a near-empty games-fps folder in haikuports. Wouldn't it make sense to move these over there? (If so I can do it, just asking out of curiosity)

### CODE REVIEW

**Comment by fbrosson** [comment]
Oops, let's wait a little bit to make sure the other contributors agree with this move/

In case everyone is OK with the move, I'd suggest these commit messages:
* `openarena: move from games-action/openarena/ to games-fps/openarena/. (#2686)`
* `quake3: move from games-action/quake3/ to games-fps/quake3/. (#2686)`

(This is just a suggestion.)

**Comment by kwyxz** [comment]
Ha. Looks like I did things wrong anyway, my 2 commits appear in the thread but not in the "Commits" list. Whoops!

**Comment by kwyxz** [comment]
Oh I see, the 2 commits were meant to be on the same branch I guess?

**Comment by fbrosson** [comment]
Yep, 2 separate commits on the same branch.

**Comment by kwyxz** [comment]
Alright, I fixed the PR. Waiting for others to chime in then :)

**Comment by fbrosson** [comment]
Oops, there's a typo in the commit message.
If there was a single commit then I would be able to change the commit message (using the "Squash and merge" method.)
But here, we need to use the "Rebase and merge" method, which does not give us a change to edit the commit messages, so if you could fix the typos it would be great!

```diff
-Moved OpenArena to more appropriate location (Issue #2686)
+OpenArena: move to more appropriate location (#2686)
-Moved Quake3 to more appropriate location (#2686)
+Quake3: move to more appropriate location (#2686)
```

**Comment by fbrosson** [comment]
Hmm, would you agree with having these commit titles?
* `openarena: move from games-action/openarena/ to games-fps/openarena/. (#2686)`
* `quake3: move from games-action/quake3/ to games-fps/quake3/. (#2686)`

**Comment by kwyxz** [comment]
Welp, at this point I can still reset everything and start over because amending the original commit name will be more painful.

**Comment by fbrosson** [comment]
Cool, you fixed the typo, but the word "issue" does not apply anymore because now it is a PR :smile:

**Comment by kwyxz** [comment]
Crap. I hoped resetting to HEAD would get rid of the original commits but it did not.

**Comment by kwyxz** [comment]
What's your suggestion @fbrosson should we delete this PR and just create another one at this point

**Comment by fbrosson** [comment]
No, you don't need to open another PR. You just need to rebase your branch against master and `git push -f`.

**Comment by fbrosson** [comment]
What do you get with `git log | head -15` ?

**Comment by fbrosson** [comment]
I have an idea: I can grab your remote branch, do the rebase and then update your PR.

**Comment by kwyxz** [comment]
I'm fine with your idea if it works for you :)

**Comment by fbrosson** [comment]
(I dropped the ` (#2686)` from one of the commits because the line would have been too long with it.)

**Comment by kwyxz** [comment]
Thanks!

**Pull request merged**
