### PR TITLE
monsterz: restore recipe.

### PR DESCRIPTION
**Pull request by OscarL**
This addresses #8410 by:

- Reverting #8256.
- Applying Debian's patches, so it it works with Python 3.x.
- Other minor fixes to the recipe, and location of the settings file (by patching configdir on monsterz.py).

Added a vector icon file generated (vía autotracer.org) based on icon.png.

Tested on 64 and 32 bits.

### CODE REVIEW

**Comment by Begasus** [comment]
Good to go?

**Comment by pulkomandy** [comment]
You can't add an icon as a BResource to anything else than an ELF executable. You can however add it directly to the file attributes instead (using 'addattr' for example).

As for starting from DeskBar, probably this results in the app getting the wrong "current directory" at start (we have patched a lot of software for this: on Linux and Windows the default is starting in the place where the executable is located, but in our case we start in /boot/home).

**Comment by pulkomandy** [comment]
> I also tried to use an .rdef file, but Icon-O-Matic was generating a file way too big for my taste (when exporting the icon).

Well, that's what you get from auto-tracing it from a PNG file. It results in way too complex SVG which in turns results in a very large HVIF file. It should be cleaned or re-drawn by hand.

**Comment by Begasus** [comment]
Maybe keep the svg icon if someone wants to tackle it, and create an issue for this icon, ps, in previous version there wasn't an icon for it?

**Comment by pulkomandy** [comment]
I made a smaller icon.

I started from graphics.svg in the source repository and extracted just the red monster using inkscape. Then I imported that in Icon O Matic and optimized it a bit to remove duplicate shapes, and some details. It's down to 1.6KB as HVIF now.

Making it even smaller would require realigning the control points to the grid, which would change the monster shape a bit, but should not really be noticeable on a small icon.

http://pulkomandy,tk/drop/monsterz.svg
http://pulkomandy,tk/drop/monsterz.iom
http://pulkomandy,tk/drop/monsterz.hvif

**Pull request merged**
