### PR TITLE
GCC 11.1

### PR DESCRIPTION
**Pull request by extrowerk**
Depends on  https://review.haiku-os.org/c/haiku/+/3890

### CODE REVIEW

**Comment by extrowerk** [comment]
Package size analysis:
```
8.3.0:
gcc_debuginfo-8.3.0_2019_05_24-9-x86_64.hpkg			372.5 MB
gcc_fortran-8.3.0_2019_05_24-9-x86_64.hpkg				11.84 MB
gcc_syslibs_devel-8.3.0_2019_05_24-9-x86_64.hpkg		2.18 MB
gcc_syslibs-8.3.0_2019_05_24-9-x86_64.hpkg					1.69 MB
gcc-8.3.0_2019_05_24-9-x86_64.hpkg								57.7 MB

10.3.0:
gcc_debuginfo-10.3.0_2021_04_08-1-x86_64.hpkg		403.7 MB
gcc_fortran-10.3.0_2021_04_08-1-x86_64.hpkg				13.08 MB
gcc_syslibs_devel-10.3.0_2021_04_08-1-x86_64.hpkg	2.2 MB
gcc_syslibs-10.3.0_2021_04_08-1-x86_64.hpkg				2.05 MB
gcc-10.3.0_2021_04_08-1-x86_64.hpkg							146.7 MB

11.1.0:
gcc_debuginfo-11.1.0_2021_04_27-1-x86_64.hpkg		420.0 MB
gcc_fortran-11.1.0_2021_04_27-1-x86_64.hpkg				13.92 MB
gcc_syslibs_devel-11.1.0_2021_04_27-1-x86_64.hpkg	2.38 MB
gcc_syslibs-11.1.0_2021_04_27-1-x86_64.hpkg				2.11 MB
gcc-11.1.0_2021_04_27-1-x86_64.hpkg							155.3 MB
```
The main gcc package is now almost 3 times bigger compared than its 8.3.0 counterpart. The debuginfo package grew also considerably.
The packages have to be analyzed and reduced in size as possible.

**Comment by extrowerk** [comment]
Newcomer "lto-dump" have to be stripped.

**Comment by extrowerk** [comment]
After stripping everything:
```
11.1.0:
gcc_debuginfo-11.1.0_2021_04_27-1-x86_64.hpkg				496.3 MB
gcc_fortran-11.1.0_2021_04_27-1-x86_64.hpkg				13.92 MB
gcc_syslibs_devel-11.1.0_2021_04_27-1-x86_64.hpkg			2.38 MB
gcc_syslibs-11.1.0_2021_04_27-1-x86_64.hpkg				2.11 MB
gcc-11.1.0_2021_04_27-1-x86_64.hpkg					72.16 MB
```

**Comment by extrowerk** [comment]
Experiences using GCC11 as part of the buildtools:
GCC8.4.0 can't build GCC11 cross, libcody complains about missing C++11:
```
Configuring in ./libcody
configure: creating cache ./config.cache
checking build system type... x86_64-unknown-haiku_buildhost
checking host system type... x86_64-unknown-haiku_buildhost
checking maintainer-mode... 
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ is for C++11... no
configure: error: C++11 is required
Makefile:7803: recipe for target 'configure-libcody' failed
make[1]: *** [configure-libcody] Error 1
make[1]: Leaving directory '/Ports/haiku/gecerated_gcc11/cross-tools-x86_64-build/gcc'
Makefile:960: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Building gcc failed.
```

**Comment by extrowerk** [comment]
Compilation test: https://gist.github.com/extrowerk/49420ea9b9f8c7807380428b43ef21ce

**Comment by extrowerk** [comment]
libgomp fails in buildtools:

```
Configuring in x86_64-unknown-haiku/libgomp
configure: creating cache ./config.cache
checking for --enable-version-specific-runtime-libs... no
checking for --enable-generated-files-in-srcdir... no
checking build system type... x86_64-unknown-haiku_buildhost
checking host system type... x86_64-unknown-haiku
checking target system type... x86_64-unknown-haiku
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for x86_64-unknown-haiku-strip... /Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-unknown-haiku-gcc... /Ports/haiku/generated_gcc11/cross-tools-x86_64-build/gcc/./gcc/xgcc -B/Ports/haiku/generated_gcc11/cross-tools-x86_64-build/gcc/./gcc/ -B/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/ -B/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/lib/ -isystem /Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/include -isystem /Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/sys-include   
checking whether the C compiler works... no
configure: error: in `/Ports/haiku/generated_gcc11/cross-tools-x86_64-build/gcc/x86_64-unknown-haiku/libgomp':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:15235: recipe for target 'configure-target-libgomp' failed
make[1]: *** [configure-target-libgomp] Error 1
make[1]: Leaving directory '/Ports/haiku/generated_gcc11/cross-tools-x86_64-build/gcc'
Makefile:960: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Building gcc failed.
```
Maybe it should be updated?

**Comment by korli** [comment]
> libgomp fails in buildtools:

libgomp can't be built as part of the cross compiler, only in the gcc11 recipe.

**Comment by extrowerk** [comment]
> > libgomp fails in buildtools:
> 
> libgomp can't be built as part of the cross compiler, only in the gcc11 recipe.

I see. Do you happen to know how is libgomp stopped from getting involved?

**Comment by korli** [comment]
> I see. Do you happen to know how is libgomp stopped from getting involved? Or do i need to use the haikuports bootstrap repo? Sorry, this area is mostly unknown to me.

A cross compiler would need a sysroot with devel headers, shared libs, linking objects. For instance this is needed to bootstrap OpenJDK for Haiku on Linux (zlib, etc...).

**Comment by extrowerk** [comment]
> > I see. Do you happen to know how is libgomp stopped from getting involved? Or do i need to use the haikuports bootstrap repo? Sorry, this area is mostly unknown to me.
> 
> A cross compiler would need a sysroot with devel headers, shared libs, linking objects. For instance this is needed to bootstrap OpenJDK for Haiku on Linux (zlib, etc...).

i can't ay i uderstand what you have meant. What i did is:
- cloned the buildtools repo
- replaced the gcc folder with the GCC11 one from haikuports, already patched
- added isl to the gcc folder
- tried to build like `../configure --cross-tools-source ../../buildtools --build-cross-tools x86_64`
this fails.
Unchanged buildtools obviously works, and it doesn't tries to build libgomp, so there must be something which triggers libgomp to get involved. Maybe the gcc11 source tree missing some patches.

I'm trying to build this on Haiku.

**Comment by korli** [comment]
>   Unchanged buildtools obviously works, and it doesn't tries to build libgomp, so there must be something which triggers libgomp to get involved. Maybe the gcc11 source tree missing some patches.
> 

Yeah, in the haikuports patchset, libgomp is automatically enabled, see:
https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/patches/gcc-8.3.0_2019_05_24.patchset#L92

It's likely that you can override this with --disable-libgomp in build/scripts/build_cross_tools_gcc4

**Comment by extrowerk** [comment]
Thanks! Will try.

In the meantime i tried to build haiku.hpkg with the host compiler:
```
/Ports/haiku/gcc11_build_test> jam -q haiku.hpkg
Starting build of type regular ... 
...patience...
...found 90874 target(s)...
...updating 13897 target(s)...
C++ objects/haiku_host/x86_64/release/build/libpackage/RepositoryBuilder.o 
In file included from /boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/11.1.0/include/c++/stdlib.h:36,
                 from ../headers/build/../private/shared/AutoDeleter.h:19,
                 from ../headers/build/private/shared/AutoDeleter.h:1,
                 from ../src/kits/package/manager/RepositoryBuilder.cpp:20:
/boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/11.1.0/include/c++/cstdlib:133:11: error: 'aligned_alloc' has not been declared in '::'
  133 |   using ::aligned_alloc;
      |           ^~~~~~~~~~~~~

gcc -c "../src/kits/package/manager/RepositoryBuilder.cpp" -O2 -Wall -Wno-trigraphs -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wpointer-arith -Wcast-align -Wsign-compare -Wno-multichar -include ../headers/build/HaikuBuildCompatibility.h -include ../headers/build/BeOSBuildCompatibility.h -fPIC -DARCH_x86_64 -D_NO_INLINE_ASM -D__NO_INLINE__ -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DHAIKU_HOST_USE_XATTR -DHAIKU_HOST_PLATFORM_HAIKU -DHAIKU_HOST_PLATFORM_64_BIT -DHAIKU_PACKAGING_ARCH=\"x86_64\" -iquote ../build/user_config_headers -iquote ../build/config_headers -iquote ../src/build/libpackage -iquote objects/common/build/libpackage -iquote objects/haiku_host/x86_64/common/build/libpackage -iquote objects/haiku/x86_64/common/build/libpackage -iquote ../src/kits/package -iquote ../src/kits/package/hpkg -iquote ../src/kits/package/hpkg/v1 -iquote ../src/kits/package/manager -iquote ../src/kits/package/solver -I ../headers/build/private/kernel -I ../headers/build/private/package -I ../headers/build/private/shared -I ../headers/build/private/libroot -I ../headers/build/private/storage -I ../headers/build/private/support -I ../headers/os/net -I ../headers/build/host/haiku_host -I ../headers/build -I ../headers/build/os -I ../headers/build/os/add-ons/registrar -I ../headers/build/os/app -I ../headers/build/os/bluetooth -I ../headers/build/os/drivers -I ../headers/build/os/kernel -I ../headers/build/os/interface -I ../headers/build/os/locale -I ../headers/build/os/storage -I ../headers/build/os/support -I ../headers/build/private -o "objects/haiku_host/x86_64/release/build/libpackage/RepositoryBuilder.o"

...failed C++ objects/haiku_host/x86_64/release/build/libpackage/RepositoryBuilder.o ...

BUILD FAILURE:
...failed updating 1 target(s)...
...skipped 4 target(s)...
```

It is still not solved.
My current temporary workaround is to add the following line to /Ports/haikuports/sys-devel/gcc/work-11.1.0_2021_04_27/sources/gcc-11.1.0/libstdc++-v3/include/c_global/cstdlib:

```
+#define _ISOC11_SOURCE
#include <bits/c++config.h>
```

**Comment by pulkomandy** [comment]
Why do we need to use _ISOC11_SOURCE here? That is apparently for getting some compatibility with C11 when using a C99 compiler.

Can't we use the --std=c11 compiler flag to enable full C11 support instead?

**Comment by extrowerk** [comment]
> It's likely that you can override this with --disable-libgomp in build/scripts/build_cross_tools_gcc4

This works, thanks!

**Comment by korli** [comment]
> Why do we need to use _ISOC11_SOURCE here? That is apparently for getting some compatibility with C11 when using a C99 compiler.
> 
> Can't we use the --std=c11 compiler flag to enable full C11 support instead?

It's a cpp file, so it uses the default c++ standard. it seems aligned_alloc is standardized in C++17. 
@extrowerk  did you try this suggestion? https://github.com/haikuports/haikuports/issues/5857#issuecomment-829861445

**Comment by extrowerk** [comment]
Sae problem with libatomic in buildtools:
```
onfigure:3756: checking whether the C compiler works
configure:3778: /Ports/haiku/generated_gcc11/cross-tools-x86_64-build/gcc/./gcc/xgcc -B/Ports/haiku/generated_gcc11/cross-tools-x86_64-build/gcc/./gcc/ -B/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/ -B/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/lib/ -isystem /Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/include -isystem /Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/sys-include    -g -O2   conftest.c  >&5
/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/ld: cannot find crti.o: No such file or directory
/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/ld: cannot find start_dyn.o: No such file or directory
/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/ld: cannot find init_term_dyn.o: No such file or directory
/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unknown-haiku/bin/ld: cannot find -lroot
/Ports/haiku/generated_gcc11/cross-tools-x86_64/x86_64-unk``nown-haiku/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by korli** [comment]
this haikuports patchset enables libatomic: https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/patches/gcc-8.3.0_2019_05_24.patchset#L1511   
perhaps you can override this with --disable-libatomic in build/scripts/build_cross_tools_gcc4

**Comment by extrowerk** [comment]
> this haikuports patchset enables libatomic: https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/patches/gcc-8.3.0_2019_05_24.patchset#L1511
> perhaps you can override this with --disable-libatomic in build/scripts/build_cross_tools_gcc4

That seems to be solved the problem.

**Comment by extrowerk** [comment]
> > Why do we need to use _ISOC11_SOURCE here? That is apparently for getting some compatibility with C11 when using a C99 compiler.
> > Can't we use the --std=c11 compiler flag to enable full C11 support instead?
> 
> It's a cpp file, so it uses the default c++ standard. it seems aligned_alloc is standardized in C++17.
> @extrowerk did you try this suggestion? [#5857 (comment)](https://github.com/haikuports/haikuports/issues/5857#issuecomment-829861445)

Yep i did, but it solved the problem only halfway, check my comment earlier.

**Comment by korli** [comment]
> > > Why do we need to use _ISOC11_SOURCE here? That is apparently for getting some compatibility with C11 when using a C99 compiler.
> > > Can't we use the --std=c11 compiler flag to enable full C11 support instead?
> > 
> > 
> > It's a cpp file, so it uses the default c++ standard. it seems aligned_alloc is standardized in C++17.
> > @extrowerk did you try this suggestion? [#5857 (comment)](https://github.com/haikuports/haikuports/issues/5857#issuecomment-829861445)
> 
> Yep i did, but it solved the problem only halfway, check my comment earlier.

Please try to amend libstdc++-v3/crossconfig.m4 adding the following in the Haiku section after AC_DEFINE(HAVE_TLS)
```m4
AC_CHECK_FUNCS(aligned_alloc posix_memalign memalign _aligned_malloc)

**Comment by extrowerk** [comment]
> ```m4
> AC_CHECK_FUNCS(aligned_alloc posix_memalign memalign _aligned_malloc)
> ```

This also not fixed the issue

**Comment by extrowerk** [comment]
This recipe depends on: https://review.haiku-os.org/c/haiku/+/3896

**Comment by korli** [comment]
What's the status on hrev55075+?

**Comment by extrowerk** [comment]
> What's the status on hrev55075+?

Just built it on hrev55075 with the libcody configure patch from tqh (have to push it), seems to be ok.

**Comment by extrowerk** [comment]
The libcody patch is required only for buildtools, but works for haikuports too.
Now GCC11 builds both for buildtools and for haikuports.
The only missing thing is: it fails to build Haiku.

**Comment by korli** [comment]
the libcody patch is useless at haikuports

**Comment by extrowerk** [comment]
> the libcody patch is useless at haikuports

True, but also not harmful.
I can remove it if you wish.

**Comment by Begasus** [comment]
I gather this can't be build on R1B2?

**Comment by extrowerk** [comment]
It should work on beta, but i havent tested it. Afaik kenmays did, and we had to extra patch Haiku for being able to build it on nightlys. No guarantee tho.

**Comment by extrowerk** [comment]
@korli i tried to adopt this https://github.com/haikuports/haikuports/commit/6b7ae7d3f50a5512d0c49c88fc73c12f074fbebe for GCC11, but after applying it i got cryptic errors. I think if that patch required for GCC11 then it needs some more work than applying it as is.

**Comment by extrowerk** [comment]
Building Haiku with GCC11 fails with this: https://dev.haiku-os.org/ticket/14366

**Comment by mt819** [comment]
I add -std=gnu++14 -Wno-error to Buildconfig, and seems to build Haiku. But the image cannot boot FirstBootPrompt.

**Comment by diversys** [comment]
@korli Thanks for all the work! I wonder why we can't enable it just yet tho?

**Comment by extrowerk** [comment]
Why does it got disabled?

**Comment by korli** [comment]
It got disabled, because the buildbot would prefer it over GCC 8.3. I'm afraid it has to be enabled with the OS.

**Comment by Coldfirex** [comment]
Do those two patches in gerrit (4081, 4082) resolve the issue with getting us to GCC11 as our base compiler?

**Pull request merged**
