### PR TITLE
QMPlay2 bump version

### PR DESCRIPTION
**Pull request by khallebal**
Here is my 3'rd attempt, hopefully this time will be the good one.As i said in my previous pull request attempt, Cmake requires harfbuzz, fontconfig and fribidi for libass,it also requires graphite2 and glib2 for harfbuzz, the glib2 is only required when building on gcc2h but not on pure x86, is this a normal behaviour of cmake or is it just our port that's acting?
Youtube doesn't work, i get connection error msg if try i do a search, it used to with Qt4, so i suspect a bug in Qt5.

### CODE REVIEW

**Comment by khallebal** [comment]
Somebody please could review it and tell me why it failed so i can fix it?

**Comment by diversys** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

**Comment by khallebal** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

> 
Sorry, i don't know what you mean by "git mv old_recipe new_recipe" git and github are all new to me, can you please explain that in few steps?

**Comment by khallebal** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

> 
Sorry, i don't know what you mean by "git mv old_recipe new_recipe" git and github are all new to me, can you please explain that in few steps?

**Comment by khallebal** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

> 
Sorry, i don't know what you mean by "git mv old_recipe new_recipe" git and github are all new to me, can you please explain that in few steps?

**Comment by khallebal** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

> 
Sorry, i don't know what you mean by "git mv old_recipe new_recipe" git and github are all new to me, can you please explain that in few steps?

**Comment by khallebal** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

> 
Sorry, i don't know what you mean by "git mv old_recipe new_recipe" git and github are all new to me, can you please explain that in few steps?

**Comment by khallebal** [comment]
Could you please use git mv old_recipe new_recipe and force push your changes.
Otherwise it is hard to see what's new and why Travis build fails.

> 
Sorry, i don't know what you mean by "git mv old_recipe new_recipe" git and github are all new to me, can you please explain that in few steps?

**Comment by diversys** [comment]
If you haven't seen this try https://try.github.io/

You created a new recipe and committed it, instead, what would be cooler (and easier to review) is to rename an old recipe to **qmplay2-17.06.09.recipe** (using `git mv old_recipe new_recipe` (as well as the patch) and update/fix stuff there.
GitHub will then show changes you made to the new recipe (and patch) which should be fairly short and easier for others to review. You can then `git -f push` changes which should automagically update this pull request (PR). So, you don't need to close this PR!

Also rename it to **QMPlay2: bump version** adding a colon.

I know it's hard to figure some things out the first time but when you do that a couple of times it should be fairly easy to do that! :)

**Comment by khallebal** [comment]
Okay, thanks for the info, one more question though regarding the patch, you mean i can modify the patch manualy too, i'm not sure this is a good idea? i'm sorry if i'm asking too many questions.

**Comment by korli** [comment]
There is still a "media-video/qmplay2-17.06.09.recipe" in your commits.

**Comment by khallebal** [comment]
`There is still a "media-video/qmplay2-17.06.09.recipe" in your commits.`
What do you mean by that? i know i have alot to learn yet about git & github.

**Comment by korli** [comment]
Well the part with "media-video/qmplay2/qmplay2-17.04.21.recipe → media-video/qmplay2-17.06.09.recipe" of the PR.

**Comment by khallebal** [comment]
That's because i used git mv old_recipe new_recipe  as suggested by diversys, do i have to remove it? i'm not sure how?

**Comment by korli** [comment]
You misused the command, because it moved the recipe in media-video.

**Comment by diversys** [comment]
You did 
`git mv media-video/qmplay2/qmplay2-17.04.21.recipe media-video/qmplay2-17.06.09.recipe` instead of  
`
cd media-video/qmplay2 ; git mv qmplay2-17.04.21.recipe qmplay2-17.06.09.recipe`

**Comment by khallebal** [comment]
Ah,okay, i didn't know that, so is there a way to fix it?

**Comment by korli** [comment]
Just do:

git rm media-video/qmplay2-17.06.09.recipe
And commit.

**Comment by khallebal** [comment]
```
Just do:

git rm media-video/qmplay2-17.06.09.recipe
And commit.
```
And the git push -f?

**Comment by diversys** [comment]
Yes, commit will only commit it to your local git repo, you need to force push it to github so it can update this PR.

**Comment by khallebal** [comment]
Okay, Done.

**Comment by diversys** [comment]
I'm not sure what you did but it still looks wrong.
I suggest you:
1. to save you recipe and patch somewhere
2. git reset --hard 
3. git mv old_recipe new_recipe (and patch)
4. replace recipe and patch with those you saved in step 1
5. git -f push

**Comment by khallebal** [comment]
I think git reset --hard did'nt fix the repo, it just regenerated the qmplay2-17.06.09.recipe & patch, so i first updated with upstream, then i did
git mv old_recipe new_recipe (and patch)
git commit . -m "QMPlay2: bump version"
git push -f
Is it alright now?

**Comment by khallebal** [comment]
I think git reset --hard did'nt fix the repo, it just regenerated the qmplay2-17.06.09.recipe & patch, so i first updated with upstream, then i did
git mv old_recipe new_recipe (and patch)
git commit . -m "QMPlay2: bump version"
git push -f
Is it alright now?

**Comment by diversys** [comment]
Please check Files changed tab. As you can see patchset was correctly renamed, i.e.:
`...qmplay2/patches/qmplay2-17.04.21.patchset → ...ay2/patches/qmplay2_x86-17.06.09.patchset`
but the old recipe was deleted and the new one was created.

**Comment by khallebal** [comment]
Sorry guys i'm gonna have to close this PR and start over, my repo has gotten all messed up.

**Comment by khallebal** [comment]
Sorry guys i'm gonna have to close this PR and start over, my repo has gotten all messed up.

**Pull request closed without merging**
