### PR TITLE
filezilla: update to 3.65.0

### PR DESCRIPTION
**Pull request by davidkaroly**

### CODE REVIEW

**Comment by Begasus** [comment]
Build failure on buildmaster: configure: error: Boost Regex 1.76 or higher not found.
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/9668/builds/81022.log

**Comment by davidkaroly** [comment]
> Build failure on buildmaster: configure: error: Boost Regex 1.76 or higher not found. https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/9668/builds/81022.log

buildmaster might have outdated packages?

**Comment by Begasus** [comment]
No, it used boost1.69 which is still available, mostly I set a version string for boost requirements. :)

**Comment by davidkaroly** [comment]
> No, it used boost1.69 which is still available, mostly I set a version string for boost requirements. :)

ok i guess this should be the way forward for this recipe as well. I'll prepare an updated PR.

**Pull request merged**
