### PR TITLE
Match SDL BUILD_REQUIRES to REQUIRES

### PR DESCRIPTION
**Pull request by Crestwave**
Also sneaked in a fix to `jumpnbump`'s `SOURCE_URI`; I forgot to replace the placeholder one I used.

### CODE REVIEW

**Comment by Begasus** [comment]
Maybe bump REVISION for them? (keeps track of the history then)

**Comment by Crestwave** [comment]
Oh, I didn't think this would change the output package. Done

**Comment by Begasus** [comment]
> Oh, I didn't think this would change the output package. Done

I doesn't, but it could be helpful to others referring to the same issue

**Comment by Begasus** [comment]
Ready? :)

**Comment by Crestwave** [comment]
To merge? Sure, I guess, if it's finalized that this is better

**Comment by Begasus** [comment]
Thanks! :+1:

**Pull request merged**
