### PR TITLE
OpenSSH: Remove work-around script that creates user.

### PR DESCRIPTION
**Pull request by agmsmith**
Now that the package daemon properly runs post-install actions
in hrev54986, such as creating users, we can remove the
work-around script files that did the same job.

### CODE REVIEW

**Comment by korli** [comment]
this can't be merged at the moment: the current stable is still beta2.

**Comment by agmsmith** [comment]
> this can't be merged at the moment: the current stable is still beta2.

Good point.  Should be safe to do it soon after Beta3 comes out and doesn't do any harm (other than being inefficient) if it's delayed a bit more.

**Comment by agmsmith** [comment]
Oops, accidentally deleted master branch while trying to force it to update.  Will have to regenerate the pull request...

**Comment by agmsmith** [comment]
Now see https://github.com/haikuports/haikuports/pull/6014

**Pull request closed without merging**
