### PR TITLE
libatomic_ops: bump to 7.6.4.

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
@ivmai, can you please help me update the `COPYRIGHT` variable?
I don't really know where to insert a 2018, nor if we should add a `2011-2018 Ivan Maidanski` or something else.
Thanks!

BTW, the tests are all OK on all architectures :)
```
PASS: test_atomic
PASS: test_atomic_generalized
PASS: test_stack
PASS: test_malloc
PASS: test_atomic_pthreads
============================================================================
Testsuite summary for libatomic_ops 7.6.4
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
Architectures tested: x86 (both primary and secondary), x86_64.

**Comment by ivmai** [comment]
Hello @fbrosson 
Thank you for making this pull request (I was thinking yesterday about the upgrade).

> can you please help me update the COPYRIGHT variable?
> I don't really know where to insert a 2018, nor if we should add a 2011-2018 Ivan Maidanski or something else.

Actually I don't care about it but I don't mind. I'm contributing to the project for 10 years already and I'm the maintainer of it for 8 years. "2011-2018 Ivan Maidanski" would be OK.

**Comment by fbrosson** [comment]
Thanks @ivmai for your comment! 
So, I'm adding `2009-2018 Ivan Maidanski` to have the right credits ;)

**Comment by fbrosson** [comment]
Oops, I guess I should `s/2009/2008/`.
Did you start contributing in 2009 or 2008?

**Pull request merged**
