### PR TITLE
Krita: bump to 5.2.6

### PR DESCRIPTION
**Pull request by kenmays**
Krita 5.2.6 - Haiku patches were upstreamed from v5.2.2

### CODE REVIEW

**Comment by Begasus** [comment]
I can understand they fixed openEXR upstream, but is the patch from @threedeyes upstreamed and obsolete now?

**Comment by kenmays** [comment]
LGTM.

**Comment by Begasus** [comment]
Checked with https://invent.kde.org/graphics/krita/-/merge_requests/2099 and the older patchset, both are the same.

**Comment by kenmays** [comment]
Retested. Builds on hrev58455 x64 with libjxl 0.6.1 installed. Migrated to libjxl 0.11.0 for buildbots.

**Pull request merged**
