### PR TITLE
Delete libaacs-0.8.1.patchset

### PR DESCRIPTION
**Pull request by ohnx**
Remove [lint error](https://gist.github.com/ohnx/676338c83bd396261dd294029387cf7c#file-haikuports-errors-txt-L72).

The file is empty anyways.

### CODE REVIEW

**Comment by fbrosson** [comment]
@korli, do you think it would be a good idea to ask @ohnx to include in this PR the removal of [line 7 of libaacs-0.8.1.recipe](https://github.com/haikuports/haikuports/blob/18eaa58543e5bcd0b1d4d5a063677ae4f817cda5/media-libs/libaacs/libaacs-0.8.1.recipe#L7) which has been [commented out](https://github.com/haikuports/haikuports/commit/8c288457a5bace9830653c5df862b35a8a19a17e#diff-490800a316bf320ebcc8062690d11188R28) ?
```
#PATCHES="libaacs-$portVersion.patchset"
```

**Comment by korli** [comment]
@fbrosson while at it, yes.

**Comment by fbrosson** [comment]
@korli: Cool! (I knew you would say so ;-)
@ohnx: I guess you are confortable with git, but if you need any guidance, please don't hesitate to ask.

**Comment by ohnx** [comment]
@fbrosson I deleted the repository I did this from by accident, so I will just create a new PR instead.

**Comment by fbrosson** [comment]
I think you don't need to close this PR.

**Comment by fbrosson** [comment]
It might be possible to re-attach a branch to this PR, if you use the exact same name.
Could you try this:
```
git checkout -b patch-3 master
git push --set-upstream origin patch-3
```

**Comment by fbrosson** [comment]
BTW, were you using git or were you editing your remote clone through GitHub's website?

**Comment by fbrosson** [comment]
I just found a way to create a patch-3 branch (on my remote repo) using only the web-based interface.

**Comment by ohnx** [comment]
I was editing my remote clone through GitHub's website.

It's not linking: https://github.com/ohnx/haikuports/tree/patch-3

**Comment by fbrosson** [comment]
You are right. It's not linking to this PR.
Well, thanks for having tried. Now we know that once a branch is deleted there is nothing we can do to continue with the same PR.

**Wait** would you mind trying this:
```
curl --user ohnx --request POST \
	--data '{"issue":"899", "head":"ohnx:patch-3", "base":"master"}' \
	https://api.github.com/repos/haikuports/haikuports/pulls
```
This is what you would do to attach your patch-3 branch to an open issue.
But I think it will not work here because it is no longuer an issue but a PR.
Well, if you could test this it would be cool ;-)
If it does not work then let's forget this. Thanks and sorry for bothering you with these queries ;-)

**Comment by fbrosson** [comment]
Hmm, I get an error:
```
{
  "message": "The specified issue is already attached to a pull request.",
  "errors": [
    {
      "value": 899,
      "resource": "PullRequest",
      "field": "issue",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
}
```
So don't bother with this.
(You can close this PR.)

**Comment by ohnx** [comment]
Haha sorry about that.

**Comment by fbrosson** [comment]
No problem. BTW, I feel guilty because **_if_** I had not suggested the removal of the commented line **_then_** we would not have had this tiny _"accident"_.
But I guess we should not be sorry. Nobody will blame us for this ;-)

**Pull request closed without merging**
