### PR TITLE
cegui, new recipe

### PR DESCRIPTION
**Pull request by Begasus**
WIP at this time, the uncommented libraries are not found or causing errors, aside from that it build ok :)

### CODE REVIEW

**Comment by extrowerk** [comment]
Here is my addition: http://0x0.st/sdYj.recipe

**Comment by Begasus** [comment]
Will check tomorrow :+1: almost on the same path :)

**Comment by Begasus** [comment]
This one should be ok, checks welcome :)

**Comment by Begasus** [comment]
Disabled the samples (speeds up the build)

**Comment by Begasus** [comment]
Also fixed reference to lib:libSDL2*_2.0

**Pull request merged**
