### PR TITLE
GLEW: bump version, recipe cleanup

### PR DESCRIPTION
**Pull request by miqlas**
@korli: does it looks good to you, or should i make a "glew2" recipe? A lib is missing from the new version.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Does software that uses GLEW work with a recompile (i.e. is it source compatible?) If not, then yes it should be glew2.

**Comment by khallebal** [comment]
@miqlas  you're missing libglewmx from provides, both devel and non devel.

**Comment by korli** [comment]
@khallebal it looks OK to me, version 2.0 doesn't provide libglewmx.

**Comment by khallebal** [comment]
Oops, sorry did'nt know that about the new 2.0 version

**Pull request merged**
