### PR TITLE
kuserfeedback, new kde framework

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Still need to check 32bit, on 64bit it works fine with Kate (checking the general settings there).

**Comment by Begasus** [comment]
Sidenote, it defaults to not sharing any information/feedback, so user still needs to adjust the level of feedback.

**Comment by korli** [comment]
> Sidenote, it defaults to not sharing any information/feedback, so user still needs to adjust the level of feedback.

Must be a KDE default?

**Comment by Begasus** [comment]
> > Sidenote, it defaults to not sharing any information/feedback, so user still needs to adjust the level of feedback.
> 
> Must be a KDE default?

Probably (and good too), checked with KWrite on 64bit, shows the same.

**Pull request merged**
