### PR TITLE
dragengine: bump version

### PR DESCRIPTION
**Pull request by LordOfDragons**

### CODE REVIEW

**Comment by LordOfDragons** [comment]
I can't view the logs in the link you mentioned. Added the changes and created a new pull request but the system is chickening out. No idea what's going on.

**Comment by Begasus** [comment]
My bad, the link is the general one, the (failed) buildlog is here: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/4658/builds/81105.log
As for the PR, there is a conflict that needs to be resolved (did you sync your branch with upstream?): https://github.com/haikuports/haikuports/pull/8860/conflicts

**Comment by LordOfDragons** [comment]
Yep, I did sync it so I don't know why the system chickens out. It's a one-line commit so I don't know what's going on.

**Comment by LordOfDragons** [comment]
Deleted now the pull request and started all over: https://github.com/haikuports/haikuports/pull/8863 . Seems to work better now.

**Comment by Begasus** [comment]
Seems to have failed again :/ https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/9044/builds/80072.log

**Pull request merged**
