### PR TITLE
flatbuffers, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Review by Barrywhyte22 — COMMENTED** [review]
dev-libs/flatbuffers/flatbuffers-1.12.0.recipe → dev-libs/flatbuffers/flatbuffers-24.3.25.recipe

**Comment by Begasus** [comment]
> dev-libs/flatbuffers/flatbuffers-1.12.0.recipe → dev-libs/flatbuffers/flatbuffers-24.3.25.recipe

That was the change, am I missing something?

**Comment by korli** [comment]
> > dev-libs/flatbuffers/flatbuffers-1.12.0.recipe → dev-libs/flatbuffers/flatbuffers-24.3.25.recipe
> 
> That was the change, am I missing something?

This is spam. This user should be blocked on this repo.

**Comment by Begasus** [comment]
> This is spam. This user should be blocked on this repo.

As in report and hide? Or maybe something more high level? :)

**Comment by pulkomandy** [comment]
User is blocked now.

**Pull request merged**
