### PR TITLE
gcc: add GCC 11.1.0 recipe

### PR DESCRIPTION
**Pull request by kenmays**
Official release: https://gcc.gnu.org/gcc-11/changes.html

NOTE:
1. Migrated the legacy Haiku GCC 8.3/8.4 patchset. 
2. Configuration test passed on Haiku R1B2 x86_64.
3. Work in progress.
4. Due to 'madvise' requirement, build/test on a recent Haiku nightly > R1B2.

### CODE REVIEW

**Comment by extrowerk** [comment]
Remove old so we can see what changed.

**Comment by extrowerk** [comment]
Maybe you should not waste your time for one of the most complex building block. But if you insists to do it, you should spend some time with git first, otherwise it will be impossible to see what you did, as you tend to delete and recreate branches, which means all the comments will gets forgotten.

I don't really think it makes any sense to attempt this.

But about the 
```
/sources/gcc-11.1.0/gcc/config/haiku.h:206:9: error: attempt to use poisoned "NO_IMPLICIT_EXTERN_C"
 #define NO_IMPLICIT_EXTERN_C
         ^
```
error:
the GCC guys said we can safely remove that line as NO_IMPLICIT_EXTERN_C became default.

**Comment by extrowerk** [comment]
It would be also a good idea to update mpfr, mpc, gmp and the binutils recipe to the version recommended for GCC11.1.0

**Comment by kenmays** [comment]
Thanks. I knew about 'NO_IMPLICIT_EXTERN_C'. Haiku implemented/improved 'madvise' after Haiku R1B2 so you'll need to review moreso on the nightly builds. GCC 8.4.0 built fine on Haiku R1B2 - why not review GCC 8.4.0 build on the buildbots?

**Comment by kenmays** [comment]
Issue: Haiku hrev55063 - os/BeBuild.h provides '__GNUC__ <=10' on line 52 for B_HAIKU_ABI. Need to review for '__GNUC__  <= 12' change.

**Comment by extrowerk** [comment]
> GCC 8.4.0 built fine on Haiku R1B2 - why not review GCC 8.4.0 build on the buildbots?

Cant build it on nightly -> can't check.

Somebody correct me if i am wrong, but i don1t think we "review" ports on the builders. It is not some kind of CI (at least not yet). One should make sure the port actually builds and works. Mistakes happens, but we still should try our best.

**Comment by extrowerk** [comment]
GCC8.4.0 is too small jump from my POV. A GCC change will require a whole repository-rebuild, as most ports depends on GCCs libs. I don't think it is economical for a minor version bump. If bump, then directly to 11 or whatever.

**Comment by pulkomandy** [comment]
You are correct. Don't submit recipes and pull requests here if you have not tested them. Especially when touching core system components like gcc, test it carefully.
Once it's merged, it automatically gets packaged and installed on everyone machine. If you make us all unable to use gcc because you shipped a broken version, no one can compile things anymore. Sounds like a bad idea.

**Comment by extrowerk** [comment]
```
/boot/system/develop/headers/os/BeBuild.h:55:9: error: #error Unsupported compiler!
   55 | #       error Unsupported compiler!
```
Proposed fix: https://review.haiku-os.org/c/haiku/+/3890

**Comment by kenmays** [comment]
Superseded by #5855.

**Pull request closed without merging**
