### PR TITLE
libretro cores : bump to latest git revisions

### PR DESCRIPTION
**Pull request by kwyxz**
As title says, bumping various libretro cores to the latest revisions that build properly

### CODE REVIEW

**Comment by diversys** [comment]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/4823/builds/17542.log

**Comment by kwyxz** [comment]
Interesting. It should not have pushed a new revision if the build failed. Looking into this, thanks!

**Comment by kwyxz** [comment]
Actually, I don't see a commit for bsnes, so I am not sure what happened :|

**Comment by kwyxz** [comment]
I see it in this commit... https://github.com/kwyxz/haikuports/commit/4b88971530af119b1bf5be5c0e59803ff9cf10ea definitely not normal.

**Comment by diversys** [comment]
Watch this place https://build.haiku-os.org/buildmaster/master/x86_64/

**Comment by kwyxz** [comment]
Fixed in #5300
Now looking at `easyrpg`

**Pull request merged**
