### PR TITLE
Fix WebKit_GTK patchset to fix issue #7462

### PR DESCRIPTION
**Pull request by SamuraiCrow**
There was an undefined macro named LITTLE_ENDIAN in xdgmime.c that is now defined in a patch to its CMakeLists.txt file.

### CODE REVIEW

**Comment by SamuraiCrow** [comment]
Don't commit yet.  Found a bug in this patch.  Converting to draft mode for now.

**Comment by korli** [comment]
your two patches should be squashed together.

**Comment by SamuraiCrow** [comment]
OK, this should actually build and is tested to do so.

**Comment by korli** [comment]
> your two patches should be squashed together.

your two patches should be squashed together.

**Comment by SamuraiCrow** [comment]
@korli
I'll wrestle with git tomorrow.  It's late.

**Comment by korli** [comment]
> @korli I'll wrestle with git tomorrow. It's late.

I amended it

**Comment by SamuraiCrow** [comment]
@korli 
Thank-you!

**Comment by SamuraiCrow** [comment]
Is there anything else needed here? I'm a first-time committer on this project.

**Comment by korli** [comment]
@SamuraiCrow  You should commit your patches in a branch, not in master.

**Pull request merged**
