### PR TITLE
qutebrowser: bump version

### PR DESCRIPTION
**Pull request by kenmays**
Qutebrowser v2.5.2
Released: Jun 22, 2022

### CODE REVIEW

**Comment by Begasus** [comment]
Checked on both arch's? (don't have the time atm to do it myself)

**Comment by kenmays** [comment]
Checked on x64. Builds fine.

**Comment by Begasus** [comment]
Build failed on buildmaster.

**Comment by kenmays** [comment]
asciidoc missing from repos? Was there.

**Pull request merged**
