### PR TITLE
kate+kwrite: bump version to 23.08.4

### PR DESCRIPTION
**Pull request by InfiniteVerma**
Compiled and ran kate on Haiku VM. Version shown was 23.08.4 as expected.

### CODE REVIEW

**Comment by korli** [comment]
I see that arch linux package depends on KUserFeedback, optional it seems.

**Comment by Begasus** [comment]
> I see that arch linux package depends on KUserFeedback, optional it seems.

From their readme: `Framework for collecting feedback from application users via telemetry and targeted surveys.`

Aside from that, version 1.3.0 should be fine to be used/build.

**Comment by Begasus** [comment]
> Compiled and ran kate on Haiku VM. Version shown was 23.04.2 as expected.

Version shows as 23.08.4 (as it should) here with the one I have?

Kate_Version

**Comment by InfiniteVerma** [comment]
> > Compiled and ran kate on Haiku VM. Version shown was 23.04.2 as expected.
> 
> Version shows as 23.08.4 (as it should) here with the one I have?
> 

My original comment was wrong, sorry. The version is as in merge request title post install.

**Comment by Begasus** [comment]
kuserfeedback has been merged in https://github.com/haikuports/haikuports/pull/9905
You could add this for Kate (and KWrite (should be fine to bump version also as the source tar is the same for both)).

**Comment by Begasus** [comment]
Thanks! 👍

**Pull request merged**
