### PR TITLE
boca: bump to 1.0~beta2

### PR DESCRIPTION
**Pull request by enzo1982**

### CODE REVIEW

**Comment by korli** [comment]
SOURCE_URI references v1.1-beta2, although the recipe version says 1.0~beta2, this is confusing.
Is it on purpose?

**Comment by enzo1982** [comment]
I agree that it's a bit confusing, but it's intentional for now.

I will change the naming of BoCA releases away from fre:ac CDK v1.1... to BoCA v1.0... before the stable release. Originally intended to do this already with the beta 2, but was short on time.

**Comment by korli** [comment]
OK!

**Comment by Begasus** [comment]
Anything that needs to be done here, and the other open PR's atm @enzo1982 ? (checked on both 32bit and 64bit?)

**Comment by enzo1982** [comment]
> Anything that needs to be done here, and the other open PR's atm @enzo1982 ? (checked on both 32bit and 64bit?)

I would not do any changes for now if that's alright with @korli. Would be great if someone could merge these PRs.

The versioning change for BoCA will happen with the next beta, probably in February.

**Comment by korli** [comment]
> Anything that needs to be done here, and the other open PR's atm @enzo1982 ? (checked on both 32bit and 64bit?)

OK to merge. Sorry, was a bit overloaded with GCI.

**Comment by enzo1982** [comment]
> Any order specific needed to merge the PR's @enzo1982 ?

#4596 should go before #4599. Otherwise any order should be fine.

**Comment by Begasus** [comment]
First one down, will check the buildbot if that is OK in a bit and then merge the other ones

**Pull request merged**
