### PR TITLE
fixing becasso

### PR DESCRIPTION
**Pull request by Ace002**

### CODE REVIEW

**Comment by korli** [comment]
Shouldn't figlet go in another PR?

**Comment by mmuman** [comment]
Indeed, you'll want to use separate branches...

**Comment by richienyhus** [comment]
@Ace002 
> The master repo is now back at HaikuArchives and the pending PR has been merged. https://github.com/HaikuArchives/Becasso/

**Comment by scottmc** [comment]
Nice to see Becasso back at HaikuArchives, now we can fix issues and get the pull requests merge quicker.  I suspect this one just needs the source url updated now and then retested, and then it can be merged?

**Comment by Ace002** [comment]
how to separate them??

**Comment by pulkomandy** [comment]
You have becasso as a separate commit already. What I suggest is:

    git fetch # Make sure you have latest version of haikuports
    git checkout origin/master # remove all your local changes (temporarily)
    git checkout -b becasso # create a becasso branch
    git cherry-pick d626494d00ab7cd # get ONLY the becasso commit
    git push becasso # Push the new branch to github
    git checkout master # Get all your other changes back

Then you should be able to create a new pull request from that branch, with only the becasso changes. We will see later how to recover your changes to figlet.

**Comment by richienyhus** [comment]
@Ace002 any luck in following pulkomandy's instructions?

**Comment by pulkomandy** [comment]
Well I'm just merging both because the changes look correct anyway.

**Comment by Ace002** [comment]
dunno, still no progress

**Pull request merged**
