### PR TITLE
codeblocks: new recipe

### PR DESCRIPTION
**Pull request by return**
This is an initial work in progress recipe for CodeBlocks and addresses #2797 and I have disabled this recipe by default (Needs some improvements to wxqt first.)

First it soft-crashes after the splash screen on a missing implementation in the wxqt port.

screenshot-23

If you skip and continue running CodeBlocks, the IDE will show up. But closing down the editor will hard crash the app (wxqt related). See: https://gist.github.com/return/e58b55c65300b88d8ee13709ca9857f4 for the report.

screenshot2

Mark this as WIP.

### CODE REVIEW

**Comment by Begasus** [comment]
Would be nice if you could fix the issue for wxqt :+1:

**Comment by waddlesplash** [comment]
The report is strange; I'm not sure how that function gets to abort(): https://github.com/wxWidgets/wxWidgets/blob/0ca45d1a59a51e6798b99eaa0e7fdbbcc33c3992/src/unix/utilsunx.cpp#L369

**Comment by Begasus** [comment]
Maybe could be looked into again now  we also have wxgtk?

**Comment by Begasus** [comment]
No progress so far, merging as disabled, someone who can tackle this can continue work based on this one.

**Pull request merged**
