### PR TITLE
librsvg, bump version, kudos to nielx for the help

### PR DESCRIPTION
**Pull request by Begasus**
Not tested on x86_64, would be nice if someone could check this out there before merging, @mazbrili could you check this out for tuxpaint (having some issues here atm with this version and previous, it worked ok before, so not sure what's going on there now)

### CODE REVIEW

**Comment by kenmays** [comment]
@Begasus - v2.50.3-1, built and packaged successfully on R1B2 x86_64.

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/5710 needs to be merged before this

**Comment by Begasus** [comment]
Adding support for gir/vala/pixbuf resulted in errors, no time for this to check it out so will leave them out here for now
```
Finished release [optimized + debuginfo] target(s) in 170m 49s
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     librsvg-2.la
ar: `u' modifier ignored since `D' is the default (see `U')
  GISCAN   Rsvg-2.0.gir
  CCLD     rsvg-convert
/boot/system/develop/tools/x86/lib/gcc/i586-pc-haiku/8.3.0/include/stddef.h:435: syntax error, unexpected identifier in '  __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));' at '__float128'
 VAPIGEN librsvg-2.0.vapi
  GICOMP   Rsvg-2.0.gir
error: Package `GLib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GdkPixbuf-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
make[2]: *** [/packages/vala_x86-0.47.1-1/.self/data/vala/Makefile.vapigen:61: librsvg-2.0.vapi] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/sources/librsvg-2.50.3'
make[1]: *** [Makefile:1276: all-recursive] Error 1
make[1]: Leaving directory '/sources/librsvg-2.50.3'
make: *** [Makefile:827: all] Error 2
```

**Comment by mazbrili** [comment]
> Not tested on x86_64, would be nice if someone could check this out there before merging, @mazbrili could you check this out for tuxpaint (having some issues here atm with this version and previous, it worked ok before, so not sure what's going on there now)

tuxpaint work on x86_64

**Pull request merged**
