### PR TITLE
Updated musicpc recipe

### PR DESCRIPTION
**Pull request by miqlas**
No functional change

### CODE REVIEW

**Comment by fbrosson** [comment]
While at it, could you please add a **`$secondaryArchSuffix`** to the **`cmd:ranlib`** in line 45? Thanks!

**Comment by miqlas** [comment]
Better to not do things at 3AM.
I have no idea, how can i fix it, so please, help.

**Comment by fbrosson** [comment]
>  I have no idea, how can i fix it, so please, help.

```
cd /path/to/haikuports/media-sound/mpc
git checkout mpc_update
sed --in-place=.backup \
	-e 's/cmd:ranlib$/&\$secondaryArchSuffix/;' \
	-e 's/cmd:libtoolize$/&\$secondaryArchSuffix/;' \
	musicpc-0.26.recipe
diff musicpc-0.26.recipe.backup musicpc-0.26.recipe
rm musicpc-0.26.recipe.backup
git commit --amend musicpc-0.26.recipe
git push -f
```

**Comment by fbrosson** [comment]
Oups, I just understood what happened. You added **`$secondaryArchSuffix`** to musicpc-**0.26**.recipe instead of musicpc-**0.28**.recipe.
Here's what you can do to drop 0.26 and fix 0.28:
```
cd /path/to/haikuports/media-sound/mpc
git checkout mpc_update

git reset musicpc-0.26.recipe
git rm musicpc-0.26.recipe
git commit --amend --no-edit musicpc-0.26.recipe

sed --in-place=.backup -e 's/cmd:ranlib$/&\$secondaryArchSuffix/' musicpc-0.28.recipe
diff musicpc-0.28.recipe.backup musicpc-0.28.recipe
rm musicpc-0.28.recipe.backup
git commit --amend --no-edit musicpc-0.28.recipe

git push -f
```

BTW, maybe it could be a good idea to get rid of the curly brackets where they are not needed:
```
	cmd:gcc${secondaryArchSuffix}
	cmd:ld${secondaryArchSuffix}
	cmd:make
	cmd:pkg_config${secondaryArchSuffix}
```
can be changed to:
```
	cmd:gcc$secondaryArchSuffix
	cmd:ld$secondaryArchSuffix
	cmd:make
	cmd:pkg_config$secondaryArchSuffix
```

**Comment by fbrosson** [comment]
@miqlas: I think you can drop the detailed commit message and use a short one, instead.
What about:
```
cd /path/to/haikuports
git checkout mpc_update
git commit --amend -m "musicpc: bump to 0.28, add a missing secondaryArchSuffix."
git push -f
```

**Pull request merged**
