### PR TITLE
Add myspell/hunspell dictionaries

### PR DESCRIPTION
**Pull request by Begasus**
First draft, not completely sure about the copyright/license, worked ok with latest PR for ghostwriter/hunspell
Ghostwriter3

### CODE REVIEW

**Comment by diversys** [comment]
Can we have one recipe for all of the available language directories?

**Comment by Begasus** [comment]
> Can we have one recipe for all of the available language directories?

Problem there is that probably they are not hosted on the same link? (didn't find one so fast for myspell_nl for instance at the libreoffice site)

**Comment by Begasus** [comment]
Ghostwriter4
Ghostwriter5

**Comment by KapiX** [comment]
How big is the resulting package?
I'd split them up into multiple packages (within one recipe), and make the main one depend on all of them.

**Comment by Begasus** [comment]
> How big is the resulting package?
> I'd split them up into multiple packages (within one recipe), and make the main one depend on all of them.

The resulting package is about 38MiB, if splitting it up I could use some help to get me started on that one :)

**Comment by Begasus** [comment]
Something in the line of _tools packages?

**Comment by Begasus** [comment]
@KapiX split them up now, base package now holds myspell_en, added myspell_de and myspell_nl for now to check if it's ok :)

**Pull request merged**
