### PR TITLE
Krita: Enable libjxl 0.11.0 support

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by Begasus** [comment]
Did you check this on both arch's, first round it failed with older libjxl, this worked fine now for 32bit (build completed) but not for 64bit, maybe 64bit needs the newer one and 32bit the older one?

**Comment by kenmays** [comment]
I disabled it for now. Should use libjxl 0.11 but not important at the moment.

**Comment by Begasus** [comment]
Checked latest changes on both arch's? (beta5 as that is what buildmasters use)

**Comment by kenmays** [comment]
On x64 it works fine for me. The x86 should pass as well.

**Comment by Begasus** [comment]
OK, let's see how far this goes now.

**Pull request merged**
