### PR TITLE
S25RTTR: new recipe

### PR DESCRIPTION
**Pull request by extrowerk**
Broken: https://github.com/haikuports/haikuports/issues/3998

### CODE REVIEW

**Comment by extrowerk** [comment]
Now the required patch merged into Haiku, so just a cleanup required here, but the keyboard of my Haiku machine got broken (i was stupid), so it will take some time yet.

**Comment by korli** [comment]
which Haiku patch? in master oder in beta1 branch?

**Comment by extrowerk** [comment]
I meant this: https://git.haiku-os.org/haiku/commit/?id=3ddf0bbc29dc201ef90f376708fbaf2dc31f2100
But yeah, it is in master, so it will yet take long time till it lands on the builders.

**Comment by Begasus** [comment]
Superseded by: https://github.com/haikuports/haikuports/pull/6988

**Pull request closed without merging**
