### PR TITLE
cloog, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Not tested on x86_64 (yet)

**Comment by Begasus** [comment]
Don't merge before latest PR for isl got merged :) https://github.com/haikuports/haikuports/pull/3741

**Comment by korli** [comment]
we could also remove the package.

**Comment by Begasus** [comment]
> we could also remove the package.

As in, remove isl and cloog? (searching on haikuports I don't see any use of it so I wouldn't have a problem with it)

**Comment by korli** [comment]
gcc can directly use isl, cloog could be removed.

**Comment by Begasus** [comment]
If this is ok with the others I will remove it then, I'll wait for a few days before doing so.

**Pull request merged**
