### PR TITLE
icu57, reanable base package (needed for libreoffice, calligra ...?) …

### PR DESCRIPTION
**Pull request by Begasus**
…on 32bit

### CODE REVIEW

**Comment by Begasus** [comment]
Related to: https://discuss.haiku-os.org/t/install-libreoffice-on-x86/12922

**Comment by waddlesplash** [comment]
LibreOffice should be rebuilt on 32-bit instead.

**Comment by Begasus** [comment]
Already tried that with a revbump on the buildmaster, seems that for some reason it still seems to depend on boot166?

**Comment by waddlesplash** [comment]
Probably because boost166 is still available and is used by default. Its own recipe should be disabled, or rebuilt against a newer ICU.

**Comment by Begasus** [comment]
Tried rebuilding boost166 localy, failed with errors, didn't investigate further at that time.

**Comment by pulkomandy** [comment]
We should also disable the older boost recipes and update everything that still uses them.

But the question remains: is there a way to query the package repo to know what depends on a package? Can pkgman do this or do we need tools in the web interface? It would help a lot for preparing these transitions and making them smoothly.

**Comment by Begasus** [comment]
Tried rebuilding boost166 localy, failed with errors, didn't investigate further at that time.

> Did you try `pkgman search -r "lib:libicuuc>=57"` ?

Doesn't reveil any matches?

**Comment by Begasus** [comment]
Boost166 fails with: error: no matching function for call to 'decay_copy(void (&)(rlimit*) noexcept)' (so far no idea how to solve this)

**Comment by pulkomandy** [comment]
> Did you try pkgman search -r "lib:libicuuc>=57" ?

It doesn't seem to work when specifying a version.

> Boost166 fails with: error: no matching function for call to 'decay_copy(void (&)(rlimit*) noexcept)' (so far no idea how to solve this)

We can't provide long term maintenance for old boost versions. They often don't work with newer compilers. So we should just make sure everything does use the newer versions.

If we can't find out what depends on boost 1.66, maybe we should remove boost 1.66 from the repository and see what the next complaining package is? But really this isn't a great way to solve this.

**Comment by Begasus** [comment]
LO for 32bit is  building atm, should fix this so it can be closed when all things are OK.

**Comment by Begasus** [comment]
Fixed with revbump for LO

**Pull request closed without merging**
