### PR TITLE
Simutrans: bump version to 122.0

### PR DESCRIPTION
**Pull request by kenmays**
Cleanup simutrans folder for Beta3.

### CODE REVIEW

**Comment by korli** [comment]
Could you also update to 122.0 ? https://github.com/aburch/simutrans/commit/ec1af849fd29606eed73d11f87034be7c95247b9

**Comment by kenmays** [comment]
@korli - Updated to simutrans 122.0.

**Comment by korli** [comment]
@kenmays I take you tested on x86 and x86_64?

**Comment by korli** [comment]
@kenmays please explain how the requirement "simutrans_pakset >= 122.0" could be possibly fulfilled?

**Comment by kenmays** [comment]
Not a BUILD req.

**Comment by Begasus** [comment]
Build failed on R1/Beta2 here (32bit): `error: no matching function for call to 'clamp....'`

**Comment by kenmays** [comment]
@Begasus - SImutrans on Haiku is mainly a 64-bit build. We can review after R1B3 release for a x86 build.

**Comment by korli** [comment]
> clamp

@kenmays this shouldn't be a big deal. 
clamp is a template function which only takes three times the same type as argument.
https://github.com/aburch/simutrans/blob/a6eaf80a8702f344ad2f68f805915c793f96193f/macros.h#L33
it's a matter of forcing types to get the template function found.

**Pull request merged**
