### PR TITLE
Kristall: Bump to 3

### PR DESCRIPTION
**Pull request by win8linux**
Ok, second attempt with much less commits.

Forgot to bump the revision for https://github.com/haikuports/haikuports/pull/5566, so this PR will remedy that oversight.

### CODE REVIEW

**Comment by Begasus** [comment]
After a merge it's best to clean (delete) the current branch (in this case branch kristall) both local and remote, and keep your master on par with upstream, for future revbumps just create a new branch then en push for a PR (check with git status that everything is clean before making changes in the new branch) :)

**Comment by Begasus** [comment]
64 bit is OK, 32 bit failed (but is known with the "out of memory" issue), thanks!

**Comment by win8linux** [comment]
Much appreciate the tips for future PRs! As for 32-bit, perhaps cross-compilation from a 64-bit host might be an option?

**Comment by Begasus** [comment]
Don't think much users of 32 bit are busy with that, or even know if it's possible :)

**Pull request merged**
