### PR TITLE
hgrep, fix recipe and pull a more recent version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by korli** [comment]
LGTM

**Comment by korli** [comment]
maybe remove the old recipes for hgrep?

**Comment by Begasus** [comment]
I was thinking of that too, but there is still a zip in it and a hgrep file that can be used? (havent tested that one), but if it's ok I can remove them ...

**Comment by waddlesplash** [comment]
Yes, please remove them.

**Comment by Begasus** [comment]
Also the zip and related parts?

**Comment by scottmc** [comment]
Looks like this is confusing two different hgreps.  The original one on
haikuports, was a script to search Haiku's headers, this new recipe is for
some different hgrep?

Also see lgrep, it was added at the same time as hgrep.  Both have a zip
file which contains a single script file.  I think that was done to fake
out haikuporter.  Not sure that anyone even uses those old hgrep and lgrep
scripts.

-scott

**Comment by Begasus** [comment]
If not, this one could/should be deleted from the haikuports tree?

**Pull request closed without merging**
