### PR TITLE
Recipe for Vifm

### PR DESCRIPTION
**Pull request by robcsi**
Pull request for Vifm recipe, a vi-like, cross-platform and command-line based file manager, using ncurses.

It is a wonderful complement for vi/VIm for users who enjoy such keybindings and who work a lot in the terminal.

### CODE REVIEW

**Comment by robcsi** [comment]
Hi miqlas,

Thanks for reviewing.

I have some questions about this:
1. What exactly is this patchset? I did what you recommended (running the "git commit -a" command in the source directory, but git reported that there's nothing to commit. 
After forking/cloning/rebranching the Haikuports repo, I ran the recipe, the packages were created (both executables and source code), installed the package and it worked on my local machine. After that I commited the recipe, pushed to the master branch, and created the PR.
2. Isn't just adding the recipe enough? Other new-recipe PRs contain only one file as well, in the PR list...
3. Can you please point me to some more detailed steps in the wiki about how to do this? In the wiki I followed exactly these steps, up to the section "How do I create a pull request (PR)?".
https://github.com/haikuports/haikuports/wiki/DevelopmentModel
I couldn't find any info on creating a patchset, though...

Thanks,
robcsi

**Comment by korli** [comment]
@robcsi miqlas thinks the sources for Vifm needs to be modified to actually build on Haiku. The patchset is what Haikuporter applies to the tarball to bring these changes.

**Comment by robcsi** [comment]
@korli I though so, but I thought that Haikuports needed to be patched in some way... like adding the recipe to a recipe list, or something.

Vifm doesn't need to be patched. The code has been adapted by the maintainer to Haiku, and it runs just fine.

**Comment by miqlas** [comment]
Robcsi, plenty (but not all) port have patchsets in the haikuports repo, check them please, and if nobody does i'll guide you at night to create the patchset.

-- Z.

2017.09.26. dátummal, 7:40 időpontban Robert Sarkozi <notifications@github.com> írta:

**Comment by miqlas** [comment]
Diver, have you actually tested it?
Afaik it doesn't compiles without a patchset.

-- Z.

2017.09.26. dátummal, 7:56 időpontban diversys <notifications@github.com> írta:

**Comment by robcsi** [comment]
@miqlas Yes, I see those, too, but I was expecting HaikuPorts to be patched, not the source code of Vifm.
Vifm was adapted by its maintainer, after test being done by myself and him. It was patched in its main repo, deliberately for Haiku. 
So no other adaptation needs to be done here.
Like I said before, there were no changes after I ran the recipe on my local branch.

**Comment by robcsi** [comment]
https://github.com/vifm/vifm/commit/e6a7b06c275eba05f4151f0923f0ac2ec4269c94

**Comment by miqlas** [comment]
@robcsi : oh, i see now. Sorry for the noise then.
Actually defining _BSD_SOURCE could fix the dirent stuff, but nice job nevertheless.

**Comment by diversys** [comment]
Builds fine: http://vmpkg.haiku-os.org/master/x86_64/buildruns/280/builds/1500.log

**Comment by miqlas** [comment]
@diversys : Great! Thanks.

**Comment by robcsi** [comment]
@miqlas no problem. Thanks for helping out on IRC. Hope many will like this little app. It's great.

**Comment by miqlas** [comment]
@robcsi : let the ports coming! ;P

**Pull request merged**
