### PR TITLE
clang: add lld support for Haiku target [WIP]

### PR DESCRIPTION
**Pull request by X547**

### CODE REVIEW

**Comment by waddlesplash** [comment]
This should be upstreamed.

**Comment by X547** [comment]
Added 32 bit support.

**Comment by X547** [comment]
https://github.com/X547/llvm-project/tree/llvm-haiku

**Comment by kenmays** [comment]
I can review if rebased on LLVM 15.0.5 (a stable release). I have a working recipe for it.

**Comment by X547** [comment]
Superseded by https://github.com/haikuports/haikuports/pull/9141.

**Pull request closed without merging**
