### PR TITLE
tuxmath: cleaned libSDL* dependencies

### PR DESCRIPTION
**Pull request by alwayslivid**
Relevant pull request: #4549

### CODE REVIEW

**Comment by Begasus** [comment]
TuxMath and TuxTyper both use t4k_common, if that needs changes it goes first, also maybe I missed it but what is the "additional change"?

**Comment by Begasus** [comment]
While looking at it, maybe see if there are newer versions released atm (not needed for this atm)

**Comment by alwayslivid** [comment]
> TuxMath and TuxTyper both use t4k_common, if that needs changes it goes first, also maybe I missed it but what is the "additional change"?

Oops, that was another recipe, my bad.

**Comment by korli** [comment]
Bump revision after changes

**Pull request merged**
