### PR TITLE
make: fix build after dirent refactor

### PR DESCRIPTION
**Pull request by davidkaroly**

### CODE REVIEW

**Comment by korli** [comment]
this is only a build problem on nightlies, correct?

**Comment by davidkaroly** [comment]
> this is only a build problem on nightlies, correct?

i think so

i'll have a try on beta3

**Comment by davidkaroly** [comment]
yep, make builds successfully on beta3.
the issue is there on nightly.

**Comment by waddlesplash** [comment]
It'll still build fine on beta3 though with this fix. So we probably should merge it.

**Pull request merged**
