### PR TITLE
Git updated to 2.8.0

### PR DESCRIPTION
**Pull request by miqlas**
Just to be up to date.

### CODE REVIEW

**Comment by korli** [comment]
Please split your PR

**Comment by miqlas** [comment]
What do you mean, Jerome? I don't understand you, sorry.

-- Z.

2016.03.29. dátummal, 17:17 időpontban Jérôme Duval <notifications@github.com> írta:

**Comment by korli** [comment]
Well, the initial PR email had changes for fish too. Since they disappeared in between, you can ignore my comment.

**Comment by miqlas** [comment]
Yep, i noticed and fixed that ;)
I'm not so good yet with git and make the same mistakes again and again, but trying hard to do my best!

-- Z.

2016.03.29. dátummal, 22:17 időpontban Jérôme Duval <notifications@github.com> írta:

**Comment by TwoFX** [comment]
git 2.8.0 introduces a new option `core.untrackedCache` which speeds up tracking untracked files e.g. in `git status`. This option only works for certain file systems, but BeFS is one of them (tested with this recipe doing `git update-index --test-untracked-cache`). At least on my virtual machine, `git status` sometimes prints a message like "Enumerating untracked files took x seconds", where x > 15, so I suggest enabling this option by default.

**Comment by miqlas** [comment]
Is it possible to enable core.untrackedCache in build-time?
As i see, it is a runtime configuration option. grepping the configure script and the whole source tree came out without any results about build-time option.
Light me up, if you got more info.

**Comment by TwoFX** [comment]
I see two options: Either running `git config --global core.untrackedCache true` at install time (this didn't work right away when I tested it, it complained that $HOME was unset, but I think it can be done), so that haikuporter captures the created settings file, or shipping a config file with the fixed contents
```
[core]
	untrackedCache = true
```
with the package (this can also be done in INSTALL).

Both have the same result.

**Pull request merged**
