### PR TITLE
afl, remove broken recipe, depends on shm that we dont have

### PR DESCRIPTION
**Pull request by Begasus**
Also checked with the latest 2.52b release, still depends on shm ...

### CODE REVIEW

**Comment by korli** [comment]
Well this is a tool one might need. Any chance to use BeOS shared memory instead?

**Comment by Begasus** [comment]
> Well this is a tool one might need. Any chance to use BeOS shared memory instead?

Any place where that could be found? It would probably mean a rewrite of the shm functions then?

**Comment by korli** [comment]
Well PostgreSQL also depends on shm, replacing with BeOS areas is probably a hack but can work.

**Comment by Begasus** [comment]
This can be closed without merging then until someone steps up to fix the shm issue :)

**Pull request closed without merging**
