### PR TITLE
ffmpeg: respin for libvpx update

### PR DESCRIPTION
**Pull request by kenmays**
Migrate to libvpx 1.13.1

### CODE REVIEW

**Comment by Begasus** [comment]
Any specific reason to revbump here? Afaik it isn't broken atm.

**Comment by kenmays** [comment]
Migrating them to libvpx 1.13.1.

**Comment by Begasus** [comment]
ffmpeg should already pick up libvpx 1.13.1, not?

**Comment by kenmays** [comment]
OK. I can pull it for now.

**Pull request closed without merging**
