### PR TITLE
libreoffice: bumped to 7.3.7.2

### PR DESCRIPTION
**Pull request by kenmays**
- Built and tested on hrev56841 x64.
Closes: https://github.com/haikuports/haikuports/issues/5251
Closes: https://github.com/haikuports/haikuports/issues/5096
Closes: https://github.com/haikuports/haikuports/issues/5991
Closes: https://github.com/haikuports/haikuports/issues/4860
Closes: https://github.com/haikuports/haikuports/issues/3400
Closes: https://github.com/haikuports/haikuports/issues/2996
Closes: https://github.com/haikuports/haikuports/issues/5989
Closes: https://github.com/haikuports/haikuports/issues/4842
Closes: https://github.com/haikuports/haikuports/issues/5252
Closes: https://github.com/haikuports/haikuports/issues/5241

### CODE REVIEW

**Comment by waddlesplash** [comment]
I am pretty skeptical that a minor upgrade fixes a lot of old issues.

**Comment by waddlesplash** [comment]
Also, disabling database import/export definitely does not mean we can close the issues related to it!

**Comment by kenmays** [comment]
The spell check and crash issues on PDF export are resolved.

**Comment by kenmays** [comment]
Removed them.

**Comment by Begasus** [comment]
Could you fix the conflict?

**Comment by Begasus** [comment]
?

**Pull request closed without merging**
