### PR TITLE
Fritzing : new recipe

### PR DESCRIPTION
**Pull request by extrowerk**
Can't find the installed assets, but i have no more ideas.
It works if i install it locally, without haikuporter.

Maybe somebody would have interest to finish/polish it.

4603729d5e984c2ba149058046d77d07

### CODE REVIEW

**Comment by scottmc** [comment]
Where does it put files when you build outside of haikuporter?  Nice work.  I've created a PC Board or two with fritzing, be nice to see this running on Haiku.

**Comment by mmuman** [comment]
Cool, I can remove it from my list :)

**Comment by mmuman** [comment]
To be fair, I couldn't start it in Linux, it couldn't find its files too...

**Comment by extrowerk** [comment]
I Put the assets in the folder of the Binary, it works so outside of Hp.
I think it might be check if it is writeable or not.
But fritzing not really polished yet, crashes frequently and using way too much abstractions level for my Taste.

**Comment by scottmc** [comment]
Perhaps a related issue: https://github.com/fritzing/fritzing-app/issues/3350
Seems like this could be a simple fix...

**Comment by scottmc** [comment]
@threedeyes please review any pending issues on this pull request and close if no actions are needed from this one.

**Comment by extrowerk** [comment]
Lets close this for now.

**Comment by scottmc** [comment]
Fritzing 0.9.4 is out now,  Might be worth looking to see if results are any different with new version

**Pull request closed without merging**
