### PR TITLE
mesa: update to 19.3.4, HGL fixes

### PR DESCRIPTION
**Pull request by X547**
Front and back buffer BBitmap are now allocated in winsys, memory copy count is
reduced.

TODO:
	BGLView::CopyPixelsIn/Out is not yet implemented.
	EGL is enabled, but not working yet.

Fixes:
	#4471
	#4466
	Fix buffer leak.

New features:
	Double buffering.
	Shared contexts (needed for Blender).

### CODE REVIEW

**Comment by X547** [comment]
I keep this version, because mesa 20.0.0 is broken (https://gitlab.freedesktop.org/mesa/mesa/issues/2559).

**Comment by X547** [comment]
This version has bug in Blender rendering that was fixed in 20.0.0.

Blender 2.82, mesa-19.3.4:
Blender 2 82, mesa-19 3 4

Blender 2.82, mesa-20.0.0:
Blender 2 82, mesa-20 0 0

Note face, skirt and legs.

Model is available here: http://kiomodel3.sblo.jp/article/23486819.html.

**Comment by kenmays** [comment]
Mesa 20.0.0 - with today's updated patch, all unit tests: PASS. We can officially decommission Mesa 19.3.x.

**Comment by waddlesplash** [comment]
Any update on CopyPixels, and on getting this upstreamed?

**Comment by X547** [comment]
No update for now. I already investigated how to properly implement CopyPixels when I was on it last time, but not yet implemented it. As I understand CopyPixels is an only issue that prevent upstreaming.

**Comment by X547** [comment]
This version is obsolete, mesa 20 is available: https://github.com/haikuports/haikuports/pull/4740.

**Comment by waddlesplash** [comment]
Can we close this then?

**Comment by X547** [comment]
Yes.

**Pull request closed without merging**
