### PR TITLE
smooth: bump to 0.9.2

### PR DESCRIPTION
**Pull request by enzo1982**

### CODE REVIEW

**Comment by Begasus** [comment]
Download is broken?
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/4071/builds/15162.log

**Comment by korli** [comment]
sourceforge might be flaky if the buildbot uses a bad mirror. wait until tonight maybe.

**Comment by enzo1982** [comment]
> Connecting to iweb.dl.sourceforge.net|192.175.120.182|:443... connected.
> Unable to establish SSL connection.

Looks like wget is rejecting the certificate or some other SSL issue. Works on my Haiku installation, though. Maybe an issue with that specific mirror. I think a random mirror is chosen everytime a request goes to downloads.sourceforge.net.

**Comment by pulkomandy** [comment]
Too old ca_root_certificates package on the builders?

**Pull request merged**
