### PR TITLE
tiny, new recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by augiedoggie** [comment]
The recipe should probably be called `dev-lang/tiny/tiny-v0.x.x`.  The `first` part in the port name is just a git tag that was used instead of `v0.x.x` or something.

**Comment by Begasus** [comment]
> The recipe should probably be called `dev-lang/tiny/tiny-0.x.x`. The `first` part in the port name is just a git tag that was used instead of `v0.x.x` or something.

Done :)

**Comment by pentalive** [comment]
Hey All - Thanks for creating this for Tiny. I hope many have some fun with this.  I looked over the recipe, I don't know much about recipes but it looks excellent to me.  Thanks again!

**Comment by pentalive** [comment]
Does this mean that tiny will show up in HaikuDepot under devel?

**Comment by Begasus** [comment]
> Does this mean that tiny will show up in HaikuDepot under dev-lang?

Yes :)

**Pull request merged**
