### PR TITLE
apache: bump version

### PR DESCRIPTION
**Pull request by kenmays**

### CODE REVIEW

**Comment by extrowerk** [comment]
Builds/packages fine on 64 bit.

**Comment by Begasus** [comment]
On 32bit build seems to be OK with gcc2 and gcc8, aside from that I haven't checked if apache is really functioning, maybe someone could check this out?

**Comment by bbjimmy** [comment]
on hrev54555 x86_gcc2:


[Sat Sep 12 14:26:26.217494 2020] [core:emerg] [pid 41149:tid 21654752] (70023)This function has not been implemented on this platform: AH00023: Couldn't create the mpm-accept mutex 
(70023)This function has not been implemented on this platform: could not create accept mutex
AH00015: Unable to open logs

**Comment by Begasus** [comment]
> (70023)This function has not been implemented on this platform: could not create accept mutex

Thanks for looking into this, a quick search on the net brought me to: https://github.com/haikuports/haikuports/issues/2949
So I'm guessing it has been an issue in the past already?

**Comment by Begasus** [comment]
Checked with current available version after installing it (2.4.41-3), same issue there, so should stop this from merging, comments welcome

**Comment by Begasus** [comment]
Maybe remove the old recipe and mark this as "?" for the arches, at this moment people maybe would like to try it and run into the same issue where it's not working, @extrowerk can you confirm the same issue at hand on 64 bit?

**Comment by Begasus** [comment]
I'm OK with these changes, if no one steps up this can be merged

**Pull request merged**
