### PR TITLE
blobby: new recipe

### PR DESCRIPTION
**Pull request by Crestwave**
There's actually a [GitHub repo](https://github.com/danielknobe/blobbyvolley2) (which I very conveniently found right before making this pull request...) with recent commits, but no release; not sure if I should make it a `~git` package.

### CODE REVIEW

**Comment by Begasus** [comment]
As they seem to have moved to github maybe try to start from there and rename the recipe to "blobby2-1.1~git.recipe"?
It seems to be active and maybe you could upstream some of the patches?

**Comment by Crestwave** [comment]
Yeah, I was just a bit hesitant to switch to git as I literally found the repo right before clicking open a pull request and my patches don't apply there. :P

**Comment by Begasus** [comment]
> Yeah, I was just a bit hesitant to switch to git as I literally found the repo right before clicking open a pull request and my patches don't apply there. :P

Maybe not all (some may be fixed by now), but I think some Haiku specific changes could be upstreamed? ;)

**Comment by Begasus** [comment]
PS, thanks for your contributions! I think some could learn some things from the patches you are making here! :+1:

**Comment by Crestwave** [comment]
> > Yeah, I was just a bit hesitant to switch to git as I literally found the repo right before clicking open a pull request and my patches don't apply there. :P
> 
> Maybe not all (some may be fixed by now), but I think some Haiku specific changes could be upstreamed? ;)

Yeah, don't worry, I always upstream patches in these situations. :)

> PS, thanks for your contributions! I think some could learn some things from the patches you are making here! 👍

Np, I also learned some things making these contributions! `FindDirectory.h` is more convenient than I thought.

**Comment by Crestwave** [comment]
Decided to go with the GitHub name (blobbyvolley2) and opened a new PR: https://github.com/haikuports/haikuports/pull/4769. I'm going to bed soon so I haven't tested it too thoroughly, but it seems to work fine. Only thing I noticed is that there's a translation error message but I didn't see any effects of it and it *seems* like the problem is from upstream.

**Pull request closed without merging**
