### PR TITLE
BrainWash: new recipe

### PR DESCRIPTION
**Pull request by dacianf**

### CODE REVIEW

**Comment by dacianf** [comment]
I will build fine after this https://github.com/HaikuArchives/BrainWash/pull/2 will be merged.

**Comment by scottmc** [comment]
I have merged your pullrequest and then fixed a few issues.  It builds cleanly now, but crashes when you run it.  So update the recipe to use the latest commit, but mark it as broken for now.

**Comment by dacianf** [comment]
@scottmc how do i mark it broken?

**Comment by mmuman** [comment]
With ! in the ARCHITECTURES.

**Comment by dacianf** [comment]
@scottmc now it builds successfully, should i still mark it broken?

**Comment by scottmc** [comment]
Yes, still mark as broken. Although it builds fine, it will crash to system if you run it.
There is an open Trac ticket on Haiku for BrainWash crashing Haiku.

**Comment by dacianf** [comment]
@scottmc I've mark it broken now. :)

**Comment by richienyhus** [comment]
@scottmc any further reviews?

**Comment by pulkomandy** [comment]
You need to set a summary and description for the package.

**Comment by dacianf** [comment]
@pulkomandy where can i find description of this app?

**Comment by pulkomandy** [comment]
I found this in an old README for it:

What is this anyways?
=================
BrainWash is a ScreenSaver module, which - with the aid of subtle
color cycling - tries to intensify the effects of hallucinogene narcotics.

Why?
=====
Eh, ... #!@?

Whirlpool?
=========
No, the authors can't be held responsible for any  brain, soft or hardware
damage done to either you, your computer or your little child (and/or little
sister) accidentally passing by the flashing screen.
This software is provided "as is" with no warranties of any kind. Use it at your
own risk.
You are allowed to reuse/recycle any part of the included sources.

Known side effects (things that bug you):
================================
- weird muscle jerks
- minor speech defects
- serious loss in productivity (some [beta] test individuals spent several days
   motionless staring at their monitor... some of them just disappeared)

Known bugs:
==========
none (anymore ;-)

**Comment by dacianf** [comment]
@pulkomandy btw, i didn't find copyright and license...

**Comment by dacianf** [comment]
Thank you @scottmc !

**Pull request merged**
