### PR TITLE
New Gutenprint 5.2.14 recipe and patchset

### PR DESCRIPTION
**Pull request by Vidrep**
Tested working on x86 and x86_64. 
x86_gcc2 fails with errors.

### CODE REVIEW

**Comment by Vidrep** [comment]
Why so many old things in this pull request?

**Comment by fbrosson** [comment]
That's because you attached this PR to your [master branch](https://github.com/Vidrep/haikuports) (instead of a [feature-branches](https://github.com/haikuports/haikuports/wiki/DevelopmentModel#what-are-feature-branches)) and that your master branch is not currently in sync with the project's master:
`This branch is 11 commits ahead of haikuports:master.`

BTW, when I compare your recipe for `5.2.14` to that of `5.2.13` which we already have, I see, among a few other changes, this:
```diff
--- gutenprint-5.2.13.recipe
+++ gutenprint-5.2.14.recipe
 
-ARCHITECTURES="x86_gcc2 x86 x86_64"
-SECONDARY_ARCHITECTURES="?x86_gcc2 x86"
+ARCHITECTURES="!x86_gcc2 x86 x86_64"
+SECONDARY_ARCHITECTURES="!x86_gcc2 x86"
```
Did you mark `x86_gcc2` as broken on x86_gcc2 for `5.2.14` because `5.2.13` was already broken?
Or is `5.2.14` the only one not building?
BTW, if their "build status" on x86_gcc2 is the same for these 2 releases, it would be nice to also drop `5.2.13` in this PR, so that the commit will look like a version bump.

**Comment by fbrosson** [comment]
I forgot to mention that the reason why your master is not in sync with the projects master because you updated your local master with a Merge commit: https://github.com/Vidrep/haikuports/commit/9498ad858075c12f9e912db98cff16f4c08b12d6 instead of using:
```bash
git checkout master
git pull upstream master
git push # origin master
```
This assumes your local repo has these remote repos attached:
```
git remote -v
origin	https://github.com/Vidrep/haikuports.git (fetch)
origin	https://github.com/Vidrep/haikuports.git (push)
upstream	https://github.com/haikuports/haikuports.git (fetch)
upstream	https://github.com/haikuports/haikuports.git (push)
```
You can probably fix this with:
```
git branch -M master guttenprint
git checkout master
EDITOR=vi git rebase -i HEAD~3
3xrdj3xrdj3xrdZZ
git pull upstream master
git push -f
```
Remark: What `3xrdj3xrdj3xrdZZ` does in `vim` is replace the "pick" by a "d" (i.e. "drop") for the first three lines of your _rebase action_.

There is at least one easier way to sync your remote master: delete your remote repo and recreate it.
There might as well be a better method, but the only one I know which does not require you to delete your remote repo is to run the commands I

(I can try to guide you if you wish.)

**Comment by Vidrep** [comment]
I seldom do Git pull requests. That’s probably a good thing. I’ll just delete the haikuports branch and create a fresh fork.

**Comment by Vidrep** [comment]
HaikuPorts repo deleted and recreated from current master. Added Gutenprint recipe and patchset, and pushed to my master on GitHub. Can we delete the last pull request (with all the stuff) and start over?

**Pull request closed without merging**
