### PR TITLE
sdl2_image, recipe update

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by korli** [comment]
Please explain.

**Comment by Begasus** [comment]
the checksum was wrong and it needs libgl as a requirement to build

**Comment by Begasus** [comment]
hmm nope (ligbl is missing on sdl2_mixer) the versions for aclocal and automake created an error with configure here ...

**Comment by Begasus** [comment]
simular thing for sdl2_ttf: build-prerequires "cmd:aclocal_1.13" of package "sdl2_ttf_x86-2.0.14" could not be resolved

**Comment by korli** [comment]
You should install automake113.

**Comment by Begasus** [comment]
I haven't installed it ;) 
automake --version
automake (GNU automake) 1.15
hence it doesn't meet the requirements in the current recipe ...

**Comment by Begasus** [comment]
Or does it change some stuff in trying to build it (with a previous version of automake)?

**Comment by waddlesplash** [comment]
SHA256 sum change is OK (verified here). Other changes aren't. Merging just that manually.

**Pull request closed without merging**
