### PR TITLE
Updated zsh recipe to use the B_USER_SETTINGS_DIRECTORY

### PR DESCRIPTION
**Pull request by miqlas**
Arch changed to x86.

### CODE REVIEW

**Comment by mmuman** [comment]
hmm this doesn't look very multiuser-safe…

**Comment by miqlas** [comment]
mmu, how can we make it better?

**Comment by mmuman** [comment]
it should be enough for now, but the code should be fixed instead.

**Comment by miqlas** [comment]
mmuman, i thought about your comment, but i just can't see the point. Can you explain me what do you meant?
Haiku have no multiuser support, and if it will be implemented in the future, then we need to save the user settings into the "user settings" folder, what i just did here.

Did I musunderstood something here?

Thank You!

**Comment by mmuman** [comment]
Except you are forcing the full path at configure time, so all users will have "/boot/home/config/..." as settings path, which will obviously be wrong then except for once of them.

**Comment by mmuman** [comment]
printf is in glibc, which we provide through libroot, which is implicitly linked to by default.

**Comment by miqlas** [comment]
Can we pass a path like: B_VERY_SPECIAL_USER_SETTINGS_DIRECTORY, what expands like :
"/boot/home/$actual_user/config/settings" ? I don't think that Haiku have infrastructure for that.

Sure, it isn't very future-proof, but we don't need to start the multi-user implementation with zsh.
Let me know if i can do something here to make the situation better.

Thanks for printf, i'll look into that.

**Comment by pulkomandy** [comment]
The find_directory API is designed for that, but it needs to be called at runtime (inside the code), not at compile time (in the configure script).

**Pull request merged**
