### PR TITLE
unarr: fix src_uri, bump rev

### PR DESCRIPTION
**Pull request by miqlas**

### CODE REVIEW

**Comment by diversys** [comment]
No need to change revision

**Comment by miqlas** [comment]
@diversys : i thought if i change a recipa, and don't bump version, then i have to bump revision, to let the buildbots know it is changed. Is it wrong?

**Comment by diversys** [comment]
Lets's check with @waddlesplash

**Comment by KapiX** [comment]
@miqlas You have to bump revision only if the RESULTING package has changed. If the SHA sum of the archive stays the same and none of the package metadata has changed, then there is no need for that.

**Pull request merged**
