### PR TITLE
featherpad: bump version

### PR DESCRIPTION
**Pull request by FuRuYa7**
featherpad-1.1.0

### CODE REVIEW

**Comment by khallebal** [comment]
@FuRuYa7 can you please add this line to the featherpad.rdef file to fix the "open with..." problem?

```diff
+resource("QT:QPA_FLAGS") "Q_REF_TO_ARGV|Q_REF_TO_FORK";
```
Thanks.

**Comment by Begasus** [comment]
Could you also fix line 77, cmake is not secondaryArchSuffix:
```diff
-	cmd:cmake$secondaryArchSuffix
+	cmd:cmake
```

**Comment by FuRuYa7** [comment]
#### Implemented an advised fix:

##### [featherpad.rdef.in]
 
```
 resource app_flags B_MULTIPLE_LAUNCH;
 
+resource ("QT:QPA_FLAGS") "Q_REF_TO_ARGV | Q_REF_TO_FORK";
+
```

##### [featherpad-1.1.0.recipe]

```
-       cmd:cmake$secondaryArchSuffix
+       cmd:cmake
```

Right-click on the text file -> Confirmed that the file can be opened.

Thanks.

**Comment by khallebal** [comment]
Thanks.

**Pull request merged**
