### PR TITLE
sdl_perl: add secondaryArch support (broken) and tests, cleanup

### PR DESCRIPTION
**Pull request by jmairboeck**
This includes the same kind of changes as in #9403 for sdl_perl and its dependencies, including tests. For the tests, a few new recipes are added.

#9403 is required before if this is merged (archive_extract is a dependency).

sdl_perl itself is marked as untested on x86, it doesn't work yet (and therefore, also frozen-bubble).

In alien_sdl, I replaced the patch function with a proper patchset. It probably requires some more patching anyway to get secondaryArch sdl_perl working.

I made separate commits for each package, so I can cherry-pick them apart in separate PRs if needed.

### CODE REVIEW

**Comment by korli** [comment]
IMO bringing sdl_perl secondaryArch support isn't worth it. There is only one old game using it, it would be OK not offering it on x86.

**Comment by jmairboeck** [comment]
sdl_perl doesn't work with gcc2 because of SDL_pango. It is likely that the problem is a more general one and concerns other things where perl XS code tries to link with other secondaryArch libraries.

If we are going to drop gcc2 perl, the secondaryArch perl will be the only one on x86, so that is even more reason to get this working.

(This PR, as it is now, is for the "two perl installations side by side" case, but could be adopted for the "only secondaryArch perl" case instead if we decide going that way.)

**Comment by jmairboeck** [comment]
I cleaned up this branch and pushed the unproblematic recipes to master.

sdl_perl still doesn't work on secondaryArch though ...

**Comment by jmairboeck** [comment]
With the latest changes, Frozen Bubble now works also on x86! (which I also added directly to this PR). I didn't test it yet on x86_64, but I want to do that now. If it works there also still, this can finally be merged.

I suppose that enabling threading in perl did the trick, as the XS handshake works completely differently in this case.

**Comment by Begasus** [comment]
Atm build error on 64bit:

```
waiting for build package sdl_perl-2.548-2 to be activated
Building ...
Can't locate Class/Inspector.pm in @INC (you may need to install the Class::Inspector module) (@INC contains: inc /packages/perl-5.32.1-3/.self/non-packaged/lib/perl5/site_perl/5.32/x86_64-haiku /packages/perl-5.32.1-3/.self/non-packaged/lib/perl5/site_perl/5.32 /packages/perl-5.32.1-3/.self/lib/perl5/vendor_perl/5.32/x86_64-haiku /packages/perl-5.32.1-3/.self/lib/perl5/vendor_perl/5.32 /packages/perl-5.32.1-3/.self/lib/perl5/5.32.1/x86_64-haiku /packages/perl-5.32.1-3/.self/lib/perl5/5.32.1) at /packages/perl-5.32.1-3/.self/lib/perl5/vendor_perl/5.32/File/ShareDir.pm line 131.
BEGIN failed--compilation aborted at /packages/perl-5.32.1-3/.self/lib/perl5/vendor_perl/5.32/File/ShareDir.pm line 131.
Compilation failed in require at /packages/perl-5.32.1-3/.self/lib/perl5/vendor_perl/5.32/Alien/SDL.pm line 5.
BEGIN failed--compilation aborted at /packages/perl-5.32.1-3/.self/lib/perl5/vendor_perl/5.32/Alien/SDL.pm line 5.
Compilation failed in require at Build.PL line 12.
BEGIN failed--compilation aborted at Build.PL line 12.
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 3.
cleaning 'chroot/boot' folder
keeping chroot folder /Opslag/haikuports/dev-perl/sdl_perl/work-2.548 intact for inspection
Error: Build has failed - stopping.
```

**Comment by jmairboeck** [comment]
It seems you still have some old packages referencing perl 5.32.1 here? Did you update your packages and clean the build before?

**Comment by Begasus** [comment]
> It seems you still have some old packages referencing perl 5.32.1 here? Did you update your packages and clean the build before?

Ran pkgman update, so those got updated (all?)

> Edit: or maybe you have a `sitecustomize.pl` script in `non-packaged/lib/perl5/site_perl` still pointing to perl 5.32?

Yep, there is still the file, anything special needed?

**Comment by jmairboeck** [comment]
> > Edit: or maybe you have a `sitecustomize.pl` script in `non-packaged/lib/perl5/site_perl` still pointing to perl 5.32?
> 
> Yep, there is still the file, anything special needed?

Just delete it, it shouldn't be needed, and as you can see, it can be problematic with perl updates.

**Comment by Begasus** [comment]
My bad, good to go on 64bit :)

**Pull request merged**
