### PR TITLE
W6, fix gcc2 build

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by korli** [comment]
Yeah, here is the one Begasus refered to: https://github.com/HaikuArchives/W6/commit/bc2f91183e159804ef8ce3773bf562a132e1ebb7

**Comment by Begasus** [comment]
Also created an issue at Haiku Archives at https://github.com/HaikuArchives/W6/issues/2

**Comment by Begasus** [comment]
@waddlesplash reverting the patch on HaikuArchives would brake the build for x86_64 again, a proper fix should be done there to remove this patch :) (out of my knowledge)

**Comment by waddlesplash** [comment]
Fixed in https://github.com/HaikuArchives/W6/commit/b1940f137e20efee91c0ae060509b7b8507a9159.

**Comment by Begasus** [comment]
@waddlesplash bumped the recipe with your new changes to the source, please check if things are ok for x86_64 :) PS, thanks! :+1:

**Pull request merged**
