### PR TITLE
paladin: bumped revision

### PR DESCRIPTION
**Pull request by kenmays**
Retested build on hrev56889 x64.
For issues and enhancement tracking: https://github.com/adamfowleruk/Paladin/issues

### CODE REVIEW

**Comment by pulkomandy** [comment]
Probably from the Paladin on HaikuArchives. I have merged some things in a develop branch there.

With Adam not replying, I don't know who can be responsible for making a new release of Paladin.

**Comment by kenmays** [comment]
@begasus - This is not a new release - just patches to current Paladin 2.8 development. I forgot to switch the uploaded recipe to HaikuArchives - containing recent patches from new contributors on top of Adam's previous development work (now merged to "HaikuArchives/Paladin/develop"  by Pulkomandy).

**Comment by Begasus** [comment]
> Probably from the Paladin on HaikuArchives. I have merged some things in a develop branch there.

@pulkomandy any reason why they are not merged into master branch?

**Comment by pulkomandy** [comment]
I don't know how Adam planned to handle the branches and I don't want to get more involved than this into Paladin maintenance. If someone wants to take care of it they can organize it however they want.

**Comment by Begasus** [comment]
If no one objects this could be merged, imo.

**Pull request merged**
