### PR TITLE
devilutionx: Bump to version 0.4.0

### PR DESCRIPTION
**Pull request by stenstorp**
Built and ran fine on x86_64 nightly VM.

### CODE REVIEW

**Comment by extrowerk** [comment]
Does it works, can we merge?

**Comment by stenstorp** [comment]
Worked fine on my machine, should be safe to merge.

**Comment by extrowerk** [comment]
I am ok with the changes, but this is still not a bump but a downgrade as the current recipe is younger. Maybe we should just wait for the next release....

**Comment by stenstorp** [comment]
This is an update from a git revision (0.3.1 with a few added commits) from the May 10th to 0.4.0, a release version released on May 20th. I'm fine waiting for a new release but what about it is "younger" than the current recipe?

**Comment by extrowerk** [comment]
You have right, my bad.

**Pull request merged**
