### PR TITLE
php8: revbump

### PR DESCRIPTION
**Pull request by TheZeldakatze**
PHP somehow caused unresolved symbols for me on x86, rebuilding it seemed to fix that. I've noticed that there are quite a few paackages where such things seem to happen. I'll have a look at those, could it be that they failed compiling for some reason and still have some old depenencies?

### CODE REVIEW

**Comment by augiedoggie** [comment]
The recipe should probably have `lib:libstdc++$secondaryArchSuffix` added to the `REQUIRES`.

**Comment by TheZeldakatze** [comment]
It seems to be a problem with libstdc++

php crashed with
```runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.32: Could not resolve symbol '___tls_get_addr'
resolve symbol "___tls_get_addr" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.32: Troubles relocating: Symbol not found
```

AndroidFileTransfer and pingus worked after recompiling, SuperTux and LibreOffice crash with similar messages, however building them fails for me.

I've attached the debugger logs for the crashing SuperTux, LibreOffice and AndroidFileTransfer versionsping
[LibreOffice-1138-debug-10-04-2024-09-24-38.report.txt](https://github.com/haikuports/haikuports/files/14931101/LibreOffice-1138-debug-10-04-2024-09-24-38.report.txt)
[SuperTux-864-debug-10-04-2024-09-20-59.report.txt](https://github.com/haikuports/haikuports/files/14931104/SuperTux-864-debug-10-04-2024-09-20-59.report.txt)
[Pingus-2308-debug-10-04-2024-10-30-48.report.txt](https://github.com/haikuports/haikuports/files/14931108/Pingus-2308-debug-10-04-2024-10-30-48.report.txt)
[AndroidFileTransfer-1038-debug-22-02-2024-23-04-42.report.txt](https://github.com/haikuports/haikuports/files/14931112/AndroidFileTransfer-1038-debug-22-02-2024-23-04-42.report.txt) (Android File Transfer has been rebuilt already, so this is an old report)

Should I open a issue about libstdc++ not being explicitly required?

**Comment by pulkomandy** [comment]
This usually happens when mixing gcc2 and gcc13 compiled code. Make sure you are always using the same compiler for all the things you try to link together.

**Review by augiedoggie — APPROVED** [review]

**Comment by Begasus** [comment]
kuserfeedback(6) failed to build on 32bit buildmaster earlier on this, checking on 32bit with `php -m` showed the above unresolved symbol.

**Comment by Begasus** [comment]
Seems the unresolved symbol came from building findutils with "cmd:ld" on 32bit, this is fixed now.

**Pull request merged**
