### PR TITLE
qemu: update to 6.2.0, enable GTK frontend

### PR DESCRIPTION
**Pull request by davidkaroly**
successful build, no policy errors in haikuporter strict mode
smoke test looks OK

### CODE REVIEW

**Comment by khallebal** [comment]
@davidkaroly The 7.1.0 is already out, tested it on haiku it's working.

**Comment by davidkaroly** [comment]
> @davidkaroly The 7.1.0 is already out, tested it on haiku it's working.

eventually we should go for 7.2.0 but that will need some more testing because of devendored libraries

**Comment by khallebal** [comment]
> because of devendored libraries?

What is that? i'm unfamiliar with this term?
To be honest i only built it with the terminal not haikuporter, the only thing that didn't work was the keyboard shortcuts which is a wayland issue.

**Comment by pulkomandy** [comment]
"vendored" libraries are when a project copies and pastes sourcecode from other libraries into their own repository, either to maintain their own patched versions, or to make sure their code is built against that one very specific version.

This is a hroblem for Haiku packaging because we often need our own patches to such libraries, so whenever possible we do the opposite known as "devendoring": reconfiguring the project to use our packaged libraries instead of their version. But sometimes the "vendored" version has patches or is newer

**Comment by khallebal** [comment]
Aah ok! vendored/devendored, i didn't make the connection, thanks for the clarification.

**Comment by Begasus** [comment]
@davidkaroly build in both 64bit and 32bit OK? (didn't check a build myself)

**Comment by davidkaroly** [comment]
Haven't tried it on 32bit yet. Probably I'll do some testing on my 32bit Haiku VM over the weekend.

**Comment by Begasus** [comment]
> Haven't tried it on 32bit yet. Probably I'll do some testing on my 32bit Haiku VM over the weekend.

If you can could you also check it builds with: https://github.com/haikuports/haikuports/pull/7674

Tried qemu-3.1.1.1_x86 on 32bit and build has been successful, only change there was "cmd:qemu_system_riscv32"
But I never really used qemu (for years) so it would be nice if it is OK with the changes for dtc (current version in haikuports fails).

**Comment by davidkaroly** [comment]
Update: it builds successfully for x86 secondary architecture, even though there are a few policy violations. (no matching self provides for qemu_x86_blablabla)

**Comment by Begasus** [comment]
> Update: it builds successfully for x86 secondary architecture, even though there are a few policy violations. (no matching self provides for qemu_x86_blablabla)
> 
Could you fix or copy the policy warnings (here)?

> Package names look a bit funny e.g. qemu_x86_arm but the best is qemu_x86_x86. Is there a way to remove the secondary arch suffix? Unless we'd like to build qemu with gcc2 but I'm not sure if that's a valid goal.

No valid goal for gcc2 (there is no GTK backend there.

**Pull request merged**
