### PR TITLE
Update libmodbus: bump version

### PR DESCRIPTION
**Pull request by mazbrili**
i'm just realized that there is another newer version of libmodbus..

### CODE REVIEW

**Comment by korli** [comment]
build failed x86_gcc2 : https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/698/builds/1173.log

**Comment by mazbrili** [comment]
> build failed x86_gcc2 : https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/698/builds/1173.log

oh my bad..  i'll try to see on x86 vm

**Comment by mazbrili** [comment]
> build failed x86_gcc2 : https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/698/builds/1173.log

.. how if we restore replaced recipe and set only for x86 and this recipe for x86_64 only? is that good idea?

**Comment by korli** [comment]
you can well disable x86_gcc2, x86 is enough.

**Pull request merged**
