### PR TITLE
wayland, new recipes

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by X547** [comment]
@threedeyes

**Comment by Begasus** [comment]
So far I've been only able to build gtk3_wayland in Terminal on 64bit, with haikuporter and on 32bit I keep hitting:
```
[31/919] Generating gtk/gtkresources_c with a custom command
FAILED: gtk/gtkresources.c 
/bin/glib-compile-resources gtk/gtk.gresources.xml --sourcedir /sources/gtk-f8eb0ae9b8e6b1f7625a447b07d52602c125939f/build/gtk --sourcedir /sources/gtk-f8eb0ae9b8e6b1f7625a447b07d52602c125939f/gtk --sourcedir ../gtk --c-name _gtk --internal --generate --target gtk/gtkresources.c --manual-register --dependency-file gtk/gtkresources.c.d
failed to load "/sources/gtk-f8eb0ae9b8e6b1f7625a447b07d52602c125939f/gtk/theme/Adwaita/assets/bullet-symbolic.symbolic.png": Couldn?t recognize the image file format for file ?/sources/gtk-f8eb0ae9b8e6b1f7625a447b07d52602c125939f/gtk/theme/Adwaita/assets/bullet-symbolic.symbolic.png?
gtk/gtk.gresources.xml: Child process exited with code 1.
```

**Comment by khallebal** [comment]
It could be because we build our glib2 without libpng support, i haven't had time to actually test this theory, if iget some time in the coming days i'll give it a shot, this is the most common reason i found on the net of people who had this issue.

**Comment by Begasus** [comment]
Superseded now.

**Pull request closed without merging**
