### PR TITLE
blender: respin

### PR DESCRIPTION
**Pull request by kenmays**
Ref  #5500
Ref #5504
Builds on x86.

### CODE REVIEW

**Comment by extrowerk** [comment]
About the switch to python 3.7: did you tested it? There was compatibility problems afair with newer python versions with 2.79.
Please try to answer as simple as possible.

**Comment by extrowerk** [comment]
Ref: https://github.com/haikuports/haikuports/pull/4465/files

**Comment by kenmays** [comment]
@extrowerk - Didn't run testsuite. Using internal python. Tested only compilation on Python 3.7 - since R1B2 is now installs for python3 versus Python 3.6. I built blender on x86 & x86_64. Crashes on exit on both platforms. Also, some GUI display issues now seen on both platform builds.

**Comment by kenmays** [comment]
Cancel this PR. X512 is moving towards Blender 2.82+

**Comment by X547** [comment]
Blender 2.79 don't work with python 3+. See https://github.com/haikuports/haikuports/issues/4459.

**Pull request closed without merging**
