### PR TITLE
QMPlay2: bump version

### PR DESCRIPTION
**Pull request by Lan72**

### CODE REVIEW

**Comment by extrowerk** [comment]
Fails for me at
```
[  6%] Building CXX object src/qmplay2/CMakeFiles/libqmplay2.dir/Settings.cpp.o
/sources/QMPlay2-19.09.03/src/qmplay2/Functions.cpp: In function 'QWindow* getNativeWindow(const QWidget*)':
/sources/QMPlay2-19.09.03/src/qmplay2/Functions.cpp:66:26: error: 'class QWidge' has no member named 'windowHandle'; did you mean 'windowTitle'?
             return winW->windowHandle();
                          ^~~~~~~~~~~~
                          windowTitle
src/qmplay2/CMakeFiles/libqmplay2.dir/build.make:95: recipe for target 'src/qmplay2/CMakeFiles/libqmplay2.dir/Functions.cpp.o' failed
```

**Comment by Lan72** [comment]
I’ve got it well, that's why I posted a new recipe.

**Comment by Lan72** [comment]
Yes, I have a 32-bit system.

**Comment by extrowerk** [comment]
I tested it o 64 bit, could you check it too on 64 bit?

**Comment by Lan72** [comment]
Unfortunately not. I only have a 32 bit system.

**Comment by Lan72** [comment]
**extrowerk**
I still did [not understand](https://github.com/haikuports/haikuports/commit/189370c45ae6d9f7b23d42eeb2d6ecbab75ba22f) why you blocked my pull request and did not give it a go.

**Comment by extrowerk** [comment]
@Lan72 : sorry, but there must be a misunderstanding somewhere. AFAIK i did not blocked your PR, i just had soem time, so i tested as much PR as i was able, and stated in comments if the build completed or not for me. I did not changed anything, according the github log i did not even added a flag or tag, so could you please explain what do you mean under "blocking" your PR?

**Comment by diversys** [comment]
Suppressed by 189370c45ae6d9f7b23d42eeb2d6ecbab75ba22f.

**Pull request closed without merging**
