### PR TITLE
Updated icon

### PR DESCRIPTION
**Pull request by roired**
I think this version matches better the Haiku HIG. Please do check it out if it's worth the change.

### CODE REVIEW

**Comment by roired** [comment]
Good day,

I'm having issues with updating the file to GitHub and pasting the PNG here. Not so sure on what is going wrong.

Nonetheless, here are the links to the PNG and to the HVIF (Icon-O-Matic). The RDEF file is also there:
https://gitlab.com/rrhaiku/haikuicons/-/blob/master/Libreoffice/LibreOffice-new.png
https://gitlab.com/rrhaiku/haikuicons/-/blob/master/Libreoffice/Libreoffice.hvif

I tried both in WebPositive and OtterBrowser. None allowed me to upload any file to the fork, nor paste the image here... Let me know if you could see the files.

Regards,
RR

**Comment by roired** [comment]
I still don't manage myself that well with GitHub or GitLab yet.. Apologies for the issues I may cause. I'll get better at it. I promise.
Regards,
RR

**Comment by humdingerb** [comment]
I never used the webinterface to upload/changestuff at github. Have you tried using 'git' from Terminal?
Have checked out the haikuports repo, so it's sitting on your harddisk?

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Good day @humdingerb,

Hehe... That should be true, it should be in the hard disk, but it's not. I recently rearranged hard disk space and clean installed Haiku again, giving it more space. I will re-clone and try from terminal.

Actually, I'm using the terminal on Gitlab, but those are my own stuff, so no problem if I mess something. I will try this afternoon, and fingers crossed, not to mess a thing :)

Regards,
RR

**Comment by roired** [comment]
Well, done. Hope I didn't make a mess.. though there seems to be a conflict in here. 
Regards,
RR

**Comment by humdingerb** [comment]
I suppose the conflict comes from your re-pulling the sources? I dunno... In any case, it gets less messy when using feature branches instead of working in 'master' all the time.

The .rdef isn't needed, the .png neither. I think Diver just wanted to be able to see it, i.e. upload somewhere, not include it in the PR.
There already is an .iom file. You should replace that one with yours instead of uploading a .hvif.

**Pull request closed without merging**
