### PR TITLE
lilypond: bump version

### PR DESCRIPTION
**Pull request by jmairboeck**

### CODE REVIEW

**Comment by Begasus** [comment]
Wont this fail on buildmaster with the current stat on texinfo/perl?

**Comment by jmairboeck** [comment]
It will probably. Maybe we should wait with that until beta 5 then.

**Comment by Begasus** [comment]
I'll leave it up to you, you can set it as draft to make sure it isn't merged, or merge and revbump if needed after the new beta release. :)

**Comment by jmairboeck** [comment]
The build finished successfully on nightly x86_64, with some local packages.

**Comment by Begasus** [comment]
Don't have (fast enough) nightly to check this, it probably will be fine there.

**Comment by jmairboeck** [comment]
Tests went fine on x86_64 (with some local packages).

**Pull request merged**
