### PR TITLE
man_pages_posix: fix 2017.a

### PR DESCRIPTION
**Pull request by lonemadmax**
The PROLOG separator we anchored in to patch a notice has changed from an empty line to a comment.

Also update the license file and remove previous version.

### CODE REVIEW

**Comment by Begasus** [comment]
LGTM (although I'm not the expert), good to go?

**Comment by lonemadmax** [comment]
Upon further inspection, please DON'T MERGE this now.

The paragraph removed from the license file seems to imply that redistribution and modification are not allowed now, or at least that permission was explicit before and it isn't now. So, until someone more versed in these issues comments, we may even have to remove the recent 2017 version.

The man pages content was corrected and ready, yes, but with this license issue I guess that doesn't matter anymore.

**Comment by Begasus** [comment]
OK, thanks for inspecting, can you take care of re-enabling the older version for now?

**Comment by Begasus** [comment]
Revbumping now adds the conflict, can be dealth with later :)
I saw at: https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/report.txt
that the old one isn't listed anymore, so did a revbump for that.

**Comment by lonemadmax** [comment]
None of the lawyers in the room approve the license change, so let's forget about this.

**Comment by korli** [comment]
See https://bugs.gentoo.org/871636

**Comment by lonemadmax** [comment]
Yes, same for Fedora (not even RPM Fusion non-free accepted it) and a few others. I found Debian ships it, but with the previous license, which doesn't give me any good feeling about it. There's even [a thread in upstream's mailing list](https://lore.kernel.org/all/cc7fc498-f068-9f62-967b-743805298ebb@gmail.com/) with no answer.

**Pull request closed without merging**
