### PR TITLE
zstd: bump to 1.3.7.

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
zstd `1.3.7` builds fine on all architectures but `hp --test zstd` fails to build on x86_gcc2.

**Comment by Begasus** [comment]
PS, there is also a GPL v2 copyright file in the source, shouldn't that be included also?

**Comment by kenmays** [comment]
@Begasus - If just reviewing the build and tests, you can also use **--no-source-package**.
zstd-1.3.5 built and tested fine with no other modifications, although I know your fix is for the buildmaster build.

**Comment by Begasus** [comment]
@kenmays --no-source-packages is arleady included in the profile for haikuporter :)

**Comment by fbrosson** [comment]
Thanks @Begasus for the fix and the remark about the license.
I've just pushed your fix. It is working like a charm!

Everything is OK now. I'll squash the commits in this PR, rebase and merge a bit later.

In case someone would like to merge, please let me do it, as I'd like to do a manual merge, with my GPG signature :)
Thanks!

**Comment by fbrosson** [comment]
I've updated my PR with an extra commit. I'm double-checking that everything is OK.
Then I'll squash the 3 commits in this PR:
* ab7da59a3b7f6459ffe24e4b6cde6bca0ac4ab66 `zstd: bump to 1.3.7.`
* 5076e7b642627802750f122e8caef4e1536d22a9 `zstd: add "GNU GPL v2" to LICENSE, amend gcc2 patch.`
* 457414d0f6e68a32c0e5eca11e0ded3c42207d5c `zstd: fix TEST, amend common patch and gcc2 patch.`

and rebase against master in order to do a manual merge.

**Pull request merged**
