### PR TITLE
keepassx: Enable on x86_64 and remove stack protector flag

### PR DESCRIPTION
**Pull request by moochris**
Built and tested on x86_64 - just needed the stack protector flagged removed (or complains about libssp.so.0 being missing).

### CODE REVIEW

**Comment by diversys** [comment]
If you get it to work we could probably drop this recipe.

**Comment by moochris** [comment]
Sure, I'll let you know once (hopefully!) I get a PR for the community one submitted.

On 3 August 2017 12:47:15 BST, diversys <notifications@github.com> wrote:
>If you get it to work we could probably drop this recipe.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/haikuports/haikuports/pull/1551#issuecomment-319946478

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KapiX** [comment]
There is a working recipe for keepassxc I've committed 6 months ago. Am I missing something in this conversation?

**Comment by moochris** [comment]
Oh. No, I have been away from my computer and haven't had a chance to look to see if it was already there...

I see it's marked as not tested on x86_64, so I can test it later if you like? I use keepassx a lot.

On 3 August 2017 13:42:00 BST, Kacper Kasper <notifications@github.com> wrote:
>There is a working recipe for keepassxc I've committed 6 months ago. Am
>I missing something in this conversation?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/haikuports/haikuports/pull/1551#issuecomment-319957708

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by diversys** [comment]
There is also a newer version of keepassxc there, see if you can build it.
@KapiX shall we remove this one then?

**Comment by KapiX** [comment]
@moochris x86_64 will probably work fine so just removing `?` should be enough. You can try to update it to 2.2.0.
@diversys Since this is a recipe for an alpha and KeePassX is unmaintained, I think so.

**Comment by moochris** [comment]
@KapiX Unfortunately, with 2.2.0, I get namespacing errors in the core Qt headers:

[ 51%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/DatabaseOpenWidget.cpp.o
In file included from /boot/system/develop/headers/QtCore/QtConcurrentRun:1:0,
                 from /sources/keepassxc-2.2.0/src/gui/ChangeMasterKeyWidget.cpp:33:
/boot/system/develop/headers/QtCore/qtconcurrentrun.h:105:61: error: 'HasResultType' is not a member of 'QtPrivate'
 auto run(Functor functor) -> typename QtPrivate::QEnableIf<!QtPrivate::HasResultType<Functor>::Value, QFuture<decltype(functor())> >::Type
                                       

I'll revert to the version you had working and try that...

**Pull request merged**
