### PR TITLE
camlp5, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Looks like it should be ok, build is starting fine, but my system here keeps freezing when trying to build (not related to Haiku), if someone could check this out it would be fine :)

**Comment by alaviss** [comment]
> Looks like it should be ok, build is starting fine, but my system here keeps freezing when trying to build (not related to Haiku), if someone could check this out it would be fine :)

Chances are we have to update our OCaml. I once tried, but was hit with too many issues so I abandoned it.

**Comment by Begasus** [comment]
The build didn't produce any errors so far here ... just that my laptop doesn't seem to cope with the build ...

**Comment by Begasus** [comment]
Finaly my system went through all the way, builds ok for x86_gcc2 (haven't checked others yet) :)

**Pull request merged**
