### PR TITLE
Rename dev-libs/cyassl and files to dev-libs/wolfssl

### PR DESCRIPTION
**Pull request by dash102**
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5644410628866048/?sp-page=1

### CODE REVIEW

**Comment by waddlesplash** [comment]
This doesn't build...

**Comment by dash102** [comment]
Does that mean there is something wrong inside the recipe files?

**Comment by waddlesplash** [comment]
Yes.

**Comment by dash102** [comment]
It says "The Travis CI build passed". When you say it doesn't build, where can I see that there is something wrong with the files?

**Comment by pulkomandy** [comment]
You can run haikuporter to test your changes and try to build the recipe.

    haikuporter -S --get-dependencies wolfssl

This shoud result in no warning/errors and one or several packages being created.

**Comment by dash102** [comment]
I got an error saying:
base: haikuporter: command not found

**Comment by pulkomandy** [comment]
Then you need to install it first.

    pkgman install haikuporter

**Comment by dash102** [comment]
I'm still getting the same error. Do I have to be in a certain directory for it to work?

**Comment by pulkomandy** [comment]
Note: the recipes didn't build before anyway. Fixing them is out of scope of the GCI task. However we should make sure this doesn't add more breakage than there already is.

**Comment by dash102** [comment]
Should I just leave the recipes as cyassl because renaming them to wolfssl doesn't fix anything?

**Comment by pulkomandy** [comment]
No, we still need to rename them, because the project was renamed. Fixing them (or porting a newer version) will be a later task.

**Comment by dash102** [comment]
I have renamed the files, is that commit okay?

**Comment by waddlesplash** [comment]
No, because the file referenced in SOURCE_URI doesn't even exist.

**Pull request closed without merging**
