### PR TITLE
nim: bump to 1.4.6

### PR DESCRIPTION
**Pull request by mgurga**
built successfuly on hrev54154

### CODE REVIEW

**Comment by Begasus** [comment]
@mgurga why closing the PR?

**Comment by mgurga** [comment]
I looked at the current pull requests and saw a [bump to 1.2.0](https://github.com/haikuports/haikuports/pull/4845). This seems more developed because they got the tests working, so I just closed mine.

**Comment by Begasus** [comment]
Thanks for looking into it :) Maybe you could use some of the 1.2.0 version changes to make them work with this one?

**Comment by korli** [comment]
@Begasus I commented on #4845  It seems to me that alaviss has submitted a lot more commits upstream as what is in the PR. I asked him for a status.

**Comment by Begasus** [comment]
Thanks for looking into it @korli :+1:

**Pull request closed without merging**
