### PR TITLE
Generation of .pc files for pkg-config

### PR DESCRIPTION
**Pull request by Sylvain78**
ncurses:Minimal changes to generate .pc files.

### CODE REVIEW

**Comment by mmuman** [comment]
Please use English for commit logs.
Also, as a convention, we prefix the first line with the name of the concerned recipe, like "ncurses: generate .pc files for pkg-config"
You'll also want to use git rebase origin and force push to remove the useless merge commit.

**Comment by korli** [comment]
ncurses 6.0 is the newest recipe, please change this one. ncurses 5.9 is deprecated in Haiku.
I'm pretty sure your patch is broken for secondary architecture. Have you tried instead to define the variable PKG_CONFIG_LIBDIR?

**Comment by mmuman** [comment]
I'm not sure, doesn't haikuporter use setarch now?

**Comment by mmuman** [comment]
Ok, just need to make sure gcc4 .pc are fine now.

**Comment by korli** [comment]
If you could just drop your first commit, only keep the 6.0 commit, that would be cool.
Also use an english comment for your patch.

**Comment by mmuman** [comment]
Oh, we'll want to bump the REVISION, too :-)

**Comment by korli** [comment]
Applied, thanks!

**Pull request closed without merging**
