### PR TITLE
LLVM: bump

### PR DESCRIPTION
**Pull request by extrowerk**
Applied 12.0.1 patches, some already merged upstream, therefore unnecessary.
Build fails.

### CODE REVIEW

**Comment by extrowerk** [comment]
@nielx : as requested

**Comment by extrowerk** [comment]
It seems the llvm ports configured and built with all features/targets enabled. Does this actually makes any sense?
I am looking at this blogpost series right now: https://www.cambus.net/speedbuilding-llvm-clang-in-5-minutes/

**Comment by extrowerk** [comment]
LLVM in default targets  AArch64, AMDGPU, ARM, AVR, BPF, Hexagon, Lanai, Mips, MSP430, NVPTX, PowerPC, RISCV, Sparc, SystemZ, WebAssembly, X86, XCore on Haiku with the unchanged recipe.

There is currently no good reason to build all of those.

I assume AArch64,, AMDGPU, ARM,PowerPC,RISCV,Sparc,WebAssembly,X86, can be enough for us. Maybe  even without PowerPC and Sparc

**Comment by augiedoggie** [comment]
I would prefer it if you left the microcontroller targets enabled(specifically arm, avr, msp430).  It might be useful in the future to have aarch64 enabled also.

**Comment by extrowerk** [comment]
Currently fails here:
```
Building ...
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR) 
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.10.2
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-haiku
-- LLVM default target triple: x86_64-unknown-haiku
-- Building with -fPIC
CMake Warning at cmake/modules/VersionFromVCS.cmake:49 (message):
  Git not found.  Version cannot be determined.
Call Stack (most recent call first):
  CMakeLists.txt:858 (get_source_info)


-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Targeting AMDGPU
-- Targeting RISCV
-- Targeting WebAssembly
-- Targeting X86
-- Compiler-RT supported architectures: x86_64
-- Builtin supported architectures: x86_64
-- For x86_64 builtins preferring i386/fp_mode.c to fp_mode.c
-- For x86_64 builtins preferring x86_64/floatdidf.c to floatdidf.c
-- For x86_64 builtins preferring x86_64/floatdisf.c to floatdisf.c
-- For x86_64 builtins preferring x86_64/floatundidf.S to floatundidf.c
-- For x86_64 builtins preferring x86_64/floatundisf.S to floatundisf.c
-- For x86_64 builtins preferring x86_64/floatdixf.c to floatdixf.c
-- For x86_64 builtins preferring x86_64/floatundixf.S to floatundixf.c
-- Builtin supported architectures: x86_64
-- check-shadowcallstack does nothing.
-- Clang version: 13.0.1
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Not building amdgpu-arch: hsa-runtime64 not found
-- LLD version: 13.0.1
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Registering Bye as a pass plugin (static build: OFF)
-- Failed to find LLVM FileCheck
-- Version: 0.0.0
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /sources/llvm-13.0.1.src/build
[218/1920] Building CXX object tools...s/obj.clangSema.dir/SemaOpenMP.cpp.o
In file included from /sources/llvm-13.0.1.src/include/llvm/ADT/APSInt.h:17,
                 from /sources/llvm-13.0.1.src/include/llvm/ADT/APFixedPoint.h:19,
                 from /sources/llvm-13.0.1.src/tools/clang/include/clang/AST/APValue.h:17,
                 from /sources/llvm-13.0.1.src/tools/clang/include/clang/AST/Decl.h:16,
                 from /sources/llvm-13.0.1.src/tools/clang/lib/Sema/CoroutineStmtBuilder.h:16,
                 from /sources/llvm-13.0.1.src/tools/clang/lib/Sema/TreeTransform.h:16,
                 from /sources/llvm-13.0.1.src/tools/clang/lib/Sema/SemaOpenMP.cpp:14:
In destructor 'llvm::APInt::~APInt()',
    inlined from 'llvm::APSInt::~APSInt()' at /sources/llvm-13.0.1.src/include/llvm/ADT/APSInt.h:22:22,
    inlined from 'bool checkOMPArraySectionConstantForReduction(clang::ASTContext&, const clang::OMPArraySectionExpr*, bool&, llvm::SmallVectorImpl<llvm::APSInt>&)' at /sources/llvm-13.0.1.src/tools/clang/lib/Sema/SemaOpenMP.cpp:16672:45,
    inlined from 'bool actOnOMPReductionKindClause(clang::Sema&, {anonymous}::DSAStackTy*, clang::OpenMPClauseKind, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::CXXScopeSpec&, const clang::DeclarationNameInfo&, llvm::ArrayRef<clang::Expr*>, {anonymous}::ReductionData&)' at /sources/llvm-13.0.1.src/tools/clang/lib/Sema/SemaOpenMP.cpp:17030:68:
/sources/llvm-13.0.1.src/include/llvm/ADT/APInt.h:333:18: warning: 'void operator delete [](void*)' called on a pointer to an unallocated object '1' [-Wfree-nonheap-object]
  333 |       delete[] U.pVal;
      |                  ^~~~
In destructor 'llvm::APInt::~APInt()',
    inlined from 'llvm::APSInt::~APSInt()' at /sources/llvm-13.0.1.src/include/llvm/ADT/APSInt.h:22:22,
    inlined from 'bool checkOMPArraySectionConstantForReduction(clang::ASTContext&, const clang::OMPArraySectionExpr*, bool&, llvm::SmallVectorImpl<llvm::APSInt>&)' at /sources/llvm-13.0.1.src/tools/clang/lib/Sema/SemaOpenMP.cpp:16691:45,
    inlined from 'bool actOnOMPReductionKindClause(clang::Sema&, {anonymous}::DSAStackTy*, clang::OpenMPClauseKind, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::CXXScopeSpec&, const clang::DeclarationNameInfo&, llvm::ArrayRef<clang::Expr*>, {anonymous}::ReductionData&)' at /sources/llvm-13.0.1.src/tools/clang/lib/Sema/SemaOpenMP.cpp:17030:68:
/sources/llvm-13.0.1.src/include/llvm/ADT/APInt.h:333:18: warning: 'void operator delete [](void*)' called on a pointer to an unallocated object '1' [-Wfree-nonheap-object]
  333 |       delete[] U.pVal;
      |                  ^~~~
[362/1920] Building CXX object tools...angDriver.dir/ToolChains/Haiku.cpp.o
FAILED: tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Haiku.cpp.o 
/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/sources/llvm-13.0.1.src/build/tools/clang/lib/Driver -I/sources/llvm-13.0.1.src/tools/clang/lib/Driver -I/sources/llvm-13.0.1.src/tools/clang/include -I/sources/llvm-13.0.1.src/build/tools/clang/include -I/sources/llvm-13.0.1.src/build/include -I/sources/llvm-13.0.1.src/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG  -fno-exceptions -std=c++14 -MD -MT tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Haiku.cpp.o -MF tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Haiku.cpp.o.d -o tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Haiku.cpp.o -c /sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Haiku.cpp
/sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Haiku.cpp: In member function 'virtual void clang::driver::toolchains::Haiku::addLibStdCxxIncludePaths(const llvm::opt::ArgList&, llvm::opt::ArgStringList&) const':
/sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Haiku.cpp:44:27:error: no matching function for call to 'clang::driver::toolchains::Haiku::addLibStdCXXIncludePaths(std::basic_string<char>, const string&, const char [1], const char [1], const char [1], const llvm::opt::ArgList&, llvm::opt::ArgStringList&) const'
   44 |   addLibStdCXXIncludePaths(getDriver().SysRoot + "/system/develop/headers/c++",
      |   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   45 |                      getTriple().str(), "", "", "", DriverArgs, CC1Args);
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Haiku.h:12,
                 from /sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Haiku.cpp:9:
/sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Gnu.h:349:8: note: candidate: 'bool clang::driver::toolchains::Generic_GCC::addLibStdCXXIncludePaths(llvm::Twine, llvm::StringRef, llvm::Twine, const llvm::opt::ArgList&, llvm::opt::ArgStringList&, bool) const'
  349 |   bool addLibStdCXXIncludePaths(Twine IncludeDir, StringRef Triple,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
/sources/llvm-13.0.1.src/tools/clang/lib/Driver/ToolChains/Gnu.h:349:8: note:   candidate expects 6 arguments, 7 provided
[367/1920] Building CXX object tools...clangARCMigrate.dir/Transforms.cpp.o
ninja: build stopped: subcommand failed.
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1.
Error: Build has failed - stopping.
```

**Comment by extrowerk** [comment]
The clang patch have this:
```
-                           getTriple().str(), "", DriverArgs, CC1Args);
+                     getTriple().str(), "", "", "", DriverArgs, CC1Args);
```
removing it makes the build progress further.

**Comment by nielx** [comment]
The vanilla code in clang/lib/Driver/Toolchains/Haiku.cpp is:
```
void Haiku::addLibStdCxxIncludePaths(const llvm::opt::ArgList &DriverArgs,
                                     llvm::opt::ArgStringList &CC1Args) const {
  addLibStdCXXIncludePaths(getDriver().SysRoot + "/system/develop/headers/c++",
                           getTriple().str(), "", DriverArgs, CC1Args);
}
```

Based on the original patch, this should probably be updated to:
```
void Haiku::addLibStdCxxIncludePaths(const llvm::opt::ArgList &DriverArgs,
                                     llvm::opt::ArgStringList &CC1Args) const {
#ifdef HAIKU_HYBRID_SECONDARY
  addLibStdCXXIncludePaths(getDriver().SysRoot, "/system/develop/headers/"
                              HAIKU_HYBRID_SECONDARY "/c++" ,getTriple().str(), "", DriverArgs, CC1Args);
#else
  addLibStdCXXIncludePaths(getDriver().SysRoot + "/system/develop/headers/c++",
                           getTriple().str(), "", DriverArgs, CC1Args);
#endif
}
```

Also... the original code enables PIE for the x86_64 architecture. The patch removes that. What is correct?

**Comment by extrowerk** [comment]
> Also... the original code enables PIE for the x86_64 architecture. The patch removes that. What is correct?

AFAIK Haiku doesn't support PIE yet.

**Comment by pulkomandy** [comment]
All code in Haiku must be compiled as position-independant. In gcc this is normally done with two different options, -fPIC for libraries and -fPIE for executables. But in Haiku, all executables can also be loaded as add-ons (for replicants) so -fPIC must always be used.

I don't know if LLVM makes a similar distinction?

In any case, position-independant code must be enabled.

**Comment by extrowerk** [comment]
Superseeded by https://github.com/haikuports/haikuports/pull/7871

**Pull request closed without merging**
