### PR TITLE
wget2, new recipe

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Builds out of the box without patching (not sure if it's needed?), quick check seems to be ok pulling links from the web.
1 failing test:
```
============================================
   wget2 2.0.1: unit-tests/test-suite.log
============================================

# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test
==========

test_buffer_printf: Failed with format ('%0lld','0'): '0' != ''
test_buffer_printf: Failed with format ('%0lli','0'): '0' != ''
test_buffer_printf: Failed with format ('%0llu','0'): '0' != ''
test_buffer_printf: Failed with format ('%0lld','0'): '0' != ''
test_buffer_printf: Failed with format ('%0lli','0'): '0' != ''
test_buffer_printf: Failed with format ('%0llu','0'): '0' != ''
test_buffer_printf: Failed with format ('%00lld','0'): '0' != ''
test_buffer_printf: Failed with format ('%00lli','0'): '0' != ''
test_buffer_printf: Failed with format ('%00llu','0'): '0' != ''
ERROR: 9 out of 193812 basic tests failed
This may completely break Wget functionality !!!
FAIL test (exit status: 1)
```

**Comment by augiedoggie** [comment]
Seems like portage puts wget2 in its own directory, net-misc/wget2

**Comment by Begasus** [comment]
> Seems like portage puts wget2 in its own directory, net-misc/wget2

So does Gentoo, fixing ... :)

**Comment by Begasus** [comment]
@OscarL Can confirm that that test works out fine on 64bit. (next round gave 5 errors out of 77)

**Comment by korli** [comment]
the failed testcases should be fixed on [hrev56607](https://cgit.haiku-os.org/haiku/tag/?h=hrev56607) or newer

**Comment by Begasus** [comment]
> the failed testcases should be fixed on [hrev56607](https://cgit.haiku-os.org/haiku/tag/?h=hrev56607) or newer

Thanks, still on R1B4, but I can switch to nightly to check this. :+1:  (when I get around to it)

**Comment by korli** [comment]
> > the failed testcases should be fixed on [hrev56607](https://cgit.haiku-os.org/haiku/tag/?h=hrev56607) or newer
> 
> Thanks, still on R1B4, but I can switch to nightly to check this. 👍 (when I get around to it)

This should hopefully land in r1beta too.

**Comment by korli** [comment]
> This should hopefully land in r1beta too.

Also committed to beta4

**Pull request merged**
