### PR TITLE
mame: Bump to 0.266

### PR DESCRIPTION
**Pull request by PocketNerdIO**
Just a version bump, still 64-bit only.

### CODE REVIEW

**Comment by Begasus** [comment]
Thanks! While you are at it, could you have a look at a new issue reported? https://github.com/haikuports/haikuports/issues/10402

**Comment by PocketNerdIO** [comment]
> Thanks! While you are at it, could you have a look at a new issue reported? #10402

Sure. Might take a little while, but I'll give it a go!

**Comment by Begasus** [comment]
Any progress here @PocketNerdIO ? (not really looking forward on running tests on this one) :)

**Comment by PocketNerdIO** [comment]
At the moment, no. I've been looking at it today and I can't work out where to begin. I'll keep working on it.

**Comment by Begasus** [comment]
Merging for now, the issue is still open and should be investigated on a next bump. Thanks! :)

**Pull request merged**
