### PR TITLE
isl, bump version, remove obsolete isl13

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
In preparation to cloog 0.20.0

**Comment by Begasus** [comment]
Not tested on x86_64 (yet)

**Comment by Begasus** [comment]
@korli could you check? afaikt I don't see any use of isl13 (and only cloog  using isl)

**Comment by Begasus** [comment]
If no one objects, I will merge this one to bump and remove the old recipe for isl13

**Comment by korli** [comment]
> If no one objects, I will merge this one to bump and remove the old recipe for isl13
Please merge.

**Pull request merged**
