### PR TITLE
uif2iso: add x86 as 2nd arch, mark !x86_gcc2, rewrite description

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
The recipe was broken on x86_gcc2 so I made the required changes to enable cross-building uif2iso_x86 on x86_gcc2.
It builds natively on x86 and x86_64, and it cross-builds for x86 on x86_gcc2:
```
package info uif2iso-0.1.7c-1-x86.hpkg 
name: uif2iso  version: 0.1.7c-1

package info uif2iso-0.1.7c-1-x86_64.hpkg 
name: uif2iso  version: 0.1.7c-1

package info uif2iso_x86-0.1.7c-1-x86_gcc2.hpkg 
name: uif2iso_x86  version: 0.1.7c-1
```

The recipe installs the uif2iso runtime to **`bin/uif2iso`**, even for uif2iso_x86.
Should I change that and install it as **`bin/x86/uif2iso`** and create a symbolic link **`uif2iso-x86 -> x86/uif2iso`** ?
Or is it OK, for packages that don't build natively on x86_gcc2, to install to bin without any suffix?
Does this recipe need more than just some polishing? In either case, please let me know what needs to be fixed or improved. Thanks!

**Comment by korli** [comment]
This is no "cross-build" AFAICT. the x86 compiler is a regular compiler (it can self hosting).

**Comment by korli** [comment]
LGTM

**Comment by fbrosson** [comment]
Oops, you are perfectly right. Thanks for your remark.

**Pull request merged**
