### PR TITLE
Kristall.iom Icon-O-Matic icon file

### PR DESCRIPTION
**Pull request by Handmaus**
This is the source .iom file for the .hvif icon I clumsily attached to a comment to issue #6259.
It has all the names for paths, shapes and styles, so that anyone can grasp what's what in case someone needs to edit or reuse it.

(For personal reference, original file name: Kristall HaikuStyle B 03 Clear 03.iom)

### CODE REVIEW

**Comment by humdingerb** [comment]
I missed that #6297 was opened by win8linux...

Those named objects are not stored in attributes of IOM files, so they wouldn't get lost. I could imagine that you originally exported to HVIF (thereby losing those names), then opened that HVIF in IOM and saved as .IOM file which then didn't have those names anymore.  If you cannot find the original IOM with named objects, it's no biggie either.

WRT github, you'll fare best with using git within Terminal instead of a browser under Haiku in the long run.
See the wiki at https://github.com/haikuports/haikuports/wiki , esp. the DevelopmentModel page. Do join us on IRC #haiku for realtime assistance. :)

**Comment by Handmaus** [comment]
> ...checking it out properly, I see the named objects...

Yay! :D

> So, everything would be OK, if the .iom was in the additional-files sub-folder... :P

Not yay.... :<

I had a slight suspicion that someone had put that folder there for some reason ^_^¡

**Comment by Handmaus** [comment]
Wohoooo! My first contrib to Haiku!
@win8linux , @pulkomandy ,
  @humdingerb ,
    thank you!
`-------v------------´
. . .      \ (^ o ^) /

**Comment by win8linux** [comment]
So my PR gets merged first since that has the new icon, then this one to add the correct IOM file. Is that what's going to happen or should this one get another commit to add the new icon in instead?

**Comment by humdingerb** [comment]
Damn. I confused the two PRs... Pfft. will fix the IOM file location in another commit...

**Pull request merged**
