### PR TITLE
ne recipe: update to 3.1.1

### PR DESCRIPTION
**Pull request by humdingerb**
It does build and seems to work in general, but I don't think the macros work.
It also uses ~/.ne as config folder, which I tried to change but failed...

### CODE REVIEW

**Comment by diversys** [comment]
Maybe you can git mv old_recipe new_recipe?

**Comment by humdingerb** [comment]
I could, but wasn't sure my INSTALL() was acceptable, seeing as the older version had a "haiku" target for the makefile in the patch. (I didn't see the sense in that.)

**Comment by diversys** [comment]
Either that or also drop the old recipe :)

**Comment by humdingerb** [comment]
Before I remove the old recipe and merge the PR, currently there's a "ne-x86" link to /bin/x86/ne in /bin. Is that OK, or is there a way to name that symlink just "ne"?

**Comment by waddlesplash** [comment]
I think that's OK, for now anyway.

**Comment by humdingerb** [comment]
All righty then. Thanks for the input, guys!

**Pull request merged**
