### PR TITLE
beshare: revert wrong edits.

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
Sorry @korli, I though the changes were OK, since [the GCI task](https://codein.withgoogle.com/dashboard/task-instances/4884492562989056/) had been approved 10 days ago and nobody had spotted this.
I should have asked before merging. I'll do so from now on..

This is to address:
* https://github.com/haikuports/haikuports/commit/1f76cce1b0a3a4e508d43ac651459af9571985d3#commitcomment-20207342
* https://github.com/haikuports/haikuports/commit/1f76cce1b0a3a4e508d43ac651459af9571985d3#commitcomment-20207322
* https://github.com/haikuports/haikuports/commit/1f76cce1b0a3a4e508d43ac651459af9571985d3#commitcomment-20207327

**Comment by fbrosson** [comment]
I've also restored the commented line:
```
	#LOCAL_INCLUDE_PATHS=$includeDir/muscle
```

Is everything OK now? Should I merge this PR?

**Comment by korli** [comment]
Well if it builds OK, then it should be OK. Thanks!

**Comment by fbrosson** [comment]
Yep, it builds fine on all architectures where it is supposed to build: x86_gcc2 and x86.

**Pull request merged**
