### PR TITLE
ctags, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Build failure on 32bit, do not merge yet.
thrd_exit undeclared, maybe switch to gcc13?

**Comment by Begasus** [comment]
From the failed test(s):
```
--- ./Tmain/interactive-mode.d/stdout-expected.txt	2024-08-30 20:34:51.050855936 +0200
+++ /sources/ctags-p6.1.20240901.0/Tmain/interactive-mode.d/stdout-actual.txt	2024-09-05 16:59:27.368574464 +0200
@@ -18 +18 @@
-{"_type": "error", "message": "cannot open input file \"test.foo\"", "warning": true, "errno": 2, "perror": "No such file or directory"}
+{"_type": "error", "message": "cannot open input file \"test.foo\"", "warning": true, "errno": -2147459069, "perror": "No such file or directory"}
```

**Comment by Begasus** [comment]
Closes: https://github.com/haikuports/haikuports/issues/11054

**Comment by Begasus** [comment]
Switched to secondary architecture on 32bit, build is fine, tests outcome the same as on 64bit.

**Comment by korli** [comment]
we should stay on a stable release aka 6.1.0

**Comment by Begasus** [comment]
Running utiltest from source (with package installed):
```
/Opslag/haikuports/dev-util/ctags/work-6.1.20240901.0/sources/ctags-p6.1.20240901.0> ./utiltest 
Test fname/absolute...                          [ OK ]
Test fname/absolute+cache...                    [ OK ]
Test fname/relative...                          [ OK ]
Test htable/update...                           [ OK ]
Test htable/grow...                             [ OK ]
Test numarray...                                [ OK ]
Test routines/strrstr...                        [ OK ]
Test vstring/ncats...                           [ OK ]
Test vstring/truncate_leading...                [ OK ]
Test vstring/EqC...                             [ OK ]
SUCCESS: All unit tests have passed.
```

**Comment by Begasus** [comment]
> we should stay on a stable release aka 6.1.0

No problem, started out with that :) behaves the same as this one, pushes for the stable one will be for tomorrow though. :)

**Comment by Begasus** [comment]
Bumped to latest stable 6.1.0.

**Comment by Begasus** [comment]
Patch send upstream in PR: https://github.com/universal-ctags/ctags/pull/4069

**Pull request merged**
