### PR TITLE
scribus: bump for rebuild

### PR DESCRIPTION
**Pull request by kenmays**
closes: https://github.com/haikuports/haikuports/issues/5892

### CODE REVIEW

**Comment by korli** [comment]
Please clarify what is different since the last build. Otherwise it will be next time the same story.

**Comment by kenmays** [comment]
The python39 sys.path (prefix) and sys._base executable mapping. This is done during Scribus build config and stored in config.
Seems to target /bin/python3 versus /bin/python3.9 - but mainly breaks with the python39 package update with package mapping suffixes if different from the original python39 used during build config (python39-3.9.2(-2 suffix)).

**Rebuilding Scribus fixes the issue easily for now**, but maybe a further patch in Haiku and Scribus can make things better to handle the current python39 mapping and package updates. Be aware that other packages/recipes may suffer the same fate as well - especially with deps using various python3 (3.6,3.7,etc) for their builds.

**Comment by kenmays** [comment]
As for uninstalling python3 from Scribus build interference:
```
~/haikuports/app-office/scribus> pkgman uninstall python3
The following changes will be made:
  in system:
    uninstall package scons-3.1.2-3
    uninstall package meson-0.57.1-1
    uninstall package poppler_devel-20.11.0-1
    uninstall package gdk_pixbuf_devel-2.42.2-2
    uninstall package requests_python3-2.25.1-2
    uninstall package mako_python3-1.1.4-2
    uninstall package numpy_python3-1.20.0-2
    uninstall package setuptools_python3-42.0.0-4
    uninstall package glib2_devel-2.62.0-3
    uninstall package urllib3_python3-1.26.3-1
    uninstall package chardet_python3-3.0.4-3
    uninstall package idna_python3-2.8-2
    uninstall package cython_python3-0.29.21-1
    uninstall package python3-3.7.10-3
```

**Comment by korli** [comment]
I see two possibilities: we fix the underlying issue, or we go back to python 3.7.

**Comment by kenmays** [comment]
Fixed.

**Pull request merged**
