### PR TITLE
fluidsynth2, revbump, fix patchset

### PR DESCRIPTION
**Pull request by Begasus**
Related issue: https://github.com/haikuports/haikuports/issues/10815

### CODE REVIEW

**Comment by Begasus** [comment]
This builds for both FLAC version, so if there is a need for a specific version this needs to be added.

**Comment by Begasus** [comment]
Pushed the latest version (marked as broken), produces next error (not checked on 32bit):
```
In file included from /sources/fluidsynth-2.3.6/src/synth/fluid_voice.h:29,
                 from /sources/fluidsynth-2.3.6/src/synth/fluid_synth.h:34,
                 from /sources/fluidsynth-2.3.6/src/drivers/fluid_haiku.cpp:26:
/sources/fluidsynth-2.3.6/src/rvoice/fluid_adsr_env.h: In function 'void fluid_adsr_env_calc(fluid_adsr_env_t*)':
/sources/fluidsynth-2.3.6/src/rvoice/fluid_adsr_env.h:85:31: error: no match for 'operator++' (operand type is 'fluid_adsr_env_section_t' {aka 'fluid_voice_envelope_index'})
   85 |         env_data = &env->data[++env->section];
      |                               ^~~~~~~~~~~~~~
/sources/fluidsynth-2.3.6/src/rvoice/fluid_adsr_env.h:95:21: warning: no 'operator++(int)' declared for postfix '++', trying prefix operator instead [-fpermissive]
   95 |         env->section++;
      |         ~~~~~~~~~~~~^~
/sources/fluidsynth-2.3.6/src/rvoice/fluid_adsr_env.h:95:21: error: no match for 'operator++' (operand type is 'fluid_adsr_env_section_t' {aka 'fluid_voice_envelope_index'})
/sources/fluidsynth-2.3.6/src/rvoice/fluid_adsr_env.h:101:21: warning: no 'operator++(int)' declared for postfix '++', trying prefix operator instead [-fpermissive]
  101 |         env->section++;
      |         ~~~~~~~~~~~~^~
/sources/fluidsynth-2.3.6/src/rvoice/fluid_adsr_env.h:101:21: error: no match for 'operator++' (operand type is 'fluid_adsr_env_section_t' {aka 'fluid_voice_envelope_index'})
In file included from /sources/fluidsynth-2.3.6/src/synth/fluid_voice.h:32:
```

**Comment by jmairboeck** [comment]
I fixed the build error by moving that function implementation from the header to the C source file (de-inlining it). Incrementing enums isn't allowed in C++, apparently.

**Comment by jmairboeck** [comment]
@Begasus The recipe still needs some changes to build successfully, I'll let you take care of it. There is some problem with installing man pages, it seems.

**Comment by Begasus** [comment]
> It may be a good idea to force the latest version to be sure, if it is different for gcc2, that can be done this way:

I think I misread this yesterday when I started looking into the latest fluidsynth version, I guess you meant forcing the latest (in the repo) FLAC version? :)

**Comment by Begasus** [comment]
> @Begasus The recipe still needs some changes to build successfully, I'll let you take care of it. There is some problem with installing man pages, it seems.

That part is fixed, looks like they are using GNUInstallDirs now, so easy fix, also changed TEST() and now all tests passed on 2.3.6.

**Comment by pulkomandy** [comment]
Yes, I meant adding a version constraint on the require for flac to make sure it doesn't use an old version of flac when building. And also having a note in the recipe of which version it was built against, so it's easier to track which recipes are updated and which aren't, when a new version comes.

**Comment by Begasus** [comment]
Well, new version included now for fluidsynth (disabled so it won't interfere here), will run some checks on 32bit first.

**Pull request merged**
