### PR TITLE
openssl: 1.0.0s→1.0.0t & reformat recipe

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by fbrosson** [comment]
Although users of openssl 1.0.0 series should upgrade to 1.0.1 or 1.0.2, it might still be usefull to have the latest 1.0.0 for testing/bootstrapping purposes. But, of course, I can simply remove 1.0.0s if you prefer.

**Comment by fbrosson** [comment]
Sorry, I though I had replied here but my reply is in another PR: https://github.com/haikuports/haikuports/pull/447

**Comment by fbrosson** [comment]
Hi! Are you OK with my proposal to add this line:
```
 *.patchset linguist-language=Diff
```
to [.gitattributes](https://github.com/haikuports/haikuports/blob/master/.gitattributes) ? May I create a PR with such a commit? Thanks!

**Comment by waddlesplash** [comment]
I don't think it'll change syntax highlighting, only language statistics. So it's pointless. Just rename the files back please.

**Comment by fbrosson** [comment]
OK. Done in https://github.com/haikuports/haikuports/pull/451.

**Pull request merged**
