### PR TITLE
nim: update to 2.0.4

### PR DESCRIPTION
**Pull request by hoanga**
this updates nim to release 2.0.4.

```
~> uname -a
Haiku shredder 1 hrev57726 May  5 2024 06:14:15 x86_64 x86_64 Haiku


~> nim --version
Nim Compiler Version 2.0.4 [Haiku: amd64]
Compiled at 2024-04-27
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8d96b3672e92920d5ce0132821ef558e3e305ed2
active boot switches: -d:release
```

### CODE REVIEW

**Comment by augiedoggie** [comment]
32 bit build failed because apparently we no longer have a functioning `nodejs` package for that arch.

Also, unrelated, I just noticed there are two different `npm` packages...
https://depot.haiku-os.org/#!/pkg/npm/haikuports/haikuports_x86_64/10/4/0/-/1/x86_64?bcguid=bc2-JYCP
https://depot.haiku-os.org/#!/pkg/npm/haikuports/haikuports_x86_64/8/5/1/-/1/any?bcguid=bc2-SIHL

**Comment by Begasus** [comment]
> 32 bit build failed because apparently we no longer have a functioning `nodejs` package for that arch.
> 
> Also, unrelated, I just noticed there are two different `npm` packages... https://depot.haiku-os.org/#!/pkg/npm/haikuports/haikuports_x86_64/10/4/0/-/1/x86_64?bcguid=bc2-JYCP https://depot.haiku-os.org/#!/pkg/npm/haikuports/haikuports_x86_64/8/5/1/-/1/any?bcguid=bc2-SIHL

Weird, should only be one, on the other hand, the second link produces a 404.

**Comment by augiedoggie** [comment]
> Weird, should only be one, on the other hand, the second link produces a 404.

Extra weird because both links work fine for me :P

**Comment by Begasus** [comment]
https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/npm-8.5.1-1-any.hpkg gives me still a 404?

**Comment by augiedoggie** [comment]
Ah, I thought you were referring to the depot link, not the actual package.

**Comment by Begasus** [comment]
My bad for not being clear on that. ;)

**Pull request merged**
