### PR TITLE
GCC: enable ObjC

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by extrowerk** [comment]
It should be ok now, builds, packages fine.

**Comment by extrowerk** [comment]
It can compile a helloworld just fine, but running the generated binary results "segmentation violation"
http://chunk.io/miqlas/f9d316c6ffa842a490e1203c7b9f87cf

**Comment by extrowerk** [comment]
But ObjFW built correctly and all test passes.

**Comment by jessicah** [comment]
As mentioned on IRC, I don't think we should ship libobjc as part of the package, since a) not recommended to use, and b) don't actually work on Haiku. Shipping broken libraries is just silly.

**Comment by alaviss** [comment]
@jessicah 

We can only hope that no one uses libobjc in that case. But sadly, tutorials showing how to compile objc code with gcc often passes `-lobjc`, so we should support that.

I found this library [gnustep/libobjc2](https://github.com/gnustep/libobjc2) that claims to be a drop-in replacement for gcc's `libobjc`, so with a couple symlinks it should be fine

**Pull request closed without merging**
