### PR TITLE
argon2: bump version

### PR DESCRIPTION
**Pull request by AlwaysLivid**
Compiles on x86_64.

### CODE REVIEW

**Comment by Begasus** [comment]
This is used by keepassxc, should be checked if that build is ok with this update

**Comment by AlwaysLivid** [comment]
> This is used by keepassxc, should be checked if that build is ok with this update

Will check shortly.

**Comment by AlwaysLivid** [comment]
Successfully compiles with the patches on x86_64.

https://paste.ubuntu.com/p/6wf77v3vRq/

**Comment by korli** [comment]
But in the log one sees that keepassxc is built with :
       /boot/system/packages/argon2-20190614-2-x86_64.hpkg
	/boot/system/packages/argon2_devel-20190614-2-x86_64.hpkg
This means it was built with the old version of argon2.

**Comment by AlwaysLivid** [comment]
> This means it was built with the old version of argon2.

Ugh, I thought I changed the branch properly. Huge thanks for catching this one for me. Will try once more.

**Comment by AlwaysLivid** [comment]
Haven't replaced the checksum yet, do not merge.

**Comment by AlwaysLivid** [comment]
Should be good to go. @Begasus

**Pull request merged**
