### PR TITLE
nodejs: add recipe for v12.3.1

### PR DESCRIPTION
**Pull request by return**
This is a very early and functioning port of Node.js 12.3.1 to Haiku, based on V8 7.4.288.28.

This recipe currently uses the bundled dependencies from libuv, openssl, V8 and brotli. This might change to use shared libraries in the future when the correct dependencies are available in HaikuPorts.

What currently works:

* Node REPL.
* Networking.
* npm (Node modules (global) needs to be in non-packaged folder to download packages)
* Remote Debugging (via Chrome Debugger and inspector)

What does not work:
* CPU activity is missing.
* File Watching (fsevents unimplemented).

Please note that this recipe is very early and is only intended to be used by testers until it is ready to be merged into HaikuPorts.

The patches in this port were adapted and imported from the following ports:

Node.js (experimental): @pahefu 
https://github.com/pahefu/haikuNodeJs

libuv: @CodeForEvolution and @alaviss
https://github.com/alaviss/libuv
https://github.com/CodeforEvolution/libuv 

V8: @return
HaikuPorts PR: https://github.com/haikuports/haikuports/pull/3330

And finally: https://imgur.com/a/FEFOAvu

### CODE REVIEW

**Comment by waddlesplash** [comment]
Libuv has been merged; so all the statically bundled dependencies should be pared down now.

Additionally, we can use GCC instead of Clang at this point too.

**Comment by return** [comment]
@waddlesplash The recipe is now compiles using GCC. It also uses a shared V8, libuv, c_ares and libz. The last one to be made shared is openssl11 which fails to compile.

With the required recipes (V8 and libuv) being available in HaikuPorts I'm opening this recipe for further review.

**Comment by waddlesplash** [comment]
Looks good to me!

**Comment by return** [comment]
@waddlesplash PR #3897 needs to be merged or else npm won't work properly.

**Comment by waddlesplash** [comment]
Done.

**Comment by return** [comment]
Thanks!

**Pull request merged**
