### PR TITLE
libaubio, bump version

### PR DESCRIPTION
**Pull request by Begasus**
Had to disable the test in INSTALL, could use some checking into before merging

### CODE REVIEW

**Comment by Begasus** [comment]
```
    /sources/aubio-0.4.9/build/tests/test-cvec 
stderr:
runtime_loader: Cannot open file libaubio.so.5: No such file or directory
```

**Comment by korli** [comment]
hey Begasus, you probably need to tweak the test setup script : https://github.com/aubio/aubio/blob/master/scripts/setenv_local.sh

```
if [ "$(uname)" == "Haiku" ]; then
  export LIBRARY_PATH=$AUBIOLIB:$LIBRARY_PATH
  echo export LIBRARY_PATH=$LIBRARY_PATH
elif "$(uname)" == "Darwin" ]; then

**Comment by Begasus** [comment]
Thanks @korli will check later (when I get around to it) :)

**Comment by Begasus** [comment]
Checked but didn't work @korli (for _x86)

**Comment by Begasus** [comment]
From the requirement file from aubio:
https://github.com/aubio/aubio/blob/8924bdf04489a93fcea408d0e45347b37a0d88a8/doc/requirements.rst#disabling-the-tests

**Comment by korli** [comment]
Looks good for me.

**Comment by Begasus** [comment]
While in the process maybe I could remove the previous version? (patchset from previous version isn't needed anymore) :)

**Pull request merged**
