### PR TITLE
libpurple, bump version

### PR DESCRIPTION
**Pull request by Begasus**
libgnt needs to be merged before this: https://github.com/haikuports/haikuports/pull/6026

### CODE REVIEW

**Comment by Begasus** [comment]
cmd:finch is in the main package atm, didn't notice that change earlier, anyway @JadedCtrl maybe you could have a look? (be sure to make backups for your current packages as libpurple isn't install-able anymore atm :) )

**Comment by JadedCtrl** [comment]
Everything's working fine on my machine :)

**Comment by Begasus** [comment]
@JadedCtrl pushed some changes (clean up mostly), could you check? I think it should be ok now :)

**Comment by JadedCtrl** [comment]
Working on my system :)

Though, did nss give grief, or was it removed for another reason? It seems to work on x86_64, and is necessary for a few protocols :o

**Comment by Begasus** [comment]
> and is necessary for a few protocols

I'll take another look then ;) it didn't seem to be any requirements when looking at configure, check for tomorrow :)

**Comment by Begasus** [comment]
Will keep the wip label for a bit

**Comment by Begasus** [comment]
Re-enabled lib's @JadedCtrl could you run them again to check? PS you have to run haikuporter without -S option (the included libperl.so will give an error otherwise) :)

**Comment by JadedCtrl** [comment]
Thanks for re-enabling― everything working on my end, SSL support too :)

**Pull request merged**
