### PR TITLE
Hermes: new recipe

### PR DESCRIPTION
**Pull request by miqlas**
build requires shouldn't needed, but they are.

### CODE REVIEW

**Comment by korli** [comment]
Versions for libraries should be hardcoded with the ones used to build the binaries. The ones present in haikuports might be incompatible.

**Comment by miqlas** [comment]
@korli, i can do it, or i can provide a static binary. Wich one do you prefer?
Btw, have you got any idea why the devel req section required?

**Comment by korli** [comment]
if you have built the binary yourself, you know which versions of hpkgs were used, then just declare them in the recipe, no need to rebuild a static binary.

haikuporter actually needs the libraries to make its policy check in the chroot:
https://github.com/haikuports/haikuporter/blob/master/HaikuPorter/Policy.py#L275
we could include the runtime dependencies when the build dependencies are empty.
haiku_devel isn't actually needed to build this recipe?

**Comment by miqlas** [comment]
@korli : only the defined stuff is required, nothing else.
Ok, i'll define the correct versions then.
Thanks for the explanation and for the link.

**Comment by korli** [comment]
You could do this: BUILD_REQUIRES=$REQUIRES

**Comment by miqlas** [comment]
@korli: thanks, fixed.

**Pull request merged**
