### PR TITLE
bunch of LibreOffice translations are enabled to pack

### PR DESCRIPTION
**Pull request by iam-git**
It is still not everything (about 70 % of all LO translations - as a compromise taken only languages I've at least heard about)

### CODE REVIEW

**Comment by extrowerk** [comment]
How much bigger the generated hpkg is? If the difference significant would it be possible to split it up to subpackages?

**Comment by iam-git** [comment]
That is already done by diversys. Every langpack is in separate package. So, recipe now produce 76 packages instead of 17.

**Comment by diversys** [comment]
Could you resolve the conflict?

**Comment by iam-git** [comment]
something like this?

**Pull request merged**
