### PR TITLE
GDB: Add GDB 8.2 recipe

### PR DESCRIPTION
**Pull request by kenmays**
See: [#253](https://github.com/haikuports/haikuports/issues/253)
Built on Haiku x86_64 R1B1 to completion. **No serious build issues.**
NOTE: Work in progress. Needs further testing and review.

### CODE REVIEW

**Comment by extrowerk** [comment]
Be apps needs specific support, wich isnt included in gdb as is. Do you plan to reintroduce the old patches in modernized form? If not, we can close this PR right now.

**Comment by extrowerk** [comment]
I see a patchset here, does it applies clealy? Does it works?
Please be as clear as possible in your response.

**Comment by kenmays** [comment]
@extrowerk - Yes, the patchset applies cleanly. Explain more about that those legacy Be-specific patches.
Was GDB officially replaced by other tools like the current Haiku GUI debugger?

**Comment by extrowerk** [comment]
@kenmays, you dedication is to be appreciate, and nice, but have you built, run, tested it? Does it works? On every arch?

**Comment by extrowerk** [comment]
@kenmays: pleasedo not oen PRs just for closing or letting closing them.

**Comment by kenmays** [comment]
@kenmays - I got it built, but the compiler mentioned a very minor issue with 1-2 Haiku-specific patches.
Since x86 builds were 'dropped', I'm mainly testing on x86_64 now.

**Comment by extrowerk** [comment]
Somehow disturbs me this “testing”. I would say, get something work and only then open a PR, not the other way, but who am i to say how other people should work?
Still i can say it seems you randomly takes things where sometimes you have no experiences/knowledge. I just ask: why dont you try you teeth on easier, less complex tasks? We got oiio/ocio recipes which needs bump, that would be fine, and no Haiku deep knowledge would be required, just extensive testing (every dependent recipes) what you do really well as far i see.
Thats my 2 cents, btw.

**Comment by KapiX** [comment]
The fact that you have added the patch and a recipe in two different commits, on GitHub, added a new header manually on top of it, and that it's a `.patch` not a `.patchset` (which would be generated by HaikuPorter) leads me to think you didn't test it at all. Same thing was happening with QtWebEngine, where you just appended patches from different sources by hand.

As @extrowerk has said, try your hand on easier things first, and actually use git and HaikuPorter.

**Comment by kenmays** [comment]
@extrowerk - Sleep on it. I'll digress on my other feedback. I clearly noted "NOTE: Work in progress. Needs further testing and review." and I answered you by saying I got it to build with no major issues. I didn't say there was NO issues - just no major issues with compiling GDB 8.2. Now, what you may not know is **I went through many submitted recipes/patches by other people that don't work - or when tested, the program didn;t even function correctly.** Sad, what is good for the goose i(i.e. key people, club members) is not for the gander (i.e. others, outsiders) as well? 

@KapiX - wrong assumption.  As for QtWebEngine, you mentioned it built for you and crashed. But, you didn't mention how I got several dependencies fixed even before we got to that point.

Guys, you are being biased. I know my own faults - but don't witchhunt. I can point out a lot of things myself - but I l;earned to play nice.....

**Comment by kenmays** [comment]
As mentioned, you can close this PR.

**Comment by KapiX** [comment]
I'm not here to pick a fight. However, it's fairly obvious you're using neither HaikuPorter to export patchsets nor git to commit them. Which is suspicious.

**Comment by kenmays** [comment]
@KapiX - Actually, I appreciated the corrective feedback. Take a look at the gdb-6.3 recipe and patch. Notice anything relevent? Basically, I know the standards probably got changed some time ago - **but hold everyone accountable** - but just the new people. We learn from those legacy recipes and patches as well. As they say, we learn from our past. People submitted a few recipes and patches not in the current trends of today's submission but got the hall pass. Guess QA didn't exist back then?

I'm OK with the debate/discussion and will respect it.

**Comment by KapiX** [comment]
The code in the patch is irrelevant to the issue I'm talking about. The problem is you are not using correct tools.

You're manually editing patches instead of using git and Haikuporter to generate them. I know that because the header at the top is 3 lines long instead of 4. HaikuPorter (actually git which is run underneath) probably accepts it when applying, because it assumes it's part of the description. This doesn't change the fact that it's not a correct way to do it. You should never need to add anything to the patchset manually.

You're using GitHub to upload and edit files. Why?

Maybe you have built this recipe, and got a package, but were you able to actually attach to the process? Print a backtrace? Do you know how to use GDB? I don't want to bring you down, but you should pace yourself. If you don't have C++ programming experience (I don't know your skillset), GDB or QtWebEngine is too much. There are easier things to do, and when you get more experience you can try your hand at those bigger ones.

Let me end with this: we want to see you succeed, because your success is our success. Nobody wants to out you because you're not part of the club, but you need to be willing to learn instead of getting defensive when people point out your mistakes.
Join the IRC channel, and just ask, or write me an e-mail privately. I'd be happy to help you get your first PR merged.

**Comment by kenmays** [comment]
@KapiX - I was pointing out the filename extension of the patch (patch versus patchset). 

My mistake was only in submitting it - unfinished. My intent was different in just getting it to the point where it required minor work to finish. As I mentioned, work in progress and where I was with it. You guys want finished products (I'm assuming that) yet why do I see countless submissions that don't merit that or broken submissions and patches in the repo??? Then, you question MY skillsets???? Bringing hammers to a glass house?

Asking me certain questions is like me asking you if you know ARM assembly programming, CUDA, or maintain your certifications in C/C++ . Notice,, I fixed and debugged a lot of things already - and maybe you or I will solve cancer, space travel, or homelessness one day.  Where are all of those previous tests results by others on GDB, GCC, binutils and other things?? Did anyone ask that of the others?? Remember the goose from the gander comment? Let's digress from this part of discuss.

**Comment by KapiX** [comment]
So you're not interested to learn. Good to know.

**Comment by extrowerk** [comment]
@kenmays have right, i also hold currently 18 PR with "wip", "help-needed" and other tags, some are even more than 1 years old.

My only explanation could be: 16 of them is either
- bumps to my own ports which are in the tree, but i met with unexpected problems
- or contains extensive recipe/logic/patch rework which i don't want to loose or get forgotten, and met with unexpected problems
- or just had no time to fight with it because IRL unexpected problems
So he have definitely right with insider/outsider thing.

But that's also true, it was told more than once to use the right tools, and i can't really imagine one needs handholding in git (at least not in the basic process, what required for a proper recipe), as there are plenty easy to follow guides on the internet, and even the GCI students gets it right. Still, @kenmays if you find any problem with HP setup, usage, logic, PRs, rebases, solving conflicts, then every door is open to get help at the Haiku IRC channel where we hang and discuss porting problems. So telling that if we want to teach we should teach is not appropriate, and i hope you also understand this.

I just checked the wiki, but there is no real explanation, how the puzzle elements connecting together, so the leraning curve could be steep, but i'm unsure if git basics are in the scope of the HaikuPorts wiki.

**Comment by fbrosson** [comment]
@kenmays, I think you have many skills I don't have. And, imo, your skills can be very useful to both HaikuPorts and Haiku. Some contributions you did so far were not trivial at all, so I can only say that you are still very welcome to contribute.
At the same time I'm a bit puzzled because you still haven't decided to learn how to use git on the command line and how to have [haikuporter generate a patchset](https://github.com/haikuports/haikuports/wiki/Patching-with-HaikuPorter). (Learning git on the command line is not that hard. You should really give it a try!)
My advice: give yourself a few weeks to become a git expert and then start using those new skills here to impress us. If you do so nobody here will ever suggest again that you should learn git! (Doesn't this sound exciting :)

**Comment by waddlesplash** [comment]
I also note the most recent GDB recipe is busted as it crashes on startup, a fact I noted when I committed it, but it does get far enough that it was worth pushing. Did you make any changes to the patch? If not, this one will probably be more broken than the last one (as GDB is currently doing a lot of internal refactoring.)

**Comment by kenmays** [comment]
@waddlesplash - I updated certain patches to build GDB 8.2 and there was two Haiku-specific patches I was going to review. The patchset applies cleanly and works but I didn't tweak it for haikuporter import/export. It'll normally fail in 2-3 spots dealing with those Haiku-specific spots but otherwise will build to completion. Didn't seem like anything major, just type conversion stuff.

Yesterday, **I mainly wanted to see if there were any build issues and what patches needed tweaking**. I had noted GDB was superceded by the GUI debugger tool (i.e. https://www.haiku-os.org/node/5004):
"This milestone is important because it marks Haiku's debugger as ready for general use. **Before Haiku used the command line tool gdb, which is very good but also very user unfriendly if you are used to a decent GUI debugger.**"

**Comment by waddlesplash** [comment]
What does "works" mean? Compiling is irrelevant. If it still crashes on startup then it's useless.

GDB is superseded by the GUI debugger tool for Haiku's internal usage. There are still scenarios where it might be useful, hence my attempts to get it to work. I think I know how to fix the crashes, but I haven't put the time in yet.

**Comment by pulkomandy** [comment]
I just want to mention that a "generic" GDB version (without support for debugging Haiku apps) is super useful to me as I use it to do remote debugging over JTAG and the like. It is nice to keep a recipe working for that, at least.

@kenmays, I don't question your knowledge, the problem is you are not using the expected workflow. We have put a lot of safeguards in haikuporter to make sure the patches apply cleanly, etc. By bypassing this, you are forcing reviewers to do extra work, and you are also forcing yourself to do extra work, which should be automated. It is fine if you get yourself doing extra work, but it is not when it involves other people. This is the problem here. After some time, people will be tired of pointing errors that an automated tool should have caught already. Of course they get a little aggressive when you waste their time this way. It's not a question of skills here, just of using the preferred workflow to avoid errors that automatic tools can catch, improving everyone's productivity.

**Pull request closed without merging**
