### PR TITLE
Godot: X86_64 support

### LINKED ISSUE #3388: godot broken on x86_64
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/2486/builds/12495.log

### PR DESCRIPTION
**Pull request by extrowerk**
fixes #3388

Builds till the end but linking fails:
```[Initial build] /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: modules/libmodules.haiku.tools.64.a(subpixel_mmx.haiku.tools.64.o): relocation R_X86_64_PC32 against symbol `vp8_bilinear_filters_x86_8' can not be used when making a shared object; recompile with -fPIC
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status```

### CODE REVIEW

**Comment by waddlesplash** [comment]
Try forcing a `-fPIC` build.

**Comment by Begasus** [comment]
https://groups.google.com/a/webmproject.org/forum/#!topic/webm-discuss/trEJtgeAvCg ?

**Comment by korli** [comment]
It seems to be related to the libvpx builtin library. Maybe depends on the system one: builtin_libvpx=no

HaikuPorts hasn't 1.6.0 anymore, only 1.7.0. Minor changes might be needed, the API seems about the same according to https://abi-laboratory.pro/index.php?view=timeline&l=libvpx

**Comment by korli** [comment]
Alternative: (temporarily) disable the problematic module like in: https://github.com/godotengine/godot/blob/master/modules/webm/config.py#L2

**Comment by extrowerk** [comment]
Builds, packages and starts, but bails out here:
```
ERROR: _display_error_with_code: CanvasShaderGLES3: Vertex Program Compilation Failed:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
```
Will try to force older GLSL somehow later...

**Comment by extrowerk** [comment]
It starts with MESA_GL_VERSION_OVERRIDE="4.1FC" and shows the Godot logo, but then it just hangs. Or maybe i'm doing something wrong. Have to say never had experiences with Godot on other platforms :)

**Comment by jeremiahbailey** [comment]
Don't feel bad, I haven't gotten Godot to build yet on any other systems. I've tried on Linux, FreeBSD, and OpenBSD using both Godot docs and googling system specifics for Godot.

**Comment by pulkomandy** [comment]
"shows logo and hangs" is as far as we got even with support from Godot developers.

Please upstream your patches, however :)

**Comment by jeremiahbailey** [comment]
On the plus side, running projects and GDscripts from the commandline has progressed with 3.0.6-4. With the latest build available in HDepot, I've gotten a very basic project to run, window opens, just no graphics. I can get my print() statements to the terminal to show that user input responses are working. I see this as a huge step forward! This was not working in previous builds on HDepot.

**Pull request merged**
