### PR TITLE
celestia, update recipe

### PR DESCRIPTION
**Pull request by TheLostProbe**
updates the copyright and homepage, since celestia.space went offline and was taken by cybersquatters, so it had to move to celestiaproject.space. not sure about the `REVISION` field though, @Begasus changed it from `2` back to `1` in #9005, so for now I'm just leaving it at `1`. is it because the `REVISION` gets reset back to `1` each time an application is updated to its' newest release or something like that?
also, is there any way that the screenshots shown on the Haiku Depot page could be updated? they look over a decade old lol

### CODE REVIEW

**Comment by Begasus** [comment]
Updating a version (reset revision to 1), updating dependencies/structual updates (revision +1), here there are no structual changes and only cosmetic, no need to bump (we call it revbump) the revision, thanks!

**Comment by humdingerb** [comment]
Do note that the URL to the new homepage will only be updated when the REVISION has increased...

@TheLostProbe : If you can email or point me to better screenshots, I'll update the entries at HaikuDepotServer

**Comment by Begasus** [comment]
Correct @humdingerb , this will be used on the next update then? (or if you really want it can get a revbump for this) :)

**Comment by humdingerb** [comment]
Depends if there are regular updates. If we're likely to have a bad homepage URL for many months, I'd say bump now. OTOH, it's a 45+ MiB download every current user will have to download... You call. :)

**Comment by Begasus** [comment]
Looking at their release cycle it could take a while, lets revbump this. :)

**Comment by TheLostProbe** [comment]
> If you can email or point me to better screenshots, I'll update the entries at HaikuDepotServer

@humdingerb on the [gallery page](https://celestiaproject.space/gallery.html) there's a few good ones. I've picked out a few that I think would make good replacements:
https://celestiaproject.space/images/gallery/cassini.jpg
https://celestiaproject.space/images/gallery/ceres.jpg
https://celestiaproject.space/images/gallery/earth-low.jpg
https://celestiaproject.space/images/gallery/europa.jpg
https://celestiaproject.space/images/gallery/pluto-charon.jpg
https://celestiaproject.space/images/gallery/saturn-rings.jpg

**Comment by humdingerb** [comment]
Done, thanks!

**Pull request merged**
