### PR TITLE
serd, updated the old bep file, bump version, wip

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
The installations fails for the devel package, guessing it has something to do with the "waf" script ... maybe someone else could look into this ...

**Comment by korli** [comment]
libaubio uses waf. Might require patching wscript_build.

**Comment by Begasus** [comment]
Already thought about that, will have a look :)

**Comment by Begasus** [comment]
The information at libaubio didn't work out, but updated to a working version now, tests run ok ...

**Comment by korli** [comment]
Thanks!

**Pull request merged**
