### PR TITLE
Pe packaging fix

### PR DESCRIPTION
**Pull request by miqlas**
Dirty fix for missing libhekkel.
Now packages fine.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Does it actually provide libhekkel though (i.e. libhekkel is installed in `lib`) or is libhekkel just in `$appsDir/Pe/lib`?

**Comment by miqlas** [comment]
It is in $appsDir/Pe/lib, so no.

**Comment by waddlesplash** [comment]
So what's the full error then? Is `lpe` dependent on it? Otherwise, I think HaikuPorter is probably wrong here then.

**Comment by miqlas** [comment]
Missing required lib: libhekkel, or something like that.

> 2017. jún. 16. dátummal, 13:32 időpontban waddlesplash <notifications@github.com> írta:
> 
> pe dependent on it? Otherwise, I think HaikuPorter is probably wrong here then.

**Comment by pulkomandy** [comment]
Haikuporter scans all apps and binaries for required libs, and check that these libs are either in REQUIRES, or part of the package. But it does not check for a $appsDir/lib directory, which is quite an unusual case: the library is shared between different binaries which are part of the package (if there was just one, we would link the lib statically in it), but is useless to other packages.

Possible solutions:
- Haikuporter should look for libs next to the executable which requires them, or
- A special syntax for declaring such libraries could be added to recipes

**Comment by waddlesplash** [comment]
> Haikuporter should look for libs next to the executable which requires them, or

This is the better solution IMO.

**Comment by Begasus** [comment]
Is this fixed with the latest change to haikuporter?

**Comment by korli** [comment]
Shouldn't be needed.

**Pull request closed without merging**
