### PR TITLE
tuxpaint: bump version

### PR DESCRIPTION
**Pull request by n0toose**
[Ask, and you shall receive.](https://twitter.com/TuxPaintTweets/status/1465962450923057153)

### CODE REVIEW

**Comment by panos** [comment]
Note: Not working, yet.

**Comment by Begasus** [comment]
Last version already had issues on 64bit, hence why only 32bit was enabled, this was discussed in the email thread on tuxpaint, nonetheless, thanks for looking into it, didn't have a change to look at it so far ...

**Comment by panos** [comment]
Oops, sorry, thought that was an "I'll take over from here".

**Comment by Begasus** [comment]
Needs SDL_gfx also, build tested on 32bit, TuxPaint doesn't respond to keys ...

**Comment by panos** [comment]
Had some issues with that, tried to also update the libraries to SDL2. Getting a weird header-related error, can't remember...

**Comment by Begasus** [comment]
...

**Comment by n0toose** [comment]
Sorry, I just wasn't sure how to navigate the key problem.

**Pull request closed without merging**
