### PR TITLE
tar: bump to 1.30.

### PR DESCRIPTION
**Pull request by fbrosson**
* On `x86_gcc2` we need `cmd:bison` because we are patching a yacc source, `gnu/parse-datetime.y`.
* On all other arches we do not need any patch.

### CODE REVIEW

**Comment by fbrosson** [comment]
For some unknow reason, some tests which are OK with `tar 1.29` are failing with `tar 1.30`:

Version | tests which are failing |
--- | --- |
1.29 | 39 81 83 87 88 90 93 98 101 104 105 108 109 110 116 117 129 131 152 182
1.30 | 12 13 14 44 87 89 91 92 96 97 99 102 107 110 113 114 119 120 121 127 128 140 142 166 176 196

(Theses results are the same on all architectures.)

But there is hope because, at one point during my builds, I did manage to get a much smaller number of failed tests on x86_64:
```
[GNU tar 1.30] testsuite: 44 87 89 92 127 128 176 196 failed
```
Unfortunately, the build which gave me these results was not a clean build. It was probably the result of some "incremental" builds with small variations in the recipe like adding `LIBS=-lbsd` and/or removing `FORCE_UNSAFE_CONFIGURE=1`

I think `1.30` fixes several bugs we had in `1.29`, but I'm not comfortable with merging right now, so if anyone would like to investigate and shed some light on the topic, it would be great!

(The gcc2 patchset, added in #2727, is not needed on x86_64. I added it because I know the patchset is not guilty :)

**Comment by waddlesplash** [comment]
> It was probably the result of some "incremental" builds with small variations in the recipe like adding 

Could you try to figure out which of those fixed it?

**Comment by fbrosson** [comment]
I already made several attempts (before I created this PR), with these variants, sometimes combined together:
* with bison added to all arches,
* with bison and the gcc2 patch also applied on x86_64,
* with `LIBS=-lbsd`
* without `FORCE_UNSAFE_CONFIGURE=1`

Actually, I had finished the gcc2 patch almost 2 weeks ago, and I have since been trying to reproduce the conditions which gave me the best test results...
BTW, next week I'll be quite busy but I'll resume my investigations in July.

**Comment by kenmays** [comment]
@fbrosson - I'm reviewing tar 1.29 and 1.30 from hrev51991:

Version | tests which are failing
-- | --
1.29 | 39 81 83 87 88 90 93 98 101 104 105 108 109 110 116 117 129 131 152 182
mine| 39 81 83 87 88 90 93 101 104 108 109 110 116 117 129 131 152 182
1.30 | 44 87 89 92 127 128 176 196
mine|

**Comment by fbrosson** [comment]
Thanks @kenmays for your message!
(BTW, I only saw your message yoday because I was AFK.)

A few weeks ago I noticed that `1.30` on x96_gcc2 was not failing on many tests. IIRC, on that arch I got this:
```
[GNU tar 1.30] testsuite: 44 87 89 92 127 128 176 196 failed
```
So I agree with you that it is probably OK to bump tar to `1.30`.
Let's see if other contributors also think we can merge this PR.

**Comment by scottmc** [comment]
@korli can you look this one over and give your input?

**Comment by korli** [comment]
I would prefer including the patch for parse-datetime.c than depending on bison (like in a tarball).

**Comment by fbrosson** [comment]
@korli: Done. But this commit adds 2536 lines to the patchset, so I can revert this change if this is too much.

BTW, as expected, this does not fix any of the test failures.

**Comment by korli** [comment]
Thanks, fine with me.

**Comment by fbrosson** [comment]
Okay, thanks.
~Shall~ Should I merge?
Or do we keep this open until someone finds out what's wrong with the tests?

Hmm, something we could do is add `1.30`, marked as untested on all arches, and keep `1.29` unchanged. Would this be desirable?

**Comment by korli** [comment]
I would merge and file an issue with outstanding issues.

**Pull request merged**
