### PR TITLE
qt5, revbump, update LLVM and ICU dependencies

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
This needs to be checked first, doing tests here with builds/runtime also.

**Comment by Begasus** [comment]
So far no downsides, one plus, I used a 64bit image in qemu to check things, installing Dolphin on there pulled in ICU66 (for Qt5), updated there with these packages I was able to uninstall ICU66 without needing to uninstall qt5 and all the kde frameworks.
Pushed some hpkg's for Qt5 on a test repo for those that don't want to build the full Qt5 packages (includes base,devel and tools packages): https://github.com/Begasus/Haiku_Testdrive/tree/master/Qt5

**Comment by Begasus** [comment]
Getting build error on 32bit:
```
kernel/qhostinfo.cpp: In static member function 'static QHostInfo QHostInfoAgent::reverseLookup(const QHostAddress&)':
kernel/qhostinfo.cpp:424:15: error: 'NI_MAXHOST' was not declared in this scope
  424 |     char hbuf[NI_MAXHOST];
      |               ^~~~~~~~~~
kernel/qhostinfo.cpp:425:39: error: 'hbuf' was not declared in this scope
  425 |     if (sa && getnameinfo(sa, saSize, hbuf, sizeof(hbuf), nullptr, 0, 0) == 0)
      |                                       ^~~~
```

**Comment by Begasus** [comment]
Build finishes fine on 32bit, it's in the INSTALL() part where it is failing (maybe something not build?) with:
```
 /sources/qt5-5.15.11-lts-lgpl/qtbase/src/corelib/qdoc_wrapper.sh: line 12: /packages/qt5_x86-5.15.11-4/.self/bin/x86/qdoc: No such file or directory
```

**Comment by korli** [comment]
anything like "QDoc will not be compiled, probably because libclang could not be located" in the build log?

**Comment by Begasus** [comment]
Is the build log saved in the process? (never saw/checked) During build it's hard to find anything due to the amount of output in Terminal, I could redirect output to a textfile for a build though.

**Comment by korli** [comment]
> Is the build log saved in the process? (never saw/checked) During build it's hard to find anything due to the amount of output in Terminal, I could redirect output to a textfile for a build though.

It's at the configure step at the beginning.

**Comment by Begasus** [comment]
I should start to read when the build starts :) seems indeed it doesn't find libclang:
```
Note: No wayland-egl support detected. Cross-toolkit compatibility disabled.

WARNING: QDoc will not be compiled, probably because libclang could not be located. This means that you cannot build the Qt documentation.

Either ensure that llvm-config is in your PATH environment variable, or set LLVM_INSTALL_DIR to the location of your llvm installation.
On Linux systems, you may be able to install libclang by installing the libclang-dev or libclang-devel package, depending on your distribution.
On macOS, you can use Homebrew's llvm package.
On Windows, you must set LLVM_INSTALL_DIR to the installation path.
```

**Comment by Begasus** [comment]
Not sure why it won't find LLVM? Will do some checks without the changes for LLVM, main thing would be to drop older ICU anyway.

**Comment by Begasus** [comment]
OK, seems for some reason on 32bit it didn't detect llvm-config from LLVM17, LLVM16 seems to be fine (main idea is to move away from ICU66, so for me this should be good enough for now).

**Comment by Begasus** [comment]
Freshly build 64bit image for Haiku with installed Qt5 (these packages):

Qt5_ICU

**Comment by korli** [comment]
@Begasus you commented about it in https://github.com/haikuports/haikuports/pull/10222#issuecomment-2067574809

**Comment by Begasus** [comment]
> @Begasus you commented about it in [#10222 (comment)](https://github.com/haikuports/haikuports/pull/10222#issuecomment-2067574809)

Getting old(er) here maybe ;)

**Comment by korli** [comment]
> > @Begasus you commented about it in [#10222 (comment)](https://github.com/haikuports/haikuports/pull/10222#issuecomment-2067574809)
> 
> Getting old(er) here maybe ;)

Apropos: it seems you added the $secondarySuffix in https://github.com/haikuports/haikuports/pull/9593 to resolve https://github.com/haikuports/haikuports/issues/9562

**Comment by Begasus** [comment]
This looks wrong:
LLVM16 (correct):
~> llvm-config --libdir
/boot/system/develop/lib/x86

LLVM17(wrong)
~> llvm-config-x86 --libdir
/boot/system/bin/develop/lib/x86

Not sure this is caused by my change? (me checks again there)

**Comment by korli** [comment]
@Begasus I updated qt5, hope you can rebase this one.

**Comment by Begasus** [comment]
@korli was/am busy doing a rebuild for LLVM17 on 32bit, guess I can close this one after the Qt5 version bump?

**Comment by Begasus** [comment]
> @Begasus I updated qt5, hope you can rebase this one.

Not sure how (yet), will leave it open for a while and check again later (see comment above), if I can sort things out on 32bit.

**Comment by Begasus** [comment]
Thanks! :)

**Comment by Begasus** [comment]
Looks promising (LLVM17 on 32bit) after fresh build with binaries in bin:
```
~> llvm-config --libs
-lLLVM-17
~> llvm-config --libdir
/boot/system/develop/lib/x86
~> llvm-config --bindir
/boot/system/bin
~> llvm-config --includedir
/boot/system/develop/headers/x86
```

**Comment by Begasus** [comment]
Changes to LLVM17 worked out on 32bit and 64bit so far, already did a rebuild for the new(er) Qt5 with calls to LLVM17 on 64 bit with success, going to check a build for qt-creator (my guess Qt5 uses llvm-config while qt-creator uses the cmake files to check availability?)

**Comment by Begasus** [comment]
Qt5 build and packaged with the new LLVM17, looks OK now.

**Comment by korli** [comment]
@Begasus I have a version bump for qt5. Do you mind if I merge with your PR?

**Comment by Begasus** [comment]
> @Begasus I have a version bump for qt5. Do you mind if I merge with your PR?

Sure, no problem, maybe first do LLVM17 for this?

**Comment by korli** [comment]
> Sure, no problem, maybe first do LLVM17 for this?

RIght, after LLVM17 is ready.

**Pull request merged**
