### PR TITLE
python3: add recipe for 3.7.2

### PR DESCRIPTION
**Pull request by hanya**

### CODE REVIEW

**Comment by hanya** [comment]
* The setup.py from Python 3.7 can find OpenSSL 1.0.2 (or 1.1 is required) without a hack.
* libffi is no longer shipped in the source package, no need to touch.
* lzma module should work.

**Comment by hanya** [comment]
Related to #3421.

**Comment by korli** [comment]
I would also rename the 3.6 recipe python36-3.6.7 and adjust the provides.

**Comment by hanya** [comment]
Added patch for:
* #3076: ~/.python_history file for interactive console place in B_USER_VAR_DIRECTORY/python/history
* #3075: change site.USER_BASE from ~/.local to B_USER_NONPACKAGED_DIRECTORY

**Comment by hanya** [comment]
Current struct spwd has sp_lstchg member in shadow.h, so we do not omit it.
Skipping sp_lstchg without hacking field list broke return value of spwd.getspnam function.

Still test_spwd fails because spwd.getspnam with invalid user name gives FileNotFoundError. It should be KeyError. It looks error mapping between Haiku error and Python is not match or incomatibility of the Haiku internal.

**Comment by extrowerk** [comment]
Nice, this will be required for the upcoming Blender release.

**Pull request merged**
