### PR TITLE
ffmpeg: bumped to 6.1.2

### PR DESCRIPTION
**Pull request by kenmays**
FFmpeg 6.1.2:
- [x] - Haiku R1B4
- [x] - Haiku R1B4 hrev57915

### CODE REVIEW

**Comment by Begasus** [comment]
LGTM (checked build on 64bit), needs a second pair of eyes.

**Comment by Begasus** [comment]
PS, 6.1.1 should be removed before this would be merged.

**Comment by Begasus** [comment]
Any objections here?

**Comment by kenmays** [comment]
Closing. Resyncing FFmpeg branch for Haiku R1B5.

**Pull request closed without merging**
