### PR TITLE
duktape, fix build for 32bit

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Needed for 32bit check on gerbera: https://github.com/haikuports/haikuports/pull/5713
@extrowerk could you check this on 64bit?

**Comment by extrowerk** [comment]
Builds ok here.

**Comment by Begasus** [comment]
> Builds ok here.

Did you check the build with gerbera if it's picked up?

**Comment by extrowerk** [comment]
Yep

**Comment by Begasus** [comment]
Thanks for checking, will merge this and see if this could be up streamed in some way :)

**Pull request merged**
