### PR TITLE
lighttpd: bump to 1.4.49.

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by alaviss** [comment]
We should consider using `addOnsDir` for lighthttpd modules.

Also, please check if the use of `USER_SETTINGS_FILES` here is correct. It's a suspect in #2270

**Comment by fbrosson** [comment]
If we change the `lib:mod_*` into `addon:mod_*` then we would also need to move the modules to `$addOnsDir/lighttpd/`, but this does not seem to be a good idea because on most OSes the modules are under the lighttpd subdirectory of `$prefix/lib/`.

That said, if there is some consensus to move to the `$addOnsDir` then I'm OK with it.

Regarding the `USER_SETTINGS_FILES`, I will try to see what can be done.
But if you already have any hints on how this should be changed, they are very welcome ;)

**Comment by alaviss** [comment]
> If we change the `lib:mod_*` into `addon:mod_*` then we would also need to move the modules to `$addOnsDir/lighttpd/`, but this does not seem to be a good idea because on most OSes the modules are under the lighttpd subdirectory of `$prefix/lib/`.
>
> That said, if there is some consensus to move to the `$addOnsDir` then I'm OK with it.

We're not other OSes. We should do what is correct, that is, to put addons where they should be.

> Regarding the `USER_SETTINGS_FILES`, I will try to see what can be done.
But if you already have any hints on how this should be changed, they are very welcome ;)

If it's confirmed that `lighthttpd` doesn't read configuration files within the user home directory (`/home/user/config/settings`), then `USER_SETTINGS_FILES` should be removed, and for every file in `USER_SETTINGS_FILES` that is not in `GLOBAL_WRITABLE_FILES`, please add the path there and left out the "action" (`keep-old`, `auto-merge`, etc.).

**Comment by fbrosson** [comment]
> We're not other OSes. We should do what is correct, that is, to put addons where they should be.

:+1:

Currently, the paths we put in lighttpd's default config are meant for a system-wide installation.
I don't know if this would be a good idea, nor if it would be worth, but I imagine we could replace these absolute paths by relative ones, so that the package would also be usable when installed in the user's space.
I guess this would be tricky. Do you think we should try that? Or just decide that lighttpd is only usable when installed system-wide?

**Comment by alaviss** [comment]
> Currently, the paths we put in lighttpd's default config are meant for a system-wide installation.
I don't know if this would be a good idea, nor if it would be worth, but I imagine we could replace these absolute paths by relative ones, so that the package would also be usable when installed in the user's space.
I guess this would be tricky. Do you think we should try that? Or just decide that lighttpd is only usable when installed system-wide?

The only directory constant that we could depends on is `sysconfDir`. For others, unfortunately, we can only obtain them reliably through `find_path()`, which mean we would need to patch `lighttpd` for that. 

I'd say we should replace `constantSystemSettingsDir` with `sysconfDir`, and left the others as is for now.

Also, don't forget to reset `REVISION`.

**Comment by fbrosson** [comment]
Thanks for the hint about the `sysconfDir`. I'll dig this.

BTW, I'm quite sure it is possible to configure lighttpd without any absolute paths.
If this is doable then we can create a package that can work no matter how it is installed, system-wide or user-only.

> Also, don't forget to reset `REVISION`.

Good catch, thanks!

**Comment by fbrosson** [comment]
After all, although modules and plugins are both shared libs, a module is _not_ a plugin.
BTW, for Apache, for instance, we are not declaring the modules as plugins.

**Comment by alaviss** [comment]
> After all, although modules and plugins are both shared libs, a module is not a plugin.

A module **is** a plugin. They extend the core functions of the program, and can be loaded dynamically. This is expressed throughout lighttpd source, check any `mod*` source file and you will find `plugin` everywhere.

> BTW, for Apache, for instance, we are not declaring the modules as plugins.

Then I believe we have to update Apache to declare modules as plugins as well, as Apache modules works the same way as lighttpd modules

**Comment by fbrosson** [comment]
Well, I'm not against the change. I just think this is a polical issue, and that there are more downsides than advantages.
BTW, I'm not sure but I think lighttpd is used for testing https://github.com/haiku/webkit, and that it references some modules with their current installation directory, so changing lighttpd would require to change some files in webkit's test suite.

Anyway, if you would like to make the changes for lighttpd and/or apache, please do not hesitate. Other contributors might even agree with this idea.
(As said earlier, I don't disagree. I just think it would be extra work for no real benefit.)

**Pull request merged**
