### PR TITLE
New recipe: SDL Sopwith

### PR DESCRIPTION
**Pull request by win8linux**
[SDL Sopwith](https://fragglet.github.io/sdl-sopwith/) is the SDL-based port of the [original  side-scrolling dogfighting game](https://en.wikipedia.org/wiki/Sopwith_(video_game)) made by David L. Clark of BMB Compuscience, all the way back in 1984 for Ms-DOS.

This is actually a combination of the first game, *Sopwith 2*, and an Author's Edition of the second game from David L. Clark. The website has a [FAQ page](https://fragglet.github.io/sdl-sopwith/FAQ.html) explaining more in detail.

This has been successfully tested on `x86_64`.

screenshot4
screenshot3
screenshot2
screenshot1

### CODE REVIEW

**Comment by Begasus** [comment]
Should be moved to games/arcade/sopwith/sdl_sopwith.recipe, see:
https://packages.gentoo.org/packages/games-arcade/sdl-sopwith

**Comment by win8linux** [comment]
The name used varies between `sdl-sopwith` and just `sopwith`:
https://repology.org/project/sopwith/versions

I went with the latter for uniformity and it being shorter.

**Comment by Begasus** [comment]
We followed Gentoo in this for (I don't know how long) the layout/naming, I still think we should follow it still here.
If anyone feels this is fine as it is I'll keep it open for a bit.

**Comment by win8linux** [comment]
Didn't use `sdl-sopwith` also due to no dashes in package name, but apparently this is fine with just folders.

**Comment by Begasus** [comment]
Still in favor of renaming the recipe to `sdl_sopwith-2.3.0.recipe`

**Pull request merged**
