### PR TITLE
Updated recipe for gcal to v4.1

### PR DESCRIPTION
**Pull request by trungnt2910**
I've updated gcal from v3.6.3 to v4.1 (Latest)
Terminal running gcal v4.1:
gcal-4 1

### CODE REVIEW

**Comment by Begasus** [comment]
You included the changes from elixir with this branch :)

**Comment by trungnt2910** [comment]
> You included the changes from elixir with this branch :)

I forked this from `trungnt2910:master`, which contains changes for elixir.

After the other pull request is merged, a rebase might work (worked for me once).

**Comment by Begasus** [comment]
It's good practice to leave master branch untouched and work with branches, this would solve the issue at hand now :)

**Comment by trungnt2910** [comment]
Ok I've rebased my branch on master. Now it only contains the commit for gcal.

**Comment by Begasus** [comment]
Could you provide a build log from Terminal?

**Comment by trungnt2910** [comment]
Here is the build log:

[gcal_build.log](https://github.com/haikuports/haikuports/files/4080624/gcal_build.log)

**Comment by Begasus** [comment]
```
configure: WARNING: this means gcal-4.1 will use its defaults now
configure: WARNING: and is unable to support several terminal types!
configure: WARNING: note: gcal-4.1 would work more flexible if libncurses.a
configure: WARNING: libtermcap.a or libtermlib.a are installed.
```
Maybe try to see that we at least get ncurses to be detected?

**Comment by trungnt2910** [comment]
This problem is already present in 3.6.3:
```
checking for working terminal libraries... hmm... whats this??

configure: WARNING: no terminal libraries available
configure: WARNING: 
configure: WARNING: this means gcal-3.6.3 will use its defaults now
configure: WARNING: and is unable to support several terminal types!
configure: WARNING: note: gcal-3.6.3 would work more flexible if libncurses.a
configure: WARNING: libtermcap.a or libtermlib.a are installed.
```
Does "detecting nurses" means that I have to make a patch to configure or something like that?
If it does, can you give me a guide on reading build and configuring scripts?
I know how to make patches for haikuports, but I don't know much about the compilation.

**Comment by Begasus** [comment]
Yeah, probably didn't noticed it before, I think it would be enough if you add it to REQUIRES_devel, and add pkg-config to BUILD_PREREQUIRES

**Comment by trungnt2910** [comment]
> Yeah, probably didn't noticed it before, I think it would be enough if you add it to REQUIRES_devel, and add pkg-config to BUILD_PREREQUIRES

Do you mean adding `libncurses` to `REQUIRES_devel`?
If that's the case, it seems that haikuporter requires that something should be added to `PROVIDES_devel`, else it will complain about errors in the recipe.

**Comment by Begasus** [comment]
Let me give it a quick run here :)

**Comment by Begasus** [comment]
Worked fine by adding "devel:libncurses" to PROVIDES_devel and adding "cmd:pkg_config" to BUILD_PREREQUIRES here

**Comment by trungnt2910** [comment]
> Worked fine by adding "devel:libncurses" to PROVIDES_devel and adding "cmd:pkg_config" to BUILD_PREREQUIRES here

Yes, but the same warnings still appears:
```
checking for working terminal libraries... hmm... whats this??

configure: WARNING: no terminal libraries available
configure: WARNING: 
configure: WARNING: this means gcal-4.1 will use its defaults now
configure: WARNING: and is unable to support several terminal types!
configure: WARNING: note: gcal-4.1 would work more flexible if libncurses.a
configure: WARNING: libtermcap.a or libtermlib.a are installed.
```

**Comment by Begasus** [comment]
Here it founds ncurses (gcc2h) and uses it? Will check out on x86_64

**Comment by Begasus** [comment]
configure: checking for libraries...
checking for initscr in -lncurses... yes
checking for working terminal libraries... using -lncurses
checking for cos in -lm... yes

**Comment by Begasus** [comment]
Jikes! I see "my error" :) It shouldn't be PROVIDES_devel but BUILD_REQUIRES for devel:libncurses, sorry about that!

**Comment by Begasus** [comment]
Thanks! :+1:

**Comment by trungnt2910** [comment]
@Begasus 
Thanks for merging. However, why does adding `devel:libncurses` and `cmd:pkg_config` work here?
I guess that `devel:libncurses` provides one of the needed terminal libraries, but what does `cmd:pkg_config` do?
I want to understand the cause of this problem so that I can fix similar ones in the future.

**Comment by Begasus** [comment]
@trungnt2910 devel:libncurses provides the headers (if needed) and the pkg-config file for it (ncurses.pc), with adding pkg-config, it's a tool to check for these files

**Comment by trungnt2910** [comment]
Thanks.

**Pull request merged**
