### PR TITLE
nmap: fix build

### PR DESCRIPTION
**Pull request by kenmays**
Closes: #6144

### CODE REVIEW

**Comment by kenmays** [comment]
Works for me.
mimesetting files for package nmap-3.81-1-x86_64.hpkg ...
creating package nmap-3.81-1-x86_64.hpkg ...
----- Package Info ----------------
header size:                     80
heap size:                   445024
TOC size:                       917
package attributes size:       1561
total size:                  445104
-----------------------------------
waiting for build package nmap-3.81-1 to be deactivated
grabbing nmap-3.81-1-x86_64.hpkg and moving it to /boot/home/haikuports/packages/nmap-3.81-1-x86_64.hpkg
~/haikuports/net-analyzer/nmap> uname -a
Haiku shredder 1 hrev55181+62 Oct 13 2021 07:38: x86_64 x86_64 Haiku

**Comment by diversys** [comment]
Yes, what is the reason for adding `--without-nmapfe` configure switch here?

**Comment by kenmays** [comment]
Fixes the 'make install' breakage' in which you could fix the installation directories or just manually disable the GTK client build.

**Comment by diversys** [comment]
I still don't understand how this is supposed to fix #6144. Care to elaborate?

**Comment by diversys** [comment]
Ok, after disabling multi-job build I see what this fix is doing. I wonder why `nmapfe` is not enabled whey I build locally though.

**Pull request merged**
