### PR TITLE
Revbump ktexteditor and fritzing for new libgit2

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by threedeyes** [comment]
It is a very bad idea to update some components of the kde-framework. They are very much correlated. And updating one of them can break the work of the others.

**Comment by Begasus** [comment]
> It is a very bad idea to update some components of the kde-framework. They are very much correlated. And updating one of them can break the work of the others.

Jikes, sorry wasn't aware of it, didn't it suffer from previous bump on libgit2?

**Comment by threedeyes** [comment]
> Jikes, sorry wasn't aware of it, didn't it suffer from previous bump on libgit2?

Oops. I'm the one who's sorry. For some reason I thought you upgraded the version instead of just running a rebuild.
It's okay, sorry.

**Comment by Begasus** [comment]
> > Jikes, sorry wasn't aware of it, didn't it suffer from previous bump on libgit2?
> 
> Oops. I'm the one who's sorry. For some reason I thought you upgraded the version instead of just running a rebuild. It's okay, sorry.

No worries there, unless there is a good reason, I'm not touching KDE recipes ;)

**Pull request merged**
