### PR TITLE
Haiku Radio, new recipe

### PR DESCRIPTION
**Pull request by Begasus**
First draft ...

### CODE REVIEW

**Comment by humdingerb** [comment]
Can't comment inline with web+. My suggestions:

1. SUMMARY="Find and listen to internet radio stations"
2. DESCRIPTION="'Radio' helps you find and listen to internet radio streams."
3. Under PROVIDES: "radio = $portVersion" and "app:Radio = $portVersion"
3. Remove empty line 28
4. Put "makefile_engine" first in block
5. Add "addAppDeskbarSymlink"

**Comment by Begasus** [comment]
Updated ...

**Comment by humdingerb** [comment]
Looks good to me. Two questions:
1. When do we use "cmd:g++" instead of "cmd:gcc"? Is the distinction of interest?
2. Since in this case the author of the app is MIA, and the app hasn't been widely released before: How free are we to rename the app? "Radio" is so meh generic and also basically wrong... "StreamRadio", "NetRadio" or "NetStreamer" would be nicer.

**Comment by Begasus** [comment]
1. I'm not the guy to ask here ;)
2. I'll hear it if there are any suggestions :)

**Comment by Begasus** [comment]
#RadioStreamer# ? ;)

**Comment by philxyz** [comment]
Name suggestion: Whisker

**Comment by Begasus** [comment]
@humdingerb tried with both cmd:gcc and cmd:g++ and see no difference in building ...

**Comment by humdingerb** [comment]
Thanks, I'll add the patch for the name change.

**Pull request merged**
