### PR TITLE
Mediatomb: decomission

### PR DESCRIPTION
**Pull request by extrowerk**

### CODE REVIEW

**Comment by Begasus** [comment]
Not so sure there, Gerbera still doesn't work for 32bit

**Comment by Begasus** [comment]
On 32bit gerbera still crashes:
```
~> gerbera 
2021-02-27 13:37:40   info: Gerbera UPnP Server git - http://gerbera.io/
2021-02-27 13:37:40   info: Copyright 2016-2021 Gerbera Contributors.
2021-02-27 13:37:40   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-02-27 13:37:40   info: Loading configuration from: /boot/home/config/settings/gerbera/config.xml
2021-02-27 13:37:40   info: Checking configuration...
2021-02-27 13:37:40   info: Configuration check succeeded.
2021-02-27 13:37:41   info: About to migrate metadata from mt_cds_object to mt_metadata
2021-02-27 13:37:41   info: No data will be removed from mt_cds_object
2021-02-27 13:37:41   info: Migrated metadata - object count: 0
2021-02-27 13:37:41   info: Loading 0 configuration items from database
2021-02-27 13:37:41   info: Initialising libupnp with interface: '', port: 0
2021-02-27 13:37:41  error: LibUPnP error code: -121
2021-02-27 13:37:41  error: UpnpUnRegisterClient failed (-116)
2021-02-27 13:37:41  error: UpnpUnRegisterRootDevice failed (-116)
Kill Thread
```

**Comment by extrowerk** [comment]
This seems to be a bug in libpupn, which should be reported upstream. The author tracked down and fixed a similar bug already. Hope he can help us again. Can you report this to him?

**Comment by Begasus** [comment]
Reported upstream in an existing issue at https://github.com/pupnp/pupnp/issues/197#issuecomment-787412095

**Comment by Begasus** [comment]
I think it's ok now ;) Just did a build on nightly and it works ok there :+1: 
Gerbera_32bit

**Pull request merged**
