### PR TITLE
Audacious plugins fix

### PR DESCRIPTION
**Pull request by miqlas**
You tricky hacker....
https://www.youtube.com/watch?v=LmE3IhHBGjI

### CODE REVIEW

**Comment by diversys** [comment]
--disable-mpris2 shouldn't be needed as it builds here just fine.
Audacious seems to not find its resources so the toolbar icons are missing and replaced with text. Could you take a look at that too? :)

**Comment by diversys** [comment]
You can also enable ARCHITECTURES.

**Comment by diversys** [comment]
Oh and --disable-dbus is needed for audacious recipe.

**Comment by miqlas** [comment]
@diversys : it is... you know... actually... your recipe :D

**Pull request merged**
