### PR TITLE
mplayer: Put dot-config files in user settings folder

### PR DESCRIPTION
**Pull request by Damillora**
Fixes https://github.com/haikuports/haikuports/issues/472

Made as part of Google Code-in 2017

### CODE REVIEW

**Comment by Damillora** [comment]
I haven't figured out how to upstream it though...

**Comment by extrowerk** [comment]
I did it trough the official IRC channel some months ago ;)

**Comment by Damillora** [comment]
Probably that's just me that is used to the GitHub interface, so haven't figured out how.

**Comment by extrowerk** [comment]
Just tested, works great!
Nice Job!

**Pull request merged**
