### PR TITLE
Erlang OTP 20.1: WIP

### PR DESCRIPTION
**Pull request by extrowerk**
Still broken, btw.
Help required.

### CODE REVIEW

**Comment by miqlas** [comment]
@korli : i know you have infinite long to-do list, but i cannot fix this stuff. can you maybe look into it please?

**Comment by korli** [comment]
@miqlas so I tried a bit on this PR, it's messy. The hacks for CFLAGS need to be removed.
There is a call to setrlimit to be disabled, because it can't really work on Haiku, because one can't extend the stack when it's already at the maximum size.

**Comment by korli** [comment]
OK this PR is superseded by 1cb2a20e9ebdc5fdebec46cde038ed01012f6cef

**Comment by Begasus** [comment]
erlang is still broken when trying to build it for x86 on x86_gcc2 ... (can't find -lcrypto)

**Pull request closed without merging**
