### PR TITLE
boehm_gc: update to 8.2.2

### PR DESCRIPTION
**Pull request by ivmai**
* Update license file

### CODE REVIEW

**Comment by ivmai** [comment]
@korli, please review

**Comment by ivmai** [comment]
@Begasus Please review this PR (as you pointed out this one relies on the updated libatomic_ops)

**Comment by Begasus** [comment]
Build is OK on 32bit, crashes during tests (haven't checked previous version - yet)

**Comment by Begasus** [comment]
Crash was around on previous version also, thanks!

**Pull request merged**
