### PR TITLE
Embree3: bump, cpucount

### PR DESCRIPTION
**Pull request by extrowerk**
Required by Blender 2.9x

### CODE REVIEW

**Comment by extrowerk** [comment]
Would be nice if somebody could test it on 32 bit, be warned it takes ages to build.

**Comment by tommyjanna** [comment]
32-bit doesn't build from your branch, not sure if anyone cares to work through it.

Build fails promptly on `error: '_mm_cvtsi128_si64' was not declared in this scope`. I did try simply replacing every occurrence with `_mm_cvtsi128_si32` but it then proceeded to fail somewhere else.

**Comment by extrowerk** [comment]
Thanks for the feedback, i have sadly no idea :(

tommyjanna <notifications@github.com>:

**Comment by Begasus** [comment]
> error: '_mm_cvtsi128_si64' was not declared in this scope

Not related to embree3, but maybe an example on how to fix this? https://github.com/p12tic/libsimdpp/issues/1

**Comment by Begasus** [comment]
Version 3.12.2 has been released 6 days ago, maybe it contains a fix for it already (not checked here)

**Pull request merged**
