### PR TITLE
llvm: remove older llvm recipes

### PR DESCRIPTION
**Pull request by kenmays**
Goal:
- Remove recipes LLVM < 9.

### CODE REVIEW

**Comment by Begasus** [comment]
Why do this in 15 commits?
This should be carfully investigated, there are still a few other still using llvm9 for instance:
- [ ] aflplusplus-3.12c
- [ ] qt_creator-6.0.1
- [ ] clazy-1.6
- [ ] kdevelop-21.12.1
(from a quick search)

**Comment by kenmays** [comment]
Actually, that is problematic for rebuilding, use case testing, and debugging. Best to migrate those ports to the default LLVM version for Haiku R1B4.

**Comment by Begasus** [comment]
At this moment only 5 up to 8 are broken in the reports, no need to remove LLVM9 at this point, it's still valid without changes.

**Comment by kenmays** [comment]
Restored LLVM9 recipe/patches.

**Comment by Begasus** [comment]
Could you please squash your commits? Up to 17 now :/

**Pull request closed without merging**
