### PR TITLE
live555: Update to 2016.06.22

### PR DESCRIPTION
**Pull request by Barrett17**

### CODE REVIEW

**Comment by Barrett17** [comment]
Well not much changed, the previous patch still apply cleanly, I will wait until tomorrow for comments then merge it.

**Comment by waddlesplash** [comment]
Looked good to me.

**Comment by Barrett17** [comment]
@waddlesplash I explicitly said I leaved it here for comments until tomorrow, please next time don't merge it.

**Comment by waddlesplash** [comment]
@Barrett17 oh sorry. Usually standard procedure here when someone requests a review is to just have at least one other committer review it, and then merge.

**Pull request merged**
