### PR TITLE
Bezilla: disabled build for R1B3 x86 and x86_64

### PR DESCRIPTION
**Pull request by kenmays**
Tested on Haiku R1B3 (hrev55181+16) x86_gcc2 and hrev55204 x86_64. Now disabled for R1B3+. 
NOTE: Compiles successfully with GCC 2.95.3 on x86_gcc2. 
Ref# #2746 - decommision bezilla from future R1B3+ build efforts.

### CODE REVIEW

**Comment by diversys** [comment]
@kenmays let me quote you from #2746

> Thanks everyone. I'll close this ticket as I now agree with keeping around this old browser - since I've experienced a few legacy commercial apps that misrender on newer Firefox browsers.

Why did you decide to remove it now all of a sudden? It did't hurt keeping it available in the repo even if it is rarely used. I think we should revert it.

**Comment by kenmays** [comment]
@diver - The release of Haikuwebkit 1.8.2+ (i.e. Webkit 612.1.21). I use haikuwebkit with the current Webkit 612.1.25 updates.

Realize it is 13 years since the Firefox 2.0.0.20 release, BeZilla was considered unsupported by Mozilla since Y2012 (see below).

extrowerk mentioned to mark the BeZilla recipe as 'untested' on every arch. Pulkomandy mentioned using NetSurf versus BeZilla. Korli mentioned something similar with NetSurf. 

The Otter Browser/NetSurf/Web+ browsers are current;y suited for most web browser tasks done by Haiku's non-developers.

NOTE: As of post Y2011 - Ref: https://support.mozilla.org/en-US/questions/911431
`There are only 2 currently updated and supported Released versions, Firefox 9.0.1 and Firefox 3.6.25. Support for the Firefox 3.6.x versions is likely to be discontinued in the first quarter of 2012. `

Also: 'Firefox 2.0.0.20 does not include Phishing Protection.' - Mozilla

**Comment by X547** [comment]
I also disagree with Bezilla removal. It has historical importance and it often works better than Netsurf. It is feature complete compared to WebPositive and can be used as reference.

**Comment by kenmays** [comment]
Resolved: https://build.haiku-os.org/buildmaster/master/x86_gcc2/

**Pull request merged**
