### PR TITLE
Mesa: bump to 17.1.10.

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by kenmays** [comment]
1. All Mesa library 17.1.10 'make check' tests pass successfully.

**Comment by kenmays** [comment]
Yes, please reopen. Just remove the "--enable-osmesa" in the recipe as it is mainly not used for Haiku.

**Comment by waddlesplash** [comment]
@kenmays OSMesa was explicitly enabled in #2029, so it should stay enabled.

@fbrosson, please incorporate #2070 at the same time, as it fixes https://dev.haiku-os.org/ticket/13191#comment:26 ! :)

**Comment by fbrosson** [comment]
I've just reverted the import of the pach from #2070, to address @waddlesplash's comment, which is still visible in: 
https://github.com/fbrosson/haikuports/commit/da1fe3054e2ff978104593d47567a7b45e9af7cf#commitcomment-29828965

> Actually we decided in the ticket that the correct way to patch would be to make the locker recursive. So, sorry, but maybe back this patch out for now, and I'll try to write a more correct one later (since @kallisti5 is too busy).

No problem :)

**Comment by extrowerk** [comment]
Nothing depends on osmesa, you can remove it.

**Comment by fbrosson** [comment]
@korli, @kallisti5, @waddlesplash and anyone else interesed in Mesa, do I have your green lights for removing `--enable-osmesa` ?

**Comment by waddlesplash** [comment]
It was enabled without much fanfare, and is apparently broken on secondary arch, so I don't see much reason to require lots of fanfare to disable it. :)

**Comment by fbrosson** [comment]
1) In `INSTALL` we currently stript `"$addOnsDir/opengl/Software Pipe"`. Shall I drop that call and, instead, include this add-on in the debuginfo package?
2) It would be easy to only disable OSMesa on secondary arches. Should I do so? Yep, I know it would require a few extra lines in the recipe, but maybe this could be worth the "trouble".

**Comment by waddlesplash** [comment]
> In INSTALL we currently stript "$addOnsDir/opengl/Software Pipe". Shall I drop that call and, instead, include this add-on in the debuginfo package?

> It would be easy to only disable OSMesa on secondary arches. Should I do so? Yep, I know it would require a few extra lines in the recipe, but maybe this could be worth the "trouble".

Eh, let's disable it globally until @kallisti5 can look into it further.

**Comment by fbrosson** [comment]
Oops, I noticed my typo (strip**t**) and, instead of fixing it only in my own message, I fixed it in yours :smile:

**Comment by fbrosson** [comment]
Good news: the reason why all my builds of mesa_x86 (for both `17.1.7` and `17.1.10`, regardless of whether or not I enabled OSMesa) were failing was because I had built and installed `binutils_x86-2.28.1_2017_08_05`. (That version is marked as untested on x86 secondary arch, and now I understand why...)

After I downgraded to `binutils-2.26.1_2016_07_22`, which is marked as tested, all my builds of mesa succeeded.

So, since OSMesa was is guilty, I suggest that we keep it.
Of course, I can remove it if you prefer not to have it.

**Comment by waddlesplash** [comment]
Yes, let's keep it then.

Yeah, that binutils version seems pretty broken on 32 bit (see #1750). I haven't spent the time trying to figure out why. We should try a newer version...

**Comment by fbrosson** [comment]
Cool, thanks!
I'll install the packages and reboot to check that Haiku is happy with it, and then, maybe, I can merge, unless someone wishes to do some more testing.

**Comment by fbrosson** [comment]
Haiku and RetroArch are both happy with Mesa 17.1.10, on all arches.
So let's merge!

**Pull request merged**
