### PR TITLE
cmake: fix detection of secondary arch

### PR DESCRIPTION
**Pull request by lonemadmax**
/boot/system/lib/x86 may not be the last path in the list, as is the case with clang after packaged version 12.

Related: #10864

Doesn't build due to an unrelated problem, though. `arc4random_buf` is not detected, but while compiling Utilities/cmlibarchive/libarchive/archive_random.c stdlib.h does include it, leading to a redefinition. Don't know where and how to add _DEFAULT_SOURCE and libbsd, all that I've tried has failed. But then I don't know cmake.

### CODE REVIEW

**Comment by Begasus** [comment]
Haven't found a way to patch this in but the next works for getting a full build, adding this just before `./configure`
```
	export CPPFLAGS="_GNU_SOURCE"
	export LDFLAGS="-lbsd"
```

For the record, I was/am building cmake without GUI so it won't take in the extra dependencies when checking here.

**Comment by Begasus** [comment]
@lonemadmax I've pushed my and your changes to: https://github.com/Begasus/haikuports/commit/21b23f3de2d9103f0e8ac54dbf0839312c9eb0f6
could you check also, and maybe import this here also (build on 32bit almost done here).
could also push the changes to the recipe here if need be :)

**Comment by lonemadmax** [comment]
> adding this just before `./configure`
> 

I feel stupid now. I had passed it to make, but never to configure. All that's needed is the library, so that the test sees the symbol and libarchive happily compiles and links.

> 
> For the record, I was/am building cmake without GUI so it won't take in the extra dependencies when checking here.

Do you mean you were going to remove cmake-gui or that you did it to cut down on compilation while trying to find a fix for my problem? In the first case I'd prefer we closed this and you went on.

**Comment by Begasus** [comment]
> > adding this just before `./configure`
> 
> I feel stupid now. I had passed it to make, but never to configure. All that's needed is the library, so that the test sees the symbol and libarchive happily compiles and links.
> 
> > For the record, I was/am building cmake without GUI so it won't take in the extra dependencies when checking here.
> 
> Do you mean you were going to remove cmake-gui or that you did it to cut down on compilation while trying to find a fix for my problem? In the first case I'd prefer we closed this and you went on.

Remove cmake-gui (to get rid of the extra dependencies), no need to close this, if checks are done I can just push the "recipe" alone to this PR.

@X547 mentioned if the next could be included for riscv: https://github.com/haikuports/haikuports/issues/10234#issuecomment-2041416537

**Comment by Begasus** [comment]
Went along and pushed the recipe here, should be on par (checking never hurts) :)

**Comment by lonemadmax** [comment]
RISCV untested.

testUVProcessChain crashes for me in 32bits.

Couldn't run the tests for x86_64.

**Comment by Begasus** [comment]
Same crash on 64bit
Think this should be good if things are fine on 32bit (few testruns went fine here) to merge?

**Comment by X547** [comment]
Recipe still have cyclic build dependency: cmake -> libcpppdap -> cmake.

**Comment by Begasus** [comment]
> Recipe still have cyclic build dependency: cmake -> libcpppdap -> cmake.

Didn't know that one untill now.

**Comment by pulkomandy** [comment]
I confirm that this fixes the problem with webkit_gtk. Merging, and the other problems can be fixed separately.

**Comment by X547** [comment]
> RISCV untested.

riscv64 build confirmed (with disabled libcppdap package for now).

**Pull request merged**
