### PR TITLE
qemu: update to 8.0.4

### PR DESCRIPTION
**Pull request by davidkaroly**

### CODE REVIEW

**Review by korli — APPROVED** [review]

**Comment by davidkaroly** [comment]
something not quite right with the sdl display driver

**Comment by korli** [comment]
x86: we get "no renderer found!" then it crashes with a segmentation fault

Is it a regression?

**Comment by davidkaroly** [comment]
it seems to be a build environment issue...
* if I install pre-build qemu-8.0.3 packages on 32-bit Haiku, it works fine
* if I build qemu-8.0.4, I get the error
* if I rebuild qemu-8.0.3 from sources, I also get the same error. Something changed recently in SDL or Mesa packages?

**Comment by davidkaroly** [comment]
re-testing shows that the issue was there on qemu-8.0.3 already therefore it's not a regression- so I think we can merge this PR as it won't make things worse.

The issue does not show up consistently: sometimes qemu starts up, sometimes it throws an exception and the 'no renderer' error message. Might be an issue in SDL initialization (CreateWindow or CreateRenderer) - I'll create a separate ticket for that.

**Pull request merged**
