### PR TITLE
imagemagick, bump version

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Compared to version 6.* it doesn't provide a few *.pc files (eg Wand.pc)

**Comment by Begasus** [comment]
Disabled the recipe, looking at repology (and some issues on the net) most of other OS's still use the 6.* versions), if someone has a need for it they can still build it locally :)
https://repology.org/project/imagemagick/versions

**Comment by Begasus** [comment]
@extrowerk you used this for embree, is it possible to use the 6.* version for that also? @threedeyes you used this for digikam, does it need the 7.* version?

**Comment by extrowerk** [comment]
Have to check

**Comment by Begasus** [comment]
Bumped version 6 also here (libVersions were wrong)

**Comment by Begasus** [comment]
Tests fail on secondary architecture for
version 6 ... demos.tap 3 and 5
version 7 ... demos.tap5

**Comment by korli** [comment]
This is a compat version change, this means all dependent recipes should be rebuilt.

**Comment by Begasus** [comment]
> This is a compat version change, this means all dependent recipes should be rebuilt.

I know (also seeing that the libversion weren't correct for previous versions) :) (hence the WIP - help appreciated) :)

**Comment by Begasus** [comment]
For version 7 rebuild is needed for:
- [ ] digikam
- [ ] embree
For version 6 rebuild is needed for:
- [ ] libopenshot
- [ ] octave
(from what I could search in haikuports tree)

**Comment by Begasus** [comment]
Version 7.0.10-0 fixes a problem when building the new RC for TuxPaint:
```
...Generating thumbnails for starters...
..tuxpaint-0.9.24: unable to open image `obj/xxxtmp_reef.png.png': No such file or directory @ error/blob.c/OpenBlob/2881.
tuxpaint-0.9.24: no images defined `starters/.thumbs/reef-t.png' @ error/convert.c/ConvertImageCommand/3235.
....tuxpaint-0.9.24: unable to open image `obj/xxxtmp_skyline-sf-dusk.png.png': No such file or directory @ error/blob.c/OpenBlob/2881.
tuxpaint-0.9.24: no images defined `starters/.thumbs/skyline-sf-dusk-t.png' @ error/convert.c/ConvertImageCommand/3235.
..tuxpaint-0.9.24: too many bezier coordinates `M 332.20247,694.0266 C 331.90263,693.64247 332.10671,692.97235 332.65597,692.53747 C 333.33389,692.0007 333.48893,678.18782 333.13869,649.52748 C 332.85491,626.30687 332.88331,606.48617 333.2018,605.48147 C 333.71796,603.85311 334.48796,603.59683 340.29219,603.12148 C 358.09358,601.66359 380.86386,596.53804 397.15806,590.32108 C 437.6582,574.86847 465.7936,553.72155 486.19033,523.40331 C 491.06201,516.1619 496.48453,506.09039 499.3289,499.00041 C 501.61498,493.302 505.273,478.63873 506.38657,470.70947 C 507.31554,464.09472 507.85903,462.39919 509.04653,462.41138 C 509.86736,462.4198 535.24375,462.38403 565.43848,462.3319 C 595.63322,462.27977 621.31966,462.27287 622.51945,462.31658 L 624.70088,462.39604 L 624.44574,475.93204 C 624.30542,483.37684 624.61134,529.96159 625.12557,579.45374 C 625.63981,628.94589 626.07321,674.93011 626.08873,681.64092 L 626.11691,693.84236 L 619.37486,694.00302 C 595.02008,694.58333 332.65387,694.60488 332.20247,694.0266 z M 408.92669,670.67671 C 408.92669,654.57213 408.63477,649.23828 407.72275,648.67816 C 407.06059,648.27149 403.48489,647.16274 399.77676,646.21429 C 396.06863,645.26581 390.2175,643.51473 386.77425,642.32298 C 383.33099,641.13122 378.9968,639.79222 377.14275,639.34743 C 375.28869,638.90263 368.97825,635.71116 363.11956,632.25526 C 357.26085,628.79935 350.88754,625.38419 348.95661,624.66602 C 345.45301,623.36292 341.87402,619.34424 342.96842,617.94218 C 343.93439,616.70467 344.99289,617.10343 346.16951,619.14808 C 346.78546,620.21844 348.771,621.58434 350.58181,622.18339 C 354.56117,623.49984 361.12096,626.92928 369.12973,631.88015 C 372.75865,634.12349 377.761,636.30096 381.94411,637.45812 C 385.71803,638.50208 389.54061,639.68547 390.43868,640.08784 C 395.22209,642.23102 413.02305,646.20736 419.52133,646.58426 C 438.19627,647.66744 451.7923,647.61199 457.08415,646.43111 C 459.99768,645.78093 462.72675,644.99645 463.14876,644.68779 C 463.57075,644.37913 459.63261,643.90435 454.39733,643.63269 C 442.16748,642.9981 428.63478,641.16293 424.33707,639.55617 C 422.483,638.863 419.66581,637.87428 418.07659,637.35901 C 416.4874,636.84374 412.36994,635.38717 408.92669,634.12219 C 405.48343,632.85719 398.33204,630.41798 393.03471,628.70173 C 383.71773,625.68316 381.24337,624.61397 374.42399,620.65998 C 366.40744,616.01184 356.9166,607.62523 356.9166,605.1895 C 356.9166,604.42 356.24255,604.19818 354.74951,604.47635 C 353.55761,604.69842 349.22345,605.29745 345.11802,605.80753 C 341.0126,606.31762 337.65361,607.07889 337.65361,607.49924 C 337.65361,607.91959 338.98441,609.97595 340.61093,612.06895 C 342.67068,614.7194 343.26222,616.11667 342.55999,616.67268 C 341.85775,617.22869 341.00954,617.08249 339.7653,616.19093 C 338.78276,615.48692 337.72534,615.11162 337.41547,615.35697 C 336.60341,615.99993 336.48718,690.75815 337.29725,691.39953 C 337.66982,691.69453 353.93887,691.93589 373.45068,691.93589 L 408.92669,691.93589 L 408.92669,670.67671 z M 504.24617,672.29917 C 504.18359,661.49898 503.88308,649.3166 503.57837,645.2272 C 502.90772,636.22678 502.85961,636.21188 490.79439,641.26571 C 484.74951,643.79779 479.07193,645.37542 469.09341,647.2958 C 450.94875,650.78774 448.3499,650.98209 431.30632,650.12152 C 423.22042,649.71325 415.74398,649.55742 414.69198,649.77525 C 412.84403,650.15787 412.77927,650.86086 412.77927,670.54519 C 412.77927,681.75084 413.06822,691.14788 413.42138,691.4275 C 413.77453,691.70711 434.38018,691.93589 459.21171,691.93589 L 504.35994,691.93589 L 504.24617,672.29917 z M 619.36303,690.72621 C 620.98583,690.40373 621.70721,689.56328 622.14001,687.49091 C 622.90383,683.83348 622.89659,669.29232 622.12773,662.84783 L 621.5233,657.78139 L 618.0412,657.33368 C 616.12605,657.08745 612.93536,656.19307 610.95078,655.34617 C 608.96622,654.49927 606.32657,653.80634 605.08494,653.80634 C 603.8433,653.80634 600.13922,652.74276 596.85364,651.44283 C 592.47685,649.71113 589.83157,647.97995 586.9585,644.96698 C 582.54044,640.33383 576.15123,627.377 575.09057,620.89974 C 573.66846,612.21528 571.48553,605.53347 567.72581,598.35672 C 565.57514,594.25.
tuxpaint-0.9.24: non-conforming drawing primitive definition `path' @ error/draw.c/RenderMVGContent/4348.
tuxpaint-0.9.24: non-conforming drawing primitive definition `path' @ error/draw.c/RenderMVGContent/4348.
tuxpaint-0.9.24: non-conforming drawing primitive definition `path' @ error/draw.c/RenderMVGContent/4348.
Makefile:706: recipe for target 'starters/.thumbs/stained_glass-t.png' failed
make: *** [starters/.thumbs/stained_glass-t.png] Error 1
```

**Pull request merged**
