### PR TITLE
mercurial: update to 4.9.1

### PR DESCRIPTION
**Pull request by congocongocongo**

### CODE REVIEW

**Comment by korli** [comment]
Remove old recipe. Please explain what was tested.

**Comment by korli** [comment]
What about the 5.x versions and switching to python 3?

**Comment by congocongocongo** [comment]
I tested with mozilla-unified, clone/pull/update works fine.  And it did not pass all unit tests like 4.8.1, mostly same tests.  Looks like something is broken in py2 datetime.datetime or around datetime.

**Comment by congocongocongo** [comment]
@korli 5.8 version crashes python3.7 on unit tests and consumes 100% cpu on mozilla-unified. Its better to stay on 4.9.1

**Pull request merged**
